-- Phase 4a: tool_registry port — 50 missing tools from Lovable Cloud
-- Generated by Kaihanga autonomous prep mode 2026-05-13
--
-- Source: ssaxxdkxzrvkdjsanhei.tool_registry (72 rows total)
-- Target: wurwcrgxjjwqdaxqceey.tool_registry (currently 22 rows)
-- Result: 72 rows after merge (assuming no name collisions on insert)
--
-- Notes:
--   * prod column name is 'tool_name' (not 'name')
--   * tool_schema is jsonb (full JSON Schema describing the function call shape)
--   * requires_integration is text[] — empty array if no integration needed
--   * is_active mirrors Lovable's setting (3 deactivated tools stay deactivated)
--   * ON CONFLICT (tool_name) DO UPDATE — idempotent re-runs land same result

BEGIN;

-- ── apex_safety_plan (construction) ──
INSERT INTO tool_registry (tool_name, tool_schema, tool_category, description, requires_integration, is_active)
VALUES (
  'apex_safety_plan',
  '{"name": "apex_safety_plan", "description": "Generate site-specific safety plan per HSWA 2015 and PCBU duties", "input_schema": {"type": "object", "required": ["project_id"], "properties": {"project_id": {"type": "string"}, "hazard_types": {"type": "array", "items": {"type": "string"}}, "site_address": {"type": "string"}}}}'::jsonb,
  'construction',
  NULL,
  ARRAY[]::text[],
  TRUE
)
ON CONFLICT (tool_name) DO UPDATE
  SET tool_schema = EXCLUDED.tool_schema,
      tool_category = EXCLUDED.tool_category,
      description = EXCLUDED.description,
      requires_integration = EXCLUDED.requires_integration,
      is_active = EXCLUDED.is_active,
      updated_at = now();

-- ── apex_schedule_risk (construction) ──
INSERT INTO tool_registry (tool_name, tool_schema, tool_category, description, requires_integration, is_active)
VALUES (
  'apex_schedule_risk',
  '{"name": "apex_schedule_risk", "description": "Analyse project schedule for weather, resource and compliance risks", "input_schema": {"type": "object", "required": ["project_id"], "properties": {"end_date": {"type": "string"}, "project_id": {"type": "string"}, "start_date": {"type": "string"}}}}'::jsonb,
  'construction',
  NULL,
  ARRAY[]::text[],
  TRUE
)
ON CONFLICT (tool_name) DO UPDATE
  SET tool_schema = EXCLUDED.tool_schema,
      tool_category = EXCLUDED.tool_category,
      description = EXCLUDED.description,
      requires_integration = EXCLUDED.requires_integration,
      is_active = EXCLUDED.is_active,
      updated_at = now();

-- ── apex_tender_announcement (construction) ──
INSERT INTO tool_registry (tool_name, tool_schema, tool_category, description, requires_integration, is_active)
VALUES (
  'apex_tender_announcement',
  '{"name": "apex_tender_announcement", "description": "Trigger cross-agent announcement when tender is won \u2014 feeds PRISM for marketing", "input_schema": {"type": "object", "required": ["project_id", "project_name"], "properties": {"value_nzd": {"type": "number"}, "project_id": {"type": "string"}, "client_name": {"type": "string"}, "project_name": {"type": "string"}}}}'::jsonb,
  'construction',
  NULL,
  ARRAY[]::text[],
  TRUE
)
ON CONFLICT (tool_name) DO UPDATE
  SET tool_schema = EXCLUDED.tool_schema,
      tool_category = EXCLUDED.tool_category,
      description = EXCLUDED.description,
      requires_integration = EXCLUDED.requires_integration,
      is_active = EXCLUDED.is_active,
      updated_at = now();

-- ── arai_hazard_register (construction) ──
INSERT INTO tool_registry (tool_name, tool_schema, tool_category, description, requires_integration, is_active)
VALUES (
  'arai_hazard_register',
  '{"name": "arai_hazard_register", "description": "Maintain HSWA 2015 hazard register with risk matrix and control hierarchy", "input_schema": {"type": "object", "required": ["site_id", "hazard"], "properties": {"hazard": {"type": "string"}, "site_id": {"type": "string"}, "likelihood": {"type": "string"}, "consequence": {"type": "string"}}}}'::jsonb,
  'construction',
  NULL,
  ARRAY[]::text[],
  TRUE
)
ON CONFLICT (tool_name) DO UPDATE
  SET tool_schema = EXCLUDED.tool_schema,
      tool_category = EXCLUDED.tool_category,
      description = EXCLUDED.description,
      requires_integration = EXCLUDED.requires_integration,
      is_active = EXCLUDED.is_active,
      updated_at = now();

-- ── arai_site_induction (construction) ──
INSERT INTO tool_registry (tool_name, tool_schema, tool_category, description, requires_integration, is_active)
VALUES (
  'arai_site_induction',
  '{"name": "arai_site_induction", "description": "Schedule and track site induction for new workers per HSWA 2015", "input_schema": {"type": "object", "required": ["worker_name", "site_id"], "properties": {"site_id": {"type": "string"}, "worker_name": {"type": "string"}, "induction_date": {"type": "string"}}}}'::jsonb,
  'construction',
  NULL,
  ARRAY[]::text[],
  TRUE
)
ON CONFLICT (tool_name) DO UPDATE
  SET tool_schema = EXCLUDED.tool_schema,
      tool_category = EXCLUDED.tool_category,
      description = EXCLUDED.description,
      requires_integration = EXCLUDED.requires_integration,
      is_active = EXCLUDED.is_active,
      updated_at = now();

-- ── assembl_allergen_matrix (hospitality) ──
INSERT INTO tool_registry (tool_name, tool_schema, tool_category, description, requires_integration, is_active)
VALUES (
  'assembl_allergen_matrix',
  '{"type": "function", "function": {"name": "assembl_allergen_matrix", "parameters": {"type": "object", "required": ["menu_items"], "properties": {"menu_items": {"type": "array", "items": {"type": "object", "properties": {"name": {"type": "string"}, "ingredients": {"type": "array", "items": {"type": "string"}}}}}}}, "description": "Generate an allergen matrix for a menu. Covers the 8 major allergens plus NZ-specific requirements. Outputs a formatted matrix suitable for display."}}'::jsonb,
  'hospitality',
  'Menu allergen matrix generator',
  ARRAY[]::text[],
  TRUE
)
ON CONFLICT (tool_name) DO UPDATE
  SET tool_schema = EXCLUDED.tool_schema,
      tool_category = EXCLUDED.tool_category,
      description = EXCLUDED.description,
      requires_integration = EXCLUDED.requires_integration,
      is_active = EXCLUDED.is_active,
      updated_at = now();

-- ── assembl_brand_dna_analyzer (creative) ──
INSERT INTO tool_registry (tool_name, tool_schema, tool_category, description, requires_integration, is_active)
VALUES (
  'assembl_brand_dna_analyzer',
  '{"type": "function", "function": {"name": "assembl_brand_dna_analyzer", "parameters": {"type": "object", "required": [], "properties": {"industry": {"type": "string"}, "website_url": {"type": "string", "description": "Brand website URL to scan"}, "brand_description": {"type": "string", "description": "Text description of brand if no URL"}}}, "description": "Analyse brand DNA from website URL or description. Extract colours, typography, voice tone, target audience, and competitive positioning."}}'::jsonb,
  'creative',
  'Brand DNA extraction and analysis tool',
  ARRAY[]::text[],
  TRUE
)
ON CONFLICT (tool_name) DO UPDATE
  SET tool_schema = EXCLUDED.tool_schema,
      tool_category = EXCLUDED.tool_category,
      description = EXCLUDED.description,
      requires_integration = EXCLUDED.requires_integration,
      is_active = EXCLUDED.is_active,
      updated_at = now();

-- ── assembl_consent_tracker (construction) ──
INSERT INTO tool_registry (tool_name, tool_schema, tool_category, description, requires_integration, is_active)
VALUES (
  'assembl_consent_tracker',
  '{"type": "function", "function": {"name": "assembl_consent_tracker", "parameters": {"type": "object", "required": ["consent_type", "current_stage"], "properties": {"consent_ref": {"type": "string", "description": "Building consent reference number"}, "consent_type": {"enum": ["new_build", "renovation", "commercial", "demolition"], "type": "string"}, "current_stage": {"enum": ["pre_lodge", "lodged", "granted", "construction", "pre_line", "post_line", "ccc_application"], "type": "string"}, "inspections_passed": {"type": "array", "items": {"type": "string"}}}}, "description": "Track building consent status and generate CCC application checklists. Covers producer statements (PS1-PS4), inspection records, and as-built documentation requirements."}}'::jsonb,
  'construction',
  'Building consent and CCC tracker',
  ARRAY[]::text[],
  TRUE
)
ON CONFLICT (tool_name) DO UPDATE
  SET tool_schema = EXCLUDED.tool_schema,
      tool_category = EXCLUDED.tool_category,
      description = EXCLUDED.description,
      requires_integration = EXCLUDED.requires_integration,
      is_active = EXCLUDED.is_active,
      updated_at = now();

-- ── assembl_content_calendar (creative) ──
INSERT INTO tool_registry (tool_name, tool_schema, tool_category, description, requires_integration, is_active)
VALUES (
  'assembl_content_calendar',
  '{"type": "function", "function": {"name": "assembl_content_calendar", "parameters": {"type": "object", "required": ["platforms"], "properties": {"industry": {"type": "string"}, "platforms": {"type": "array", "items": {"enum": ["linkedin", "instagram", "facebook", "tiktok", "x"], "type": "string"}}, "brand_voice": {"type": "string", "description": "Brand voice description"}, "week_starting": {"type": "string", "description": "Start date for the calendar week"}}}, "description": "Generate a weekly content calendar with platform-specific posts. Includes NZ calendar events (Matariki, ANZAC Day, school holidays), optimal posting times for NZ audiences, and hashtag recommendations."}}'::jsonb,
  'creative',
  'NZ-optimised content calendar generator',
  ARRAY[]::text[],
  TRUE
)
ON CONFLICT (tool_name) DO UPDATE
  SET tool_schema = EXCLUDED.tool_schema,
      tool_category = EXCLUDED.tool_category,
      description = EXCLUDED.description,
      requires_integration = EXCLUDED.requires_integration,
      is_active = EXCLUDED.is_active,
      updated_at = now();

-- ── assembl_cross_agent_handoff (platform) ──
INSERT INTO tool_registry (tool_name, tool_schema, tool_category, description, requires_integration, is_active)
VALUES (
  'assembl_cross_agent_handoff',
  '{"name": "assembl_cross_agent_handoff", "description": "Trigger a symbiotic handoff to another agent with context payload. Used for cross-kete workflows like tender-won \u2192 marketing post, or new-worker \u2192 site induction.", "input_schema": {"type": "object", "required": ["source_agent", "target_agent", "trigger_event"], "properties": {"payload": {"type": "object"}, "source_agent": {"type": "string"}, "target_agent": {"type": "string"}, "trigger_event": {"type": "string"}}}}'::jsonb,
  'platform',
  NULL,
  ARRAY[]::text[],
  TRUE
)
ON CONFLICT (tool_name) DO UPDATE
  SET tool_schema = EXCLUDED.tool_schema,
      tool_category = EXCLUDED.tool_category,
      description = EXCLUDED.description,
      requires_integration = EXCLUDED.requires_integration,
      is_active = EXCLUDED.is_active,
      updated_at = now();

-- ── assembl_duty_manager_check (hospitality) ──
INSERT INTO tool_registry (tool_name, tool_schema, tool_category, description, requires_integration, is_active)
VALUES (
  'assembl_duty_manager_check',
  '{"type": "function", "function": {"name": "assembl_duty_manager_check", "parameters": {"type": "object", "required": ["certificate_number"], "properties": {"certificate_expiry": {"type": "string", "description": "Certificate expiry date"}, "certificate_number": {"type": "string", "description": "Manager certificate number (e.g. GM-20241234)"}, "host_responsibility_date": {"type": "string", "description": "Last host responsibility training date"}}}, "description": "Check duty manager certificate validity and SSAA 2012 compliance. Verifies certificate expiry, host responsibility training currency, and on-duty requirements."}}'::jsonb,
  'hospitality',
  'Duty manager certificate and SSAA 2012 compliance checker',
  ARRAY[]::text[],
  TRUE
)
ON CONFLICT (tool_name) DO UPDATE
  SET tool_schema = EXCLUDED.tool_schema,
      tool_category = EXCLUDED.tool_category,
      description = EXCLUDED.description,
      requires_integration = EXCLUDED.requires_integration,
      is_active = EXCLUDED.is_active,
      updated_at = now();

-- ── assembl_employment_cost (employment) ──
INSERT INTO tool_registry (tool_name, tool_schema, tool_category, description, requires_integration, is_active)
VALUES (
  'assembl_employment_cost',
  '{"type": "function", "function": {"name": "assembl_employment_cost", "parameters": {"type": "object", "required": ["annual_salary"], "properties": {"acc_levy_rate": {"type": "number", "description": "ACC employer levy rate per $100 (industry-specific)"}, "annual_salary": {"type": "number"}, "kiwisaver_rate": {"type": "number", "description": "Employee KiwiSaver rate"}}}, "description": "Calculate the true cost of employment in NZ including salary, KiwiSaver employer contribution (3%), ACC employer levy, annual leave (4 weeks), sick leave (10 days), public holidays (12 days)."}}'::jsonb,
  'employment',
  'True cost of employment calculator for NZ',
  ARRAY[]::text[],
  TRUE
)
ON CONFLICT (tool_name) DO UPDATE
  SET tool_schema = EXCLUDED.tool_schema,
      tool_category = EXCLUDED.tool_category,
      description = EXCLUDED.description,
      requires_integration = EXCLUDED.requires_integration,
      is_active = EXCLUDED.is_active,
      updated_at = now();

-- ── assembl_ets_calculator (agriculture) ──
INSERT INTO tool_registry (tool_name, tool_schema, tool_category, description, requires_integration, is_active)
VALUES (
  'assembl_ets_calculator',
  '{"type": "function", "function": {"name": "assembl_ets_calculator", "parameters": {"type": "object", "required": ["farm_type", "stock_numbers"], "properties": {"farm_type": {"enum": ["dairy", "sheep_beef", "mixed", "deer"], "type": "string"}, "forestry_ha": {"type": "number", "description": "Hectares of registered ETS forestry"}, "stock_numbers": {"type": "object", "properties": {"deer": {"type": "number"}, "sheep": {"type": "number"}, "dairy_cows": {"type": "number"}, "beef_cattle": {"type": "number"}}}, "fertiliser_tonnes": {"type": "number", "description": "Annual nitrogen fertiliser use in tonnes"}}}, "description": "Calculate on-farm emissions under the NZ Emissions Trading Scheme. Model mitigation scenarios including methane reduction, forestry offsets, and He Waka Eke Noa reporting obligations."}}'::jsonb,
  'agriculture',
  'NZ ETS on-farm emissions calculator',
  ARRAY[]::text[],
  TRUE
)
ON CONFLICT (tool_name) DO UPDATE
  SET tool_schema = EXCLUDED.tool_schema,
      tool_category = EXCLUDED.tool_category,
      description = EXCLUDED.description,
      requires_integration = EXCLUDED.requires_integration,
      is_active = EXCLUDED.is_active,
      updated_at = now();

-- ── assembl_evidence_pack (platform) ──
INSERT INTO tool_registry (tool_name, tool_schema, tool_category, description, requires_integration, is_active)
VALUES (
  'assembl_evidence_pack',
  '{"name": "assembl_evidence_pack", "description": "Generate a branded cross-agent evidence pack PDF with compliance sign-off block. Aggregates outputs from multiple contributing agents into a single auditable document.", "input_schema": {"type": "object", "required": ["title", "pack_id", "sections"], "properties": {"title": {"type": "string"}, "client": {"type": "string"}, "pack_id": {"type": "string"}, "summary": {"type": "string"}, "sections": {"type": "array", "items": {"type": "object", "required": ["agent", "title", "body"], "properties": {"body": {"type": "string"}, "agent": {"type": "string"}, "title": {"type": "string"}, "status": {"enum": ["pass", "flag", "fail"], "type": "string"}, "legislation_ref": {"type": "string"}}}}, "kete_slug": {"type": "string"}}}}'::jsonb,
  'platform',
  NULL,
  ARRAY[]::text[],
  TRUE
)
ON CONFLICT (tool_name) DO UPDATE
  SET tool_schema = EXCLUDED.tool_schema,
      tool_category = EXCLUDED.tool_category,
      description = EXCLUDED.description,
      requires_integration = EXCLUDED.requires_integration,
      is_active = EXCLUDED.is_active,
      updated_at = now();

-- ── assembl_fcp_export (hospitality) ──
INSERT INTO tool_registry (tool_name, tool_schema, tool_category, description, requires_integration, is_active)
VALUES (
  'assembl_fcp_export',
  '{"type": "function", "function": {"name": "assembl_fcp_export", "parameters": {"type": "object", "required": [], "properties": {"period_months": {"type": "number", "description": "Number of months to export (default 12)"}, "include_sections": {"type": "array", "items": {"enum": ["temperatures", "corrective_actions", "staff_training", "suppliers", "cleaning", "allergens"], "type": "string"}, "description": "Sections to include in export"}}}, "description": "Generate a Food Control Plan compliance records pack for MPI verification. Exports 12 months of temperature records, corrective actions, staff training, supplier records, and cleaning schedules."}}'::jsonb,
  'hospitality',
  'FCP verification pack generator for MPI',
  ARRAY[]::text[],
  TRUE
)
ON CONFLICT (tool_name) DO UPDATE
  SET tool_schema = EXCLUDED.tool_schema,
      tool_category = EXCLUDED.tool_category,
      description = EXCLUDED.description,
      requires_integration = EXCLUDED.requires_integration,
      is_active = EXCLUDED.is_active,
      updated_at = now();

-- ── assembl_fep_builder (agriculture) ──
INSERT INTO tool_registry (tool_name, tool_schema, tool_category, description, requires_integration, is_active)
VALUES (
  'assembl_fep_builder',
  '{"type": "function", "function": {"name": "assembl_fep_builder", "parameters": {"type": "object", "required": ["region", "farm_type", "effective_area_ha"], "properties": {"region": {"type": "string", "description": "Regional council area"}, "farm_type": {"enum": ["dairy", "sheep_beef", "horticulture", "mixed", "deer", "forestry"], "type": "string"}, "stock_units": {"type": "number"}, "effluent_system": {"type": "string"}, "effective_area_ha": {"type": "number"}, "waterways_present": {"type": "boolean"}}}, "description": "Build a Farm Environment Plan (FEP) that meets regional council requirements. Covers nutrient management, waterways, effluent, biodiversity, and erosion control. Requirements vary by region."}}'::jsonb,
  'agriculture',
  'Regional council FEP builder',
  ARRAY[]::text[],
  TRUE
)
ON CONFLICT (tool_name) DO UPDATE
  SET tool_schema = EXCLUDED.tool_schema,
      tool_category = EXCLUDED.tool_category,
      description = EXCLUDED.description,
      requires_integration = EXCLUDED.requires_integration,
      is_active = EXCLUDED.is_active,
      updated_at = now();

-- ── assembl_food_safety_check (hospitality) ──
INSERT INTO tool_registry (tool_name, tool_schema, tool_category, description, requires_integration, is_active)
VALUES (
  'assembl_food_safety_check',
  '{"type": "function", "function": {"name": "assembl_food_safety_check", "parameters": {"type": "object", "required": ["business_type"], "properties": {"has_fcp": {"type": "boolean", "description": "Has a registered Food Control Plan"}, "business_type": {"enum": ["restaurant", "cafe", "takeaway", "catering", "food_truck", "bar"], "type": "string"}, "staff_trained": {"type": "boolean", "description": "Staff have food safety training"}, "temperature_records": {"type": "boolean", "description": "Maintaining temperature logs"}}}, "description": "Assess food safety compliance under NZ Food Act 2014. Check temperature records, cleaning schedules, staff training, and FCP (Food Control Plan) requirements."}}'::jsonb,
  'hospitality',
  'Food Act 2014 compliance checker',
  ARRAY[]::text[],
  TRUE
)
ON CONFLICT (tool_name) DO UPDATE
  SET tool_schema = EXCLUDED.tool_schema,
      tool_category = EXCLUDED.tool_category,
      description = EXCLUDED.description,
      requires_integration = EXCLUDED.requires_integration,
      is_active = EXCLUDED.is_active,
      updated_at = now();

-- ── assembl_forge_cin_generator (uncategorised) ──
INSERT INTO tool_registry (tool_name, tool_schema, tool_category, description, requires_integration, is_active)
VALUES (
  'assembl_forge_cin_generator',
  '{"type": "object", "required": ["rego", "make", "model", "year", "odometer_km"], "properties": {"make": {"type": "string"}, "rego": {"type": "string"}, "year": {"type": "number"}, "model": {"type": "string"}, "odometer_km": {"type": "number"}}}'::jsonb,
  NULL,
  'Generate CCCFA-compliant Consumer Information Notice',
  ARRAY[]::text[],
  TRUE
)
ON CONFLICT (tool_name) DO UPDATE
  SET tool_schema = EXCLUDED.tool_schema,
      tool_category = EXCLUDED.tool_category,
      description = EXCLUDED.description,
      requires_integration = EXCLUDED.requires_integration,
      is_active = EXCLUDED.is_active,
      updated_at = now();

-- ── assembl_forge_fleet_dashboard (uncategorised) ──
INSERT INTO tool_registry (tool_name, tool_schema, tool_category, description, requires_integration, is_active)
VALUES (
  'assembl_forge_fleet_dashboard',
  '{"type": "object", "required": [], "properties": {"include_ruc": {"type": "boolean"}, "include_wof": {"type": "boolean"}, "include_services": {"type": "boolean"}}}'::jsonb,
  NULL,
  'Generate fleet status overview with compliance metrics',
  ARRAY[]::text[],
  TRUE
)
ON CONFLICT (tool_name) DO UPDATE
  SET tool_schema = EXCLUDED.tool_schema,
      tool_category = EXCLUDED.tool_category,
      description = EXCLUDED.description,
      requires_integration = EXCLUDED.requires_integration,
      is_active = EXCLUDED.is_active,
      updated_at = now();

-- ── assembl_forge_ruc_calculator (uncategorised) ──
INSERT INTO tool_registry (tool_name, tool_schema, tool_category, description, requires_integration, is_active)
VALUES (
  'assembl_forge_ruc_calculator',
  '{"type": "object", "required": ["vehicle_type", "distance_km"], "properties": {"distance_km": {"type": "number"}, "vehicle_type": {"enum": ["diesel_light", "ev_light", "phev_light", "diesel_heavy"], "type": "string"}}}'::jsonb,
  NULL,
  'Calculate Road User Charges for diesel and EV vehicles',
  ARRAY[]::text[],
  TRUE
)
ON CONFLICT (tool_name) DO UPDATE
  SET tool_schema = EXCLUDED.tool_schema,
      tool_category = EXCLUDED.tool_category,
      description = EXCLUDED.description,
      requires_integration = EXCLUDED.requires_integration,
      is_active = EXCLUDED.is_active,
      updated_at = now();

-- ── assembl_forge_service_reminder (uncategorised) ──
INSERT INTO tool_registry (tool_name, tool_schema, tool_category, description, requires_integration, is_active)
VALUES (
  'assembl_forge_service_reminder',
  '{"type": "object", "required": ["customer_id", "service_type"], "properties": {"customer_id": {"type": "string"}, "overdue_days": {"type": "number"}, "service_type": {"type": "string"}}}'::jsonb,
  NULL,
  'Generate and send service due reminders to customers',
  ARRAY[]::text[],
  TRUE
)
ON CONFLICT (tool_name) DO UPDATE
  SET tool_schema = EXCLUDED.tool_schema,
      tool_category = EXCLUDED.tool_category,
      description = EXCLUDED.description,
      requires_integration = EXCLUDED.requires_integration,
      is_active = EXCLUDED.is_active,
      updated_at = now();

-- ── assembl_forge_wof_tracker (uncategorised) ──
INSERT INTO tool_registry (tool_name, tool_schema, tool_category, description, requires_integration, is_active)
VALUES (
  'assembl_forge_wof_tracker',
  '{"type": "object", "required": ["action"], "properties": {"rego": {"type": "string"}, "action": {"enum": ["check_due", "schedule_reminder", "list_fleet"], "type": "string"}}}'::jsonb,
  NULL,
  'Track WoF/CoF expiry dates for fleet vehicles',
  ARRAY[]::text[],
  TRUE
)
ON CONFLICT (tool_name) DO UPDATE
  SET tool_schema = EXCLUDED.tool_schema,
      tool_category = EXCLUDED.tool_category,
      description = EXCLUDED.description,
      requires_integration = EXCLUDED.requires_integration,
      is_active = EXCLUDED.is_active,
      updated_at = now();

-- ── assembl_generate_agreement (employment) ──
INSERT INTO tool_registry (tool_name, tool_schema, tool_category, description, requires_integration, is_active)
VALUES (
  'assembl_generate_agreement',
  '{"type": "function", "function": {"name": "assembl_generate_agreement", "parameters": {"type": "object", "required": ["employee_name", "role_title", "employment_type", "annual_salary"], "properties": {"role_title": {"type": "string"}, "start_date": {"type": "string"}, "annual_salary": {"type": "number"}, "employee_name": {"type": "string"}, "hours_per_week": {"type": "number"}, "employment_type": {"enum": ["permanent_fulltime", "permanent_parttime", "fixed_term", "casual"], "type": "string"}, "trial_period_days": {"type": "number", "description": "Trial period in days (max 90)"}}}, "description": "Generate an NZ employment agreement compliant with Employment Relations Act 2000. Includes mandatory clauses: parties, duties, location, hours, remuneration, leave, termination, disputes, trial period (if applicable)."}}'::jsonb,
  'employment',
  'NZ employment agreement generator (ERA 2000 compliant)',
  ARRAY[]::text[],
  TRUE
)
ON CONFLICT (tool_name) DO UPDATE
  SET tool_schema = EXCLUDED.tool_schema,
      tool_category = EXCLUDED.tool_category,
      description = EXCLUDED.description,
      requires_integration = EXCLUDED.requires_integration,
      is_active = EXCLUDED.is_active,
      updated_at = now();

-- ── assembl_gst_calculator (finance) ──
INSERT INTO tool_registry (tool_name, tool_schema, tool_category, description, requires_integration, is_active)
VALUES (
  'assembl_gst_calculator',
  '{"type": "function", "function": {"name": "assembl_gst_calculator", "parameters": {"type": "object", "required": ["amount", "direction"], "properties": {"rate": {"enum": ["standard", "zero"], "type": "string", "description": "GST rate: standard (15%) or zero-rated"}, "amount": {"type": "number", "description": "Transaction amount in NZD"}, "direction": {"enum": ["add", "remove"], "type": "string", "description": "Add GST to amount or remove GST from GST-inclusive amount"}}}, "description": "Calculate GST for NZ transactions. Handles 15% GST inclusive/exclusive, zero-rated supplies, and exempt supplies under Goods and Services Tax Act 1985."}}'::jsonb,
  'finance',
  'NZ GST calculator with standard and zero-rated support',
  ARRAY[]::text[],
  TRUE
)
ON CONFLICT (tool_name) DO UPDATE
  SET tool_schema = EXCLUDED.tool_schema,
      tool_category = EXCLUDED.tool_category,
      description = EXCLUDED.description,
      requires_integration = EXCLUDED.requires_integration,
      is_active = EXCLUDED.is_active,
      updated_at = now();

-- ── assembl_healthy_homes_check (property) ──
INSERT INTO tool_registry (tool_name, tool_schema, tool_category, description, requires_integration, is_active)
VALUES (
  'assembl_healthy_homes_check',
  '{"type": "function", "function": {"name": "assembl_healthy_homes_check", "parameters": {"type": "object", "required": ["property_type", "floor_area_sqm"], "properties": {"drainage_ok": {"type": "boolean"}, "heating_type": {"type": "string"}, "property_type": {"enum": ["house", "apartment", "unit", "townhouse"], "type": "string"}, "floor_area_sqm": {"type": "number"}, "ventilation_type": {"type": "string"}, "has_extractor_fans": {"type": "boolean"}, "insulation_ceiling": {"type": "boolean"}, "insulation_underfloor": {"type": "boolean"}}}, "description": "Assess property compliance against NZ Healthy Homes Standards (heating, insulation, ventilation, moisture, drainage, draught stopping). Returns pass/fail per standard with remediation guidance."}}'::jsonb,
  'property',
  'Healthy Homes Standards compliance checker',
  ARRAY[]::text[],
  TRUE
)
ON CONFLICT (tool_name) DO UPDATE
  SET tool_schema = EXCLUDED.tool_schema,
      tool_category = EXCLUDED.tool_category,
      description = EXCLUDED.description,
      requires_integration = EXCLUDED.requires_integration,
      is_active = EXCLUDED.is_active,
      updated_at = now();

-- ── assembl_host_responsibility (hospitality) ──
INSERT INTO tool_registry (tool_name, tool_schema, tool_category, description, requires_integration, is_active)
VALUES (
  'assembl_host_responsibility',
  '{"type": "function", "function": {"name": "assembl_host_responsibility", "parameters": {"type": "object", "required": ["staff"], "properties": {"staff": {"type": "array", "items": {"type": "object", "properties": {"name": {"type": "string"}, "training_date": {"type": "string"}, "certificate_number": {"type": "string"}}}}}}, "description": "Track and verify host responsibility training compliance for all staff serving alcohol. Under SSAA 2012, all bar staff must have current host responsibility training."}}'::jsonb,
  'hospitality',
  'Host responsibility training tracker',
  ARRAY[]::text[],
  TRUE
)
ON CONFLICT (tool_name) DO UPDATE
  SET tool_schema = EXCLUDED.tool_schema,
      tool_category = EXCLUDED.tool_category,
      description = EXCLUDED.description,
      requires_integration = EXCLUDED.requires_integration,
      is_active = EXCLUDED.is_active,
      updated_at = now();

-- ── assembl_hs_checklist (construction) ──
INSERT INTO tool_registry (tool_name, tool_schema, tool_category, description, requires_integration, is_active)
VALUES (
  'assembl_hs_checklist',
  '{"type": "function", "function": {"name": "assembl_hs_checklist", "parameters": {"type": "object", "required": ["site_type"], "properties": {"hazards": {"type": "array", "items": {"type": "string"}, "description": "Known hazards on site"}, "site_type": {"enum": ["residential", "commercial", "civil", "demolition", "renovation"], "type": "string"}, "workers_count": {"type": "number"}, "has_notifiable_work": {"type": "boolean", "description": "Work at height >5m, excavation >1.5m, etc."}}}, "description": "Generate a site-specific H&S checklist under HSWA 2015. Covers hazard identification, PPE requirements, notifiable work assessment, emergency procedures, and PCBU obligations."}}'::jsonb,
  'construction',
  'HSWA 2015 site H&S checklist generator',
  ARRAY[]::text[],
  TRUE
)
ON CONFLICT (tool_name) DO UPDATE
  SET tool_schema = EXCLUDED.tool_schema,
      tool_category = EXCLUDED.tool_category,
      description = EXCLUDED.description,
      requires_integration = EXCLUDED.requires_integration,
      is_active = EXCLUDED.is_active,
      updated_at = now();

-- ── assembl_invoice_generator (finance) ──
INSERT INTO tool_registry (tool_name, tool_schema, tool_category, description, requires_integration, is_active)
VALUES (
  'assembl_invoice_generator',
  '{"type": "function", "function": {"name": "assembl_invoice_generator", "parameters": {"type": "object", "required": ["client_name", "items"], "properties": {"items": {"type": "array", "items": {"type": "object", "properties": {"quantity": {"type": "number"}, "unit_price": {"type": "number"}, "description": {"type": "string"}}}}, "gst_number": {"type": "string", "description": "Supplier GST number"}, "client_name": {"type": "string"}, "payment_terms_days": {"type": "number", "description": "Payment terms in days (default 20)"}}}, "description": "Generate a professional NZ tax invoice compliant with IRD requirements. Includes GST number, due date calculation, and payment terms."}}'::jsonb,
  'finance',
  'NZ tax invoice generator',
  ARRAY[]::text[],
  TRUE
)
ON CONFLICT (tool_name) DO UPDATE
  SET tool_schema = EXCLUDED.tool_schema,
      tool_category = EXCLUDED.tool_category,
      description = EXCLUDED.description,
      requires_integration = EXCLUDED.requires_integration,
      is_active = EXCLUDED.is_active,
      updated_at = now();

-- ── assembl_leave_calculator (employment) ──
INSERT INTO tool_registry (tool_name, tool_schema, tool_category, description, requires_integration, is_active)
VALUES (
  'assembl_leave_calculator',
  '{"type": "function", "function": {"name": "assembl_leave_calculator", "parameters": {"type": "object", "required": ["start_date", "leave_type"], "properties": {"leave_type": {"enum": ["annual", "sick", "bereavement", "parental", "public_holidays"], "type": "string"}, "start_date": {"type": "string", "description": "Employment start date"}, "hours_per_week": {"type": "number"}}}, "description": "Calculate leave entitlements under NZ Holidays Act 2003. Annual leave (4 weeks after 12 months), sick leave (10 days after 6 months), bereavement, public holidays, parental leave."}}'::jsonb,
  'employment',
  'NZ leave entitlements calculator',
  ARRAY[]::text[],
  TRUE
)
ON CONFLICT (tool_name) DO UPDATE
  SET tool_schema = EXCLUDED.tool_schema,
      tool_category = EXCLUDED.tool_category,
      description = EXCLUDED.description,
      requires_integration = EXCLUDED.requires_integration,
      is_active = EXCLUDED.is_active,
      updated_at = now();

-- ── assembl_licence_renewal (hospitality) ──
INSERT INTO tool_registry (tool_name, tool_schema, tool_category, description, requires_integration, is_active)
VALUES (
  'assembl_licence_renewal',
  '{"type": "function", "function": {"name": "assembl_licence_renewal", "parameters": {"type": "object", "required": ["licence_type"], "properties": {"expiry_date": {"type": "string"}, "licence_type": {"enum": ["on_licence", "off_licence", "club_licence", "special"], "type": "string"}, "licence_number": {"type": "string"}, "premises_changes": {"type": "boolean", "description": "Have there been any changes to the premises?"}}}, "description": "Generate a liquor licence renewal application checklist under SSAA 2012. Includes required documentation, timeline, and objection risk assessment."}}'::jsonb,
  'hospitality',
  'SSAA 2012 liquor licence renewal checklist generator',
  ARRAY[]::text[],
  TRUE
)
ON CONFLICT (tool_name) DO UPDATE
  SET tool_schema = EXCLUDED.tool_schema,
      tool_category = EXCLUDED.tool_category,
      description = EXCLUDED.description,
      requires_integration = EXCLUDED.requires_integration,
      is_active = EXCLUDED.is_active,
      updated_at = now();

-- ── assembl_nait_checker (agriculture) ──
INSERT INTO tool_registry (tool_name, tool_schema, tool_category, description, requires_integration, is_active)
VALUES (
  'assembl_nait_checker',
  '{"type": "function", "function": {"name": "assembl_nait_checker", "parameters": {"type": "object", "required": ["nait_number", "animal_type"], "properties": {"animal_type": {"enum": ["cattle", "deer"], "type": "string"}, "nait_number": {"type": "string", "description": "NAIT location number"}, "total_animals": {"type": "number"}, "last_movement_date": {"type": "string"}}}, "description": "Check NAIT compliance status. Verify registration, review movement recording obligations, and generate compliance report under NAIT Act 2012."}}'::jsonb,
  'agriculture',
  'NAIT Act 2012 compliance checker',
  ARRAY[]::text[],
  TRUE
)
ON CONFLICT (tool_name) DO UPDATE
  SET tool_schema = EXCLUDED.tool_schema,
      tool_category = EXCLUDED.tool_category,
      description = EXCLUDED.description,
      requires_integration = EXCLUDED.requires_integration,
      is_active = EXCLUDED.is_active,
      updated_at = now();

-- ── assembl_payment_claim (construction) ──
INSERT INTO tool_registry (tool_name, tool_schema, tool_category, description, requires_integration, is_active)
VALUES (
  'assembl_payment_claim',
  '{"type": "function", "function": {"name": "assembl_payment_claim", "parameters": {"type": "object", "required": ["contract_value", "completed_to_date"], "properties": {"variations": {"type": "array", "items": {"type": "object", "properties": {"amount": {"type": "number"}, "description": {"type": "string"}}}}, "contract_value": {"type": "number"}, "retention_rate": {"type": "number", "description": "Retention percentage (typically 5-10%)"}, "previous_claims": {"type": "number"}, "completed_to_date": {"type": "number"}}}, "description": "Generate a payment claim under Construction Contracts Act 2002. Calculates retentions, variations, and payment schedule deadlines."}}'::jsonb,
  'construction',
  'Construction Contracts Act 2002 payment claim calculator',
  ARRAY[]::text[],
  TRUE
)
ON CONFLICT (tool_name) DO UPDATE
  SET tool_schema = EXCLUDED.tool_schema,
      tool_category = EXCLUDED.tool_category,
      description = EXCLUDED.description,
      requires_integration = EXCLUDED.requires_integration,
      is_active = EXCLUDED.is_active,
      updated_at = now();

-- ── assembl_payroll_calculator (finance) ──
INSERT INTO tool_registry (tool_name, tool_schema, tool_category, description, requires_integration, is_active)
VALUES (
  'assembl_payroll_calculator',
  '{"type": "function", "function": {"name": "assembl_payroll_calculator", "parameters": {"type": "object", "required": ["gross_pay", "pay_frequency", "tax_code"], "properties": {"tax_code": {"type": "string", "description": "IRD tax code e.g. M, ME, S, SH"}, "gross_pay": {"type": "number"}, "student_loan": {"type": "boolean"}, "pay_frequency": {"enum": ["weekly", "fortnightly", "monthly"], "type": "string"}, "kiwisaver_rate": {"type": "number", "description": "Employee KiwiSaver rate: 3, 4, 6, 8, or 10 percent"}}}, "description": "Calculate NZ payroll including PAYE, KiwiSaver (employer 3%), ACC earner levy, and student loan deductions. Uses current IRD tax tables."}}'::jsonb,
  'finance',
  'NZ payroll calculator with PAYE, KiwiSaver, ACC',
  ARRAY[]::text[],
  TRUE
)
ON CONFLICT (tool_name) DO UPDATE
  SET tool_schema = EXCLUDED.tool_schema,
      tool_category = EXCLUDED.tool_category,
      description = EXCLUDED.description,
      requires_integration = EXCLUDED.requires_integration,
      is_active = EXCLUDED.is_active,
      updated_at = now();

-- ── assembl_qualmark_check (hospitality) ──
INSERT INTO tool_registry (tool_name, tool_schema, tool_category, description, requires_integration, is_active)
VALUES (
  'assembl_qualmark_check',
  '{"type": "function", "function": {"name": "assembl_qualmark_check", "parameters": {"type": "object", "required": ["business_type"], "properties": {"business_type": {"enum": ["accommodation", "activity", "transport", "attraction", "food_beverage"], "type": "string"}, "current_rating": {"type": "string", "description": "Current Qualmark rating if any"}, "sustainability_practices": {"type": "array", "items": {"type": "string"}}}}, "description": "Assess tourism business readiness for Qualmark certification. Covers sustainability, visitor safety, cultural competency, and operational standards."}}'::jsonb,
  'hospitality',
  'Qualmark tourism certification readiness checker',
  ARRAY[]::text[],
  TRUE
)
ON CONFLICT (tool_name) DO UPDATE
  SET tool_schema = EXCLUDED.tool_schema,
      tool_category = EXCLUDED.tool_category,
      description = EXCLUDED.description,
      requires_integration = EXCLUDED.requires_integration,
      is_active = EXCLUDED.is_active,
      updated_at = now();

-- ── assembl_rent_review (property) ──
INSERT INTO tool_registry (tool_name, tool_schema, tool_category, description, requires_integration, is_active)
VALUES (
  'assembl_rent_review',
  '{"type": "function", "function": {"name": "assembl_rent_review", "parameters": {"type": "object", "required": ["location", "bedrooms", "property_type"], "properties": {"bedrooms": {"type": "number"}, "location": {"type": "string", "description": "Suburb or city"}, "property_type": {"enum": ["house", "apartment", "unit", "townhouse"], "type": "string"}, "current_rent_weekly": {"type": "number"}}}, "description": "Calculate market rent review based on location, property type, bedrooms, and current market data. References Tenancy Services rent data."}}'::jsonb,
  'property',
  'NZ market rent review calculator',
  ARRAY[]::text[],
  TRUE
)
ON CONFLICT (tool_name) DO UPDATE
  SET tool_schema = EXCLUDED.tool_schema,
      tool_category = EXCLUDED.tool_category,
      description = EXCLUDED.description,
      requires_integration = EXCLUDED.requires_integration,
      is_active = EXCLUDED.is_active,
      updated_at = now();

-- ── assembl_temp_log (hospitality) ──
INSERT INTO tool_registry (tool_name, tool_schema, tool_category, description, requires_integration, is_active)
VALUES (
  'assembl_temp_log',
  '{"type": "function", "function": {"name": "assembl_temp_log", "parameters": {"type": "object", "required": ["equipment_name", "equipment_type", "temperature_c"], "properties": {"notes": {"type": "string", "description": "Any observations"}, "recorded_by": {"type": "string", "description": "Name of person recording"}, "temperature_c": {"type": "number", "description": "Temperature reading in Celsius"}, "equipment_name": {"type": "string", "description": "Name of equipment (e.g. Chiller 1, Walk-in freezer)"}, "equipment_type": {"enum": ["chiller", "freezer", "hot_hold", "thermometer"], "type": "string"}}}, "description": "Record food temperature readings and assess compliance under Food Act 2014. Chiller must be \u22645\u00b0C, freezer \u2264-15\u00b0C, hot-hold \u226565\u00b0C. Flags exceedances and generates corrective action requirements."}}'::jsonb,
  'hospitality',
  'Food Act 2014 temperature log recorder with compliance assessment',
  ARRAY[]::text[],
  TRUE
)
ON CONFLICT (tool_name) DO UPDATE
  SET tool_schema = EXCLUDED.tool_schema,
      tool_category = EXCLUDED.tool_category,
      description = EXCLUDED.description,
      requires_integration = EXCLUDED.requires_integration,
      is_active = EXCLUDED.is_active,
      updated_at = now();

-- ── assembl_toro_ets_calculator (uncategorised) ──
INSERT INTO tool_registry (tool_name, tool_schema, tool_category, description, requires_integration, is_active)
VALUES (
  'assembl_toro_ets_calculator',
  '{"type": "object", "required": ["stock_units", "area_ha"], "properties": {"area_ha": {"type": "number"}, "stock_units": {"type": "object"}, "forestry_blocks_ha": {"type": "number"}}}'::jsonb,
  NULL,
  'Calculate on-farm emissions and model mitigation scenarios',
  ARRAY[]::text[],
  TRUE
)
ON CONFLICT (tool_name) DO UPDATE
  SET tool_schema = EXCLUDED.tool_schema,
      tool_category = EXCLUDED.tool_category,
      description = EXCLUDED.description,
      requires_integration = EXCLUDED.requires_integration,
      is_active = EXCLUDED.is_active,
      updated_at = now();

-- ── assembl_toro_fep_builder (uncategorised) ──
INSERT INTO tool_registry (tool_name, tool_schema, tool_category, description, requires_integration, is_active)
VALUES (
  'assembl_toro_fep_builder',
  '{"type": "object", "required": ["region", "farm_type"], "properties": {"region": {"type": "string"}, "area_ha": {"type": "number"}, "farm_type": {"type": "string"}}}'::jsonb,
  NULL,
  'Guide creation of Farm Environment Plan for regional council compliance',
  ARRAY[]::text[],
  TRUE
)
ON CONFLICT (tool_name) DO UPDATE
  SET tool_schema = EXCLUDED.tool_schema,
      tool_category = EXCLUDED.tool_category,
      description = EXCLUDED.description,
      requires_integration = EXCLUDED.requires_integration,
      is_active = EXCLUDED.is_active,
      updated_at = now();

-- ── assembl_toro_milk_price (uncategorised) ──
INSERT INTO tool_registry (tool_name, tool_schema, tool_category, description, requires_integration, is_active)
VALUES (
  'assembl_toro_milk_price',
  '{"type": "object", "required": [], "properties": {"season": {"type": "string"}, "production_kgms": {"type": "number"}}}'::jsonb,
  NULL,
  'Retrieve current and forecast Fonterra farmgate milk prices',
  ARRAY[]::text[],
  TRUE
)
ON CONFLICT (tool_name) DO UPDATE
  SET tool_schema = EXCLUDED.tool_schema,
      tool_category = EXCLUDED.tool_category,
      description = EXCLUDED.description,
      requires_integration = EXCLUDED.requires_integration,
      is_active = EXCLUDED.is_active,
      updated_at = now();

-- ── assembl_toro_nait_tracker (uncategorised) ──
INSERT INTO tool_registry (tool_name, tool_schema, tool_category, description, requires_integration, is_active)
VALUES (
  'assembl_toro_nait_tracker',
  '{"type": "object", "required": ["action"], "properties": {"action": {"enum": ["check_compliance", "record_movement", "list_animals", "expiry_check"], "type": "string"}, "nait_number": {"type": "string"}}}'::jsonb,
  NULL,
  'Track NAIT compliance for cattle and deer',
  ARRAY[]::text[],
  TRUE
)
ON CONFLICT (tool_name) DO UPDATE
  SET tool_schema = EXCLUDED.tool_schema,
      tool_category = EXCLUDED.tool_category,
      description = EXCLUDED.description,
      requires_integration = EXCLUDED.requires_integration,
      is_active = EXCLUDED.is_active,
      updated_at = now();

-- ── assembl_toro_seasonal_sweep (uncategorised) ──
INSERT INTO tool_registry (tool_name, tool_schema, tool_category, description, requires_integration, is_active)
VALUES (
  'assembl_toro_seasonal_sweep',
  '{"type": "object", "required": [], "properties": {"farm_id": {"type": "string"}}}'::jsonb,
  NULL,
  'Run seasonal compliance sweep across NAIT, FEP, water, effluent, ETS',
  ARRAY[]::text[],
  TRUE
)
ON CONFLICT (tool_name) DO UPDATE
  SET tool_schema = EXCLUDED.tool_schema,
      tool_category = EXCLUDED.tool_category,
      description = EXCLUDED.description,
      requires_integration = EXCLUDED.requires_integration,
      is_active = EXCLUDED.is_active,
      updated_at = now();

-- ── assembl_toro_weather_ops (uncategorised) ──
INSERT INTO tool_registry (tool_name, tool_schema, tool_category, description, requires_integration, is_active)
VALUES (
  'assembl_toro_weather_ops',
  '{"type": "object", "required": ["region"], "properties": {"region": {"type": "string"}, "days_ahead": {"type": "number", "default": 3}}}'::jsonb,
  NULL,
  'Map weather forecasts to farming operations and alerts',
  ARRAY[]::text[],
  TRUE
)
ON CONFLICT (tool_name) DO UPDATE
  SET tool_schema = EXCLUDED.tool_schema,
      tool_category = EXCLUDED.tool_category,
      description = EXCLUDED.description,
      requires_integration = EXCLUDED.requires_integration,
      is_active = EXCLUDED.is_active,
      updated_at = now();

-- ── echo_analytics_feedback (creative) ──
INSERT INTO tool_registry (tool_name, tool_schema, tool_category, description, requires_integration, is_active)
VALUES (
  'echo_analytics_feedback',
  '{"name": "echo_analytics_feedback", "description": "Analyse content performance and update Brand DNA with learnings", "input_schema": {"type": "object", "required": ["period"], "properties": {"period": {"type": "string"}, "platform": {"type": "string"}}}}'::jsonb,
  'creative',
  NULL,
  ARRAY[]::text[],
  TRUE
)
ON CONFLICT (tool_name) DO UPDATE
  SET tool_schema = EXCLUDED.tool_schema,
      tool_category = EXCLUDED.tool_category,
      description = EXCLUDED.description,
      requires_integration = EXCLUDED.requires_integration,
      is_active = EXCLUDED.is_active,
      updated_at = now();

-- ── echo_content_calendar (creative) ──
INSERT INTO tool_registry (tool_name, tool_schema, tool_category, description, requires_integration, is_active)
VALUES (
  'echo_content_calendar',
  '{"name": "echo_content_calendar", "description": "Generate weekly content calendar based on Brand DNA, trends, and NZ calendar", "input_schema": {"type": "object", "required": ["week_start"], "properties": {"platforms": {"type": "array", "items": {"type": "string"}}, "week_start": {"type": "string"}}}}'::jsonb,
  'creative',
  NULL,
  ARRAY[]::text[],
  TRUE
)
ON CONFLICT (tool_name) DO UPDATE
  SET tool_schema = EXCLUDED.tool_schema,
      tool_category = EXCLUDED.tool_category,
      description = EXCLUDED.description,
      requires_integration = EXCLUDED.requires_integration,
      is_active = EXCLUDED.is_active,
      updated_at = now();

-- ── kaupapa_progress_claim (construction) ──
INSERT INTO tool_registry (tool_name, tool_schema, tool_category, description, requires_integration, is_active)
VALUES (
  'kaupapa_progress_claim',
  '{"name": "kaupapa_progress_claim", "description": "Generate CCA 2002 compliant progress payment claim with retention and variation tracking", "input_schema": {"type": "object", "required": ["project_id", "claim_period"], "properties": {"project_id": {"type": "string"}, "variations": {"type": "array", "items": {"type": "object"}}, "claim_period": {"type": "string"}}}}'::jsonb,
  'construction',
  NULL,
  ARRAY[]::text[],
  TRUE
)
ON CONFLICT (tool_name) DO UPDATE
  SET tool_schema = EXCLUDED.tool_schema,
      tool_category = EXCLUDED.tool_category,
      description = EXCLUDED.description,
      requires_integration = EXCLUDED.requires_integration,
      is_active = EXCLUDED.is_active,
      updated_at = now();

-- ── nova_qualmark_prep (hospitality) ──
INSERT INTO tool_registry (tool_name, tool_schema, tool_category, description, requires_integration, is_active)
VALUES (
  'nova_qualmark_prep',
  '{"name": "nova_qualmark_prep", "description": "Prepare Qualmark sustainability assessment checklist for tourism operators", "input_schema": {"type": "object", "required": ["business_name"], "properties": {"business_name": {"type": "string"}, "qualmark_level": {"type": "string"}}}}'::jsonb,
  'hospitality',
  NULL,
  ARRAY[]::text[],
  TRUE
)
ON CONFLICT (tool_name) DO UPDATE
  SET tool_schema = EXCLUDED.tool_schema,
      tool_category = EXCLUDED.tool_category,
      description = EXCLUDED.description,
      requires_integration = EXCLUDED.requires_integration,
      is_active = EXCLUDED.is_active,
      updated_at = now();

-- ── prism_brand_lock (creative) ──
INSERT INTO tool_registry (tool_name, tool_schema, tool_category, description, requires_integration, is_active)
VALUES (
  'prism_brand_lock',
  '{"name": "prism_brand_lock", "description": "Validate content against Brand DNA guardrails before publish", "input_schema": {"type": "object", "required": ["content"], "properties": {"content": {"type": "string"}, "content_type": {"type": "string"}}}}'::jsonb,
  'creative',
  NULL,
  ARRAY[]::text[],
  TRUE
)
ON CONFLICT (tool_name) DO UPDATE
  SET tool_schema = EXCLUDED.tool_schema,
      tool_category = EXCLUDED.tool_category,
      description = EXCLUDED.description,
      requires_integration = EXCLUDED.requires_integration,
      is_active = EXCLUDED.is_active,
      updated_at = now();

-- ── prism_brand_scanner (creative) ──
INSERT INTO tool_registry (tool_name, tool_schema, tool_category, description, requires_integration, is_active)
VALUES (
  'prism_brand_scanner',
  '{"name": "prism_brand_scanner", "description": "Scan website or collateral to extract Brand DNA \u2014 colours, voice, typography", "input_schema": {"type": "object", "required": ["url"], "properties": {"url": {"type": "string"}, "scan_depth": {"type": "string"}}}}'::jsonb,
  'creative',
  NULL,
  ARRAY[]::text[],
  TRUE
)
ON CONFLICT (tool_name) DO UPDATE
  SET tool_schema = EXCLUDED.tool_schema,
      tool_category = EXCLUDED.tool_category,
      description = EXCLUDED.description,
      requires_integration = EXCLUDED.requires_integration,
      is_active = EXCLUDED.is_active,
      updated_at = now();

-- ── prism_campaign_engine (creative) ──
INSERT INTO tool_registry (tool_name, tool_schema, tool_category, description, requires_integration, is_active)
VALUES (
  'prism_campaign_engine',
  '{"name": "prism_campaign_engine", "description": "Generate multi-platform campaign from Brand DNA and brief", "input_schema": {"type": "object", "required": ["brief", "platforms"], "properties": {"brief": {"type": "string"}, "platforms": {"type": "array", "items": {"type": "string"}}, "budget_nzd": {"type": "number"}}}}'::jsonb,
  'creative',
  NULL,
  ARRAY[]::text[],
  TRUE
)
ON CONFLICT (tool_name) DO UPDATE
  SET tool_schema = EXCLUDED.tool_schema,
      tool_category = EXCLUDED.tool_category,
      description = EXCLUDED.description,
      requires_integration = EXCLUDED.requires_integration,
      is_active = EXCLUDED.is_active,
      updated_at = now();

-- ── whakae_consent_checklist (construction) ──
INSERT INTO tool_registry (tool_name, tool_schema, tool_category, description, requires_integration, is_active)
VALUES (
  'whakae_consent_checklist',
  '{"name": "whakae_consent_checklist", "description": "Building Act 2004 consent application checklist with BCA requirements", "input_schema": {"type": "object", "required": ["consent_type"], "properties": {"council": {"type": "string"}, "consent_type": {"type": "string"}, "building_work": {"type": "string"}}}}'::jsonb,
  'construction',
  NULL,
  ARRAY[]::text[],
  TRUE
)
ON CONFLICT (tool_name) DO UPDATE
  SET tool_schema = EXCLUDED.tool_schema,
      tool_category = EXCLUDED.tool_category,
      description = EXCLUDED.description,
      requires_integration = EXCLUDED.requires_integration,
      is_active = EXCLUDED.is_active,
      updated_at = now();

COMMIT;

-- Verification:
-- SELECT count(*) FROM tool_registry;  -- expect 72
-- SELECT tool_category, count(*) FROM tool_registry GROUP BY tool_category ORDER BY count DESC;