-- Phase 4b: agent_toolsets fill with casing merge
-- Generated by Kaihanga autonomous prep mode 2026-05-13
--
-- Source: ssaxxdkxzrvkdjsanhei.agent_toolsets (254 rows, 74 distinct agents incl. casing dupes)
-- Target: wurwcrgxjjwqdaxqceey.agent_toolsets
--
-- Strategy:
--   1. UNION tool wirings across casings on the Lovable side (e.g. PRISM and prism merge into 'prism')
--   2. Canonical case = lowercase
--   3. INSERT only the wirings missing from prod after that UNION
--
-- IMPORTANT: This migration assumes Phase 4a (tool_registry) has run first.
--   Otherwise FK errors will block every INSERT touching a tool not yet in registry.
--
-- IMPORTANT: This migration also assumes Phase 5 (casing normalisation on prod's existing
--   ECHO and PRISM rows) has run first. Otherwise the prod-side casing collision remains.
--
-- Idempotent: ON CONFLICT (agent_id, tool_name) DO NOTHING

BEGIN;

-- ako (5 tool wiring(s) to add)
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('ako', 'assembl_cross_agent_handoff') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('ako', 'assembl_evidence_pack') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('ako', 'toro_curriculum_resources') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('ako', 'toro_list_children') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('ako', 'toro_today_routine') ON CONFLICT (agent_id, tool_name) DO NOTHING;

-- ako-comply (5 tool wiring(s) to add)
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('ako-comply', 'assembl_cross_agent_handoff') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('ako-comply', 'assembl_evidence_pack') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('ako-comply', 'toro_curriculum_resources') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('ako-comply', 'toro_list_children') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('ako-comply', 'toro_today_routine') ON CONFLICT (agent_id, tool_name) DO NOTHING;

-- ako-whanau (5 tool wiring(s) to add)
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('ako-whanau', 'assembl_cross_agent_handoff') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('ako-whanau', 'assembl_evidence_pack') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('ako-whanau', 'toro_curriculum_resources') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('ako-whanau', 'toro_list_children') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('ako-whanau', 'toro_today_routine') ON CONFLICT (agent_id, tool_name) DO NOTHING;

-- anchor (1 tool wiring(s) to add)
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('anchor', 'assembl_evidence_pack') ON CONFLICT (agent_id, tool_name) DO NOTHING;

-- apex (5 tool wiring(s) to add)
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('apex', 'apex_safety_plan') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('apex', 'apex_schedule_risk') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('apex', 'apex_tender_announcement') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('apex', 'assembl_cross_agent_handoff') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('apex', 'assembl_evidence_pack') ON CONFLICT (agent_id, tool_name) DO NOTHING;

-- arai (5 tool wiring(s) to add)
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('arai', 'arai_hazard_register') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('arai', 'arai_site_induction') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('arai', 'assembl_cross_agent_handoff') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('arai', 'assembl_evidence_pack') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('arai', 'assembl_hs_checklist') ON CONFLICT (agent_id, tool_name) DO NOTHING;

-- arataki (6 tool wiring(s) to add)
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('arataki', 'assembl_cross_agent_handoff') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('arataki', 'assembl_evidence_pack') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('arataki', 'assembl_forge_fleet_dashboard') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('arataki', 'assembl_forge_ruc_calculator') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('arataki', 'assembl_forge_service_reminder') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('arataki', 'assembl_forge_wof_tracker') ON CONFLICT (agent_id, tool_name) DO NOTHING;

-- arc (2 tool wiring(s) to add)
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('arc', 'assembl_cross_agent_handoff') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('arc', 'assembl_evidence_pack') ON CONFLICT (agent_id, tool_name) DO NOTHING;

-- aroha (5 tool wiring(s) to add)
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('aroha', 'assembl_cross_agent_handoff') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('aroha', 'assembl_employment_cost') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('aroha', 'assembl_evidence_pack') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('aroha', 'assembl_generate_agreement') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('aroha', 'assembl_leave_calculator') ON CONFLICT (agent_id, tool_name) DO NOTHING;

-- ata (7 tool wiring(s) to add)
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('ata', 'arai_hazard_register') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('ata', 'arai_site_induction') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('ata', 'assembl_consent_tracker') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('ata', 'assembl_cross_agent_handoff') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('ata', 'assembl_evidence_pack') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('ata', 'assembl_hs_checklist') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('ata', 'assembl_payment_claim') ON CONFLICT (agent_id, tool_name) DO NOTHING;

-- aura (6 tool wiring(s) to add)
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('aura', 'assembl_allergen_matrix') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('aura', 'assembl_cross_agent_handoff') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('aura', 'assembl_evidence_pack') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('aura', 'assembl_fcp_export') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('aura', 'assembl_food_safety_check') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('aura', 'assembl_temp_log') ON CONFLICT (agent_id, tool_name) DO NOTHING;

-- cellar (3 tool wiring(s) to add)
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('cellar', 'assembl_duty_manager_check') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('cellar', 'assembl_host_responsibility') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('cellar', 'assembl_licence_renewal') ON CONFLICT (agent_id, tool_name) DO NOTHING;

-- compass (1 tool wiring(s) to add)
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('compass', 'assembl_evidence_pack') ON CONFLICT (agent_id, tool_name) DO NOTHING;

-- compliance-scanner (4 tool wiring(s) to add)
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('compliance-scanner', 'assembl_consent_tracker') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('compliance-scanner', 'assembl_cross_agent_handoff') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('compliance-scanner', 'assembl_evidence_pack') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('compliance-scanner', 'assembl_hs_checklist') ON CONFLICT (agent_id, tool_name) DO NOTHING;

-- concierge (2 tool wiring(s) to add)
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('concierge', 'assembl_cross_agent_handoff') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('concierge', 'assembl_evidence_pack') ON CONFLICT (agent_id, tool_name) DO NOTHING;

-- echo (4 tool wiring(s) to add)
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('echo', 'assembl_content_calendar') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('echo', 'assembl_evidence_pack') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('echo', 'echo_analytics_feedback') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('echo', 'echo_content_calendar') ON CONFLICT (agent_id, tool_name) DO NOTHING;

-- flux (2 tool wiring(s) to add)
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('flux', 'assembl_cross_agent_handoff') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('flux', 'assembl_evidence_pack') ON CONFLICT (agent_id, tool_name) DO NOTHING;

-- harvest (6 tool wiring(s) to add)
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('harvest', 'assembl_toro_ets_calculator') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('harvest', 'assembl_toro_fep_builder') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('harvest', 'assembl_toro_milk_price') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('harvest', 'assembl_toro_nait_tracker') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('harvest', 'assembl_toro_seasonal_sweep') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('harvest', 'assembl_toro_weather_ops') ON CONFLICT (agent_id, tool_name) DO NOTHING;

-- haven (3 tool wiring(s) to add)
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('haven', 'assembl_evidence_pack') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('haven', 'assembl_healthy_homes_check') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('haven', 'assembl_rent_review') ON CONFLICT (agent_id, tool_name) DO NOTHING;

-- hui (2 tool wiring(s) to add)
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('hui', 'assembl_cross_agent_handoff') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('hui', 'assembl_evidence_pack') ON CONFLICT (agent_id, tool_name) DO NOTHING;

-- iho (2 tool wiring(s) to add)
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('iho', 'assembl_cross_agent_handoff') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('iho', 'assembl_evidence_pack') ON CONFLICT (agent_id, tool_name) DO NOTHING;

-- kahu (4 tool wiring(s) to add)
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('kahu', 'assembl_consent_tracker') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('kahu', 'assembl_cross_agent_handoff') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('kahu', 'assembl_evidence_pack') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('kahu', 'assembl_hs_checklist') ON CONFLICT (agent_id, tool_name) DO NOTHING;

-- kahu-advisor (4 tool wiring(s) to add)
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('kahu-advisor', 'assembl_consent_tracker') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('kahu-advisor', 'assembl_cross_agent_handoff') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('kahu-advisor', 'assembl_evidence_pack') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('kahu-advisor', 'assembl_hs_checklist') ON CONFLICT (agent_id, tool_name) DO NOTHING;

-- kaupapa (4 tool wiring(s) to add)
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('kaupapa', 'assembl_cross_agent_handoff') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('kaupapa', 'assembl_evidence_pack') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('kaupapa', 'assembl_payment_claim') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('kaupapa', 'kaupapa_progress_claim') ON CONFLICT (agent_id, tool_name) DO NOTHING;

-- ledger (5 tool wiring(s) to add)
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('ledger', 'assembl_cross_agent_handoff') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('ledger', 'assembl_evidence_pack') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('ledger', 'assembl_gst_calculator') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('ledger', 'assembl_invoice_generator') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('ledger', 'assembl_payroll_calculator') ON CONFLICT (agent_id, tool_name) DO NOTHING;

-- mahara (2 tool wiring(s) to add)
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('mahara', 'assembl_cross_agent_handoff') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('mahara', 'assembl_evidence_pack') ON CONFLICT (agent_id, tool_name) DO NOTHING;

-- mana (2 tool wiring(s) to add)
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('mana', 'assembl_cross_agent_handoff') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('mana', 'assembl_evidence_pack') ON CONFLICT (agent_id, tool_name) DO NOTHING;

-- manaaki (8 tool wiring(s) to add)
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('manaaki', 'assembl_allergen_matrix') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('manaaki', 'assembl_cross_agent_handoff') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('manaaki', 'assembl_duty_manager_check') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('manaaki', 'assembl_evidence_pack') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('manaaki', 'assembl_food_safety_check') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('manaaki', 'assembl_host_responsibility') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('manaaki', 'assembl_licence_renewal') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('manaaki', 'assembl_temp_log') ON CONFLICT (agent_id, tool_name) DO NOTHING;

-- meeting-copilot (2 tool wiring(s) to add)
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('meeting-copilot', 'assembl_cross_agent_handoff') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('meeting-copilot', 'assembl_evidence_pack') ON CONFLICT (agent_id, tool_name) DO NOTHING;

-- motor (7 tool wiring(s) to add)
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('motor', 'assembl_cross_agent_handoff') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('motor', 'assembl_evidence_pack') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('motor', 'assembl_forge_cin_generator') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('motor', 'assembl_forge_fleet_dashboard') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('motor', 'assembl_forge_ruc_calculator') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('motor', 'assembl_forge_service_reminder') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('motor', 'assembl_forge_wof_tracker') ON CONFLICT (agent_id, tool_name) DO NOTHING;

-- muse (6 tool wiring(s) to add)
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('muse', 'assembl_brand_dna_analyzer') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('muse', 'assembl_content_calendar') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('muse', 'assembl_cross_agent_handoff') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('muse', 'assembl_evidence_pack') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('muse', 'auaha_buffer_scheduler') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('muse', 'auaha_falai_image_gen') ON CONFLICT (agent_id, tool_name) DO NOTHING;

-- nexus (2 tool wiring(s) to add)
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('nexus', 'assembl_cross_agent_handoff') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('nexus', 'assembl_evidence_pack') ON CONFLICT (agent_id, tool_name) DO NOTHING;

-- nova (3 tool wiring(s) to add)
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('nova', 'assembl_evidence_pack') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('nova', 'assembl_qualmark_check') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('nova', 'nova_qualmark_prep') ON CONFLICT (agent_id, tool_name) DO NOTHING;

-- pai (7 tool wiring(s) to add)
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('pai', 'arai_hazard_register') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('pai', 'arai_site_induction') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('pai', 'assembl_consent_tracker') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('pai', 'assembl_cross_agent_handoff') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('pai', 'assembl_evidence_pack') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('pai', 'assembl_hs_checklist') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('pai', 'assembl_payment_claim') ON CONFLICT (agent_id, tool_name) DO NOTHING;

-- pikau (3 tool wiring(s) to add)
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('pikau', 'assembl_consent_tracker') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('pikau', 'assembl_cross_agent_handoff') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('pikau', 'assembl_evidence_pack') ON CONFLICT (agent_id, tool_name) DO NOTHING;

-- pikau-biosecurity (3 tool wiring(s) to add)
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('pikau-biosecurity', 'assembl_consent_tracker') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('pikau-biosecurity', 'assembl_cross_agent_handoff') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('pikau-biosecurity', 'assembl_evidence_pack') ON CONFLICT (agent_id, tool_name) DO NOTHING;

-- pikau-customs (3 tool wiring(s) to add)
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('pikau-customs', 'assembl_consent_tracker') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('pikau-customs', 'assembl_cross_agent_handoff') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('pikau-customs', 'assembl_evidence_pack') ON CONFLICT (agent_id, tool_name) DO NOTHING;

-- pilot (2 tool wiring(s) to add)
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('pilot', 'assembl_cross_agent_handoff') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('pilot', 'assembl_evidence_pack') ON CONFLICT (agent_id, tool_name) DO NOTHING;

-- pixel (6 tool wiring(s) to add)
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('pixel', 'assembl_brand_dna_analyzer') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('pixel', 'assembl_content_calendar') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('pixel', 'assembl_cross_agent_handoff') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('pixel', 'assembl_evidence_pack') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('pixel', 'auaha_buffer_scheduler') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('pixel', 'auaha_falai_image_gen') ON CONFLICT (agent_id, tool_name) DO NOTHING;

-- prism (7 tool wiring(s) to add)
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('prism', 'assembl_brand_dna_analyzer') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('prism', 'assembl_content_calendar') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('prism', 'assembl_cross_agent_handoff') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('prism', 'assembl_evidence_pack') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('prism', 'prism_brand_lock') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('prism', 'prism_brand_scanner') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('prism', 'prism_campaign_engine') ON CONFLICT (agent_id, tool_name) DO NOTHING;

-- pulse (1 tool wiring(s) to add)
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('pulse', 'assembl_gst_calculator') ON CONFLICT (agent_id, tool_name) DO NOTHING;

-- rawa (7 tool wiring(s) to add)
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('rawa', 'arai_hazard_register') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('rawa', 'arai_site_induction') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('rawa', 'assembl_consent_tracker') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('rawa', 'assembl_cross_agent_handoff') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('rawa', 'assembl_evidence_pack') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('rawa', 'assembl_hs_checklist') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('rawa', 'assembl_payment_claim') ON CONFLICT (agent_id, tool_name) DO NOTHING;

-- saffron (3 tool wiring(s) to add)
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('saffron', 'assembl_fcp_export') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('saffron', 'assembl_food_safety_check') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('saffron', 'assembl_temp_log') ON CONFLICT (agent_id, tool_name) DO NOTHING;

-- sentinel (2 tool wiring(s) to add)
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('sentinel', 'assembl_cross_agent_handoff') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('sentinel', 'assembl_evidence_pack') ON CONFLICT (agent_id, tool_name) DO NOTHING;

-- shield (1 tool wiring(s) to add)
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('shield', 'assembl_evidence_pack') ON CONFLICT (agent_id, tool_name) DO NOTHING;

-- signal (2 tool wiring(s) to add)
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('signal', 'assembl_cross_agent_handoff') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('signal', 'assembl_evidence_pack') ON CONFLICT (agent_id, tool_name) DO NOTHING;

-- ta (2 tool wiring(s) to add)
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('ta', 'assembl_cross_agent_handoff') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('ta', 'assembl_evidence_pack') ON CONFLICT (agent_id, tool_name) DO NOTHING;

-- terra (3 tool wiring(s) to add)
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('terra', 'assembl_ets_calculator') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('terra', 'assembl_fep_builder') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('terra', 'assembl_nait_checker') ON CONFLICT (agent_id, tool_name) DO NOTHING;

-- toro (6 tool wiring(s) to add)
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('toro', 'assembl_cross_agent_handoff') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('toro', 'assembl_evidence_pack') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('toro', 'toro_add_shopping_item') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('toro', 'toro_get_pocket_money_balances') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('toro', 'toro_list_children') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('toro', 'toro_today_routine') ON CONFLICT (agent_id, tool_name) DO NOTHING;

-- verse (6 tool wiring(s) to add)
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('verse', 'assembl_brand_dna_analyzer') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('verse', 'assembl_content_calendar') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('verse', 'assembl_cross_agent_handoff') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('verse', 'assembl_evidence_pack') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('verse', 'auaha_buffer_scheduler') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('verse', 'auaha_falai_image_gen') ON CONFLICT (agent_id, tool_name) DO NOTHING;

-- waihanga (7 tool wiring(s) to add)
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('waihanga', 'arai_hazard_register') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('waihanga', 'arai_site_induction') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('waihanga', 'assembl_consent_tracker') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('waihanga', 'assembl_cross_agent_handoff') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('waihanga', 'assembl_evidence_pack') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('waihanga', 'assembl_hs_checklist') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('waihanga', 'assembl_payment_claim') ON CONFLICT (agent_id, tool_name) DO NOTHING;

-- waihanga-comply (7 tool wiring(s) to add)
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('waihanga-comply', 'arai_hazard_register') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('waihanga-comply', 'arai_site_induction') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('waihanga-comply', 'assembl_consent_tracker') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('waihanga-comply', 'assembl_cross_agent_handoff') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('waihanga-comply', 'assembl_evidence_pack') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('waihanga-comply', 'assembl_hs_checklist') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('waihanga-comply', 'assembl_payment_claim') ON CONFLICT (agent_id, tool_name) DO NOTHING;

-- waihanga-subbies (7 tool wiring(s) to add)
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('waihanga-subbies', 'arai_hazard_register') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('waihanga-subbies', 'arai_site_induction') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('waihanga-subbies', 'assembl_consent_tracker') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('waihanga-subbies', 'assembl_cross_agent_handoff') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('waihanga-subbies', 'assembl_evidence_pack') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('waihanga-subbies', 'assembl_hs_checklist') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('waihanga-subbies', 'assembl_payment_claim') ON CONFLICT (agent_id, tool_name) DO NOTHING;

-- whakaae (1 tool wiring(s) to add)
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('whakaae', 'assembl_consent_tracker') ON CONFLICT (agent_id, tool_name) DO NOTHING;

-- whakae (2 tool wiring(s) to add)
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('whakae', 'assembl_evidence_pack') ON CONFLICT (agent_id, tool_name) DO NOTHING;
INSERT INTO agent_toolsets (agent_id, tool_name) VALUES ('whakae', 'whakae_consent_checklist') ON CONFLICT (agent_id, tool_name) DO NOTHING;

COMMIT;

-- Verification:
-- SELECT agent_id, count(*) AS tools FROM agent_toolsets GROUP BY agent_id ORDER BY agent_id;
-- SELECT count(*) FROM agent_toolsets;  -- expect ~250+ after merge