# Generated by ATA spec doc cmorXXXXX, generic prefab timber 2-bed unit pattern,
# identifying details abstracted.
#
# Run headless:
#   blender --background --python build_unit.py
#
# Output: ./demo-unit-16c.glb (Y-up, Draco-compressed glTF Binary)

import math
import os
import bpy

# ---------------------------------------------------------------------------
# Dimensions (Blender uses metres, source spec is millimetres)
# ---------------------------------------------------------------------------
MM = 0.001

UNIT_LEN = 10800 * MM      # east-west external
UNIT_WID = 6000 * MM       # north-south external
WALL_EXT = 140 * MM
WALL_INT = 90 * MM

FFL = 0.0
SLAB_BOTTOM = -100 * MM
SUBFRAME_BOTTOM = -450 * MM
WALL_PLATE = 2400 * MM
ROOF_OVERHANG = 600 * MM
ROOF_PITCH_DEG = 15.0
RIDGE_HEIGHT = WALL_PLATE + (UNIT_WID / 2.0) * math.tan(math.radians(ROOF_PITCH_DEG))

CEILING_THICK = 30 * MM

# Zone widths along X (east-west)
ZONE_W_WEST = 3100 * MM
ZONE_W_MID = 4288 * MM
ZONE_W_EAST = 2991 * MM

# Zone depths along Y (north-south)
ZONE_D_NORTH = 3645 * MM   # bedrooms / lounge
ZONE_D_SOUTH = 1999 * MM   # bath / dining / kitchen

# Internal wall positions (south face of wall-N, west face of wall-W etc.)
X_W_INT_FACE = WALL_EXT
X_E_INT_FACE = UNIT_LEN - WALL_EXT
Y_S_INT_FACE = WALL_EXT
Y_N_INT_FACE = UNIT_WID - WALL_EXT

# E-W internal partition between south half and north half
PARTITION_Y0 = Y_S_INT_FACE + ZONE_D_SOUTH
PARTITION_Y1 = PARTITION_Y0 + WALL_INT

# N-S internal partitions in north half (bedroom / lounge separators)
N_PART_W_X0 = X_W_INT_FACE + ZONE_W_WEST
N_PART_W_X1 = N_PART_W_X0 + WALL_INT
N_PART_E_X1 = X_E_INT_FACE - ZONE_W_EAST
N_PART_E_X0 = N_PART_E_X1 - WALL_INT

# N-S internal partitions in south half (bath/dining, kitchen/dining separators)
S_PART_W_X0 = N_PART_W_X0
S_PART_W_X1 = N_PART_W_X1
S_PART_E_X0 = N_PART_E_X0
S_PART_E_X1 = N_PART_E_X1


# ---------------------------------------------------------------------------
# Scene reset (idempotent)
# ---------------------------------------------------------------------------
def reset_scene() -> None:
    bpy.ops.wm.read_factory_settings(use_empty=True)
    for collection in list(bpy.data.collections):
        bpy.data.collections.remove(collection)
    for mat in list(bpy.data.materials):
        bpy.data.materials.remove(mat)
    for mesh in list(bpy.data.meshes):
        bpy.data.meshes.remove(mesh)
    for obj in list(bpy.data.objects):
        bpy.data.objects.remove(obj, do_unlink=True)


# ---------------------------------------------------------------------------
# Materials
# ---------------------------------------------------------------------------
MATERIAL_SPECS = {
    'mat_timber_cladding': {'base_color': (0.45, 0.32, 0.20, 1.0), 'roughness': 0.85},
    'mat_metal_roof':      {'base_color': (0.18, 0.18, 0.20, 1.0), 'roughness': 0.45, 'metallic': 0.6},
    'mat_timber_deck':     {'base_color': (0.55, 0.42, 0.28, 1.0), 'roughness': 0.75},
    'mat_concrete':        {'base_color': (0.78, 0.76, 0.72, 1.0), 'roughness': 0.92},
    'mat_glass':           {'base_color': (0.75, 0.85, 0.90, 0.3), 'roughness': 0.05, 'transmission': 0.95},
    'mat_aluminium':       {'base_color': (0.82, 0.83, 0.84, 1.0), 'roughness': 0.30, 'metallic': 0.85},
    'mat_white_interior':  {'base_color': (0.94, 0.92, 0.88, 1.0), 'roughness': 0.55},
    'mat_porcelain':       {'base_color': (0.96, 0.95, 0.94, 1.0), 'roughness': 0.20},
}


def build_materials() -> dict:
    materials = {}
    for name, props in MATERIAL_SPECS.items():
        mat = bpy.data.materials.new(name=name)
        mat.use_nodes = True
        bsdf = mat.node_tree.nodes.get('Principled BSDF')
        if bsdf is None:
            continue
        bsdf.inputs['Base Color'].default_value = props['base_color']
        bsdf.inputs['Roughness'].default_value = props.get('roughness', 0.5)
        if 'metallic' in props:
            bsdf.inputs['Metallic'].default_value = props['metallic']
        transmission_input = (
            bsdf.inputs.get('Transmission Weight')
            or bsdf.inputs.get('Transmission')
        )
        if 'transmission' in props and transmission_input is not None:
            transmission_input.default_value = props['transmission']
        if props['base_color'][3] < 1.0:
            mat.blend_method = 'BLEND'
            bsdf.inputs['Alpha'].default_value = props['base_color'][3]
        materials[name] = mat
    return materials


def assign_material(obj: bpy.types.Object, material: bpy.types.Material) -> None:
    if obj.data is None or material is None:
        return
    if obj.data.materials:
        obj.data.materials[0] = material
    else:
        obj.data.materials.append(material)


# ---------------------------------------------------------------------------
# Mesh primitives
# ---------------------------------------------------------------------------
def make_box(name: str, x0: float, y0: float, z0: float,
             x1: float, y1: float, z1: float,
             material: bpy.types.Material | None = None) -> bpy.types.Object:
    cx = (x0 + x1) / 2.0
    cy = (y0 + y1) / 2.0
    cz = (z0 + z1) / 2.0
    sx = abs(x1 - x0)
    sy = abs(y1 - y0)
    sz = abs(z1 - z0)
    bpy.ops.mesh.primitive_cube_add(size=1.0, location=(cx, cy, cz))
    obj = bpy.context.active_object
    obj.scale = (sx, sy, sz)
    bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
    obj.name = name
    obj.data.name = name + '_mesh'
    if material is not None:
        assign_material(obj, material)
    return obj


def make_cylinder(name: str, radius: float, depth: float,
                  cx: float, cy: float, cz: float,
                  material: bpy.types.Material | None = None,
                  vertices: int = 16) -> bpy.types.Object:
    bpy.ops.mesh.primitive_cylinder_add(
        radius=radius, depth=depth, vertices=vertices,
        location=(cx, cy, cz),
    )
    obj = bpy.context.active_object
    obj.name = name
    obj.data.name = name + '_mesh'
    if material is not None:
        assign_material(obj, material)
    return obj


def boolean_difference(target: bpy.types.Object, cutters: list[bpy.types.Object]) -> None:
    for cutter in cutters:
        mod = target.modifiers.new(name='cut_' + cutter.name, type='BOOLEAN')
        mod.operation = 'DIFFERENCE'
        mod.object = cutter
        mod.solver = 'FAST'
    bpy.context.view_layer.objects.active = target
    for mod in list(target.modifiers):
        if mod.type == 'BOOLEAN':
            bpy.ops.object.modifier_apply(modifier=mod.name)
    for cutter in cutters:
        bpy.data.objects.remove(cutter, do_unlink=True)


# ---------------------------------------------------------------------------
# Floor + subframe
# ---------------------------------------------------------------------------
def build_floor(materials: dict) -> None:
    make_box(
        'floor_slab',
        0.0, 0.0, SLAB_BOTTOM,
        UNIT_LEN, UNIT_WID, FFL,
        materials['mat_concrete'],
    )
    make_box(
        'floor_subframe',
        0.05, 0.05, SUBFRAME_BOTTOM,
        UNIT_LEN - 0.05, UNIT_WID - 0.05, SLAB_BOTTOM,
        materials['mat_timber_cladding'],
    )


# ---------------------------------------------------------------------------
# External walls (with door + window apertures)
# ---------------------------------------------------------------------------
APERTURES = [
    # name, host_wall, axis-pos centre (along wall length), width, sill_z, head_z, kind
    # south wall apertures (axis = X)
    ('door_main_entry',         'south', X_W_INT_FACE + ZONE_W_WEST + WALL_INT * 0.5, 0.813, 0.0,   2.0,  'door'),
    ('door_dining_slider',      'south', X_W_INT_FACE + ZONE_W_WEST + WALL_INT + ZONE_W_MID / 2.0, 1.800, 0.0, 2.0, 'door'),
    ('window_dining_south',     'south', X_W_INT_FACE + ZONE_W_WEST + WALL_INT + ZONE_W_MID * 0.25, 1.200, 1.100, 2.100, 'window'),
    ('window_kitchen_south',    'south', X_E_INT_FACE - ZONE_W_EAST / 2.0, 1.200, 1.100, 2.100, 'window'),
    # north wall apertures
    ('window_lounge_north',     'north', X_W_INT_FACE + ZONE_W_WEST + WALL_INT + ZONE_W_MID / 2.0, 2.400, 0.600, 2.100, 'window'),
    ('window_bedroom1_north',   'north', X_W_INT_FACE + ZONE_W_WEST / 2.0, 1.200, 0.900, 2.100, 'window'),
    ('window_bedroom2_north',   'north', X_E_INT_FACE - ZONE_W_EAST / 2.0, 1.200, 0.900, 2.100, 'window'),
    # west wall apertures (axis = Y)
    ('window_bedroom1_west',    'west',  Y_S_INT_FACE + ZONE_D_SOUTH + WALL_INT + ZONE_D_NORTH / 2.0, 0.600, 1.500, 2.100, 'window'),
    ('window_bath_west',        'west',  Y_S_INT_FACE + ZONE_D_SOUTH / 2.0, 0.600, 1.500, 2.100, 'window'),
    # east wall apertures
    ('window_bedroom2_east',    'east',  Y_S_INT_FACE + ZONE_D_SOUTH + WALL_INT + ZONE_D_NORTH / 2.0, 0.600, 1.500, 2.100, 'window'),
]


def aperture_box(host_wall: str, centre: float, width: float, sill: float, head: float, depth_pad: float = 0.05):
    """Return (x0,y0,z0,x1,y1,z1) for a cutter that fully passes through the host wall."""
    if host_wall == 'south':
        return (centre - width / 2.0, -depth_pad, sill,
                centre + width / 2.0, WALL_EXT + depth_pad, head)
    if host_wall == 'north':
        return (centre - width / 2.0, UNIT_WID - WALL_EXT - depth_pad, sill,
                centre + width / 2.0, UNIT_WID + depth_pad, head)
    if host_wall == 'west':
        return (-depth_pad, centre - width / 2.0, sill,
                WALL_EXT + depth_pad, centre + width / 2.0, head)
    # east
    return (UNIT_LEN - WALL_EXT - depth_pad, centre - width / 2.0, sill,
            UNIT_LEN + depth_pad, centre + width / 2.0, head)


def build_external_walls(materials: dict) -> None:
    cladding = materials['mat_timber_cladding']

    walls = {
        'wall_external_south': make_box('wall_external_south',
                                        0.0, 0.0, FFL,
                                        UNIT_LEN, WALL_EXT, WALL_PLATE, cladding),
        'wall_external_north': make_box('wall_external_north',
                                        0.0, UNIT_WID - WALL_EXT, FFL,
                                        UNIT_LEN, UNIT_WID, WALL_PLATE, cladding),
        'wall_external_west':  make_box('wall_external_west',
                                        0.0, WALL_EXT, FFL,
                                        WALL_EXT, UNIT_WID - WALL_EXT, WALL_PLATE, cladding),
        'wall_external_east':  make_box('wall_external_east',
                                        UNIT_LEN - WALL_EXT, WALL_EXT, FFL,
                                        UNIT_LEN, UNIT_WID - WALL_EXT, WALL_PLATE, cladding),
    }

    cutters_per_wall: dict[str, list[bpy.types.Object]] = {k: [] for k in walls}
    for ap_name, host, centre, width, sill, head, _kind in APERTURES:
        coords = aperture_box(host, centre, width, sill, head)
        cutter = make_box('_cut_' + ap_name, *coords)
        cutters_per_wall['wall_external_' + host].append(cutter)

    for wall_name, cutters in cutters_per_wall.items():
        if cutters:
            boolean_difference(walls[wall_name], cutters)


# ---------------------------------------------------------------------------
# Internal walls
# ---------------------------------------------------------------------------
INTERNAL_WALLS = [
    # name, x0, y0, x1, y1
    ('wall_internal_bedroom1_bath',
     X_W_INT_FACE, PARTITION_Y0, N_PART_W_X0, PARTITION_Y1),
    ('wall_internal_bedroom2_kitchen',
     N_PART_E_X1, PARTITION_Y0, X_E_INT_FACE, PARTITION_Y1),
    ('wall_internal_bedroom1_lounge',
     N_PART_W_X0, PARTITION_Y1, N_PART_W_X1, Y_N_INT_FACE),
    ('wall_internal_bedroom2_lounge',
     N_PART_E_X0, PARTITION_Y1, N_PART_E_X1, Y_N_INT_FACE),
    ('wall_internal_bath_dining',
     S_PART_W_X0, Y_S_INT_FACE, S_PART_W_X1, PARTITION_Y0),
    ('wall_internal_kitchen_dining',
     S_PART_E_X0, Y_S_INT_FACE, S_PART_E_X1, PARTITION_Y0),
]


def build_internal_walls(materials: dict) -> None:
    interior = materials['mat_white_interior']
    for name, x0, y0, x1, y1 in INTERNAL_WALLS:
        wall = make_box(name, x0, y0, FFL, x1, y1, WALL_PLATE, interior)
        cutter_specs = []
        if name == 'wall_internal_bedroom1_bath':
            cx = (x0 + x1) / 2.0
            cy = (y0 + y1) / 2.0
            cutter_specs.append((
                cx - 0.760 / 2.0, y0 - 0.05, 0.0,
                cx + 0.760 / 2.0, y1 + 0.05, 2.0,
            ))
        elif name == 'wall_internal_bedroom1_lounge':
            cy = (y0 + y1) / 2.0
            cutter_specs.append((
                x0 - 0.05, cy - 0.813 / 2.0, 0.0,
                x1 + 0.05, cy + 0.813 / 2.0, 2.0,
            ))
        elif name == 'wall_internal_bedroom2_lounge':
            cy = (y0 + y1) / 2.0
            cutter_specs.append((
                x0 - 0.05, cy - 0.813 / 2.0, 0.0,
                x1 + 0.05, cy + 0.813 / 2.0, 2.0,
            ))
        if cutter_specs:
            cutters = [make_box('_cut_int_' + name + str(i), *c) for i, c in enumerate(cutter_specs)]
            boolean_difference(wall, cutters)


# ---------------------------------------------------------------------------
# Roof (gable) + fascia + ceiling
# ---------------------------------------------------------------------------
def build_roof(materials: dict) -> None:
    metal = materials['mat_metal_roof']
    timber = materials['mat_timber_cladding']

    half_w = UNIT_WID / 2.0
    eave_y_north = UNIT_WID + ROOF_OVERHANG
    eave_y_south = -ROOF_OVERHANG
    eave_x_west = -ROOF_OVERHANG
    eave_x_east = UNIT_LEN + ROOF_OVERHANG

    # Roof plane thickness (apparent slab of roofing)
    roof_thick = 60 * MM
    rise_total = (half_w + ROOF_OVERHANG) * math.tan(math.radians(ROOF_PITCH_DEG))
    eave_z = WALL_PLATE - ROOF_OVERHANG * math.tan(math.radians(ROOF_PITCH_DEG))
    ridge_z_apex = WALL_PLATE + half_w * math.tan(math.radians(ROOF_PITCH_DEG))

    # Build a flat panel mesh and rotate it to the pitched plane.
    panel_len = UNIT_LEN + 2 * ROOF_OVERHANG
    panel_slope = math.hypot(half_w + ROOF_OVERHANG, rise_total)

    def make_pitched_panel(name: str, side: str) -> bpy.types.Object:
        sign = -1.0 if side == 'south' else 1.0
        # Build axis-aligned panel centred on ridge line, then rotate around X.
        bpy.ops.mesh.primitive_cube_add(size=1.0, location=(0, 0, 0))
        obj = bpy.context.active_object
        obj.scale = (panel_len, panel_slope, roof_thick)
        bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
        # translate so ridge edge sits on ridge line
        # before rotation: panel centred at origin, extends ±panel_slope/2 in Y
        # we want one edge at Y=0 (ridge) extending to Y = -panel_slope (downhill)
        obj.location = (panel_len / 2.0, -panel_slope / 2.0, 0)
        bpy.ops.object.transform_apply(location=True, rotation=False, scale=False)
        # rotate around X so the panel pitches down from ridge
        rot = math.radians(ROOF_PITCH_DEG) * sign
        obj.rotation_euler = (rot, 0.0, 0.0)
        bpy.ops.object.transform_apply(location=False, rotation=True, scale=False)
        # translate to position: ridge sits along Y = half_w at z = ridge_z_apex
        if side == 'south':
            obj.location = (-ROOF_OVERHANG, half_w, ridge_z_apex)
        else:
            # mirror across ridge line by rotating 180 around Z then placing
            obj.rotation_euler = (0, 0, math.radians(180.0))
            bpy.ops.object.transform_apply(location=False, rotation=True, scale=False)
            obj.location = (UNIT_LEN + ROOF_OVERHANG, half_w, ridge_z_apex)
        bpy.ops.object.transform_apply(location=True, rotation=False, scale=False)
        obj.name = name
        obj.data.name = name + '_mesh'
        assign_material(obj, metal)
        return obj

    make_pitched_panel('roof_gable_south', 'south')
    make_pitched_panel('roof_gable_north', 'north')

    # Ridge cap
    make_box(
        'roof_ridge',
        -ROOF_OVERHANG, half_w - 0.05, ridge_z_apex - 0.01,
        UNIT_LEN + ROOF_OVERHANG, half_w + 0.05, ridge_z_apex + 0.05,
        metal,
    )

    # Fascia boards along eaves
    fascia_h = 0.20
    make_box('roof_fascia_south',
             eave_x_west, eave_y_south - 0.02, eave_z - fascia_h,
             eave_x_east, eave_y_south + 0.02, eave_z, timber)
    make_box('roof_fascia_north',
             eave_x_west, eave_y_north - 0.02, eave_z - fascia_h,
             eave_x_east, eave_y_north + 0.02, eave_z, timber)
    # East/west fascia run along gable ends, sloped — model as flat boards
    # sitting just inboard of the eave_x_west/east lines, full height of gable.
    make_box('roof_fascia_west',
             eave_x_west - 0.02, eave_y_south, eave_z - fascia_h,
             eave_x_west + 0.02, eave_y_north, ridge_z_apex, timber)
    make_box('roof_fascia_east',
             eave_x_east - 0.02, eave_y_south, eave_z - fascia_h,
             eave_x_east + 0.02, eave_y_north, ridge_z_apex, timber)

    # Ceiling
    make_box('ceiling_main',
             WALL_EXT, WALL_EXT, WALL_PLATE - CEILING_THICK,
             UNIT_LEN - WALL_EXT, UNIT_WID - WALL_EXT, WALL_PLATE,
             materials['mat_white_interior'])


# ---------------------------------------------------------------------------
# Doors and windows (leaves / panes inside the apertures)
# ---------------------------------------------------------------------------
DOORS = [
    # name, host, centre, width, height
    ('door_main_entry',    'south', X_W_INT_FACE + ZONE_W_WEST + WALL_INT * 0.5, 0.813, 2.0),
    ('door_dining_slider', 'south', X_W_INT_FACE + ZONE_W_WEST + WALL_INT + ZONE_W_MID / 2.0, 1.800, 2.0),
]

INT_DOORS = [
    # name, position descriptor, width, height
    ('door_bathroom',  'wall_internal_bedroom1_bath', 0.760, 2.0),
    ('door_bedroom1',  'wall_internal_bedroom1_lounge', 0.813, 2.0),
    ('door_bedroom2',  'wall_internal_bedroom2_lounge', 0.813, 2.0),
]

WINDOWS = [
    ('window_lounge_north',     'north', X_W_INT_FACE + ZONE_W_WEST + WALL_INT + ZONE_W_MID / 2.0, 2.400, 0.600, 2.100),
    ('window_dining_south',     'south', X_W_INT_FACE + ZONE_W_WEST + WALL_INT + ZONE_W_MID * 0.25, 1.200, 1.100, 2.100),
    ('window_kitchen_south',    'south', X_E_INT_FACE - ZONE_W_EAST / 2.0, 1.200, 1.100, 2.100),
    ('window_bedroom1_north',   'north', X_W_INT_FACE + ZONE_W_WEST / 2.0, 1.200, 0.900, 2.100),
    ('window_bedroom1_west',    'west',  Y_S_INT_FACE + ZONE_D_SOUTH + WALL_INT + ZONE_D_NORTH / 2.0, 0.600, 1.500, 2.100),
    ('window_bath_west',        'west',  Y_S_INT_FACE + ZONE_D_SOUTH / 2.0, 0.600, 1.500, 2.100),
    ('window_bedroom2_north',   'north', X_E_INT_FACE - ZONE_W_EAST / 2.0, 1.200, 0.900, 2.100),
    ('window_bedroom2_east',    'east',  Y_S_INT_FACE + ZONE_D_SOUTH + WALL_INT + ZONE_D_NORTH / 2.0, 0.600, 1.500, 2.100),
]


def build_doors_and_windows(materials: dict) -> None:
    glass = materials['mat_glass']
    aluminium = materials['mat_aluminium']
    interior = materials['mat_white_interior']

    pane_thick = 8 * MM

    # External doors (leaves sit inside aperture, half-glazed where relevant)
    for name, host, centre, width, height in DOORS:
        if host == 'south':
            x0 = centre - width / 2.0
            x1 = centre + width / 2.0
            y_centre = WALL_EXT / 2.0
            y0 = y_centre - pane_thick / 2.0
            y1 = y_centre + pane_thick / 2.0
            make_box(name, x0, y0, 0.0, x1, y1, height, aluminium)

    # Internal doors as thin leaves in the partition
    int_wall_lookup = {entry[0]: entry[1:] for entry in INTERNAL_WALLS}
    for name, host_wall, width, height in INT_DOORS:
        extents = int_wall_lookup.get(host_wall)
        if extents is None:
            continue
        x0, y0, x1, y1 = extents
        cx = (x0 + x1) / 2.0
        cy = (y0 + y1) / 2.0
        if abs(x1 - x0) > abs(y1 - y0):
            make_box(name,
                     cx - width / 2.0, cy - pane_thick / 2.0, 0.0,
                     cx + width / 2.0, cy + pane_thick / 2.0, height,
                     interior)
        else:
            make_box(name,
                     cx - pane_thick / 2.0, cy - width / 2.0, 0.0,
                     cx + pane_thick / 2.0, cy + width / 2.0, height,
                     interior)

    # Windows: glazed pane sitting in aperture
    for name, host, centre, width, sill, head in WINDOWS:
        if host in ('north', 'south'):
            y_centre = WALL_EXT / 2.0
            x0 = centre - width / 2.0
            x1 = centre + width / 2.0
            if host == 'north':
                y_centre = UNIT_WID - WALL_EXT / 2.0
            make_box(name,
                     x0, y_centre - pane_thick / 2.0, sill,
                     x1, y_centre + pane_thick / 2.0, head,
                     glass)
        else:
            x_centre = WALL_EXT / 2.0
            y0 = centre - width / 2.0
            y1 = centre + width / 2.0
            if host == 'east':
                x_centre = UNIT_LEN - WALL_EXT / 2.0
            make_box(name,
                     x_centre - pane_thick / 2.0, y0, sill,
                     x_centre + pane_thick / 2.0, y1, head,
                     glass)


# ---------------------------------------------------------------------------
# Decks + piles
# ---------------------------------------------------------------------------
def build_decks_and_piles(materials: dict) -> None:
    deck_mat = materials['mat_timber_deck']
    concrete = materials['mat_concrete']

    # North deck: full unit length, raised
    make_box('deck_north',
             0.0, UNIT_WID, SLAB_BOTTOM,
             UNIT_LEN, UNIT_WID + 1.500, FFL,
             deck_mat)

    # South entry deck (between main entry and dining slider span)
    deck_south_x0 = X_W_INT_FACE + ZONE_W_WEST  # roughly aligns with main entry
    deck_south_x1 = deck_south_x0 + 6.000
    if deck_south_x1 > UNIT_LEN:
        deck_south_x1 = UNIT_LEN
        deck_south_x0 = max(0.0, deck_south_x1 - 6.000)
    make_box('deck_south',
             deck_south_x0, -1.500, SUBFRAME_BOTTOM + 0.1,
             deck_south_x1, 0.0, FFL,
             deck_mat)

    pile_radius = 0.125
    pile_top = SLAB_BOTTOM
    pile_bottom = SUBFRAME_BOTTOM - 0.500
    pile_height = pile_top - pile_bottom

    pile_positions = {
        'pile_nw':    (0.300, UNIT_WID - 0.300),
        'pile_ne':    (UNIT_LEN - 0.300, UNIT_WID - 0.300),
        'pile_sw':    (0.300, 0.300),
        'pile_se':    (UNIT_LEN - 0.300, 0.300),
        'pile_mid_n': (UNIT_LEN / 2.0, UNIT_WID - 0.300),
        'pile_mid_s': (UNIT_LEN / 2.0, 0.300),
    }
    for name, (px, py) in pile_positions.items():
        make_cylinder(name, pile_radius, pile_height,
                      px, py, pile_bottom + pile_height / 2.0,
                      concrete)


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------
def build_fixtures(materials: dict) -> None:
    porcelain = materials['mat_porcelain']
    interior = materials['mat_white_interior']

    # Bath zone (south-west cell). South wall at y0=WALL_EXT, north wall at PARTITION_Y0,
    # west wall at WALL_EXT, east wall at S_PART_W_X0.
    bath_x0 = X_W_INT_FACE
    bath_x1 = S_PART_W_X0
    bath_y0 = Y_S_INT_FACE
    bath_y1 = PARTITION_Y0

    # toilet — south-east corner of bath
    make_box('fixture_bath_toilet',
             bath_x1 - 0.700 - 0.05, bath_y0 + 0.05, 0.0,
             bath_x1 - 0.05, bath_y0 + 0.05 + 0.400, 0.400,
             porcelain)
    # shower — south-west corner of bath
    make_box('fixture_bath_shower',
             bath_x0 + 0.02, bath_y0 + 0.02, 0.0,
             bath_x0 + 0.02 + 0.900, bath_y0 + 0.02 + 0.900, 2.000,
             porcelain)
    # wall-hung basin on north wall of bath
    make_box('fixture_bath_basin',
             bath_x0 + 0.6, bath_y1 - 0.400 - 0.02, 0.85,
             bath_x0 + 0.6 + 0.600, bath_y1 - 0.02, 1.00,
             porcelain)
    # hot water cylinder — protrudes from north wall of bath
    make_box('fixture_hot_water_cylinder',
             bath_x1 - 0.6 - 0.05, bath_y1 - 0.6 - 0.02, 0.0,
             bath_x1 - 0.05, bath_y1 - 0.02, 2.000,
             interior)

    # Kitchen zone (south-east cell)
    kit_x0 = S_PART_E_X1
    kit_x1 = X_E_INT_FACE
    kit_y0 = Y_S_INT_FACE
    kit_y1 = PARTITION_Y0
    bench_d = 0.600

    # L-shaped bench: combine east-leg + south-leg as union via two boxes joined.
    east_leg = make_box('_kitbench_east',
                        kit_x1 - bench_d, kit_y0, 0.0,
                        kit_x1, kit_y1, 0.900,
                        interior)
    south_leg = make_box('_kitbench_south',
                         kit_x0, kit_y0, 0.0,
                         kit_x1 - bench_d, kit_y0 + bench_d, 0.900,
                         interior)
    # Join the two pieces into a single named object
    bpy.ops.object.select_all(action='DESELECT')
    east_leg.select_set(True)
    south_leg.select_set(True)
    bpy.context.view_layer.objects.active = east_leg
    bpy.ops.object.join()
    bench = bpy.context.active_object
    bench.name = 'fixture_kitchen_bench'
    bench.data.name = 'fixture_kitchen_bench_mesh'

    # Sink cutout placeholder — independent named object inside bench
    sink_cx = kit_x1 - bench_d / 2.0
    sink_cy = kit_y0 + (kit_y1 - kit_y0) * 0.55
    make_box('fixture_kitchen_sink',
             sink_cx - 0.350, sink_cy - 0.200, 0.85,
             sink_cx + 0.350, sink_cy + 0.200, 0.91,
             porcelain)


# ---------------------------------------------------------------------------
# Export
# ---------------------------------------------------------------------------
def export_glb() -> str:
    out_path = os.path.join(os.getcwd(), 'demo-unit-16c.glb')
    bpy.ops.object.select_all(action='SELECT')
    bpy.ops.export_scene.gltf(
        filepath=out_path,
        export_format='GLB',
        export_draco_mesh_compression_enable=True,
        export_draco_mesh_compression_level=6,
        export_apply=True,
        export_yup=True,
        export_materials='EXPORT',
        export_cameras=False,
        export_lights=False,
        export_extras=False,
        export_morph=False,
        export_animations=False,
    )
    return out_path


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main() -> None:
    reset_scene()
    materials = build_materials()
    build_floor(materials)
    build_external_walls(materials)
    build_internal_walls(materials)
    build_roof(materials)
    build_doors_and_windows(materials)
    build_decks_and_piles(materials)
    build_fixtures(materials)
    out = export_glb()
    object_names = sorted(o.name for o in bpy.data.objects)
    print(f'[build_unit] wrote {out}')
    print(f'[build_unit] {len(object_names)} named objects:')
    for n in object_names:
        print(f'  - {n}')


if __name__ == '__main__':
    main()
