// ═══════════════════════════════════════════════════════════════════════
// ako-transparency-pack — generates the four whānau-facing transparency
// documents required by the 20 April 2026 ECE licensing regime.
//
// POST { centre: { name, licenceNumber, manager, address, lastEroReview,
//                  policiesHeld[] }, voice?: "warm"|"plain"|"formal" }
// → { ok, version, generatedAt, documents: { complaints, ero, licensing,
//                                            operational } }
//
// Documents produced (markdown):
//   1. complaints       — complaints procedure incl. Director of Regulation pathway
//   2. ero              — ERO report access instructions
//   3. licensing        — current licensing status statement
//   4. operational      — operational document summary
//
// Uses Lovable AI Gateway (google/gemini-2.5-flash) for drafting, then
// applies the legislative-citation block deterministically so the
// references can't drift.
//
// HIGH-RISK kete: outputs are draft-only and watermarked for head-teacher
// review. Never auto-publishes.
// ═══════════════════════════════════════════════════════════════════════
const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

import { createClient } from "https://esm.sh/@supabase/supabase-js@2.49.4";
import { resolveModel, DEFAULT_MODEL } from "../_shared/model-router.ts";

const LOVABLE_AI_BASE = "https://ai.gateway.lovable.dev/v1";
// Resolved at request time via resolveModel("ako", supabase). Constant
// retained as a safe fallback if the helper or DB are unreachable.
const MODEL = DEFAULT_MODEL;
const PACK_VERSION = "v2026-04-20";

// Deterministic legislative footer appended to every doc — never AI-generated.
const REFERENCES = `
---
**Legislative basis (current as of 20 April 2026)**
- Education and Training Act 2020, Part 3 — Early Childhood Education
- Education (Early Childhood Services) Regulations 2008 (consolidated April 2026)
- Licensing Criteria for ECE and Care Services 2008 — 78-criterion regime effective 20 April 2026
- Children's Act 2014 — Safety Checking of the Children's Workforce
- Privacy Act 2020 + Health Information Privacy Code 2020

*Generated by Assembl AKO · Pack ${PACK_VERSION} · DRAFT for head-teacher review and sign-off before issuing to whānau.*`.trim();

interface CentreInput {
  name?: string;
  licenceNumber?: string;
  manager?: string;
  address?: string;
  lastEroReview?: string;
  policiesHeld?: string[];
}

function buildPrompt(centre: CentreInput, voice: string) {
  const policies = (centre.policiesHeld ?? []).filter(Boolean);
  const policyList = policies.length
    ? policies.map((p) => `- ${p}`).join("\n")
    : "- (no policies declared yet)";

  return `You are NOVA-AKO, an Assembl AGENT drafting four short whānau-facing
documents for an Aotearoa New Zealand early-learning service. Reading age 12.
Tone: ${voice}. Use plain English. Use "whānau" not "parents". Use "tamariki"
when natural. NEVER invent facts, complaint addresses, dates, or statistics.
If a fact is missing, write "[centre to confirm]" inline.

CENTRE:
- Name: ${centre.name ?? "[centre to confirm]"}
- Licence number: ${centre.licenceNumber ?? "[centre to confirm]"}
- Manager / person responsible: ${centre.manager ?? "[centre to confirm]"}
- Address: ${centre.address ?? "[centre to confirm]"}
- Last ERO review: ${centre.lastEroReview ?? "[centre to confirm]"}

POLICIES HELD:
${policyList}

Return ONLY valid JSON matching this shape — no preamble, no markdown fence:
{
  "complaints":  "...markdown body...",
  "ero":         "...markdown body...",
  "licensing":   "...markdown body...",
  "operational": "...markdown body..."
}

REQUIREMENTS for each doc:
- "complaints": three escalation steps — (1) head teacher, (2) licensee /
  service manager, (3) Director of Regulation at the Ministry of Education
  (use the exact phrase "Director of Regulation" — that role is live from
  23 Feb 2026). Include the Tenancy/ECE complaints email placeholder
  "[centre to confirm complaints email]". Mention timeframes: 5 working days
  to acknowledge, 20 working days to resolve.
- "ero": explain that ERO reviews are public, link by exact URL
  "https://ero.govt.nz/review-reports", and tell whānau they can request
  the centre's most recent review or any earlier review through the centre
  manager. 6-8 sentences max.
- "licensing": one paragraph stating the licence number, that the service
  is licensed under the Education and Training Act 2020, the date of last
  ERO review, and how to ask to see a copy of the licence on the wall.
- "operational": a bulleted list of the policies held (verbatim from POLICIES
  HELD above) followed by one sentence saying any whānau can ask to read
  any policy and the centre will provide a copy within 5 working days.

Do NOT include the legislative reference block — that is added separately.
Each doc body must NOT start with a heading; the caller adds the heading.`;
}

interface DocSet {
  complaints: string;
  ero: string;
  licensing: string;
  operational: string;
}

function withFrame(title: string, body: string, centreName: string) {
  return `# ${title}\n_${centreName} · Pack ${PACK_VERSION}_\n\n${body}\n\n${REFERENCES}\n`;
}

function fallbackDocs(centre: CentreInput): DocSet {
  const name = centre.name ?? "[centre to confirm]";
  const policies = (centre.policiesHeld ?? []).filter(Boolean);
  const policyLines = policies.length
    ? policies.map((p) => `- ${p}`).join("\n")
    : "- [centre to confirm policies held]";
  return {
    complaints:
      `If you have a concern, please raise it with us. We take every concern seriously.\n\n` +
      `**Step 1 — Head teacher.** Talk with your child's head teacher. We will acknowledge in writing within 5 working days and aim to resolve within 20 working days.\n\n` +
      `**Step 2 — Service manager.** If the matter is not resolved, contact ${centre.manager ?? "[centre to confirm]"}, our service manager, in writing at [centre to confirm complaints email].\n\n` +
      `**Step 3 — Director of Regulation.** From 23 February 2026, you can escalate to the Director of Regulation at the Ministry of Education. Visit education.govt.nz for the current contact details.`,
    ero:
      `ERO (Education Review Office) reviews early-learning services and publishes the reports publicly.\n\n` +
      `You can read our most recent ERO review at https://ero.govt.nz/review-reports — search for "${name}".\n\n` +
      `If you want a printed copy or an earlier report, ask the centre manager and we will provide it within 5 working days.`,
    licensing:
      `${name} is licensed under the Education and Training Act 2020. Our licence number is ${centre.licenceNumber ?? "[centre to confirm]"}. ` +
      `Our last ERO review was ${centre.lastEroReview ?? "[centre to confirm]"}. A copy of our current licence is displayed in the entrance — ask any kaiako if you would like to see it.`,
    operational:
      `We hold the following operational documents and policies:\n\n${policyLines}\n\n` +
      `Any whānau member can ask to read any policy. We will provide a copy within 5 working days.`,
  };
}

interface AiResp {
  choices?: Array<{ message?: { content?: string } }>;
  error?: { message?: string };
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  try {
    const body = await req.json().catch(() => ({}));
    const centre: CentreInput = body?.centre ?? {};
    const voice = ["warm", "plain", "formal"].includes(body?.voice) ? body.voice : "warm";
    const centreName = centre.name?.trim() || "Your centre";

    const lovableKey = Deno.env.get("LOVABLE_API_KEY");
    let docs: DocSet | null = null;
    let usedFallback = false;
    let modelMsg = "";

    if (lovableKey) {
      try {
        const sb = createClient(
          Deno.env.get("SUPABASE_URL")!,
          Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
        );
        const akoModel = await resolveModel("ako", sb);
        const aiRes = await fetch(`${LOVABLE_AI_BASE}/chat/completions`, {
          method: "POST",
          headers: { Authorization: `Bearer ${lovableKey}`, "Content-Type": "application/json" },
          body: JSON.stringify({
            model: akoModel,
            messages: [
              { role: "system", content: "You return only valid JSON. No prose, no fences." },
              { role: "user", content: buildPrompt(centre, voice) },
            ],
            response_format: { type: "json_object" },
          }),
        });
        const aiJson = (await aiRes.json().catch(() => null)) as AiResp | null;
        if (aiRes.ok && aiJson?.choices?.[0]?.message?.content) {
          const raw = aiJson.choices[0].message.content;
          const parsed = JSON.parse(raw) as Partial<DocSet>;
          if (parsed.complaints && parsed.ero && parsed.licensing && parsed.operational) {
            docs = parsed as DocSet;
          } else {
            modelMsg = "ai response missing one or more docs";
          }
        } else {
          modelMsg = `ai ${aiRes.status}: ${aiJson?.error?.message ?? "unknown"}`;
        }
      } catch (err) {
        modelMsg = err instanceof Error ? err.message : "ai call threw";
      }
    } else {
      modelMsg = "LOVABLE_API_KEY not configured";
    }

    if (!docs) {
      docs = fallbackDocs(centre);
      usedFallback = true;
    }

    const documents = {
      complaints:  withFrame("Complaints procedure", docs.complaints, centreName),
      ero:         withFrame("How to read our ERO review", docs.ero, centreName),
      licensing:   withFrame("Our licensing status", docs.licensing, centreName),
      operational: withFrame("Operational documents we hold", docs.operational, centreName),
    };

    return new Response(JSON.stringify({
      ok: true,
      version: PACK_VERSION,
      generatedAt: new Date().toISOString(),
      mode: usedFallback ? "fallback" : "ai",
      modelNote: modelMsg || undefined,
      documents,
    }), { status: 200, headers: { ...corsHeaders, "Content-Type": "application/json" } });
  } catch (err) {
    const msg = err instanceof Error ? err.message : "Unknown error";
    return new Response(JSON.stringify({ error: msg }), {
      status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
