export interface KeteAgent {
  name: string;
  desc: string;
  status?: 'existing' | 'restored' | 'new';
  capabilities?: string[];
}

export interface KeteData {
  slug: string;
  name: string;
  englishName: string;
  description: string;
  longDescription: string;
  agentCount: number;
  accentColor: string;
  accentLight: string;
  variant: 'standard' | 'dense' | 'organic' | 'tricolor' | 'warm';
  category: 'industry' | 'specialist' | 'whanau';
  badge?: string;
  agents: KeteAgent[];
  keyCapabilities: string[];
  legislationCovered: string[];
}

export const SHARED_CORE_AGENTS: KeteAgent[] = [
  { name: 'CHARTER', desc: 'Company governance & director duties', status: 'new', capabilities: ['Companies Act 1993 compliance', 'Director duty guidance', 'Board governance frameworks', 'Annual return preparation', 'Shareholder agreements'] },
  { name: 'ARBITER', desc: 'Dispute resolution & legal remedies', status: 'new', capabilities: ['Mediation guidance', 'Arbitration Act compliance', 'Disputes Tribunal preparation', 'Employment disputes', 'Contractual remedies'] },
  { name: 'SHIELD', desc: 'Privacy Act 2020 & data protection', status: 'new', capabilities: ['Privacy impact assessments', 'Breach notification workflows', 'Cross-border data transfer rules', 'IPP compliance checks', 'Data retention policies'] },
  { name: 'ANCHOR', desc: 'Non-profit, charities & community organisations', status: 'new', capabilities: ['Charities Act compliance', 'Incorporated Societies Act 2022', 'Grant application writing', 'Governance frameworks', 'Annual reporting'] },
  { name: 'AROHA', desc: 'HR & employment relations', status: 'existing', capabilities: ['Employment agreements (ERA s65)', 'Personal grievance workflows', 'Performance management', 'Restructuring & redundancy', 'Leave entitlements'] },
  { name: 'PULSE', desc: 'Employment law & payroll compliance', status: 'new', capabilities: ['PAYE calculations', 'Holiday pay (Holidays Act)', 'KiwiSaver employer obligations', 'Minimum wage compliance', 'Parental leave administration'] },
  { name: 'SCHOLAR', desc: 'Education & training sector compliance', status: 'new', capabilities: ['NZQA framework guidance', 'Education Act compliance', 'Training programme design', 'Micro-credential frameworks', 'Professional development planning'] },
  { name: 'NOVA', desc: 'General operations & technical troubleshooting', status: 'new', capabilities: ['Process optimisation', 'Workflow automation', 'Technical troubleshooting', 'Tool integration', 'Productivity audits'] },
];

export const KETE_DATA: KeteData[] = [
  {
    slug: 'manaaki',
    name: 'Manaaki',
    englishName: 'Hospitality & Tourism',
    description: 'Your venue runs itself. Food safety, liquor licensing, guest experience — compliance without the paperwork pile-up.',
    longDescription: 'The Manaaki kete covers every aspect of New Zealand hospitality — from Food Act 2014 food control plans and Sale of Alcohol Act licensing, to luxury lodging operations, cultural tourism (tikanga-aligned), adventure activity regulation, coastal tourism, and large-scale event catering.',
    agentCount: 9,
    accentColor: '#D4A843',
    accentLight: '#F0D078',
    variant: 'standard',
    category: 'industry',
    keyCapabilities: [
      'Food control plans & Food Act 2014 compliance',
      'Liquor licensing & Sale of Alcohol Act management',
      'Guest experience workflows & staff training',
      'Luxury lodging & premium hospitality operations',
      'Adventure Activities Register & safety management',
      'Cultural tourism & tikanga Māori protocols',
      'Event catering & temporary food operations',
      'Revenue management & booking optimisation',
    ],
    legislationCovered: ['Food Act 2014', 'Sale and Supply of Alcohol Act 2012', 'HSWA 2015', 'Adventure Activities Regulations'],
    agents: [
      { name: 'AURA', desc: 'Front-of-house operations & guest experience', status: 'existing', capabilities: ['Guest welcome workflows', 'Staff training matrices', 'Revenue management', 'Booking optimisation', 'Service standards', 'Housekeeping scheduling'] },
      { name: 'SAFFRON', desc: 'Food safety & Food Act 2014 compliance', status: 'restored', capabilities: ['Food control plans', 'Temperature monitoring logs', 'Allergen management', 'MPI audit preparation', 'HACCP plans', 'Kitchen hygiene protocols'] },
      { name: 'CELLAR', desc: 'Liquor licensing & Sale of Alcohol Act', status: 'restored', capabilities: ['On/off-licence applications', 'DLC submissions', 'Duty manager certification', 'Host responsibility policies', 'LCQ preparation'] },
      { name: 'LUXE', desc: 'Luxury lodging & premium hospitality', status: 'new', capabilities: ['VIP guest management', 'Concierge services', 'Premium dining curation', 'Loyalty programme design', 'Luxury pricing strategy'] },
      { name: 'MOANA', desc: 'Tourism operations & adventure compliance', status: 'existing', capabilities: ['Tour operator compliance', 'Risk assessment frameworks', 'Seasonal planning', 'Itinerary design', 'Visitor experience management'] },
      { name: 'COAST', desc: 'Coastal & marine tourism', status: 'existing', capabilities: ['Water safety compliance', 'Eco-tourism certification', 'Marine insurance guidance', 'Environmental impact assessments', 'Coastal activity operations'] },
      { name: 'KURA', desc: 'Cultural tourism & Māori hospitality', status: 'existing', capabilities: ['Māori hospitality protocols', 'Pōwhiri guidance', 'Cultural experience design', 'Tikanga compliance', 'Cultural narrative development'] },
      { name: 'PAU', desc: 'Event catering & temporary food operations', status: 'existing', capabilities: ['Event catering compliance', 'Temporary food stall registration', 'Large-scale food safety', 'Menu planning at scale', 'Vendor coordination'] },
      { name: 'SUMMIT', desc: 'Tourism & adventure activities regulation', status: 'restored', capabilities: ['Adventure Activities Register', 'Safety audit preparation', 'Operator certification', 'WorkSafe compliance', 'Risk management systems'] },
    ],
  },
  {
    slug: 'waihanga',
    name: 'Waihanga',
    englishName: 'Construction',
    description: 'Site to sign-off. Safety plans, BIM coordination, consenting, tenders — approvals that don\'t stall.',
    longDescription: 'The Waihanga kete is the complete construction intelligence platform — from site safety and BIM model analysis, to project management under NZS 3910, resource consent navigation, quality assurance, architecture compliance, and GETS tender writing.',
    agentCount: 9,
    accentColor: '#3A7D6E',
    accentLight: '#7ECFC2',
    variant: 'standard',
    category: 'industry',
    keyCapabilities: [
      'Site safety plans & HSWA compliance',
      'BIM analysis, clash detection & 4D scheduling',
      'Project management & NZS 3910 contracts',
      'Resource consent & RMA compliance',
      'Quality assurance & defect tracking',
      'NZ Building Code compliance checking',
      'Land management & property development',
      'GETS tender & award submission writing',
    ],
    legislationCovered: ['HSWA 2015', 'Building Act 2004', 'NZ Building Code', 'CCA 2002', 'RMA 1991', 'NZS 3910'],
    agents: [
      { name: 'ATA', desc: 'Building Information Modelling (BIM)', status: 'existing' },
      { name: 'ĀRAI', desc: 'Site safety & H&S compliance (WorkSafe)', status: 'existing' },
      { name: 'KAUPAPA', desc: 'Project management & contract administration', status: 'existing' },
      { name: 'RAWA', desc: 'Resources, procurement & supply chain', status: 'existing' },
      { name: 'WHAKAAĒ', desc: 'Resource consent & planning compliance', status: 'existing' },
      { name: 'PAI', desc: 'Quality assurance & building standards', status: 'existing' },
      { name: 'ARC', desc: 'Architecture & NZ Building Code compliance', status: 'restored' },
      { name: 'TERRA', desc: 'Property & land management (RMA)', status: 'restored' },
      { name: 'PINNACLE', desc: 'Construction awards, tenders & application writing', status: 'new' },
    ],
  },
  {
    slug: 'auaha',
    name: 'Auaha',
    englishName: 'Creative & Media',
    description: 'Brief to published. Copy, design, video, ads, analytics — one coordinated studio, not six tools and a freelancer.',
    longDescription: 'The Auaha kete runs the complete 8-stage creative pipeline: Brief → Copy → Design → Video → Schedule → Publish → Analyse → Iterate. Nine specialist agents handle brand identity, copywriting, visual design, image generation, video production, podcast creation, colour systems, and marketing compliance.',
    agentCount: 9,
    accentColor: '#F0D078',
    accentLight: '#FFE866',
    variant: 'standard',
    category: 'industry',
    keyCapabilities: [
      'Brand DNA development & visual identity',
      'Content creation with Kiwi voice',
      'Image generation & design innovation',
      'Video production & social media content',
      'Podcast scripting & audio production',
      'Colour systems & design system management',
      'Ad campaign creation & Fair Trading compliance',
      'Social media scheduling & analytics',
    ],
    legislationCovered: ['Fair Trading Act 1986', 'Copyright Act 1994', 'ASA Codes'],
    agents: [
      { name: 'PRISM', desc: 'Creative design & brand development', status: 'existing' },
      { name: 'MUSE', desc: 'Content creation & copywriting', status: 'existing' },
      { name: 'PIXEL', desc: 'Visual design & digital media', status: 'existing' },
      { name: 'VERSE', desc: 'Narrative design & storytelling', status: 'existing' },
      { name: 'ECHO', desc: 'Technical production & platform setup', status: 'existing' },
      { name: 'FLUX', desc: 'Image generation & design innovation', status: 'existing' },
      { name: 'CHROMATIC', desc: 'Colour, brand aesthetics & visual identity', status: 'existing' },
      { name: 'RHYTHM', desc: 'Audio, podcast & media production', status: 'existing' },
      { name: 'MARKET', desc: 'Marketing & advertising compliance (Fair Trading)', status: 'restored' },
    ],
  },
  {
    slug: 'arataki',
    name: 'Arataki',
    englishName: 'Automotive',
    description: 'Enquiry → test drive → sale → delivery → service → loyalty. No handoff dropped across DMS, CRM, and OEM portals.',
    longDescription: 'The Arataki kete is built for automotive dealerships — the complete customer relay race from first enquiry to long-term loyalty. Eleven specialist workflows cover sales pipeline, F&I compliance, service scheduling, warranty claims, loan car allocation, and IPP3A privacy obligations.',
    agentCount: 11,
    accentColor: '#E8E8E8',
    accentLight: '#FFFFFF',
    variant: 'standard',
    category: 'industry',
    badge: 'IPP3A READY · MAY 2026',
    keyCapabilities: [
      'Customer journey orchestration (enquiry to loyalty)',
      'F&I disclosure & CCCFA compliance',
      'Service scheduling & workshop management',
      'Warranty claim narrative drafting',
      'Loan car allocation & fleet tracking',
      'IPP3A privacy compliance (effective 1 May 2026)',
      'DMS/CRM integration workflows',
      'Vehicle listing & stock management',
    ],
    legislationCovered: ['Motor Vehicle Sales Act 2003', 'CCCFA 2003', 'Privacy Act 2020 (IPP3A)', 'Consumer Guarantees Act 1993'],
    agents: [
      { name: 'MOTOR', desc: 'Sales pipeline & dealership compliance', status: 'existing' },
      { name: 'PĪKAU', desc: 'Privacy Act 2020 & IPP3A compliance', status: 'new' },
      { name: 'SHIELD', desc: 'Data protection & breach notification', status: 'new' },
      { name: 'AROHA', desc: 'HR & employment data compliance', status: 'existing' },
    ],
  },
  {
    slug: 'pikau',
    name: 'Pikau',
    englishName: 'Freight & Customs',
    description: 'Route optimisation, declarations, broker hand-off, customs compliance. Border compliance without the scramble.',
    longDescription: 'The Pikau kete handles customs entries, tariff classification, freight quoting, dangerous goods checks, biosecurity clearances, and MPI import standards — everything a freight forwarder or customs broker needs.',
    agentCount: 7,
    accentColor: '#5AADA0',
    accentLight: '#7ECFC2',
    variant: 'dense',
    category: 'industry',
    keyCapabilities: [
      'Customs entry processing & declarations',
      'HS code tariff classification',
      'Freight route optimisation & quoting',
      'Dangerous goods (HSNO) classification',
      'Biosecurity clearance & MPI standards',
      'Landed cost calculation & FTA analysis',
      'Broker hand-off workflows',
    ],
    legislationCovered: ['Customs & Excise Act 2018', 'Biosecurity Act 1993', 'HSNO Act 1996'],
    agents: [
      { name: 'GATEWAY', desc: 'Customs brokerage & border compliance', status: 'existing' },
      { name: 'TRANSIT', desc: 'Transport & logistics regulations', status: 'existing' },
      { name: 'CARGO', desc: 'Freight optimisation & route planning', status: 'new' },
      { name: 'BIOSEC', desc: 'Biosecurity & MPI compliance', status: 'new' },
      { name: 'TARIFF', desc: 'HS code classification & duty calculation', status: 'new' },
      { name: 'HAZMAT', desc: 'HSNO dangerous goods classification', status: 'new' },
      { name: 'DOCK', desc: 'Port operations & shipping coordination', status: 'new' },
    ],
  },
  {
    slug: 'hoko',
    name: 'Hoko',
    englishName: 'Retail',
    description: 'Pricing intelligence vs Temu/Amazon, POS-driven re-orders, FTA/CGA compliance lint, unified customer view — for NZ retail\'s $92.3bn frontline.',
    longDescription: 'The Hoko kete is built for the New Zealand retail sector. It tracks pricing intelligence against offshore platforms (Temu, Amazon), drives POS re-order signals from real sell-through, lints product copy and pricing claims against the Fair Trading Act 1986 and Consumer Guarantees Act 1993, and unifies customer view across channels.',
    agentCount: 10,
    accentColor: '#C66B5C',
    accentLight: '#E89484',
    variant: 'warm',
    category: 'industry',
    keyCapabilities: [
      'Price benchmarking against Temu/Amazon',
      'POS-driven re-order signals',
      'Fair Trading Act 1986 compliance lint',
      'Consumer Guarantees Act remedy workflow',
      'Unified customer view across channels',
      'Returns and refund automation',
      'Promotion compliance review',
      'Stocktake and shrinkage tracking',
    ],
    legislationCovered: ['Fair Trading Act 1986', 'Consumer Guarantees Act 1993', 'Privacy Act 2020', 'Weights and Measures Act 1987'],
    agents: [
      { name: 'TILL', desc: 'Point-of-sale operations & re-order signals', status: 'new' },
      { name: 'PRICE', desc: 'Pricing intelligence vs Temu/Amazon', status: 'new' },
      { name: 'CGA', desc: 'Consumer Guarantees Act remedy workflow', status: 'new' },
      { name: 'TRADE', desc: 'Fair Trading Act 1986 compliance lint', status: 'new' },
      { name: 'STOCK', desc: 'Inventory & stocktake intelligence', status: 'new' },
      { name: 'LOYAL', desc: 'Unified customer view & loyalty', status: 'new' },
      { name: 'PROMO', desc: 'Promotion claim review', status: 'new' },
      { name: 'RETURN', desc: 'Returns & refunds automation', status: 'new' },
      { name: 'BENCH', desc: 'Cross-retailer benchmarking', status: 'new' },
      { name: 'SHELF', desc: 'Merchandising & planogram intelligence', status: 'new' },
    ],
  },
  {
    slug: 'ako',
    name: 'Ako',
    englishName: 'Early Childhood Education',
    description: 'Licensing criteria matcher, transparency pack generator, graduated enforcement readiness — built for the 20 April 2026 ECE wedge moment.',
    longDescription: 'The Ako kete supports New Zealand early childhood education centres through the licensing criteria matcher, the parent-facing transparency pack generator, and a graduated enforcement readiness scorecard. Built specifically for the 20 April 2026 ECE regulatory wedge moment.',
    agentCount: 3,
    accentColor: '#7BA7C7',
    accentLight: '#A8C8DD',
    variant: 'standard',
    category: 'industry',
    badge: '20 APRIL 2026 READY',
    keyCapabilities: [
      'Licensing criteria matcher (Education Act)',
      'Parent-facing transparency pack generator',
      'Graduated enforcement readiness scorecard',
      'Ratio and qualification tracking',
      'Incident & accident register',
      'ERO review preparation',
    ],
    legislationCovered: ['Education and Training Act 2020', 'Education (ECE) Regulations 2008', 'Privacy Act 2020', 'Vulnerable Children Act 2014'],
    agents: [
      { name: 'TAMARIKI', desc: 'Licensing criteria matcher & ECE compliance', status: 'new' },
      { name: 'CLARITY', desc: 'Parent-facing transparency pack generator', status: 'new' },
      { name: 'READY', desc: 'Graduated enforcement readiness scorecard', status: 'new' },
    ],
  },
  {
    slug: 'contracts',
    name: 'Contracts & Invoices',
    englishName: 'Cross-kete Workflow',
    description: 'Contract review against CCA 2002 · Payment-claim discipline · FTA 1986 fair-dealing checks · Retention tracking · Audit-ready invoice packs.',
    longDescription: 'The Contracts & Invoices workflow spans every industry kete — reviewing contracts for Construction Contracts Act 2002 compliance, verifying payment claims, checking fair dealing under the Fair Trading Act 1986, tracking retentions, and producing audit-ready invoice evidence packs.',
    agentCount: 3,
    accentColor: '#5AADA0',
    accentLight: '#7ECFC2',
    variant: 'standard',
    category: 'specialist',
    keyCapabilities: [
      'Contract review against CCA 2002',
      'Payment-claim discipline & schedules',
      'FTA 1986 fair-dealing checks',
      'Retention tracking & ledger management',
      'Audit-ready invoice packs',
      'Monthly payment-claim compliance reports',
    ],
    legislationCovered: ['Construction Contracts Act 2002', 'Fair Trading Act 1986', 'Contract and Commercial Law Act 2017'],
    agents: [
      { name: 'ACCORD', desc: 'Contract review & CCA 2002 compliance', status: 'new', capabilities: ['Construction contract review', 'Payment claim validation', 'Retention tracking', 'Default notice drafting'] },
      { name: 'LEDGER', desc: 'Invoice processing & audit packs', status: 'new', capabilities: ['Invoice verification', 'Audit-ready pack generation', 'Payment schedule tracking', 'Reconciliation'] },
      { name: 'FAIR', desc: 'Fair Trading Act compliance checks', status: 'new', capabilities: ['FTA 1986 compliance', 'Fair dealing verification', 'Misleading conduct screening', 'Price representation checks'] },
    ],
  },
  {
    slug: 'toro',
    name: 'Toro',
    englishName: 'Family Navigator',
    description: 'SMS-first whānau coordination. School notices, kai plans, appointments, budgets — just text.',
    longDescription: 'Toro is the SMS-first family navigator — a $29/month consumer product that works entirely via text message. No app download, no login required. Families text Toro for school newsletter parsing, meal planning, budget tracking, and family calendar management.',
    agentCount: 1,
    accentColor: '#D4A843',
    accentLight: '#F0D078',
    variant: 'warm',
    badge: 'CONSUMER · $29/MO',
    category: 'whanau',
    keyCapabilities: [
      'School newsletter parsing & action extraction',
      'Meal planning from fridge photos',
      'Household budget tracking & alerts',
      'Family calendar management',
      'Homework tracking & study reminders',
      'Grocery list generation',
    ],
    legislationCovered: ['Privacy Act 2020'],
    agents: [
      { name: 'TORO', desc: 'Family SMS navigator', status: 'existing', capabilities: ['School newsletter parsing', 'Meal planning', 'Budget tracking', 'Calendar management', 'Homework reminders', 'Grocery lists'] },
    ],
  },
];

export const TOTAL_AGENTS = SHARED_CORE_AGENTS.length + KETE_DATA.reduce((s, k) => s + k.agentCount, 0);
