export interface KeteData {
  slug: string;
  name: string;
  englishName: string;
  description: string;
  agentCount: number;
  accentColor: string;
  accentLight: string;
  variant: 'standard' | 'dense' | 'organic' | 'tricolor' | 'warm';
  category: 'industry' | 'specialist' | 'whanau';
  badge?: string;
  agents?: { name: string; desc: string }[];
}

export const KETE_DATA: KeteData[] = [
  {
    slug: 'manaaki',
    name: 'Manaaki',
    englishName: 'Hospitality & Tourism',
    description: 'Your venue runs itself. Food safety, liquor licensing, guest experience, luxury lodging, adventure tourism.',
    agentCount: 9,
    accentColor: '#D4A843',
    accentLight: '#F0D078',
    variant: 'standard',
    category: 'industry',
    agents: [
      { name: 'AURA', desc: 'Property operations & guest experience' },
      { name: 'HAVEN', desc: 'Accommodation management' },
      { name: 'TIDE', desc: 'Revenue & demand forecasting' },
      { name: 'BEACON', desc: 'Tourism marketing & bookings' },
      { name: 'COAST', desc: 'Adventure & outdoor tourism' },
      { name: 'KURA', desc: 'Food safety & compliance' },
      { name: 'MOANA', desc: 'Marine & coastal operations' },
      { name: 'PAU', desc: 'Events & venue management' },
      { name: 'SIGNAL', desc: 'Security & monitoring' },
    ],
  },
  {
    slug: 'hanga',
    name: 'Hanga',
    englishName: 'Construction',
    description: 'Site to sign-off. Safety, BIM, consenting, project management, architecture, awards, tenders.',
    agentCount: 9,
    accentColor: '#3A7D6E',
    accentLight: '#5AADA0',
    variant: 'standard',
    category: 'industry',
    agents: [
      { name: 'ATA', desc: 'BIM & 3D modelling' },
      { name: 'ĀRAI', desc: 'Site safety & H&S compliance' },
      { name: 'KAUPAPA', desc: 'Project management' },
      { name: 'RAWA', desc: 'Resource & materials tracking' },
      { name: 'WHAKAAĒ', desc: 'Consenting & approvals' },
      { name: 'PAI', desc: 'Quality assurance & inspections' },
      { name: 'KAHU', desc: 'Compliance engine' },
      { name: 'KANOHI', desc: 'Site overview dashboard' },
      { name: 'SIGNAL', desc: 'Security & monitoring' },
    ],
  },
  {
    slug: 'auaha',
    name: 'Auaha',
    englishName: 'Creative & Media',
    description: 'Brief to published. Copy, image, video, podcast, ads, analytics — the full creative pipeline.',
    agentCount: 9,
    accentColor: '#F0D078',
    accentLight: '#D4A843',
    variant: 'standard',
    category: 'industry',
    agents: [
      { name: 'PRISM', desc: 'Brand intelligence & DNA' },
      { name: 'MUSE', desc: 'Copywriting & content' },
      { name: 'PIXEL', desc: 'Image generation & editing' },
      { name: 'VERSE', desc: 'Podcast production' },
      { name: 'ECHO', desc: 'Video production' },
      { name: 'FLUX', desc: 'Social media publishing' },
      { name: 'CHROMATIC', desc: 'Design & visual identity' },
      { name: 'RHYTHM', desc: 'Campaign analytics' },
      { name: 'SIGNAL', desc: 'Security & monitoring' },
    ],
  },
  {
    slug: 'pakihi',
    name: 'Pakihi',
    englishName: 'Business & Commerce',
    description: 'Accounting, insurance, retail, trade, agriculture, real estate, immigration. The engine of NZ commerce.',
    agentCount: 11,
    accentColor: '#5AADA0',
    accentLight: '#3A7D6E',
    variant: 'dense',
    category: 'industry',
    agents: [
      { name: 'LEDGER', desc: 'Bank reconciliation & accounting' },
      { name: 'AROHA', desc: 'HR & employment law' },
      { name: 'TURF', desc: 'Resource management' },
      { name: 'SAGE', desc: 'Tax & compliance' },
      { name: 'COMPASS', desc: 'Market research' },
      { name: 'NEXUS', desc: 'Business intelligence' },
      { name: 'PRISM-B', desc: 'Brand analytics' },
      { name: 'ASCEND', desc: 'Growth strategy' },
      { name: 'ANCHOR', desc: 'Contract scanning' },
      { name: 'ATLAS', desc: 'Strategic planning' },
      { name: 'SIGNAL', desc: 'Security & monitoring' },
    ],
  },
  {
    slug: 'waka',
    name: 'Waka',
    englishName: 'Transport & Vehicles',
    description: 'Automotive, maritime, trucking, logistics. Dealership compliance to heavy vehicle logbooks.',
    agentCount: 3,
    accentColor: '#6B8FA3',
    accentLight: '#3A6A9C',
    variant: 'standard',
    category: 'industry',
    agents: [
      { name: 'FORGE', desc: 'Dealership operations' },
      { name: 'TOROA-M', desc: 'Maritime navigation' },
      { name: 'SIGNAL', desc: 'Security & monitoring' },
    ],
  },
  {
    slug: 'hangarau',
    name: 'Hangarau',
    englishName: 'Technology',
    description: 'Your in-house tech team. Security, DevOps, infrastructure, monitoring, environment, manufacturing, IP.',
    agentCount: 12,
    accentColor: '#3A6A9C',
    accentLight: '#1A3A5C',
    variant: 'standard',
    category: 'industry',
    agents: [
      { name: 'SPARK', desc: 'App builder' },
      { name: 'SENTINEL', desc: 'Threat detection' },
      { name: 'NEXUS-T', desc: 'Tech intelligence' },
      { name: 'CIPHER', desc: 'Encryption & data' },
      { name: 'RELAY', desc: 'API management' },
      { name: 'MATRIX', desc: 'Infrastructure' },
      { name: 'FORGE', desc: 'DevOps pipeline' },
      { name: 'ORACLE', desc: 'Predictive analytics' },
      { name: 'APEX', desc: 'IoT & field tech' },
      { name: 'KINDLE', desc: 'Non-profit tech' },
      { name: 'AXIS', desc: 'Automation engine' },
      { name: 'SIGNAL', desc: 'Security & monitoring' },
    ],
  },
  {
    slug: 'hauora',
    name: 'Hauora',
    englishName: 'Health, Wellbeing & Lifestyle',
    description: 'Sport, health, beauty, nutrition, interior design, travel. Everything that keeps people well.',
    agentCount: 8,
    accentColor: '#A87D4A',
    accentLight: '#D4A843',
    variant: 'organic',
    category: 'industry',
    agents: [
      { name: 'ORA', desc: 'Daily wellness check-in' },
      { name: 'TAHI', desc: 'Health navigation' },
      { name: 'VITAE', desc: 'Care journey tracking' },
      { name: 'MĀHINA', desc: 'Mental wellbeing' },
      { name: 'HAUMARU', desc: 'Home safety' },
      { name: 'WHĀNAU', desc: 'Family support' },
      { name: 'RONGOĀ', desc: 'Natural health' },
      { name: 'SIGNAL', desc: 'Security & monitoring' },
    ],
  },
  {
    slug: 'te-kahui-reo',
    name: 'Te Kāhui Reo',
    englishName: 'Māori Business Intelligence',
    description: 'Data sovereignty, whānau governance, iwi reporting, kaupapa Māori — built from the ground up.',
    agentCount: 8,
    accentColor: '#D4A843',
    accentLight: '#3A7D6E',
    variant: 'tricolor',
    category: 'specialist',
    agents: [
      { name: 'WHĀNAU', desc: 'Whānau governance' },
      { name: 'ROHE', desc: 'Regional coordination' },
      { name: 'KAUPAPA-M', desc: 'Kaupapa Māori frameworks' },
      { name: 'MANA', desc: 'Access & permissions' },
      { name: 'KAITIAKI', desc: 'Data guardianship' },
      { name: 'TĀURA', desc: 'Cultural compliance' },
      { name: 'WHAKAARO', desc: 'Strategic thinking' },
      { name: 'HIRINGA', desc: 'Innovation & growth' },
    ],
  },
  {
    slug: 'toroa',
    name: 'Tōroa',
    englishName: 'Family Navigator',
    description: 'SMS-first. No app, no login. Just text. School notices, meals, budgets, reminders, learning.',
    agentCount: 1,
    accentColor: '#D4A843',
    accentLight: '#F0D078',
    variant: 'warm',
    badge: 'CONSUMER · $29/MO',
    category: 'whanau',
    agents: [
      { name: 'TŌROA', desc: 'Family SMS navigator' },
    ],
  },
];
