export interface KeteAgent {
  name: string;
  desc: string;
  status?: 'existing' | 'restored' | 'new';
  capabilities?: string[];
}

export interface KeteData {
  slug: string;
  name: string;
  englishName: string;
  description: string;
  longDescription: string;
  agentCount: number;
  accentColor: string;
  accentLight: string;
  variant: 'standard' | 'dense' | 'organic' | 'tricolor' | 'warm';
  category: 'industry' | 'specialist' | 'whanau';
  badge?: string;
  agents: KeteAgent[];
  keyCapabilities: string[];
  legislationCovered: string[];
}

export const SHARED_CORE_AGENTS: KeteAgent[] = [
  { name: 'CHARTER', desc: 'Company governance & director duties', status: 'new', capabilities: ['Companies Act 1993 compliance', 'Director duty guidance', 'Board governance frameworks', 'Annual return preparation', 'Shareholder agreements'] },
  { name: 'ARBITER', desc: 'Dispute resolution & legal remedies', status: 'new', capabilities: ['Mediation guidance', 'Arbitration Act compliance', 'Disputes Tribunal preparation', 'Employment disputes', 'Contractual remedies'] },
  { name: 'SHIELD', desc: 'Privacy Act 2020 & data protection', status: 'new', capabilities: ['Privacy impact assessments', 'Breach notification workflows', 'Cross-border data transfer rules', 'IPP compliance checks', 'Data retention policies'] },
  { name: 'ANCHOR', desc: 'Non-profit, charities & community organisations', status: 'new', capabilities: ['Charities Act compliance', 'Incorporated Societies Act 2022', 'Grant application writing', 'Governance frameworks', 'Annual reporting'] },
  { name: 'AROHA', desc: 'HR & employment relations', status: 'existing', capabilities: ['Employment agreements (ERA s65)', 'Personal grievance workflows', 'Performance management', 'Restructuring & redundancy', 'Leave entitlements'] },
  { name: 'PULSE', desc: 'Employment law & payroll compliance', status: 'new', capabilities: ['PAYE calculations', 'Holiday pay (Holidays Act)', 'KiwiSaver employer obligations', 'Minimum wage compliance', 'Parental leave administration'] },
  { name: 'SCHOLAR', desc: 'Education & training sector compliance', status: 'new', capabilities: ['NZQA framework guidance', 'Education Act compliance', 'Training programme design', 'Micro-credential frameworks', 'Professional development planning'] },
  { name: 'NOVA', desc: 'General operations & technical troubleshooting', status: 'new', capabilities: ['Process optimisation', 'Workflow automation', 'Technical troubleshooting', 'Tool integration', 'Productivity audits'] },
];

export const KETE_DATA: KeteData[] = [
  {
    slug: 'manaaki',
    name: 'Manaaki',
    englishName: 'Hospitality & Tourism',
    description: 'Your venue runs itself. Food safety, liquor licensing, guest experience, luxury lodging, adventure tourism.',
    longDescription: 'The Manaaki kete covers every aspect of New Zealand hospitality — from Food Act 2014 food control plans and Sale of Alcohol Act licensing, to luxury lodging operations, cultural tourism (tikanga-aligned), adventure activity regulation, coastal tourism, and large-scale event catering. Nine specialist agents ensure your venue, tour, or accommodation business meets compliance while delivering exceptional guest experiences.',
    agentCount: 9,
    accentColor: '#FFD700',
    accentLight: '#FFE866',
    variant: 'standard',
    category: 'industry',
    keyCapabilities: [
      'Food control plans & Food Act 2014 compliance',
      'Liquor licensing & Sale of Alcohol Act management',
      'Guest experience workflows & staff training',
      'Luxury lodging & premium hospitality operations',
      'Adventure Activities Register & safety management',
      'Cultural tourism & tikanga Māori protocols',
      'Event catering & temporary food operations',
      'Revenue management & booking optimisation',
    ],
    legislationCovered: ['Food Act 2014', 'Sale and Supply of Alcohol Act 2012', 'HSWA 2015', 'Adventure Activities Regulations'],
    agents: [
      { name: 'AURA', desc: 'Front-of-house operations & guest experience', status: 'existing', capabilities: ['Guest welcome workflows', 'Staff training matrices', 'Revenue management', 'Booking optimisation', 'Service standards', 'Housekeeping scheduling'] },
      { name: 'SAFFRON', desc: 'Food safety & Food Act 2014 compliance', status: 'restored', capabilities: ['Food control plans', 'Temperature monitoring logs', 'Allergen management', 'MPI audit preparation', 'HACCP plans', 'Kitchen hygiene protocols'] },
      { name: 'CELLAR', desc: 'Liquor licensing & Sale of Alcohol Act', status: 'restored', capabilities: ['On/off-licence applications', 'DLC submissions', 'Duty manager certification', 'Host responsibility policies', 'LCQ preparation'] },
      { name: 'LUXE', desc: 'Luxury lodging & premium hospitality', status: 'new', capabilities: ['VIP guest management', 'Concierge services', 'Premium dining curation', 'Loyalty programme design', 'Luxury pricing strategy'] },
      { name: 'MOANA', desc: 'Tourism operations & adventure compliance', status: 'existing', capabilities: ['Tour operator compliance', 'Risk assessment frameworks', 'Seasonal planning', 'Itinerary design', 'Visitor experience management'] },
      { name: 'COAST', desc: 'Coastal & marine tourism', status: 'existing', capabilities: ['Water safety compliance', 'Eco-tourism certification', 'Marine insurance guidance', 'Environmental impact assessments', 'Coastal activity operations'] },
      { name: 'KURA', desc: 'Cultural tourism & Māori hospitality', status: 'existing', capabilities: ['Māori hospitality protocols', 'Pōwhiri guidance', 'Cultural experience design', 'Tikanga compliance', 'Cultural narrative development'] },
      { name: 'PAU', desc: 'Event catering & temporary food operations', status: 'existing', capabilities: ['Event catering compliance', 'Temporary food stall registration', 'Large-scale food safety', 'Menu planning at scale', 'Vendor coordination'] },
      { name: 'SUMMIT', desc: 'Tourism & adventure activities regulation', status: 'restored', capabilities: ['Adventure Activities Register', 'Safety audit preparation', 'Operator certification', 'WorkSafe compliance', 'Risk management systems'] },
    ],
  },
  {
    slug: 'hanga',
    name: 'Hanga',
    englishName: 'Construction',
    description: 'Site to sign-off. Safety, BIM, consenting, project management, architecture, awards, tenders.',
    longDescription: 'The Hanga kete is the complete construction intelligence platform — from site safety and BIM model analysis, to project management under NZS 3910, resource consent navigation, quality assurance, architecture compliance, land management under the RMA, and GETS tender writing. Nine specialist agents handle the full lifecycle from site setup to CCC sign-off.',
    agentCount: 9,
    accentColor: '#00CED1',
    accentLight: '#40E0D0',
    variant: 'standard',
    category: 'industry',
    keyCapabilities: [
      'Site safety plans & HSWA compliance',
      'BIM analysis, clash detection & 4D scheduling',
      'Project management & NZS 3910 contracts',
      'Resource consent & RMA compliance',
      'Quality assurance & defect tracking',
      'NZ Building Code compliance checking',
      'Land management & property development',
      'GETS tender & award submission writing',
    ],
    legislationCovered: ['HSWA 2015', 'Building Act 2004', 'NZ Building Code', 'CCA 2002', 'RMA 1991', 'NZS 3910'],
    agents: [
      { name: 'ATA', desc: 'Building Information Modelling (BIM)', status: 'existing', capabilities: ['BIM model analysis', 'Clash detection', '4D scheduling', 'MEP coordination', 'IFC processing', '3D walkthroughs'] },
      { name: 'ĀRAI', desc: 'Site safety & H&S compliance (WorkSafe)', status: 'existing', capabilities: ['Site safety plans', 'Hazard identification', 'SWMS generation', 'Incident investigation', 'PPE requirements', 'Toolbox talk preparation'] },
      { name: 'KAUPAPA', desc: 'Project management & contract administration', status: 'existing', capabilities: ['Project charters', 'NZS 3910 administration', 'Payment claim review', 'Variation management', 'Programme scheduling'] },
      { name: 'RAWA', desc: 'Resources, procurement & supply chain', status: 'existing', capabilities: ['Procurement planning', 'Supply chain risk review', 'Vendor assessment', 'Capacity planning', 'Cost control analysis'] },
      { name: 'WHAKAAĒ', desc: 'Resource consent & planning compliance', status: 'existing', capabilities: ['Resource consent applications', 'Building consent preparation', 'CCC checklists', 'Council liaison', 'RMA compliance checks'] },
      { name: 'PAI', desc: 'Quality assurance & building standards', status: 'existing', capabilities: ['Quality control checklists', 'Defect identification', 'Punch list management', 'Producer statements', 'ITP tracking'] },
      { name: 'ARC', desc: 'Architecture & NZ Building Code compliance', status: 'restored', capabilities: ['Building Code compliance', 'Architectural review', 'Specification writing', 'Design compliance', 'BRANZ guidance'] },
      { name: 'TERRA', desc: 'Property & land management (RMA)', status: 'restored', capabilities: ['RMA compliance', 'Land use assessment', 'Environmental assessment', 'LINZ requirements', 'Heritage impact reviews'] },
      { name: 'PINNACLE', desc: 'Construction awards, tenders & application writing', status: 'new', capabilities: ['GETS tender responses', 'Award submission writing', 'Case study development', 'Competitive positioning', 'RFP/RFT responses'] },
    ],
  },
  {
    slug: 'auaha',
    name: 'Auaha',
    englishName: 'Creative & Media',
    description: 'Brief to published. Copy, image, video, podcast, ads, analytics — the full creative pipeline.',
    longDescription: 'The Auaha kete runs the complete 8-stage creative pipeline: Brief → Copy → Design → Video → Schedule → Publish → Analyse → Iterate. Nine specialist agents handle brand identity, copywriting (with anti-AI-slop Kiwi voice), visual design, image generation, video production, podcast creation, colour systems, and marketing compliance under the Fair Trading Act.',
    agentCount: 9,
    accentColor: '#FF8C00',
    accentLight: '#FFB347',
    variant: 'standard',
    category: 'industry',
    keyCapabilities: [
      'Brand DNA development & visual identity',
      'Content creation with Kiwi voice (anti-AI-slop)',
      'AI image generation & design innovation',
      'Video production & social media content',
      'Podcast scripting & audio production',
      'Colour systems & design system management',
      'Ad campaign creation & Fair Trading compliance',
      'Social media scheduling & analytics',
    ],
    legislationCovered: ['Fair Trading Act 1986', 'Copyright Act 1994', 'ASA Codes'],
    agents: [
      { name: 'PRISM', desc: 'Creative design & brand development', status: 'existing', capabilities: ['Brand DNA creation', 'Visual identity systems', 'Logo design guidance', 'Brand guidelines', 'Canva integration', 'Design critique'] },
      { name: 'MUSE', desc: 'Content creation & copywriting', status: 'existing', capabilities: ['Website copy', 'Blog content', 'Email campaigns', 'Tagline creation', 'Brand voice enforcement', 'Anti-AI-slop writing'] },
      { name: 'PIXEL', desc: 'Visual design & digital media', status: 'existing', capabilities: ['Graphic design', 'Social media visuals', 'Infographic creation', 'Photography direction', 'Digital asset production'] },
      { name: 'VERSE', desc: 'Narrative design & storytelling', status: 'existing', capabilities: ['Brand storytelling', 'Script writing', 'Narrative frameworks', 'Customer story development', 'Creative writing'] },
      { name: 'ECHO', desc: 'Technical production & platform setup', status: 'existing', capabilities: ['Video editing guidance', 'Platform configuration', 'Technical production', 'YouTube optimisation', 'Social media tools'] },
      { name: 'FLUX', desc: 'Image generation & design innovation', status: 'existing', capabilities: ['AI image generation', 'Product photography', 'Marketing imagery', 'Algorithmic art', 'Social media visuals'] },
      { name: 'CHROMATIC', desc: 'Colour, brand aesthetics & visual identity', status: 'existing', capabilities: ['Colour palette creation', 'Typography selection', 'Design system management', 'Visual consistency', 'Brand aesthetic direction'] },
      { name: 'RHYTHM', desc: 'Audio, podcast & media production', status: 'existing', capabilities: ['Podcast episode scripting', 'Audio production guidance', 'Series planning', 'Guest preparation', 'Distribution strategy'] },
      { name: 'MARKET', desc: 'Marketing & advertising compliance (Fair Trading)', status: 'restored', capabilities: ['Fair Trading Act compliance', 'ASA advertising standards', 'Social media management', 'Campaign analytics', 'Meta/Google ads'] },
    ],
  },
  {
    slug: 'arataki',
    name: 'Arataki',
    englishName: 'Privacy & Business Compliance',
    description: 'IPP3A-ready. Every Privacy Act 2020 run ends in a signed evidence pack your Privacy Officer can file, forward, or footnote.',
    longDescription: 'The Arataki kete is built for professional services businesses — consultancies, advisories, and agencies — that hold personal information about employees, clients, and contractors. Four specialist agents work through the Privacy Act 2020 Information Privacy Principles (IPP 1–13) and the new IPP3A indirect collection obligations (effective 1 May 2026). Every Arataki run ends in a structured evidence pack: an IPP snapshot table, sourced findings, a citations list, and a signing block for your named Privacy Officer. For a 20-person Wellington consultancy using rostering apps and overseas payroll processors, Arataki closes the IPP3A gap before it becomes a compliance event.',
    agentCount: 4,
    accentColor: '#C65D4E',
    accentLight: '#E08070',
    variant: 'warm',
    category: 'industry',
    badge: 'IPP3A READY · MAY 2026',
    keyCapabilities: [
      'IPP3A notice obligations for indirect collection (effective 1 May 2026)',
      'Privacy Act 2020 IPP 1–13 gap analysis with sourced findings',
      'Signed evidence pack — IPP snapshot, citations, signing block',
      'Data retention policy review & scheduled deletion planning',
      'Vendor register & Data Processing Agreement (DPA) checklist',
      'Breach notification assessment (Privacy Act 2020 Part 6)',
      'Employee data flow mapping — rostering, payroll, HR integrations',
      'Named Privacy Officer support & sign-off workflow',
    ],
    legislationCovered: [
      'Privacy Act 2020 (IPP 1–13)',
      'Privacy Act 2020 s22A (IPP3A — indirect collection, effective 1 May 2026)',
      'Employment Relations Act 2000',
      'Companies Act 1993',
    ],
    agents: [
      {
        name: 'PĪKAU',
        desc: 'Privacy Act 2020 & IPP3A compliance copilot',
        status: 'new',
        capabilities: [
          'IPP 1–13 gap analysis against your inputs',
          'IPP3A checklist — indirect collection notice obligations',
          'Evidence pack generation (IPP snapshot + findings + citations)',
          'Signing block for named Privacy Officer',
          'SIMULATED watermark when inputs are not production data',
          'Source-pointer enforcement — no unsourced findings',
        ],
      },
      {
        name: 'SHIELD',
        desc: 'Data protection & breach notification (Privacy Act 2020 Part 6)',
        status: 'new',
        capabilities: [
          'Notifiable breach assessment — serious harm threshold',
          'Breach notification to Privacy Commissioner',
          'Incident timeline documentation',
          'Data processing agreement (DPA) review checklist',
          'Vendor register gap analysis',
          'Security safeguard assessment (IPP5)',
        ],
      },
      {
        name: 'AROHA',
        desc: 'HR & employment data compliance',
        status: 'existing',
        capabilities: [
          'Employee data flow mapping — rostering, payroll, HR integrations',
          'IPP3A trigger identification for workforce data',
          'Employment agreement privacy disclosure review',
          'Access and correction request workflows (IPP6, IPP7)',
          'Overseas payroll processor safeguards check (IPP13)',
          'Retention policy for employment records (IPP9)',
        ],
      },
      {
        name: 'CHARTER',
        desc: 'Corporate governance & director privacy obligations',
        status: 'new',
        capabilities: [
          'Director duty alignment with Privacy Act obligations',
          'Privacy policy drafting & review',
          'Board-level privacy governance frameworks',
          'Annual privacy review preparation',
          'Privacy Officer appointment & mandate documentation',
          'Companies Act 1993 compliance cross-check',
        ],
      },
    ],
  },
  {
    slug: 'pakihi',
    name: 'Pakihi',
    englishName: 'Business & Commerce',
    description: 'Accounting, insurance, retail, trade, agriculture, real estate, immigration. The engine of NZ commerce.',
    longDescription: 'The Pakihi kete covers the breadth of NZ commerce — from IRD tax compliance and GST, to business insurance, recruitment, immigration pathways, real estate (RTA compliance), retail consumer guarantees, customs brokerage, agriculture (MPI/Fonterra), horticulture/viticulture export, business analytics, and growth strategy. Eleven specialist agents for every commercial need.',
    agentCount: 11,
    accentColor: '#4169E1',
    accentLight: '#6B8DF5',
    variant: 'dense',
    category: 'industry',
    keyCapabilities: [
      'Tax compliance, GST returns & IRD obligations',
      'Business insurance & risk management',
      'Recruitment pipelines & talent management',
      'Immigration & visa guidance (AEWV, residence)',
      'Real estate & Residential Tenancies Act compliance',
      'Retail operations & Consumer Guarantees Act',
      'Customs brokerage & border compliance',
      'Agriculture, horticulture & export compliance',
      'Business analytics, strategy & growth planning',
    ],
    legislationCovered: ['Income Tax Act 2007', 'GST Act 1985', 'Consumer Guarantees Act 1993', 'RTA 1986', 'Immigration Act 2009', 'Customs & Excise Act 2018', 'Biosecurity Act 1993'],
    agents: [
      { name: 'LEDGER', desc: 'Accounting & tax compliance (IRD, GST)', status: 'existing', capabilities: ['GST return preparation', 'PAYE calculations', 'Provisional tax planning', 'Financial statements', 'Xero/MYOB integration', 'Cashflow forecasting'] },
      { name: 'VAULT', desc: 'Business insurance & risk management', status: 'restored', capabilities: ['Policy comparison', 'Claims dispute navigation', 'Sum insured calculations', 'EQC guidance', 'Risk assessment frameworks'] },
      { name: 'CATALYST', desc: 'Recruitment & talent management', status: 'restored', capabilities: ['Job listing creation', 'Interview frameworks', 'Candidate assessment', 'Onboarding checklists', 'Retention strategies'] },
      { name: 'COMPASS', desc: 'Immigration & visa guidance', status: 'restored', capabilities: ['AEWV process navigation', 'Visa pathway mapping', 'Employer accreditation', 'Document checklists', 'INZ requirements'] },
      { name: 'HAVEN', desc: 'Real estate & property management', status: 'restored', capabilities: ['Healthy Homes compliance', 'Tenancy agreement drafting', 'Bond management', 'Tenancy Tribunal guidance', 'Investment yield analysis'] },
      { name: 'COUNTER', desc: 'Retail operations & consumer guarantees', status: 'restored', capabilities: ['Consumer Guarantees Act compliance', 'Sales campaign creation', 'Loyalty programme design', 'Inventory management', 'POS integration'] },
      { name: 'GATEWAY', desc: 'Customs brokerage & border compliance', status: 'restored', capabilities: ['Tariff classification', 'Landed cost calculation', 'FTA origin analysis', 'MPI biosecurity requirements', 'Import entry processing'] },
      { name: 'HARVEST', desc: 'Agriculture & farming compliance', status: 'restored', capabilities: ['Freshwater Farm Plans', 'GHG emission calculations', 'Biosecurity management', 'MPI compliance', 'Farm health & safety'] },
      { name: 'GROVE', desc: 'Horticulture & viticulture export', status: 'restored', capabilities: ['Export compliance', 'Phytosanitary certification', 'Wine industry regulations', 'Orchard management', 'MPI export standards'] },
      { name: 'SAGE', desc: 'Business analytics & insights', status: 'existing', capabilities: ['Market research', 'Competitive analysis', 'SWOT frameworks', 'Benchmarking', 'Data-driven strategy'] },
      { name: 'ASCEND', desc: 'Growth strategy & performance', status: 'existing', capabilities: ['Growth planning', 'KPI/OKR frameworks', 'Expansion strategy', 'Performance optimisation', 'Business scaling'] },
    ],
  },
  {
    slug: 'waka',
    name: 'Waka',
    englishName: 'Transport & Vehicles',
    description: 'Automotive, maritime, trucking, logistics. Dealership compliance to heavy vehicle logbooks.',
    longDescription: 'The Waka kete covers all NZ transport sectors — automotive dealership compliance (MVSA, CCCFA, CGA), heavy vehicle transport and logistics (NZTA, RUC, chain rule), and maritime vessel operations (Maritime Transport Act). Three specialist agents for every vehicle on road or water.',
    agentCount: 3,
    accentColor: '#FF7F50',
    accentLight: '#FFA07A',
    variant: 'standard',
    category: 'industry',
    keyCapabilities: [
      'Automotive dealership compliance (MVSA, CGA)',
      'F&I disclosure & CCCFA compliance',
      'Heavy vehicle logbooks & NZTA regulations',
      'Maritime vessel safety & Maritime Transport Act',
      'Freight & logistics operations',
      'WoF/CoF & vehicle registration',
    ],
    legislationCovered: ['Motor Vehicle Sales Act 2003', 'CCCFA 2003', 'Land Transport Act 1998', 'Maritime Transport Act 1994'],
    agents: [
      { name: 'MOTOR', desc: 'Automotive industry & dealership compliance', status: 'restored', capabilities: ['F&I disclosure compliance', 'Vehicle listing optimisation', 'GST margin scheme', 'Warranty tracking', 'MVSA compliance', 'Used car regulations'] },
      { name: 'TRANSIT', desc: 'Transport & logistics regulations (NZTA)', status: 'restored', capabilities: ['Heavy vehicle compliance', 'RUC calculations', 'Driver logbooks', 'Chain rule responsibilities', 'Freight management', 'NZTA licensing'] },
      { name: 'MARINER', desc: 'Maritime compliance & vessel operations', status: 'restored', capabilities: ['Vessel safety compliance', 'Maritime Transport Act', 'Seafarer certification', 'Port operations', 'Coastguard coordination', 'Trip planning'] },
    ],
  },
  {
    slug: 'hangarau',
    name: 'Hangarau',
    englishName: 'Technology',
    description: 'Your in-house tech team. Security, DevOps, infrastructure, monitoring, environment, manufacturing, IP.',
    longDescription: 'The Hangarau kete is a full technology department — cybersecurity, DevOps, cloud infrastructure, API integration, data architecture, predictive analytics, energy/carbon reporting, environmental compliance, intellectual property registration, and manufacturing operations. Twelve specialist agents covering every technical need.',
    agentCount: 12,
    accentColor: '#00BFFF',
    accentLight: '#66D9FF',
    variant: 'standard',
    category: 'industry',
    keyCapabilities: [
      'Cloud infrastructure & platform engineering',
      'Cybersecurity audits & NZISM compliance',
      'DevOps pipelines & CI/CD automation',
      'API integration & middleware management',
      'Data architecture & warehouse design',
      'Predictive analytics & ML model guidance',
      'Carbon reporting & ETS compliance',
      'Environmental compliance & RMA',
      'Patent & IP registration (IPONZ)',
      'Manufacturing & industrial operations',
    ],
    legislationCovered: ['Privacy Act 2020', 'NZISM', 'ETS', 'RMA 1991', 'Patents Act 2013', 'Trade Marks Act 2002'],
    agents: [
      { name: 'SPARK', desc: 'Cloud infrastructure & platform engineering', status: 'existing', capabilities: ['Cloud migration planning', 'Infrastructure design', 'SaaS platform setup', 'AWS/Azure/GCP guidance', 'System architecture'] },
      { name: 'SENTINEL', desc: 'Security monitoring & alert systems', status: 'existing', capabilities: ['Security monitoring setup', 'Incident response plans', 'Uptime tracking', 'Alert configuration', 'NZISM compliance'] },
      { name: 'NEXUS-T', desc: 'API integration & tech compliance', status: 'existing', capabilities: ['API management', 'Webhook configuration', 'Integration architecture', 'Middleware design', 'Data flow mapping'] },
      { name: 'CIPHER', desc: 'Cybersecurity & encryption', status: 'existing', capabilities: ['Penetration testing guidance', 'Encryption standards', 'OWASP compliance', 'Security policy generation', 'Vulnerability assessment'] },
      { name: 'RELAY', desc: 'Communication systems & messaging', status: 'existing', capabilities: ['Email infrastructure', 'SMS/push notification systems', 'Communication architecture', 'Messaging platform setup'] },
      { name: 'MATRIX', desc: 'Data architecture & management', status: 'existing', capabilities: ['Database design', 'ETL pipeline planning', 'Data warehouse architecture', 'Schema migration', 'Data governance'] },
      { name: 'FORGE', desc: 'DevOps, CI/CD & deployment automation', status: 'existing', capabilities: ['CI/CD pipeline design', 'Docker/Kubernetes guidance', 'Infrastructure as code', 'Deployment automation', 'GitHub Actions'] },
      { name: 'ORACLE', desc: 'Predictive analytics & AI systems', status: 'existing', capabilities: ['ML model guidance', 'Predictive analytics', 'AI implementation strategy', 'Data science workflows', 'Metric tracking'] },
      { name: 'EMBER', desc: 'Energy efficiency & carbon reporting', status: 'existing', capabilities: ['Carbon footprint calculation', 'ETS compliance', 'Solar ROI analysis', 'Energy efficiency audits', 'Climate disclosure preparation'] },
      { name: 'REEF', desc: 'Environmental compliance & RMA', status: 'existing', capabilities: ['Resource consent navigation', 'Environmental impact assessment', 'RMA compliance', 'EPA requirements', 'Discharge consent'] },
      { name: 'PATENT', desc: 'Intellectual property & IP registration', status: 'existing', capabilities: ['Patent applications (IPONZ)', 'Trademark registration', 'Copyright protection', 'IP strategy', 'Design registration'] },
      { name: 'FOUNDRY', desc: 'Manufacturing & industrial compliance', status: 'existing', capabilities: ['Manufacturing compliance', 'Lean production', 'Industrial safety', 'Supply chain optimisation', 'Quality management'] },
    ],
  },
  {
    slug: 'hauora',
    name: 'Hauora',
    englishName: 'Health, Wellbeing, Sport & Lifestyle',
    description: 'Sport, health, beauty, nutrition, interior design, travel. Everything that keeps people well.',
    longDescription: 'The Hauora kete covers sports governance (Incorporated Societies Act 2022), competition management, workplace health & safety, healthcare practice compliance (HPCAA), nutrition and dietary standards, beauty/wellness industry regulation, interior design, and travel planning. Eight specialist agents for sport, health, and lifestyle needs.',
    agentCount: 8,
    accentColor: '#00FF7F',
    accentLight: '#66FFB2',
    variant: 'organic',
    category: 'industry',
    keyCapabilities: [
      'Sports club governance & Inc Societies Act 2022',
      'Competition & event management',
      'Workplace health & safety (HSWA)',
      'Healthcare practice compliance (HPCAA)',
      'Nutrition & dietary compliance',
      'Beauty & wellness industry regulation',
      'Interior design & space planning',
      'Travel planning & tourism regulations',
    ],
    legislationCovered: ['Incorporated Societies Act 2022', 'HSWA 2015', 'HPCAA 2003', 'Food Act 2014'],
    agents: [
      { name: 'TURF', desc: 'Sports & recreation governance (Inc Societies Act)', status: 'restored', capabilities: ['Club constitution generation', 'Grant application writing', 'Season fixture planning', 'Incorporated Societies Act compliance', 'AGM preparation'] },
      { name: 'LEAGUE', desc: 'Competition & events management', status: 'restored', capabilities: ['Tournament draw generation', 'Event planning', 'League management', 'Seasonal scheduling', 'Venue coordination'] },
      { name: 'VITALS', desc: 'Workplace health & safety (HSWA)', status: 'restored', capabilities: ['HSWA compliance checking', 'ACC claims navigation', 'Workplace injury management', 'Safety system design', 'Risk assessments'] },
      { name: 'REMEDY', desc: 'Healthcare practice compliance (HPCAA)', status: 'restored', capabilities: ['APC renewal tracking', 'Practice audit checklists', 'HDC complaint response', 'Clinical governance', 'Patient recall systems'] },
      { name: 'VITAE', desc: 'Nutrition & dietary compliance', status: 'new', capabilities: ['Meal planning', 'Dietary requirement management', 'Food standards compliance', 'Nutritional analysis', 'Supplement guidance'] },
      { name: 'RADIANCE', desc: 'Beauty & wellness industry compliance', status: 'new', capabilities: ['Salon/spa compliance', 'Cosmetics regulations', 'Skincare ingredient analysis', 'UV protection guidance', 'NZ beauty brand curation'] },
      { name: 'PALETTE', desc: 'Interior design & space planning', status: 'new', capabilities: ['Space planning', 'Interior styling guidance', 'Renovation planning', 'Furniture sourcing', 'Design trend analysis'] },
      { name: 'ODYSSEY', desc: 'Travel planning & tourism regulations', status: 'new', capabilities: ['Road trip planning', 'Great Walk booking guidance', 'Family holiday planning', 'Freedom camping rules', 'Travel itinerary creation'] },
    ],
  },
  {
    slug: 'te-kahui-reo',
    name: 'Te Kāhui Reo',
    englishName: 'Māori Business Intelligence',
    description: 'Data sovereignty, whānau governance, iwi reporting, kaupapa Māori — built from the ground up.',
    longDescription: 'Te Kāhui Reo is a purpose-built kete for Māori business intelligence — covering whānau-centred governance, rohe-based community coordination, kaupapa Māori frameworks, mana whenua and Te Tiriti obligations, environmental kaitiakitanga, community network building, strategic Māori perspectives, and organisational resilience. All eight agents are grounded in tikanga Māori and data sovereignty principles.',
    agentCount: 8,
    accentColor: '#FF69B4',
    accentLight: '#FF99CC',
    variant: 'tricolor',
    category: 'specialist',
    keyCapabilities: [
      'Whānau-centred governance & decision-making',
      'Rohe-based community coordination & iwi reporting',
      'Kaupapa Māori frameworks & mātauranga application',
      'Mana whenua engagement & Te Tiriti compliance',
      'Environmental kaitiakitanga & taonga stewardship',
      'Community network building & relationship management',
      'Strategic Māori perspectives & long-term planning',
      'Organisational resilience & innovation',
    ],
    legislationCovered: ['Te Tiriti o Waitangi', 'Treaty of Waitangi Act 1975', 'Te Ture Whenua Māori Act 1993', 'Resource Management Act 1991'],
    agents: [
      { name: 'WHĀNAU', desc: 'Whānau-centred support & relationship management', status: 'existing', capabilities: ['Whānau governance frameworks', 'Hapū coordination', 'Family data management', 'Relationship mapping', 'Support network building'] },
      { name: 'ROHE', desc: 'Rohe-based community coordination & governance', status: 'existing', capabilities: ['Regional coordination', 'Local governance frameworks', 'Iwi reporting', 'Community engagement', 'Regional data analysis'] },
      { name: 'KAUPAPA-M', desc: 'Kaupapa Māori frameworks & cultural guidance', status: 'existing', capabilities: ['Kaupapa Māori methodology', 'Mātauranga Māori application', 'Te ao Māori frameworks', 'Cultural assessment', 'Tikanga-aligned planning'] },
      { name: 'MANA', desc: 'Mana whenua engagement & Te Tiriti compliance', status: 'existing', capabilities: ['Te Tiriti obligations mapping', 'Iwi engagement guidance', 'Treaty settlement navigation', 'Mana whenua protocols', 'Crown-Māori relations'] },
      { name: 'KAITIAKI', desc: 'Environmental stewardship & taonga guardianship', status: 'existing', capabilities: ['Environmental kaitiakitanga', 'Taonga management', 'Conservation guidance', 'Resource management', 'Cultural heritage protection'] },
      { name: 'TĀURA', desc: 'Community connections & network building', status: 'existing', capabilities: ['Community network building', 'Support service coordination', 'Relationship management', 'Tāura (connection) frameworks', 'Partnership development'] },
      { name: 'WHAKAARO', desc: 'Strategic Māori perspectives & planning', status: 'existing', capabilities: ['Strategic planning with Māori lens', 'Long-term vision development', 'Policy analysis', 'Investment strategy', 'Governance advisory'] },
      { name: 'HIRINGA', desc: 'Organisational resilience & innovation', status: 'existing', capabilities: ['Organisational strength building', 'Innovation frameworks', 'Growth strategy', 'Wellbeing initiatives', 'Resilience planning'] },
    ],
  },
  {
    slug: 'toroa',
    name: 'Tōroa',
    englishName: 'Family Navigator',
    description: 'SMS-first. No app, no login. Just text. School notices, meals, budgets, reminders, learning.',
    longDescription: 'Tōroa is the SMS-first family navigator — a $29/month consumer product that works entirely via text message. No app download, no login required. Families text Tōroa for school newsletter parsing, meal planning from fridge photos, budget tracking, Auckland Transport bus times, homework reminders, family calendar management, and general NZ family advice. One agent, nine intent categories.',
    agentCount: 1,
    accentColor: '#87CEEB',
    accentLight: '#B0E2FF',
    variant: 'warm',
    badge: 'CONSUMER · $29/MO',
    category: 'whanau',
    keyCapabilities: [
      'School newsletter parsing & action extraction',
      'Meal planning from fridge photos',
      'Household budget tracking & alerts',
      'Auckland Transport bus tracking',
      'Family calendar management',
      'Homework tracking & study reminders',
      'Grocery list generation',
      'NZ family advice & resources',
    ],
    legislationCovered: ['Privacy Act 2020'],
    agents: [
      { name: 'TŌROA', desc: 'Family SMS navigator', status: 'existing', capabilities: ['School newsletter parsing', 'Meal planning', 'Budget tracking', 'Bus tracking (AT API)', 'Calendar management', 'Homework reminders', 'Grocery lists', 'Family advice'] },
    ],
  },
];

export const TOTAL_AGENTS = SHARED_CORE_AGENTS.length + KETE_DATA.reduce((s, k) => s + k.agentCount, 0);
