project_id = "ssaxxdkxzrvkdjsanhei"

[functions.chat]
verify_jwt = false

[functions.generate-3d]
verify_jwt = false

[functions.admin-api]
verify_jwt = false

[functions.scan-website]
verify_jwt = false

[functions.proxy-model]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false