import {describe,it,expect,vi} from 'vitest';
import {createLocalOwnerRunStore,createProductionOwnerRunStore,startSchema,outcomeSchema,type Owner} from './owner-run-store';
import {costMicros,reserveMicros,runPolicySchema,createRunSchema,claimActionSchema,type RunPolicy} from './owner-run-policy';
import {z} from 'zod';
import {readFileSync} from 'node:fs';
const uid='11111111-1111-4111-8111-111111111111',runId='22222222-2222-4222-8222-222222222222',actionId='33333333-3333-4333-8333-333333333333';
const owner:Owner={userId:uid,verified:true,anonymous:false},fingerprint='a'.repeat(64);
const policy:RunPolicy={id:'approved-local-test',ownerId:uid,expiresAt:'2099-01-01T00:00:00Z',maxRuns:1,provider:'openai',accountRef:'fictional-test-only',model:'test-model',pricingVersion:'synthetic-v1',maxCalls:2,maxInputTokens:2000,maxOutputTokens:1000,maxUsdMicros:20000,inputUsdMicrosPerMillion:1000000,outputUsdMicrosPerMillion:5000000,tools:false,cache:false,retries:0,repairs:0};
const input={runId,inputFingerprint:fingerprint,selectedSourceReceipts:[],policyId:policy.id};
function setup(p=policy){return createLocalOwnerRunStore(new Map([[p.id,p]]),new Set([uid]));}
describe('owner run admission (local fake, no providers)',()=>{
 it('uses ceiling integer arithmetic, including fractional micro-dollars',()=>{expect(reserveMicros(policy)).toBe(7000);expect(costMicros({...policy,inputUsdMicrosPerMillion:1},1,0)).toBe(1);});
 it('serializes competing run IDs against one approved policy',async()=>{const s=setup();const results=await Promise.allSettled([s.createRun(owner,input),s.createRun(owner,{...input,runId:crypto.randomUUID()})]);expect(results.filter(r=>r.status==='fulfilled')).toHaveLength(1);});
 it('does not allow owner spoofing or caller policy fields',async()=>{const s=setup();await expect(s.createRun({...owner,userId:crypto.randomUUID()},input)).rejects.toThrow();await expect(s.createRun(owner,{...input,model:'forged'} as typeof input)).rejects.toThrow();});
 it('binds immutable input and selected context',async()=>{const s=setup();await s.createRun(owner,input);await expect(s.createRun(owner,{...input,inputFingerprint:'b'.repeat(64)})).rejects.toThrow('run_input_conflict');});
 it('returns one claim for concurrent duplicate requests and starts once',async()=>{const s=setup();await s.createRun(owner,input);const req={runId,actionId,action:'develop' as const,inputFingerprint:fingerprint,expectedRevision:0};const a=await Promise.all([s.claimAction(owner,req),s.claimAction(owner,req)]);expect(a.map(x=>x.kind).sort()).toEqual(['claimed','existing']);const c=a.find(x=>x.kind==='claimed')!;if(c.kind!=='claimed')throw Error();const starts=await Promise.allSettled([s.startAction(owner,{runId,claimId:c.claimId,expectedRevision:1}),s.startAction(owner,{runId,claimId:c.claimId,expectedRevision:1})]);expect(starts.filter(x=>x.status==='fulfilled')).toHaveLength(1);expect((await s.lookupRun(owner,runId)).claims[0].state).toBe('started');});
 it('arbitrates distinct concurrent actions through CAS',async()=>{const s=setup();await s.createRun(owner,input);const req={runId,actionId,action:'develop' as const,inputFingerprint:fingerprint,expectedRevision:0};const r=await Promise.allSettled([s.claimAction(owner,req),s.claimAction(owner,{...req,actionId:crypto.randomUUID()})]);expect(r.filter(x=>x.status==='fulfilled')).toHaveLength(1);});
 it('retains reserve on missing usage and lookup never dispatches',async()=>{const s=setup();await s.createRun(owner,input);const c=await s.claimAction(owner,{runId,actionId,action:'develop',inputFingerprint:fingerprint,expectedRevision:0});if(c.kind!=='claimed')throw Error();await s.startAction(owner,{runId,claimId:c.claimId,expectedRevision:1});const r=await s.recordOutcome(owner,{runId,claimId:c.claimId,expectedRevision:2,status:'complete'});expect(r.claims[0].state).toBe('usage-unverified');expect(r.reservedUsdMicros).toBe(7000);expect(await s.lookupRun(owner,runId)).toEqual(r);await expect(s.startAction(owner,{runId,claimId:c.claimId,expectedRevision:3})).rejects.toThrow('run_dispatch_denied');});
 it('records complete usage without refund and respects total dollar ceiling',async()=>{const s=setup({...policy,maxUsdMicros:7000});await s.createRun(owner,input);const c=await s.claimAction(owner,{runId,actionId,action:'develop',inputFingerprint:fingerprint,expectedRevision:0});if(c.kind!=='claimed')throw Error();await s.startAction(owner,{runId,claimId:c.claimId,expectedRevision:1});const r=await s.recordOutcome(owner,{runId,claimId:c.claimId,expectedRevision:2,status:'complete',providerRequestId:'request-test',providerEvidence:{provider:policy.provider,model:policy.model,accountRef:policy.accountRef},usage:{inputTokens:10,outputTokens:10,cacheTokens:0,toolCalls:0},validatedOutputFingerprint:fingerprint});expect(r.claims[0].actualUsdMicros).toBe(60);expect(r.reservedUsdMicros).toBe(7000);await expect(s.claimAction(owner,{runId,actionId:crypto.randomUUID(),action:'build',inputFingerprint:fingerprint,expectedRevision:3})).rejects.toThrow('run_budget_exceeded');});
 it('rejects expiry and makes returned receipts immutable snapshots',async()=>{await expect(setup({...policy,expiresAt:'2020-01-01T00:00:00Z'}).createRun(owner,input)).rejects.toThrow();const s=setup();const r=await s.createRun(owner,input);r.policy.maxCalls=100;expect((await s.lookupRun(owner,runId)).policy.maxCalls).toBe(2);});
 it('keeps production disabled and never substitutes memory on storage failure',async()=>{const rpc=vi.fn();await expect(createProductionOwnerRunStore(rpc).createRun(owner,input)).rejects.toThrow('run_storage_not_activated');expect(rpc).not.toHaveBeenCalled();rpc.mockResolvedValue({data:null,error:{}});await expect(createProductionOwnerRunStore(rpc,true).createRun(owner,input)).rejects.toThrow('run_storage_unavailable');});
 it('keeps wrong returned model/account evidence uncertain without refund',async()=>{const s=setup();await s.createRun(owner,input);const c=await s.claimAction(owner,{runId,actionId,action:'develop',inputFingerprint:fingerprint,expectedRevision:0});if(c.kind!=='claimed')throw Error();await s.startAction(owner,{runId,claimId:c.claimId,expectedRevision:1});const r=await s.recordOutcome(owner,{runId,claimId:c.claimId,expectedRevision:2,status:'complete',providerRequestId:'test',providerEvidence:{provider:'openai',model:'wrong-model',accountRef:policy.accountRef},usage:{inputTokens:10,outputTokens:10,cacheTokens:0,toolCalls:0},validatedOutputFingerprint:fingerprint});expect(r.claims[0].state).toBe('usage-unverified');expect(r.reservedUsdMicros).toBe(7000);});
 it('cannot dispatch after policy expiry',async()=>{vi.useFakeTimers();try{vi.setSystemTime(new Date('2026-10-02T00:00:00Z'));const s=setup({...policy,expiresAt:'2026-10-02T00:01:00Z'});await s.createRun(owner,input);const c=await s.claimAction(owner,{runId,actionId,action:'develop',inputFingerprint:fingerprint,expectedRevision:0});if(c.kind!=='claimed')throw Error();vi.setSystemTime(new Date('2026-10-02T00:02:00Z'));await expect(s.startAction(owner,{runId,claimId:c.claimId,expectedRevision:1})).rejects.toThrow('run_policy_expired');}finally{vi.useRealTimers();}});
 it('enforces maxCalls even when dollar capacity remains',async()=>{const s=setup({...policy,maxCalls:1});await s.createRun(owner,input);await s.claimAction(owner,{runId,actionId,action:'develop',inputFingerprint:fingerprint,expectedRevision:0});await expect(s.claimAction(owner,{runId,actionId:crypto.randomUUID(),action:'build',inputFingerprint:fingerprint,expectedRevision:1})).rejects.toThrow('run_budget_exceeded');});
 it('keeps embedded SQL validation identical to the adapter schemas',()=>{const sql=readFileSync(new URL('../../docs/migration-review/owner-run-schema-proposal.sql',import.meta.url),'utf8');const schemas={policy:runPolicySchema,create:createRunSchema,claim:claimActionSchema,start:startSchema,outcome:outcomeSchema,lookup:z.object({runId:z.uuid()}).strict()};for(const [key,schema] of Object.entries(schemas)){const marker=`$${key}$`,start=sql.indexOf(marker)+marker.length,end=sql.indexOf(marker,start);expect(start).toBeGreaterThan(marker.length);expect(JSON.parse(sql.slice(start,end))).toEqual(z.toJSONSchema(schema,{target:'draft-7'}));}});
 it('isolates two enabled owners with distinct policies and runs',async()=>{const otherId=crypto.randomUUID(),otherRun=crypto.randomUUID(),otherPolicy={...policy,id:'owner-b-policy',ownerId:otherId},other:Owner={userId:otherId,verified:true,anonymous:false};const s=createLocalOwnerRunStore(new Map([[policy.id,policy],[otherPolicy.id,otherPolicy]]),new Set([uid,otherId]));await s.createRun(owner,input);await s.createRun(other,{...input,runId:otherRun,policyId:otherPolicy.id});for(const [o,foreignRun] of [[owner,otherRun],[other,runId]] as const){await expect(s.lookupRun(o,foreignRun)).rejects.toThrow('run_unavailable');await expect(s.claimAction(o,{runId:foreignRun,actionId:crypto.randomUUID(),action:'develop',inputFingerprint:fingerprint,expectedRevision:0})).rejects.toThrow('run_unavailable');}expect((await s.lookupRun(owner,runId)).revision).toBe(0);expect((await s.lookupRun(other,otherRun)).revision).toBe(0);});
});
