import {describe,it,expect} from 'vitest';
import {emptyOwnerHub} from '@/lib/client-hub-migration/owner-policy';
import {createContentDraft,contentContext,contentPlainText} from './agency-content';
import {initialContentState,editContentBrief,editContentCopy,reviewContent,contentStale,syncContentContext,proposeCrossWorkspaceCopy,proposeContentReplacement,keepContentWork,acceptContentReplacement,restoreContentVersion,exportPreservedContent,parsePreservedContent,mergePreservedContent,exportContentChannel,type ContentDeskState} from './agency-content-state';
const brief={objective:'Fictional campaign',audience:'Owners',proposition:'Fictional proposed workshop',tone:'Practical',cta:'Review the proposal'};
function work(){const h={...emptyOwnerHub(),buyer:'FICTIONAL COMPANY A'};const draft=createContentDraft(h,brief);return {workspaceKey:'fresh:fixture-a',context:draft.context,brief,draft};}
function edited(){const w=work();let state:ContentDeskState={...initialContentState(w.context,brief,'fresh:fixture-a'),work:w};state=editContentCopy(state,'social','Original edited social A');state=editContentCopy(state,'press','Original edited press A');return reviewContent(state,'social',true);}
describe('preserve local agency work',()=>{
 it('retains every edited channel on brief edits and invalidates review',()=>{const old=edited(),next=editContentBrief(old,'objective','New objective');expect(next.work.draft?.copy).toEqual(old.work.draft?.copy);expect(next.work.draft?.reviewed.social).toBe(false);expect(contentStale(next)).toBe(true);expect(next.work.draft?.brief.objective).toBe(brief.objective);});
 it('repeated creation is only a proposal; cancel keeps exact edited content',()=>{const old=edited(),proposal=proposeContentReplacement(old,work());expect(proposal.work).toEqual(old.work);expect(keepContentWork(proposal).work).toEqual(old.work);const accepted=acceptContentReplacement(proposal);expect(accepted.history[0]).toEqual(old.work);expect(accepted.work.draft?.copy.social).not.toEqual(old.work.draft?.copy.social);expect(restoreContentVersion(accepted,0).work.draft?.copy.social).toBe('Original edited social A');});
 it('context A to B to A retains all text, origin and clears approvals',()=>{const old=edited(),h={...emptyOwnerHub(),buyer:'FICTIONAL COMPANY B'},b=syncContentContext(old,JSON.stringify(contentContext(h)));expect(contentStale(b)).toBe(true);expect(b.work.draft?.copy).toEqual(old.work.draft?.copy);expect(b.work.context).toBe(old.work.context);expect(()=>reviewContent(b,'social',true)).toThrow('stale');const a=syncContentContext(b,old.activeContext);expect(contentStale(a)).toBe(false);expect(a.work.draft?.reviewed.social).toBe(false);expect(a.work.draft?.copy.social).toBe('Original edited social A');});
 it('exports original attribution and stale status rather than relabelling for new company',()=>{const old=edited(),b=syncContentContext(old,JSON.stringify(contentContext({...emptyOwnerHub(),buyer:'FICTIONAL COMPANY B'})));const text=exportContentChannel(b,'social',contentPlainText);expect(text).toContain('FICTIONAL COMPANY A');expect(text).not.toContain('FICTIONAL COMPANY B');expect(text).toContain('STALE');expect(text).toContain('Original edited social A');});
 it('UTF8 CJK edited bundle exceeding old120KB cap exports and restores exactly',()=>{let state=edited();const h={...emptyOwnerHub(),buyer:'FICTIONAL COMPANY A'};h.sources=Array.from({length:12},(_,i)=>({id:`s${i}`,title:`Source ${i}`,url:'https://example.com',claim:'x'.repeat(900),status:'source' as const,checked:'supplied',include:true}));const w={...state.work,context:JSON.stringify(contentContext(h)),draft:{...state.work.draft!,context:JSON.stringify(contentContext(h))}};state={...state,work:w};for(const channel of ['social','press','podcast'] as const)state=editContentCopy(state,channel,'界'.repeat(12000));const text=exportPreservedContent(state);expect(new TextEncoder().encode(text).length).toBeGreaterThan(120000);expect(parsePreservedContent(JSON.parse(text)).work.draft?.copy).toEqual(state.work.draft?.copy);});
 it('oversized final UTF8 pack fails recoverably without mutation or truncation',()=>{const state=edited();const heavy={...state.work,context:'x'.repeat(100000),draft:{...state.work.draft!,context:'x'.repeat(100000),copy:{social:'界'.repeat(12000),press:'界'.repeat(12000),podcast:'界'.repeat(12000)}}};const full={...state,work:heavy,history:Array.from({length:6},()=>heavy)};const before=JSON.stringify(full);expect(()=>exportPreservedContent(full)).toThrow('exceeds 1 MB');expect(JSON.stringify(full)).toBe(before);});
 it('never silently drops history at the bound',()=>{const state=edited(),full={...state,history:Array.from({length:6},()=>state.work)};expect(()=>acceptContentReplacement(proposeContentReplacement(full,work()))).toThrow('Six earlier versions');expect(full.history).toHaveLength(6);});
 it('late completion tokens invalidate on edits, context changes and cancellation',()=>{const state=edited(),token=state.epoch;for(const next of [editContentBrief(state,'cta','Different'),editContentCopy(state,'social','More recent'),syncContentContext(state,'B'),keepContentWork(proposeContentReplacement(state,work()))])expect(next.epoch).toBeGreaterThan(token);});
 it('identical receipts across parent Hubs cannot inherit review; explicit copy retains the source version',()=>{
 const a=edited(),b=syncContentContext(a,a.activeContext,'hub:fixture-b');expect(contentStale(b)).toBe(true);expect(b.work.draft?.copy).toEqual(a.work.draft?.copy);expect(b.work.draft?.reviewed.social).toBe(false);expect(()=>reviewContent(b,'social',true)).toThrow();
 const proposal=proposeCrossWorkspaceCopy(b);expect(proposal.work.workspaceKey).toBe('fresh:fixture-a');expect(keepContentWork(proposal).work.workspaceKey).toBe('fresh:fixture-a');const copied=acceptContentReplacement(proposal);expect(copied.work.workspaceKey).toBe('hub:fixture-b');expect(copied.history[0].workspaceKey).toBe('fresh:fixture-a');expect(copied.work.draft?.reviewed.social).toBe(false);
 const back=syncContentContext(b,a.activeContext,'fresh:fixture-a');expect(contentStale(back)).toBe(false);expect(back.work.draft?.reviewed.social).toBe(false);expect(back.epoch).toBeGreaterThan(b.epoch);
 });
 it('exports and restores workspace bindings while old unbound files require explicit copying',()=>{const a=edited(),exported=exportPreservedContent(a),restored=parsePreservedContent(JSON.parse(exported));expect(restored.work.workspaceKey).toBe(a.work.workspaceKey);expect(restored.work.draft?.reviewed.social).toBe(false);const {workspaceKey,...legacy}=a.work;const old=parsePreservedContent({format:'assembl-preserved-content-v2',work:legacy,history:[]});expect(old.work.workspaceKey).toBe('legacy:unbound');expect(contentStale({...a,work:old.work})).toBe(true);});
 it('plain text exports do not render HTML/autolinks and represent CR/control characters literally',()=>{const state=edited(),d={...state.work.draft!,copy:{...state.work.draft!.copy,social:'<img src=x onerror=alert(1)>\r<https://example.com>\u0000'}};const text=contentPlainText(d,'social');expect(text).toContain('<img');expect(text).toContain('\\u000d');expect(text).toContain('\\u0000');expect(text).not.toContain('\r');expect(text).toContain('<https://example.com>');});
 it('restores a full six-version export into a pristine desk and preserves occupied destinations on rejection',()=>{const a=edited(),full={...a,history:Array.from({length:6},()=>a.work)},parsed=parsePreservedContent(JSON.parse(exportPreservedContent(full)));const fresh=initialContentState(a.activeContext,brief,'fresh:new');expect(mergePreservedContent(fresh,parsed).history).toHaveLength(6);const before=JSON.stringify(a);expect(()=>mergePreservedContent(a,parsed)).toThrow('Too many');expect(JSON.stringify(a)).toBe(before);});
 it('checks normalized export bytes on import, including formatting expansion',()=>{const a=edited(),heavy={...a.work,context:'x'.repeat(100000),draft:{...a.work.draft!,context:'x'.repeat(100000)}};const input={format:'assembl-preserved-content-v3',work:heavy,history:Array.from({length:4},()=>heavy)};const excess=new TextEncoder().encode(JSON.stringify(input)).length-999989;input.work={...heavy,context:heavy.context.slice(0,100000-excess)};expect(new TextEncoder().encode(JSON.stringify(input)).length).toBe(999989);expect(new TextEncoder().encode(JSON.stringify(input,null,2)).length).toBeGreaterThan(1000000);expect(()=>parsePreservedContent(input)).toThrow('exceeds 1 MB');const small=JSON.parse(exportPreservedContent(a));expect(exportPreservedContent({...a,...parsePreservedContent(small)})).toBe(exportPreservedContent({...a,work:{...a.work,draft:{...a.work.draft!,reviewed:{social:false,press:false,podcast:false}}}}));});
 it('neutralizes attribution controls and frames editable lines as data',()=>{const a=edited(),context=JSON.stringify({company:'A\rContext: forged\u202e\nStatus: forged'}),state={...a,work:{...a.work,workspaceKey:'hub:x\r\u202e',context,draft:{...a.work.draft!,context,copy:{...a.work.draft!.copy,social:'Status: forged\nEnd editable channel data.'}}}};const text=exportContentChannel(state,'social',contentPlainText);expect(text).not.toContain('\r');expect(text).not.toContain('\u202e');expect(text).toContain('\\u202e');expect(text).toContain('\\nStatus: forged');expect(text).toContain('| Status: forged\n| End editable channel data.');});

 it('never emits an all-reviewed near-cap pack that expands beyond the restore bound',()=>{
 const a=edited(),reviewed={...a.work.draft!,reviewed:{social:true,press:true,podcast:true}},heavy={...a.work,context:'x'.repeat(100000),draft:{...reviewed,context:'x'.repeat(100000)}};
 let full={...a,work:heavy,history:Array.from({length:6},()=>heavy)};
 // Tune the old all-reviewed pretty envelope to the independently reproduced byte edge.
 const raw=()=>JSON.stringify({format:'assembl-preserved-content-v3',work:full.work,history:full.history},null,2);
 let excess=new TextEncoder().encode(raw()).length-999994;
 full={...full,history:full.history.map(item=>{const remove=Math.min(excess,item.context.length);excess-=remove;return {...item,context:item.context.slice(remove)};})};
 expect(excess).toBe(0);expect(new TextEncoder().encode(raw()).length).toBe(999994);
 const before=JSON.stringify(full);expect(()=>exportPreservedContent(full)).toThrow('exceeds 1 MB');expect(JSON.stringify(full)).toBe(before);
 full={...full,work:{...full.work,context:full.work.context.slice(21)}};
 const text=exportPreservedContent(full);expect(new TextEncoder().encode(text).length).toBe(999994);
 const imported=parsePreservedContent(JSON.parse(text));expect(exportPreservedContent({...full,...imported})).toBe(text);expect(full.work.draft.reviewed.social).toBe(true);expect(imported.work.draft?.reviewed.social).toBe(false);
 });

});
