import {describe,it,expect} from 'vitest';
import {defaultSellerBrand} from '@/components/client-hub-migration/original/lib/seller-brand';
import {emptyOwnerHub} from '@/lib/client-hub-migration/owner-policy';
import {contentContext,createContentDraft,importContentDraft,contentMarkdown,specialistPrompt} from './agency-content';
const brief={objective:'Introduce a fictional service',audience:'Owners',proposition:'A fictional proposed planning session',tone:'Practical',cta:'Discuss the proposal'};
describe('local agency content boundary',()=>{
 it('produces all channels from one explicit brief with honest gaps',()=>{const d=createContentDraft(emptyOwnerHub(),brief);for(const copy of Object.values(d.copy)){expect(copy).toContain('no model called');expect(copy).toContain('[EVIDENCE REQUIRED]');expect(copy).toContain(brief.cta);}expect(d.copy.press).toContain('PROPOSED QUOTE — NOT APPROVED');expect(d.copy.podcast).toContain('recording consent');});
 it('uses only selected factual sources and excludes private notes',()=>{const h=emptyOwnerHub();h.privateNotes='SECRET';h.sources=[{id:'selected',title:'Selected',url:'https://example.com',claim:'Supplied claim',status:'source',include:true,checked:'unverified'},{id:'ignored',title:'Ignored',url:'https://example.com',claim:'Excluded claim',status:'source',include:false,checked:''}];const d=createContentDraft(h,brief);expect(d.copy.social).toContain('[selected]');expect(JSON.stringify(d)).not.toContain('SECRET');expect(JSON.stringify(d)).not.toContain('Excluded claim');expect(contentContext(h).sources).toHaveLength(1);});
 it('does not project unreviewed seller notes, deck metadata or embedded logos',()=>{const h=emptyOwnerHub();h.sellerBrand={...defaultSellerBrand('assembl'),notes:'PRIVATE UNREVIEWED NOTES',notesApproved:false};expect(JSON.stringify(contentContext(h))).not.toContain('PRIVATE UNREVIEWED');h.sellerBrand.notesApproved=true;expect(contentContext(h).brand.seller?.reviewedNotes).toBe('PRIVATE UNREVIEWED NOTES');});
 it('rejects cross-client, changed source and changed brand imports',()=>{const h=emptyOwnerHub(),d=createContentDraft(h,brief);expect(()=>importContentDraft({...h,buyer:'Another company'},d)).toThrow('different brief');expect(()=>importContentDraft({...h,engine:{...h.engine!,brief:'Changed'}},d)).toThrow();});
 it('clears imported approvals, rejects extra fields and missing brief inputs',()=>{const h=emptyOwnerHub(),d=createContentDraft(h,brief);d.reviewed.social=true;expect(importContentDraft(h,d).reviewed.social).toBe(false);expect(()=>importContentDraft(h,{...d,send:true})).toThrow();expect(()=>createContentDraft(h,{...brief,cta:''})).toThrow();});
 it('exports truthful status and explicit constrained prompts',()=>{const d=createContentDraft(emptyOwnerHub(),brief);expect(contentMarkdown(d,'press')).toContain('Unreviewed local template');d.reviewed.press=true;expect(contentMarkdown(d,'press')).toContain('Locally reviewed draft');for(const role of ['strategist','social','press','podcast'] as const){const p=specialistPrompt(role);for(const label of ['ROLE:','TOOLS:','INPUT:','OUTPUT:','SOURCES:','APPROVAL:'])expect(p).toContain(label);expect(p).toContain('never evidence');}});
});
