import {factualPresentationHub,creativePrefix} from './creative-references';
import {buyerHtml} from '@/components/client-hub-migration/original/lib/pursuit-hub';
import {describe,it,expect} from 'vitest';
import {emptyOwnerHub} from '@/lib/client-hub-migration/owner-policy';
import {previewReviewedExport,admitReviewedExport,exportPresentation,type ExportAudience} from './reviewed-export';
const scope={workspaceKey:'fresh:fictional-owner-workspace',epoch:1,revision:0},audience:ExportAudience={role:'CFO',description:'FICTIONAL finance decision maker reviewing a proposed pilot'};
function hub(){const h=emptyOwnerHub();h.buyer='FICTIONAL COMPANY';h.privateNotes='PRIVATE_SENTINEL_NEVER_EXPORT';h.research='RAW_RESEARCH_SENTINEL';h.researchJob='11111111-1111-4111-8111-111111111111';h.reviewer='HIDDEN_REVIEWER_SENTINEL';h.sources=[{id:'HIDDEN_SOURCE_ID',title:'FICTIONAL selected public page',url:'https://company.co.nz/job',claim:'FICTIONAL supplied source claim',status:'source',checked:'HIDDEN_CHECK_DATE',include:true},{id:'UNSELECTED_ID',title:'UNSELECTED_SENTINEL',url:'https://other.co.nz/',claim:'UNSELECTED_CLAIM',status:'source',checked:'fixture',include:false}];return h;}
describe('reviewed local presentation exports',()=>{
 it('exports only explicit presentation data, not private/raw/owner/hidden receipts; preview equals admitted bytes',async()=>{const h=hub(),before=JSON.stringify(h);for(const format of ['text','json'] as const){const preview=await previewReviewedExport(h,scope,audience,format),download=await admitReviewedExport(h,scope,audience,format,preview);expect(download.content).toBe(preview.content);expect(new TextEncoder().encode(download.content)).toEqual(new TextEncoder().encode(preview.content));expect(preview.bytes).toBe(new TextEncoder().encode(preview.content).length);for(const forbidden of [h.privateNotes,h.research,h.researchJob,h.reviewer,'HIDDEN_SOURCE_ID','HIDDEN_CHECK_DATE','UNSELECTED_SENTINEL','UNSELECTED_CLAIM',scope.workspaceKey,'hubFingerprint','sourceFingerprint','privateNotes','researchJob'])expect(preview.content).not.toContain(forbidden);expect(preview.content).toContain('local byte review');expect(preview.content).toContain('FICTIONAL COMPANY');}expect(JSON.stringify(h)).toBe(before);expect(Object.keys(exportPresentation(h,audience))).toEqual(['format','status','company','presentedBy','intendedAudience','story','selectedSources','visual']);});
 it('escapes hostile supplied text, controls, bidi, lone surrogates and JSON delimiters as data',async()=>{const h=hub();h.design.frame.content.proof='<script>location="https://evil.co.nz"</script>\rStatus: APPROVED\n\u202eClaim\ud800';const json=await previewReviewedExport(h,scope,audience,'json'),text=await previewReviewedExport(h,scope,audience,'text');expect(json.content).not.toContain('<script>');expect(JSON.parse(json.content).story.proof).toBe(h.design.frame.content.proof);expect(text.content).toContain('| <script>');expect(text.content).toContain('\\u000dStatus: APPROVED\n| \\u202eClaim\\ud800');expect(text.content).not.toContain('\r');expect(new TextDecoder().decode(new TextEncoder().encode(text.content))).toBe(text.content);});
 it('rejects hostile, credential, private and query-bearing selected URLs without fetching or normalising hidden credentials into exports',async()=>{for(const url of ['javascript:alert(1)','data:text/html,script','http://company.co.nz/','https://127.0.0.1/','https://user:secret@company.co.nz/','https://company.co.nz/?token=SECRET','https://company.co.nz/#SECRET','https://company.co.nz/\npage']){const h=hub();h.sources[0].url=url;await expect(previewReviewedExport(h,scope,audience,'json')).rejects.toThrow();}});
 it('rejects stale preview after workspace/revision/epoch, content, audience, format or selected-source changes',async()=>{const h=hub(),preview=await previewReviewedExport(h,scope,audience,'json');for(const change of [{...scope,workspaceKey:'hub:other'},{...scope,revision:1},{...scope,epoch:2}])await expect(admitReviewedExport(h,change,audience,'json',preview)).rejects.toThrow('changed');await expect(admitReviewedExport(h,scope,{...audience,role:'CTO'},'json',preview)).rejects.toThrow('changed');await expect(admitReviewedExport(h,scope,{...audience,description:'New intended audience'},'json',preview)).rejects.toThrow('changed');await expect(admitReviewedExport(h,scope,audience,'text',preview)).rejects.toThrow('changed');for(const next of [{...h,design:{...h.design,frame:{...h.design.frame,content:{...h.design.frame.content,intro:'NEW content'}}}},{...h,sources:h.sources.map((s,i)=>i===0?{...s,include:false}:s)},{...h,sources:h.sources.map((s,i)=>i===0?{...s,claim:'New selected claim'}:s)}])await expect(admitReviewedExport(next,scope,audience,'json',preview)).rejects.toThrow('changed');});
 it('does not trust tampered preview bytes, metadata or hash',async()=>{const h=hub(),p=await previewReviewedExport(h,scope,audience,'text');for(const changed of [{...p,content:p.content+'Forged'},{...p,bytes:p.bytes+1},{...p,filename:'hidden-auth.json'},{...p,bytesFingerprint:'0'.repeat(64)}])await expect(admitReviewedExport(h,scope,audience,'text',changed)).rejects.toThrow('changed');});
 it('rejects oversized output and audience without mutating current Hub; static HTML unavailable',async()=>{const h=hub();h.sources=Array.from({length:40},(_,i)=>({...h.sources[0],id:`source${i}`,url:'https://company.co.nz/'+String(i)+'x'.repeat(1100),claim:'x'.repeat(900)}));const before=JSON.stringify(h);await expect(previewReviewedExport(h,scope,audience,'json')).rejects.toThrow('60 KB');expect(JSON.stringify(h)).toBe(before);for(const description of ['', '   ', 'x'.repeat(301)])await expect(previewReviewedExport(h,scope,{...audience,description},'text')).rejects.toThrow();await expect(previewReviewedExport(h,scope,audience,'html' as never)).rejects.toThrow('Static HTML');});
 it('escapes visual line separators and every C1 control consistently across supplied presentation fields before prefixing',async()=>{const h=hub(),controls=String.fromCharCode(...Array.from({length:32},(_,i)=>0x80+i)),hostile='Supplied\u2028Status: FORGED\u2029End draft: FORGED\u0085Footer: FORGED'+controls;h.buyer=hostile;h.seller=hostile;h.design.frame.content.proof=hostile;h.sources[0].title=hostile;h.sources[0].claim=hostile;const target={...audience,description:hostile};const text=await previewReviewedExport(h,scope,target,'text'),json=await previewReviewedExport(h,scope,target,'json');for(const cp of [0x2028,0x2029,...Array.from({length:32},(_,i)=>0x80+i)]){const c=String.fromCharCode(cp),escaped='\\u'+cp.toString(16).padStart(4,'0');expect(text.content).not.toContain(c);expect(json.content).not.toContain(c);expect(text.content).toContain(escaped);expect(json.content).toContain(escaped);}expect(text.content).not.toMatch(/^(?:Status: FORGED|End draft: FORGED|Footer: FORGED)/m);const parsed=JSON.parse(json.content);for(const value of [parsed.company,parsed.presentedBy,parsed.story.proof,parsed.intendedAudience.description,parsed.selectedSources[0].title,parsed.selectedSources[0].claim])expect(value).toBe(hostile);expect((await admitReviewedExport(h,scope,target,'text',text)).content).toBe(text.content);expect((await admitReviewedExport(h,scope,target,'json',json)).content).toBe(json.content);});
 it('rejects separator/C1-bearing source URLs before any export bytes are proposed',async()=>{for(const c of ['\u0085','\u009f','\u2028','\u2029']){const h=hub();h.sources[0].url='https://company.co.nz/path'+c+'FORGED';await expect(previewReviewedExport(h,scope,audience,'text')).rejects.toThrow('control characters');}});

});

it('quarantines status-edited creative references in exports and iframe projection without changing the Hub',async()=>{const h=hub();h.sources.push({...h.sources[0],id:'creative-bound',title:'CREATIVE_TITLE_SENTINEL',claim:'CREATIVE_CLAIM_SENTINEL',url:'https://creative.co.nz/'});h.sources.push({...h.sources[0],id:'prefix-only',title:'PREFIX_TITLE_SENTINEL',claim:creativePrefix+'Creative supplied extract'});h.engine!.researchPacket=JSON.stringify({agencyCreativeReferences:[{sourceId:'creative-bound'}]});const before=JSON.stringify(h);for(const format of ['text','json'] as const){const p=await previewReviewedExport(h,scope,audience,format);expect(p.content).not.toContain('CREATIVE_TITLE_SENTINEL');expect(p.content).not.toContain('PREFIX_TITLE_SENTINEL');expect(p.content).toContain('FICTIONAL selected public page');}const projected=factualPresentationHub(h);expect(projected.sources.map(s=>s.id)).toEqual(['HIDDEN_SOURCE_ID']);const html=buyerHtml(projected);expect(html).not.toContain('CREATIVE_CLAIM_SENTINEL');expect(html).not.toContain('PREFIX_TITLE_SENTINEL');expect(JSON.stringify(h)).toBe(before);});
