import {describe,it,expect} from 'vitest';
import {emptyOwnerHub} from '@/lib/client-hub-migration/owner-policy';
import {newOwnerIdea} from '@/lib/client-hub-migration/owner-idea';
import {nodeIds} from '@/components/client-hub-migration/original/lib/creative';
import {editStudioSection,validateStudioSaveAcknowledgement,promoteStudioCheckpoints,studioHasUnsavedWork,compareStudioDirections,applyStudioDirection,retainStudioCheckpoint,restoreStudioCheckpoint} from './section-controls';
const key='fresh:fictional-workspace';
function hub(){return {...emptyOwnerHub(),privateNotes:'Fictional local private note',buyer:'FICTIONAL COMPANY'};}
describe('original section controls in one Hub',()=>{
 it('edits all named sections without erasing other text, notes or source context',()=>{let h=hub();for(const node of nodeIds)h=editStudioSection(h,node,`Edited ${node}`);expect(h.design.frame.content).toEqual(Object.fromEntries(nodeIds.map(n=>[n,`Edited ${n}`])));expect(h.privateNotes).toBe('Fictional local private note');expect(h.sources).toEqual([]);expect(h.design.approved).toBeNull();});
 it('rejects invalid text and artwork without truncating or changing the Hub',()=>{const h=hub(),before=JSON.stringify(h);expect(()=>editStudioSection(h,'headline','x'.repeat(151))).toThrow();expect(()=>editStudioSection({...h,design:{...h.design,frame:{...h.design.frame,artwork:{src:'/cinematic/assembl-plum-aerial.jpg',alt:'Invalid archival default'}}}},'intro','edit')).toThrow();expect(JSON.stringify(h)).toBe(before);});
 it('keeps the chosen idea linked without rebuilding the journey or other section edits',()=>{let h=hub();const idea=newOwnerIdea(h);h={...h,engine:{...h.engine!,selected:idea.id,concepts:[idea]}};const before=h.engine!.concepts[0].journey;h=editStudioSection(h,'proof','Supplied fictional proof');h=editStudioSection(h,'headline','Edited headline');expect(h.engine!.concepts[0].title).toBe('Edited headline');expect(h.engine!.concepts[0].gaps).toEqual(['Supplied fictional proof']);expect(h.engine!.concepts[0].journey).toEqual(before);expect(h.design.frame.content.proof).toBe('Supplied fictional proof');});
 it('compares three layouts without mutating copy, typeface or approval, then admits only the captured workspace/draft',()=>{const h=hub(),before=JSON.stringify(h),comparison=compareStudioDirections(h,key,1);expect(comparison.directions.map(d=>d.frame.tokens.layout)).toEqual(['editorial','statement','blueprint']);expect(comparison.directions.every(d=>d.frame.tokens.font===h.design.frame.tokens.font&&JSON.stringify(d.frame.content)===JSON.stringify(h.design.frame.content))).toBe(true);expect(JSON.stringify(h)).toBe(before);const next=applyStudioDirection(h,comparison,comparison.directions[1].id,key,1);expect(next.design.frame.tokens.layout).toBe('statement');expect(next.design.approved).toBeNull();expect(()=>applyStudioDirection(editStudioSection(h,'intro','Newer'),comparison,comparison.directions[0].id,key,1)).toThrow('draft changed');expect(()=>applyStudioDirection(h,comparison,comparison.directions[0].id,'hub:other',1)).toThrow('workspace');expect(()=>applyStudioDirection(h,comparison,comparison.directions[0].id,key,2)).toThrow('draft changed');});
 it('retains and restores full Hub context as a draft while swapping the newer Hub into the checkpoint',()=>{const h=hub(),history=retainStudioCheckpoint([],h,key),newer=editStudioSection({...h,privateNotes:'NEWER notes',buyerRole:'NEWER audience'},'intro','NEWER text');const restored=restoreStudioCheckpoint(newer,history,history[0].id,key);expect(restored.hub.privateNotes).toBe(h.privateNotes);expect(restored.hub.buyerRole).toBe(h.buyerRole);expect(restored.hub.design.frame.content.intro).toBe(h.design.frame.content.intro);expect(restored.hub.design.approved).toBeNull();expect(restored.history[0].hub).toEqual(newer);expect(()=>restoreStudioCheckpoint(newer,history,history[0].id,'hub:other')).toThrow('another workspace');});
 it('does not evict full histories or add over-byte snapshots',()=>{const h=hub(),one=retainStudioCheckpoint([],h,key),six=Array.from({length:6},()=>one[0]);expect(()=>retainStudioCheckpoint(six,h,key)).toThrow('Six checkpoints');expect(six).toHaveLength(6);});
 it('clears evidence and tender approvals on restore without treating a reviewer name as approval',()=>{const h=hub();h.design={...h.design,evidenceState:'reviewed',reviewer:'Fictional reviewer',approved:{by:'Fictional reviewer',at:'fixture',fingerprint:'fixture'}};h.engine={...h.engine!,requirements:[{id:'r',question:'Fixture question',reference:'Fixture',answer:'Fixture answer',evidenceIds:['e'],status:'reviewed draft',usedExtracts:[]}],evidence:[{id:'e',title:'Fixture evidence',body:'Fixture supplied text',approved:true}]};const history=retainStudioCheckpoint([],h,key),restored=restoreStudioCheckpoint(h,history,history[0].id,key);expect(restored.hub.design.approved).toBeNull();expect(restored.hub.design.evidenceState).toBe('supplied');expect(restored.hub.design.reviewer).toBe('Fictional reviewer');expect(restored.hub.engine?.requirements[0].status).toBe('agent draft');expect(restored.hub.engine?.evidence[0].approved).toBe(false);expect(editStudioSection(h,'proof','New proof').design.evidenceState).toBe('supplied');});
 it('rejects oversized checkpoint envelopes without losing the prior snapshots',()=>{const h=hub();h.sources=Array.from({length:40},(_,i)=>({id:`s${i}`,title:'Fictional source',url:'https://example.com',claim:'x'.repeat(900),status:'source' as const,checked:'Fixture',include:true}));h.engine={...h.engine!,evidence:Array.from({length:30},(_,i)=>({id:`e${i}`,title:'Fictional evidence',body:'x'.repeat(9000),approved:false}))};const one=retainStudioCheckpoint([],h,key),five=Array.from({length:5},()=>one[0]),before=JSON.stringify(five);expect(()=>retainStudioCheckpoint(five,h,key)).toThrow('1.8 MB');expect(JSON.stringify(five)).toBe(before);});

 it('promotes only confirmed first-save checkpoint bindings from the selected fresh workspace',()=>{const h=hub(),history=retainStudioCheckpoint([],h,key),foreign=retainStudioCheckpoint([],h,'fresh:other'),all=[...history,...foreign],e={fromWorkspaceKey:key,currentWorkspaceKey:key,startedEpoch:1,currentEpoch:1,acknowledgedId:'11111111-1111-4111-8111-111111111111',acknowledgedRevision:1,submittedHub:h,acknowledgedHub:h};const promoted=promoteStudioCheckpoints(all,e);expect(promoted[0].workspaceKey).toBe(`hub:${e.acknowledgedId}`);expect(promoted[1]).toEqual(foreign[0]);expect(restoreStudioCheckpoint(h,promoted,promoted[0].id,`hub:${e.acknowledgedId}`).hub.design.approved).toBeNull();for(const delta of [{currentWorkspaceKey:'fresh:other'},{currentEpoch:2},{existingId:e.acknowledgedId},{acknowledgedId:'invalid'},{acknowledgedRevision:2},{acknowledgedHub:{...h,buyer:'Different saved payload'}}])expect(promoteStudioCheckpoints(all,{...e,...delta})).toBe(all);});
 it('keeps page-only checkpoints dirty independently of Hub saves until explicitly removed',()=>{const history=retainStudioCheckpoint([],hub(),key);expect(studioHasUnsavedWork(false,false,history)).toBe(true);expect(studioHasUnsavedWork(false,false,[])).toBe(false);expect(studioHasUnsavedWork(true,false,[])).toBe(true);expect(studioHasUnsavedWork(false,true,[])).toBe(true);});

 it('rejects valid but mismatched save ACK before adopting identity, including updates',()=>{const h=hub(),id='11111111-1111-4111-8111-111111111111',ack={id,revision:1,payload:h};expect(validateStudioSaveAcknowledgement(ack,h,undefined,0)).toBe(ack);expect(()=>validateStudioSaveAcknowledgement({...ack,payload:{...h,buyer:'Different valid Hub'}},h,undefined,0)).toThrow('does not match');expect(()=>validateStudioSaveAcknowledgement({...ack,revision:2},h,undefined,0)).toThrow();expect(()=>validateStudioSaveAcknowledgement({...ack,id:'22222222-2222-4222-8222-222222222222',revision:2},h,id,1)).toThrow();expect(validateStudioSaveAcknowledgement({...ack,revision:2},h,id,1).revision).toBe(2);});

});
