import {describe,it,expect} from 'vitest';
import {newOwnerIdea} from '@/lib/client-hub-migration/owner-idea';
import {emptyOwnerHub} from '@/lib/client-hub-migration/owner-policy';
import {applySectionPatch,reviewSectionPatch,sectionPatchBinding} from './section-patch';
import {retainStudioCheckpoint} from './section-controls';
const scope={workspaceKey:'fresh:fictional',epoch:1,revision:0};
function hub(){return {...emptyOwnerHub(),privateNotes:'Fictional private notes retained',buyer:'FICTIONAL COMPANY'};}
async function proposal(h=hub()){return {schemaVersion:1 as const,binding:await sectionPatchBinding(h,scope),changes:{headline:'FICTIONAL NEW HEADLINE',intro:'<script>text remains data</script>'}};}
describe('bounded local section patch admission and atomic application',()=>{
 it('stages literal before/after without changing Hub or histories, then checkpoints exact full Hub before draft application',async()=>{const h=hub(),before=JSON.stringify(h),p=await proposal(h);h.design.approved={by:'Fictional reviewer',at:'fixture',fingerprint:'fixture'};p.binding=await sectionPatchBinding(h,scope);const review=await reviewSectionPatch(h,scope,JSON.stringify(p));expect(review.changes.map(c=>c.field)).toEqual(['headline','intro']);expect(review.changes[0].before).toBe(h.design.frame.content.headline);const history=retainStudioCheckpoint([],h,scope.workspaceKey),historyBefore=JSON.stringify(history);const result=await applySectionPatch(h,history,scope,p);expect(result.history).toHaveLength(2);expect(result.history[1].hub).toEqual(h);expect(result.hub.privateNotes).toBe(h.privateNotes);expect(result.hub.design.frame.content.intro).toBe('<script>text remains data</script>');expect(result.hub.design.approved).toBeNull();expect(JSON.stringify(history)).toBe(historyBefore);expect(before).not.toBe(JSON.stringify(result.hub));expect(h.design.frame.content.headline).not.toBe('FICTIONAL NEW HEADLINE');});
 it('rejects another workspace, changed epoch/save revision, source/brief/design/content and private context at review and apply',async()=>{const h=hub(),p=await proposal(h);for(const s of [{...scope,workspaceKey:'hub:other'},{...scope,epoch:2},{...scope,revision:1}])await expect(applySectionPatch(h,[],s,p)).rejects.toThrow('revision changed');for(const next of [{...h,privateNotes:'NEW private context'},{...h,sources:[{id:'fictional',title:'Fictional source',url:'https://example.com',claim:'Fictional',status:'source' as const,checked:'fixture',include:true}]},{...h,offer:'Changed brief offer'},{...h,design:{...h.design,frame:{...h.design.frame,tokens:{...h.design.frame.tokens,paper:'#ffffff'}}}},{...h,design:{...h.design,frame:{...h.design.frame,content:{...h.design.frame.content,proof:'Newer proof'}}}}])await expect(reviewSectionPatch(next,scope,JSON.stringify(p))).rejects.toThrow('revision changed');});
 it('rejects oversized UTF-8 envelopes and field values, unknown/private/approval fields and empty changes without mutation',async()=>{const h=hub(),p=await proposal(h),before=JSON.stringify(h);for(const input of ['界'.repeat(6000),JSON.stringify({...p,changes:{headline:'x'.repeat(151)}}),JSON.stringify({...p,changes:{privateNotes:'forbidden'}}),JSON.stringify({...p,changes:{approved:true}}),JSON.stringify({...p,privateNotes:'forbidden'}),JSON.stringify({...p,changes:{}})])await expect(reviewSectionPatch(h,scope,input)).rejects.toThrow();expect(JSON.stringify(h)).toBe(before);});
 it('does not evict checkpoints or mutate work when checkpoint admission fails',async()=>{const h=hub(),history=retainStudioCheckpoint([],h,scope.workspaceKey),six=Array.from({length:6},()=>history[0]),before=JSON.stringify(six);await expect(applySectionPatch(h,six,scope,await proposal(h))).rejects.toThrow('Six checkpoints');expect(JSON.stringify(six)).toBe(before);expect(h.privateNotes).toBe('Fictional private notes retained');});
 it('revalidates proposal schema and all bindings at application instead of trusting a staged DTO',async()=>{const h=hub(),p=await proposal(h);const tampered={...p,changes:{...p.changes,privateNotes:'No'}};await expect(applySectionPatch(h,[],scope,tampered)).rejects.toThrow();const revised={...p,binding:{...p.binding,sourceFingerprint:'0'.repeat(64)}};await expect(applySectionPatch(h,[],scope,revised)).rejects.toThrow('revision changed');});
 it('rejects blank/padded headline before preview and preserves exact preview/application and chosen-idea text',async()=>{const h=hub(),idea=newOwnerIdea(h);h.engine={...h.engine!,concepts:[idea],selected:idea.id};const p=await proposal(h);for(const headline of ['', '   ', ' padded ', '\nPadded'])await expect(reviewSectionPatch(h,scope,JSON.stringify({...p,changes:{headline}}))).rejects.toThrow('headline must be nonempty');const values={headline:'Exact headline',intro:'  Supplied proposition  ',problem:'Problem',solution:'Solution',proof:'Literal <b>proof</b>',next:'Next step'},review=await reviewSectionPatch(h,scope,JSON.stringify({...p,changes:values})),result=await applySectionPatch(h,[],scope,{...p,changes:values});for(const change of review.changes)expect(result.hub.design.frame.content[change.field]).toBe(change.after);const chosen=result.hub.engine!.concepts[0];expect(chosen.title).toBe(values.headline);expect(chosen.promise).toBe(values.intro);expect(chosen.why).toBe(values.problem);expect(chosen.agent).toBe(values.solution);expect(chosen.gaps).toEqual([values.proof]);expect(chosen.pilot).toBe(values.next);});
 it('rejects raw own __proto__ and other unknown keys at every permitted object depth',async()=>{const h=hub(),p=await proposal(h);for(const level of ['root','binding','changes']){const raw=JSON.parse(JSON.stringify(p));const target=level==='root'?raw:raw[level];Object.defineProperty(target,'__proto__',{value:{polluted:true},enumerable:true});await expect(reviewSectionPatch(h,scope,JSON.stringify(raw))).rejects.toThrow('Unknown');}expect(({} as Record<string,unknown>).polluted).toBeUndefined();});

});
