import nextVitals from 'eslint-config-next/core-web-vitals';

const config = [
  {
    ignores: [
      '.next/**', 'node_modules/**', 'out/**', 'dist/**', 'coverage/**',
      // Unmodified Apache-licensed Draco decoder, generated by upstream.
      'public/do/office/draco/**',
    ],
  },
  ...nextVitals,
];

export default config;
