import { useEffect, useState } from "react";

const ContentHubHero = () => {
  const [agentCount, setAgentCount] = useState(0);

  useEffect(() => {
    const target = 42;
    const duration = 2000;
    const step = duration / target;
    let current = 0;
    const timer = setInterval(() => {
      current++;
      setAgentCount(current);
      if (current >= target) clearInterval(timer);
    }, step);
    return () => clearInterval(timer);
  }, []);

  return (
    <section className="relative px-4 sm:px-8 pt-20 pb-12 text-center">
      <h1
        className="font-syne font-extrabold text-3xl sm:text-5xl lg:text-6xl tracking-tight halo-heading"
        style={{ color: "hsl(var(--foreground))" }}
      >
        See what your AI workforce builds
      </h1>
      <p
        className="mt-4 font-jakarta text-sm sm:text-base lg:text-lg max-w-2xl mx-auto"
        style={{ color: "rgba(255,255,255,0.4)" }}
      >
        Not mockups. Not concepts. Actual outputs generated by Assembl agents in seconds.
      </p>
      <div
        className="mt-6 font-mono-jb text-xs sm:text-sm tracking-widest"
        style={{ color: "rgba(255,255,255,0.25)" }}
      >
        <span style={{ color: "#00FF88" }}>{agentCount}</span> agents ·{" "}
        <span style={{ color: "#00E5FF" }}>200+</span> document types ·{" "}
        <span style={{ color: "#B388FF" }}>Every NZ industry</span>
      </div>
    </section>
  );
};

export default ContentHubHero;
