// ═══════════════════════════════════════════════════════════════
// AAAIP — Researcher API client
// Read-only access to the aaaip_audit_exports table for AAAIP
// partners. Used by the /aaaip/researcher admin view.
// Authenticated reads only — RLS on the table enforces this.
//
// Note: the auto-generated Supabase Database type in
// src/integrations/supabase/types.ts is regenerated by Lovable on
// migration sync, but is not in sync with the new table at the
// time of writing. We use a narrow `any` cast at the .from() call
// site so the rest of the file stays strongly typed against
// AuditExportRow. Once Lovable regenerates types this can be
// replaced with the typed call.
// ═══════════════════════════════════════════════════════════════

import { supabase } from "@/integrations/supabase/client";

export interface AuditExportRow {
  id: string;
  domain: "clinic" | "robot" | "science" | "community";
  pilot_label: string | null;
  exported_at: string;
  entry_count: number;
  total_decisions: number;
  allowed: number;
  needs_human: number;
  blocked: number;
  applied: number;
  compliance_rate: number | null;
  human_approval_rate: number | null;
  policy_hits: Record<string, number>;
  entries: unknown[];
  user_agent: string | null;
  source_ip: string | null;
  created_at: string;
}

export interface ListExportsOptions {
  domain?: string;
  limit?: number;
}

const SELECT_COLUMNS =
  "id, domain, pilot_label, exported_at, entry_count, total_decisions, allowed, needs_human, blocked, applied, compliance_rate, human_approval_rate, policy_hits, entries, user_agent, source_ip, created_at";

export async function listAuditExports(
  opts: ListExportsOptions = {},
): Promise<{ rows: AuditExportRow[]; error?: string }> {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  let query: any = (supabase as unknown as {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    from: (table: string) => any;
  })
    .from("aaaip_audit_exports")
    .select(SELECT_COLUMNS)
    .order("created_at", { ascending: false })
    .limit(opts.limit ?? 50);

  if (opts.domain && opts.domain !== "all") {
    query = query.eq("domain", opts.domain);
  }

  const { data, error } = await query;
  if (error) {
    return { rows: [], error: error.message as string };
  }
  return { rows: (data ?? []) as AuditExportRow[] };
}
