import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { SampleSite } from '@/components/living-site/SampleSite';
import { getInstall } from '@/lib/living-site/install-store';

// A generated install reads its genome rows on every request — the same
// ripple as the sample sites, on a genome the visitor wrote minutes ago.
export const dynamic = 'force-dynamic';

type Params = { id: string };

export const metadata: Metadata = {
  title: 'your living site — a generated install · assembl',
  description:
    'A Living Site generated by the assembl installer: ten answers became a real Business Genome, and this page reads it live.',
  // Visitor-generated demo data — never indexed.
  robots: { index: false, follow: false },
};

export default async function InstallSitePage({ params }: { params: Promise<Params> }) {
  const install = await getInstall((await params).id);
  if (!install) notFound();

  return (
    <SampleSite
      v={install.v}
      facts={install.facts}
      live
      install={{ id: install.id }}
    />
  );
}
