'use client';
import {useLayoutEffect,useRef,useState} from 'react';
import PreviewImage from '@/components/client-hub-migration/PreviewImage';
import type {Hub} from '@/components/client-hub-migration/original/lib/pursuit-hub';
import {channels,contentContext,createContentDraft,importContentDraft,contentPlainText,specialistPrompt,type Channel,type ContentBrief} from '@/lib/private-showpiece/agency-content';
import {initialContentState,proposeCrossWorkspaceCopy,syncContentContext,editContentBrief,editContentCopy,reviewContent,contentStale,proposeContentReplacement,acceptContentReplacement,keepContentWork,restoreContentVersion,exportPreservedContent,parsePreservedContent,mergePreservedContent,contentAttribution,exportContentChannel,type ContentDeskState} from '@/lib/private-showpiece/agency-content-state';
import {creativeReferenceIssue} from '@/lib/private-showpiece/creative-references';
import './agency-content.css';
function download(name:string,text:string,type:string){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
const labels={objective:'Campaign objective',audience:'Content audience',proposition:'Core proposition',tone:'Brand voice',cta:'Call to action'};
export default function AgencyContentDesk({hub,busy,workspaceKey,onDirtyChange,retainedState,onRetain}:{hub:Hub;workspaceKey:string;busy:boolean;onDirtyChange?:(dirty:boolean)=>void;retainedState?:ContentDeskState;onRetain?:(state:ContentDeskState)=>void}){
 const context=contentContext(hub),contextKey=JSON.stringify(context),referenceIssue=creativeReferenceIssue(hub);
 const [state,setState]=useState(()=>retainedState||initialContentState(contextKey,{objective:'',audience:hub.buyerRole||'',proposition:hub.engine?.brief.slice(0,1500)||'',tone:'Clear, considered and practical',cta:''},workspaceKey));
 const [channel,setChannel]=useState<Channel>('social'),[message,setMessage]=useState(''),[pendingImport,setPendingImport]=useState<ReturnType<typeof parsePreservedContent>>();
 const latest=useRef(state),currentContext=useRef(JSON.stringify([workspaceKey,contextKey])),mounted=useRef(true),loadEpoch=useRef(0);
 useLayoutEffect(()=>{latest.current=state;onRetain?.(state);},[state,onRetain]);
 if(state.activeContext!==contextKey||state.activeWorkspaceKey!==workspaceKey){setState(old=>syncContentContext(old,contextKey,workspaceKey));if(pendingImport)setPendingImport(undefined);}
 useLayoutEffect(()=>{currentContext.current=JSON.stringify([workspaceKey,contextKey]);loadEpoch.current++;},[contextKey,workspaceKey]);
 useLayoutEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 useLayoutEffect(()=>{onDirtyChange?.(state.dirty);},[state.dirty,onDirtyChange]);
 function change(fn:(old:ContentDeskState)=>ContentDeskState){const next=fn(latest.current);loadEpoch.current++;setPendingImport(undefined);latest.current=next;setState(next);}
 function exportWork(){try{download('assembl-preserved-content.json',exportPreservedContent(latest.current),'application/json');setMessage('Preserved work export requested. This tab still holds unsaved local work; no account save occurred.');}catch(error){setMessage((error as Error).message);}}
 const active=syncContentContext(state,contextKey,workspaceKey),{brief,draft}=active.work,stale=contentStale(active);
 return <section className="agency-desk" aria-label="Agency content desk">
  <header><PreviewImage className="agency-room" src="/do/world/atelier-glass-poster.webp" alt="Existing assembl glass identity in the daylight atelier; static artwork"/><div className="agency-hero-copy"><PreviewImage className="agency-do-mark" src="/brand/do-assembled-plum.webp" alt="DO locked glass identity"/><span className="cs-eyebrow">assembl / STUDIO → DO</span><h2>One brief.<br/>A voice across channels.</h2><p>Shape the campaign here. Then take the same proposition into the ideas canvas, working experience and pitch.</p><small>Local editable templates · no live generation · no remote save</small></div></header>
  <div className="agency-workbench"><aside><h3>Selected library</h3><b>{context.company}</b><p>{context.agency} → {context.audience}</p><p>{context.brand.client?'Client brand attached':'Client brand awaiting review'} · {context.brand.seller?'Agency brand attached':'Agency brand awaiting review'}</p><p>{context.sources.length} selected factual sources<br/>{context.creativeReferences.length} creative references, never cited evidence</p>{referenceIssue&&<p role="status">{referenceIssue}</p>}<details><summary>Review selected context receipt</summary><pre>{JSON.stringify(context,null,2)}</pre></details><p>Content work stays in this tab across Studio stages and context changes. Earlier drafts keep their original attribution. Export to retain work after leaving. Retained work is bound to the parent workspace key. Identical receipts in different Hubs require an explicit copy; these local keys are not owner proof. Restoring a file grants no account access.</p>{state.dirty&&<b>Content work is local and unsaved. Save concept does not save this desk.</b>}</aside>
  <fieldset disabled={busy}><h3>Content brief for {contentAttribution(active.work)}</h3><details><summary>Strategist prompt / version 1.0.0 / inactive</summary><pre>{specialistPrompt('strategist')}</pre></details>{(Object.keys(labels) as (keyof ContentBrief)[]).map(k=><label key={k}>{labels[k]}<textarea aria-label={labels[k]} rows={k==='proposition'?4:2} maxLength={k==='proposition'?1500:k==='objective'?500:300} value={brief[k]} onChange={e=>change(old=>editContentBrief(old,k,e.target.value))}/></label>)}<button className="cs-primary" onClick={()=>{try{const next=createContentDraft(hub,brief);change(old=>{const candidate={workspaceKey,brief:next.brief,context:next.context,draft:next};if(!old.work.draft&&!old.history.length&&old.work.context===contextKey)return {...old,work:candidate,dirty:true,epoch:old.epoch+1};return proposeContentReplacement(old,candidate);});setMessage('Templates are local drafts. Existing edited work is retained until you choose a replacement.');}catch(error){setMessage((error as Error).message);}}}>{draft?'Propose fresh channel templates':'Create local channel templates'}</button><button className="cs-secondary" onClick={exportWork}>Export preserved work</button>
   <label className="agency-import">Restore exported draft<input type="file" accept=".json,application/json" onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;const token=++loadEpoch.current,contextAtStart=currentContext.current;try{if(file.size>1000000)throw Error('File exceeds 1 MB.');const text=await file.text();if(!mounted.current||token!==loadEpoch.current||contextAtStart!==currentContext.current)return;const input=JSON.parse(text);if(input.format==='assembl-preserved-content-v2'||input.format==='assembl-preserved-content-v3'){const imported=parsePreservedContent(input);mergePreservedContent(latest.current,imported);setPendingImport(imported);}else{const next=importContentDraft(hub,input);setState(old=>proposeContentReplacement(old,{workspaceKey:'legacy:unbound',context:next.context,brief:next.brief,draft:next}));}setMessage('Restore proposal ready. Existing work is unchanged until you choose.');}catch(error){if(mounted.current&&token===loadEpoch.current)setMessage((error as Error).message);}}}/></label>
  </fieldset></div>
  {stale&&<div className="agency-stale" role="status"><b>Retained draft is stale.</b><p>Original content: {contentAttribution(active.work)}. Original workspace: {active.work.workspaceKey}. Selected workspace: {workspaceKey}. Current selected company: {context.company}. The brief, brand or sources changed. Edited channels are kept; review is invalidated. Export or keep editing the original, or explicitly propose fresh templates for the current selection.</p>{active.work.workspaceKey!==workspaceKey&&active.work.context===contextKey&&<button className="cs-secondary" onClick={()=>{try{change(proposeCrossWorkspaceCopy);}catch(error){setMessage((error as Error).message);}}}>Propose explicit copy into this workspace</button>}</div>}
  {(active.pending||pendingImport)&&<section className="agency-replacement" role="region" aria-label="Content replacement choice"><h3>Keep this work or use the proposal?</h3><p>Current work stays attributed to {contentAttribution(active.work)} ({active.work.workspaceKey}). Proposed work is attributed to {contentAttribution(pendingImport?.work||active.pending!)} ({(pendingImport?.work||active.pending!).workspaceKey}). Using the proposal retains the current version in this tab; it does not approve or save anything.</p><div className="cs-actions"><button className="cs-secondary" onClick={()=>{change(keepContentWork);setMessage('Proposal cancelled. Existing edited work kept.');}}>Keep current edited work</button><button className="cs-secondary" onClick={exportWork}>Export before choosing</button><button className="cs-primary" disabled={busy} onClick={()=>{try{if(pendingImport){const imported=pendingImport;change(old=>mergePreservedContent(old,imported));}else change(acceptContentReplacement);setMessage('Proposal selected. Previous work remains in earlier versions; all new review flags are clear.');}catch(error){setMessage((error as Error).message);}}}>Use proposal and retain previous version</button></div></section>}
  {draft&&<div className="agency-editor"><nav aria-label="Content channels">{channels.map(c=><button key={c} aria-pressed={channel===c} onClick={()=>setChannel(c)}>{({social:'Social posts',press:'Press release',podcast:'Podcast script'})[c]}<small>{stale?'Stale — retained':draft.reviewed[c]?'Locally reviewed':'Needs review'}</small></button>)}</nav><div><b>Draft attribution: {contentAttribution(active.work)}</b><label>Editable {channel} draft<textarea aria-label={`Editable ${channel} draft`} rows={22} maxLength={12000} value={draft.copy[channel]} onChange={e=>change(old=>editContentCopy(old,channel,e.target.value))}/></label><label className="cs-check"><input type="checkbox" disabled={stale||busy} checked={!stale&&draft.reviewed[channel]} onChange={e=>change(old=>reviewContent(old,channel,e.target.checked))}/>I reviewed facts, permissions and placeholders for this draft. External release still needs approval.</label><div className="cs-actions"><button className="cs-secondary" onClick={()=>{try{download(`assembl-${channel}-draft.txt`,exportContentChannel(active,channel,contentPlainText),'text/plain');}catch(error){setMessage((error as Error).message);}}}>Export {channel} draft</button><button className="cs-secondary" onClick={exportWork}>Export editable bundle</button></div><details><summary>Original draft context receipt</summary><pre>{draft.context}</pre></details><details><summary>Specialist prompt / version 1.0.0 / inactive</summary><pre>{specialistPrompt(channel)}</pre></details></div></div>}
  {!!active.history.length&&<details className="agency-history"><summary>Earlier versions retained · {active.history.length}</summary>{active.history.map((work,i)=><p key={i}>{i+1} · {contentAttribution(work)} · {work.brief.objective||'Unfinished brief'} <button className="cs-secondary" onClick={()=>change(old=>restoreContentVersion(old,i))}>Restore version {i+1} and keep current</button> <button className="cs-text" onClick={()=>{if(window.confirm('Discard this retained content version? Export preserved work first to keep a file copy.'))change(old=>({...old,history:old.history.filter((_,index)=>index!==i),dirty:true,epoch:old.epoch+1}));}}>Discard retained version {i+1}</button></p>)}</details>}
  {message&&<p role="status">{message}</p>}<p className="agency-boundary">Nothing is sent, published, voiced or saved to an account. Stage and context changes retain work in this tab. Leaving the page requires a keep/export/leave decision; export files for durable local copies.</p>
 </section>;
}
