'use client';
import RasterPreview from './RasterPreview';
import {useEffect,useLayoutEffect,useRef,useState} from 'react';
import type {Hub} from '@/components/client-hub-migration/original/lib/pursuit-hub';
import {readIntake} from '@/lib/private-showpiece/contract';
import {applyReviewedBrand,brandContextFingerprint,undoReviewedBrand,brandRasterSchema,brandReviewSchema,inspectBrandMarkup,type BrandReview as Review} from '@/lib/private-showpiece/brand-review';
import {selectedPublicUrl} from '@/lib/private-showpiece/public-url';
const hash=async(text:string)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text))),b=>b.toString(16).padStart(2,'0')).join('');
type Logo={data:string;sourceUrl:string;sha256:string};
export default function BrandReview({hub,onApply,busy=false,localPreview=false}:{hub:Hub;onApply:(hub:Hub)=>void;busy?:boolean;localPreview?:boolean}){
 const [url,setUrl]=useState(readIntake(hub)?.url||''),[paste,setPaste]=useState(''),[review,setReview]=useState<Review>(),[reviewContext,setReviewContext]=useState(''),[logoUrl,setLogoUrl]=useState(''),[logo,setLogo]=useState<Logo>(),[choices,setChoices]=useState<Record<string,string>>({}),[approved,setApproved]=useState(false),[message,setMessage]=useState(''),[loading,setLoading]=useState(false),[undo,setUndo]=useState<{before:Hub;applied:Hub}>();
 const epoch=useRef(0),controller=useRef<AbortController|null>(null),current=useRef(hub);useLayoutEffect(()=>{current.current=hub;},[hub]);
 useEffect(()=>()=>controller.current?.abort(),[]);
 const context=()=>brandContextFingerprint(current.current);
 const invalidate=()=>{epoch.current++;controller.current?.abort();setApproved(false);setReview(undefined);setLogo(undefined);setChoices({});};
 async function discover(cssUrl?:string){const token=epoch.current,base=context();setLoading(true);setApproved(false);setMessage('');const abort=new AbortController();controller.current=abort;try{
  const source=selectedPublicUrl(cssUrl||url);if(!cssUrl){setReview(undefined);setReviewContext('');setChoices({});setLogo(undefined);setLogoUrl('');}if(cssUrl&&review?.documents.some(d=>d.inputKind==='css'))throw Error('One selected stylesheet per review. Review the page again to choose another.');let result:Review;
  if(paste&&!cssUrl){result=inspectBrandMarkup(paste,source,'manual-paste',await hash(paste));}
  else {if(localPreview)throw Error('Local fixture preview: paste labelled test metadata; no public fetch occurs.');const response=await fetch('/api/private-showpiece/brand',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:source,kind:cssUrl?'css':'page',companyPage:cssUrl?url:undefined}),signal:abort.signal});const body=await response.json();if(!response.ok)throw Error(body.error);result=brandReviewSchema.parse(body.review);}
  if(abort.signal.aborted||epoch.current!==token||context()!==base)throw Error('Company, brand or selected source changed. Collect and review again.');
  setReviewContext(base);setReview(cssUrl&&review?{...result,candidates:[...review.candidates,...result.candidates].slice(0,32),documents:[...review.documents,...result.documents]}:result);setMessage('Observed declarations are ready for your review. They do not establish a complete corporate identity.');
 }catch(error){setMessage((error as Error).message);}finally{if(controller.current===abort){setLoading(false);controller.current=null;}}}
 async function importLogo(){const token=epoch.current,base=context();setLoading(true);setApproved(false);const abort=new AbortController();controller.current=abort;try{
  if(localPreview)throw Error('Logo fetching requires the verified owner workspace. Keep this fixture reference unimported.');const response=await fetch('/api/private-showpiece/brand',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:selectedPublicUrl(logoUrl),kind:'logo'}),signal:abort.signal});const body=await response.json();if(!response.ok)throw Error(body.error);
  if(abort.signal.aborted||epoch.current!==token||context()!==base)throw Error('Brand review changed; no logo imported.');setLogo(brandRasterSchema.parse({data:body.logo.data,sourceUrl:body.logo.sourceUrl,sha256:body.logo.sha256}));setMessage('Bounded raster ready. Review identity and reproduction rights before Apply.');
 }catch(error){setMessage((error as Error).message);}finally{if(controller.current===abort){setLoading(false);controller.current=null;}}}
 function cancel(){invalidate();setPaste('');setLogoUrl('');setMessage('Review cancelled. Original client branding is unchanged.');}
 return <section className="sp-brand cs-card" aria-label="Company brand review"><div className="sp-brand-heading"><span className="cs-eyebrow">REVIEW THE COMPANY IDENTITY</span><h2>Bring their visual world into the piece.</h2><p>Observe a selected page’s logo, colours and type references. Choose what belongs in this private proposal.</p></div><p className="cs-small">{hub.clientBrand?`Current identity: ${hub.clientBrand.name}. Kept until Apply; review it against the current company.`:'No client brand imported. Existing preview colours remain until Apply.'}</p><fieldset disabled={busy||loading}><label>Selected company page URL<input type="url" value={url} maxLength={1500} onChange={e=>{invalidate();setUrl(e.target.value);}}/></label><details><summary>Blocked page? Paste selected page or CSS metadata</summary><label>Inert metadata or labelled local fixture<textarea rows={4} value={paste} maxLength={24000} onChange={e=>{invalidate();setPaste(e.target.value);}}/></label><p className="cs-small">Pasted markup is parsed as text. It is never rendered or executed.</p></details><button className="cs-secondary" disabled={!url||localPreview&&!paste} onClick={()=>void discover()}>{loading?'Reading selected reference…':paste?'Review pasted metadata':'Discover from this selected page'}</button>{localPreview&&<p className="cs-small">Fictional local review: public collection and logo fetching are unavailable.</p>}
 {review&&<div className="sp-brand-observations"><h3>Observed references · not a verified brand guide</h3>{review.candidates.length===0&&<p>No usable declarations found. Add a manual reviewed reference in Sources.</p>}<ul>{review.candidates.map((c,i)=><li key={`${c.kind}-${i}`}><b>{c.status} · {c.kind}</b><span>{c.value}</span><small>{c.evidence} <a href={c.sourceUrl} target="_blank" rel="noopener noreferrer">Evidence page ↗</a></small>{c.kind==='stylesheet'&&<button className="cs-secondary" disabled={localPreview||review.documents.some(d=>d.inputKind==='css')} onClick={()=>void discover(c.value)}>Review this stylesheet</button>}{c.kind==='logo'&&<button className="cs-secondary" onClick={()=>{setLogoUrl(c.value);setLogo(undefined);setApproved(false);}}>Select logo reference</button>}</li>)}</ul><p className="cs-small">CSS selection reads one same-origin file. CDN CSS, blocked pages and unsupported logo formats need manual reviewed references. SVG logos and remote fonts remain references. No imports, scripts or fonts are loaded.</p>
 <div className="sp-pair">{['primary','accent','paper','ink'].map(key=><label key={key}>Manual {key} mapping<select value={choices[key]||''} onChange={e=>{setChoices(old=>({...old,[key]:e.target.value}));setApproved(false);}}><option value="">Keep current</option>{[...new Set(review.candidates.filter(c=>c.kind==='colour').map(c=>c.value))].map(hex=><option key={hex}>{hex}</option>)}</select></label>)}</div><p className="cs-small">Observed colours become manual role mappings only when you choose them. Suggested button text may adjust for contrast; incompatible body contrast rejects Apply.</p><div className="sp-brand-swatches">{review.candidates.filter(c=>c.kind==='colour').map((c,i)=><span key={i}><i style={{backgroundColor:c.value}}/>{c.value}</span>)}</div>
 <label>Manual logo reference URL<input value={logoUrl} maxLength={1500} onChange={e=>{setLogoUrl(e.target.value);setLogo(undefined);setApproved(false);}}/></label><button className="cs-secondary" disabled={!logoUrl||localPreview} onClick={()=>void importLogo()}>Prepare bounded raster logo</button>{logo&&<figure className="sp-brand-logo"><RasterPreview data={logo.data}/><figcaption>Prepared raster · original logo unchanged until Apply. Inspect this image and its rights.</figcaption></figure>}
 <p className="cs-small">Typography is evidence only. Observed font names stay in the saved review; the original experience uses seller typography. Applying a client typeface needs schema and renderer review. No remote font is loaded.</p><label className="cs-check"><input type="checkbox" checked={approved} onChange={e=>setApproved(e.target.checked)}/>I reviewed the evidence, manual mappings and any logo reproduction rights.</label><button className="cs-primary" disabled={!approved} onClick={()=>{try{if(context()!==reviewContext)throw Error('Company or current brand changed. Review the selected source again.');const before=current.current,applied=applyReviewedBrand(before,{reviewed:approved,review,...Object.fromEntries(Object.entries(choices).filter(([,v])=>v)),...(logoUrl?{manualLogoUrl:selectedPublicUrl(logoUrl)}:{}),...(logo?{logo}:{} )},reviewContext);setUndo({before,applied});onApply(applied);invalidate();setMessage('Reviewed choices applied. Save this private piece. Later edits and prepared run requests are checked independently against the byte limit.');}catch(error){setMessage((error as Error).message);}}}>Apply reviewed choices</button></div>}
 <button className="cs-text" onClick={cancel}>Cancel brand review</button></fieldset>{loading&&<button className="cs-secondary" onClick={()=>controller.current?.abort()}>Cancel collection</button>}{undo&&<button className="cs-secondary" disabled={busy||loading} onClick={()=>{try{onApply(undoReviewedBrand(current.current,undo.before,undo.applied));setUndo(undefined);setMessage('Import undone. Original branding restored; other draft edits preserved.');}catch(error){setMessage((error as Error).message);}}}>Undo last brand import</button>}{message&&<p role="status">{message}</p>}</section>;
}
