'use client';
import {useState} from 'react';
import type {Hub} from '@/components/client-hub-migration/original/lib/pursuit-hub';
import {applyIntake,intakeSchema,readIntake,type Intake} from '@/lib/private-showpiece/contract';
import './showpiece.css';
export default function ShowpieceIntake({hub,onApply,busy}:{hub:Hub;onApply:(h:Hub)=>void;busy:boolean}) {
 const [v,setV]=useState<Intake>(()=>readIntake(hub)||{company:'',url:'',kind:'job',brief:'',audience:'Hiring decision-maker',positioning:'Both',objective:'Make a proposed working experience they can try.'}),[error,setError]=useState('');
 const field=<K extends keyof Intake>(key:K,value:Intake[K])=>setV(old=>({...old,[key]:value}));
 return <section className="sp-intake" aria-label="Personal showpiece brief"><div className="sp-intake-title"><span className="cs-eyebrow">YOUR PRIVATE AGENCY STUDIO</span><h1>Make the brief<br/>worth experiencing.</h1><p>Brand, campaign and experience work from one selected brief. Shape the content and give the decision-maker something useful to try.</p></div><fieldset disabled={busy}><div className="sp-pair"><label>Target company<input value={v.company} maxLength={120} onChange={e=>field('company',e.target.value)}/></label><label>Company website<input type="url" placeholder="https://" value={v.url} maxLength={1500} onChange={e=>field('url',e.target.value)}/></label></div><div className="sp-starters" aria-label="Optional company name starters"><span>Optional name starters</span>{['Deloitte','PwC'].map(name=><button type="button" className="cs-secondary" key={name} onClick={()=>field('company',name)}>{name}</button>)}<small>Names only. No client facts, affiliation or brand is assumed.</small></div><div className="sp-pair"><label>Starting point<select value={v.kind} onChange={e=>field('kind',e.target.value as Intake['kind'])}><option value="job">Job advertisement</option><option value="prospect">Prospect brief</option></select></label><label>Audience<select value={v.audience} onChange={e=>field('audience',e.target.value as Intake['audience'])}>{['Hiring decision-maker','CFO','CTO','GM'].map(x=><option key={x}>{x}</option>)}</select></label></div><label>Job advertisement or prospect brief<textarea rows={5} value={v.brief} maxLength={4200} onChange={e=>field('brief',e.target.value)} placeholder="Paste the brief and the need you want to demonstrate."/></label><div className="sp-pair"><label>Position this piece for<select value={v.positioning} onChange={e=>field('positioning',e.target.value as Intake['positioning'])}><option>Kate</option><option>assembl</option><option>Both</option></select></label><label>What should this piece achieve?<input value={v.objective} maxLength={300} onChange={e=>field('objective',e.target.value)}/></label></div><button className="cs-primary" onClick={()=>{const parsed=intakeSchema.safeParse(v);if(!parsed.success){setError(parsed.error.issues[0].message);return;}onApply(applyIntake(hub,parsed.data));setError('');}}>Use this brief</button><p className="cs-small">Changing the target clears previous concepts and selected sources. Existing client branding is kept for review. Save the current piece first.</p>{error&&<p role="alert">{error}</p>}</fieldset></section>;
}
