'use client';
import {useCallback,useLayoutEffect,useRef,useState} from 'react';
import type {Hub} from '@/components/client-hub-migration/original/lib/pursuit-hub';
import type {SectionPatchScope} from '@/lib/private-showpiece/section-patch';
import {admitReviewedExport,previewReviewedExport,reviewedExportMaxBytes,type ExportAudience,type ReviewedExportFormat,type ReviewedExportPreview} from '@/lib/private-showpiece/reviewed-export';
export default function ReviewedExport({hub,scope,busy}:{hub:Hub;scope:SectionPatchScope;busy:boolean}){
 const [audience,setAudience]=useState<ExportAudience>({role:'CFO',description:''}),[format,setFormat]=useState<ReviewedExportFormat>('text'),[preview,setPreview]=useState<{key:string;version:number;value:ReviewedExportPreview}>(),[reviewed,setReviewed]=useState<{key:string;version:number;fingerprint:string}>(),[job,setJob]=useState<{key:string;version:number;busy:boolean}>(),[notice,setNotice]=useState<{key:string;version:number;text:string}>();
 const generation=useRef(0),currentKey=useRef(''),key=JSON.stringify({hub,scope,audience,format});
 const [context,setContext]=useState({key,version:0});
 if(context.key!==key)setContext({key,version:context.version+1});
 const version=context.version;
 const invalidate=useCallback(()=>{generation.current++;},[]);
 useLayoutEffect(()=>{invalidate();currentKey.current=key;return invalidate;},[key,invalidate]);
 const visible=preview?.key===key&&preview.version===version?preview.value:undefined,working=job?.key===key&&job.version===version&&job.busy,checked=!!visible&&reviewed?.key===key&&reviewed.version===version&&reviewed.fingerprint===visible.bytesFingerprint;
 function reset(){invalidate();setPreview(undefined);setReviewed(undefined);setJob(undefined);setNotice(undefined);}
 async function prepare(){const token=++generation.current;setJob({key,version,busy:true});setNotice(undefined);setReviewed(undefined);try{const value=await previewReviewedExport(hub,scope,audience,format);if(token!==generation.current||currentKey.current!==key)return;setPreview({key,version,value});setNotice({key,version,text:'Exact draft bytes prepared. Review them for this audience before downloading.'});}catch(e){if(token===generation.current&&currentKey.current===key)setNotice({key,version,text:(e as Error).message});}finally{if(token===generation.current&&currentKey.current===key)setJob({key,version,busy:false});}}
 async function download(){if(!visible||!checked)return;const token=++generation.current;setJob({key,version,busy:true});setNotice(undefined);try{const value=await admitReviewedExport(hub,scope,audience,format,visible);if(token!==generation.current||currentKey.current!==key)return;const url=URL.createObjectURL(new Blob([new TextEncoder().encode(value.content)],{type:value.mimeType}));const anchor=document.createElement('a');anchor.href=url;anchor.download=value.filename;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1500);setNotice({key,version,text:'Local draft download requested. Nothing was sent, published or saved to an account.'});}catch(e){if(token===generation.current&&currentKey.current===key)setNotice({key,version,text:(e as Error).message});}finally{if(token===generation.current&&currentKey.current===key)setJob({key,version,busy:false});}}
 return <section className="section-export" aria-label="Reviewed draft export"><h3>Review a presentation export</h3><p>Export only the six story sections, company/presenter labels, your described audience and selected public references. Private notes, research histories and internal receipts stay outside the file. Local review does not approve sending or publication.</p>
 <label>Intended audience role<select aria-label="Intended audience role" disabled={busy} value={audience.role} onChange={e=>{reset();setAudience({...audience,role:e.target.value as ExportAudience['role']});}}>{['CFO','CTO','GM','Hiring manager','Other'].map(role=><option key={role}>{role}</option>)}</select></label>
 <label>Intended audience description<textarea aria-label="Intended audience description" disabled={busy} rows={3} value={audience.description} onChange={e=>{reset();setAudience({...audience,description:e.target.value});}}/></label>
 <label>Draft file format<select aria-label="Draft file format" disabled={busy} value={format} onChange={e=>{reset();setFormat(e.target.value as ReviewedExportFormat);}}><option value="text">Plain text</option><option value="json">JSON</option></select></label>
 <p>Maximum {reviewedExportMaxBytes.toLocaleString()} UTF-8 bytes. Artwork and static HTML are unavailable in this slice.</p><button className="cs-secondary" disabled={busy||working} onClick={prepare}>Preview exact draft bytes</button>
 {(visible||working)&&<button className="cs-secondary" disabled={busy} onClick={reset}>Cancel export review</button>}
 {visible&&<div role="region" aria-label="Exact export preview"><p>{visible.bytes} UTF-8 bytes · SHA-256 <code>{visible.bytesFingerprint}</code> · {visible.filename}</p><pre aria-label="Exact draft bytes">{visible.content}</pre><label className="cs-check"><input type="checkbox" aria-label="I reviewed these exact bytes for this audience" disabled={busy||working} checked={checked} onChange={e=>setReviewed(e.target.checked?{key,version,fingerprint:visible.bytesFingerprint}:undefined)}/>I reviewed these exact bytes for the described audience. Sending and publication still need approval.</label><button className="cs-primary" disabled={busy||working||!checked} onClick={download}>Download reviewed draft</button></div>}
 {notice?.key===key&&notice.version===version&&<p role="status">{notice.text}</p>}
 </section>;
}
