'use client';
import {useState} from 'react';
import type {Hub} from '@/components/client-hub-migration/original/lib/pursuit-hub';

export default function SourceReview({hub,onApply,localPreview=false,busy=false}:{hub:Hub;onApply:(hub:Hub)=>void;localPreview?:boolean;busy?:boolean}){
 const [url,setUrl]=useState(''),[title,setTitle]=useState(''),[kind,setKind]=useState<'company'|'job'|'brand'>('company'),[text,setText]=useState(''),[reviewed,setReviewed]=useState(false),[collecting,setCollecting]=useState(false),[message,setMessage]=useState('');
 async function collect(){setCollecting(true);setReviewed(false);setMessage('');try{
  const response=await fetch('/api/private-showpiece/source',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:crypto.randomUUID(),url,kind})});
  const body=await response.json();if(!response.ok)throw Error(body.error||'Paste selected public text.');
  setUrl(body.source.url);setText(body.source.text.slice(0,900));setMessage('Page text returned for review. Only your reviewed extract will be retained; its fetch receipt will not be saved. No facts or brand permissions have been verified.');
 }catch(error){setMessage((error as Error).message);}finally{setCollecting(false);}}
 function add(){try{
  const target=new URL(url);if(target.protocol!=='https:'||target.username||target.password||!title.trim()||!text.trim()||!reviewed)throw Error('Use a public HTTPS reference, title and reviewed extract.');
  if(hub.sources.length>=40)throw Error('Source register is full. Review existing sources first.');
  onApply({...hub,sources:[...hub.sources,{id:crypto.randomUUID(),title:`${kind}: Owner-reviewed extract · ${title.trim()}`.slice(0,180),url:target.href,claim:text.trim().slice(0,900),status:'source',checked:new Date().toISOString().slice(0,10),include:true}]});
  setText('');setReviewed(false);setMessage('Reviewed extract added to this draft. Save the piece to retain it.');
 }catch(error){setMessage((error as Error).message);}}
 return <section className="cs-card" aria-label="Selected company, job and brand sources"><h3>Choose the evidence for this piece</h3><p>Use selected public company pages, job advertisements and brand references. Review what each source supports before adding it to the canvas.</p><fieldset disabled={busy||collecting}><label>Source purpose<select value={kind} onChange={e=>setKind(e.target.value as typeof kind)}><option value="company">Company context</option><option value="job">Job advertisement</option><option value="brand">Brand reference</option></select></label><label>Public page URL<input value={url} maxLength={1500} type="url" onChange={e=>{setUrl(e.target.value);setReviewed(false);}}/></label><button className="cs-secondary" disabled={localPreview||!url} onClick={collect}>{collecting?'Collecting selected page…':'Collect this public page'}</button>{localPreview&&<p className="cs-small">Local fixture review: public collection requires the authenticated owner workspace. Paste a labelled test extract below.</p>}<label>Reference title<input value={title} maxLength={170} onChange={e=>setTitle(e.target.value)}/></label><label>Relevant public extract<textarea rows={5} value={text} maxLength={900} onChange={e=>{setText(e.target.value);setReviewed(false);}} placeholder="Paste the relevant text if the page blocks collection. Keep claims within what this reference supports."/></label><label className="cs-check"><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>I reviewed this public reference and the extract’s provenance.</label><button className="cs-primary" disabled={!reviewed} onClick={add}>Add reviewed source</button></fieldset>{message&&<p role="status">{message}</p>}<p className="cs-small">No private notes or seller files are retrieved. A brand reference does not grant permission to reproduce its assets.</p></section>;
}
