export type ScoreCategory = 'A' | 'B' | 'C' | 'D' | 'E';

export type ScorecardQuestion = {
  id: number;
  category: ScoreCategory;
  prompt: string;
  options: Array<{ label: string; points: 1 | 2 | 3 | 4 }>;
};

export const categoryLabels: Record<ScoreCategory, string> = {
  A: 'Service Lane Conversion',
  B: 'Workshop Capacity',
  C: 'Customer Retention',
  D: 'Lead Response',
  E: 'F&I + Compliance',
};

const optionSet = [
  { label: 'No clear process', points: 1 },
  { label: 'Ad hoc process', points: 2 },
  { label: 'Tracked but not automated', points: 3 },
  { label: 'Visible, owned, and reviewed weekly', points: 4 },
] as const;

export const scorecardQuestions: ScorecardQuestion[] = [
  ['A', 'When a customer is in for service, can your sales floor see they are here?'],
  ['A', 'Do you have a process for identifying customers in the 3-5 year trade-up window?'],
  ['A', 'How often does a service customer leave with a quote for their next car?'],
  ['A', 'Do you track service-to-sales conversion as a metric?'],
  ['B', 'What share of workshop time goes to declined work follow-up?'],
  ['B', 'Do you have visibility into loan car fleet utilisation across rooftops?'],
  ['B', 'When a job is declined, what happens to it?'],
  ['B', 'How do you allocate workshop bays across appointment and walk-in demand?'],
  ['C', 'What share of your new-car customers return for first service?'],
  ['C', 'How do you track customers who have not had a service in 18+ months?'],
  ['C', 'Do you have a structured re-engagement process for lapsed customers?'],
  ['C', 'When a finance term matures, who reaches out to the customer?'],
  ['D', 'What is your typical response time to a new sales enquiry?'],
  ['D', 'After-hours enquiries: what happens to them?'],
  ['D', 'Do you have visibility into lead source performance?'],
  ['D', 'When a lead does not convert, what is the follow-up cadence?'],
  ['E', 'Are your CCCFA disclosures generated by a system or written by hand?'],
  ['E', 'How do you track finance maturity dates across your customer base?'],
  ['E', 'When a vehicle is listed for sale, who checks Fair Trading Act compliance?'],
  ['E', 'What share of your F&I product attach rate are you tracking?'],
].map(([category, prompt], index) => ({
  id: index + 1,
  category: category as ScoreCategory,
  prompt,
  options: optionSet.map((option) => ({ ...option })),
}));

export function parseScores(encoded?: string): Record<ScoreCategory, number> {
  const defaults: Record<ScoreCategory, number> = { A: 0, B: 0, C: 0, D: 0, E: 0 };
  if (!encoded) return defaults;
  for (const part of encoded.split(',')) {
    const [key, raw] = part.split(':');
    if (key && key in defaults) defaults[key as ScoreCategory] = Math.max(0, Math.min(16, Number(raw) || 0));
  }
  return defaults;
}

export function encodeScores(scores: Record<ScoreCategory, number>) {
  return (Object.keys(categoryLabels) as ScoreCategory[])
    .map((key) => `${key}:${scores[key]}`)
    .join(',');
}

export function categoryBand(score: number) {
  if (score >= 16) return 'Strong';
  if (score >= 12) return 'Healthy with opportunity';
  if (score >= 8) return 'Significant gap';
  return 'Leaking heavily';
}

export function categoryRecommendations(category: ScoreCategory, score: number) {
  const map: Record<ScoreCategory, string[]> = {
    A: ['Service-to-Sales Matcher', 'Service Lane Trade-In calculator', 'Book a Pilot Sprint'],
    B: ['Loan Car Warden', 'Declined-Work Recovery workflow', 'Fleet Uptime calculator'],
    C: ['First-Service Handoff', 'First-Service Retention calculator', 'F&I Maturity Watcher'],
    D: ['After-Hours Lead Agent', 'Lead Response Leakage calculator', 'Missed-Call Rescue'],
    E: ['Listing Compliance Agent', 'NZ Listing Compliance Checker', 'FORGE review'],
  };
  if (score >= 16) return ['Keep the rhythm visible in Pulse'];
  if (score >= 12) return map[category].slice(0, 1);
  if (score >= 8) return map[category].slice(0, 2);
  return map[category];
}

export function topRecommendations(scores: Record<ScoreCategory, number>) {
  return (Object.keys(categoryLabels) as ScoreCategory[])
    .sort((a, b) => scores[a] - scores[b])
    .flatMap((category) => categoryRecommendations(category, scores[category]).map((text) => ({ category, text })))
    .slice(0, 3);
}
