import Link from 'next/link';
import {ArrowRight,ArrowUpRight} from 'lucide-react';
import {GlowDoWidget} from './GlowDoWidget';
import {PRODUCT_DESTINATIONS} from '@/lib/product-destinations';
import './assembl-the-work.css';
import './product-landing.css';
const content={
 pursuit:{name:'Pursuit',line:'find it.',eyebrow:'RESEARCH. REASON. POSSIBILITY.',heading:<>Find the opening.<br/>Build the possibility.</>,body:'Bring client context, sources and a useful idea into one pursuit. Prepare work worth taking to the next conversation.',action:'Open your Pursuit hub',photo:'/cinematic-nature/ocean-assembly.webp',steps:[['Find a reason to act.','Research relevant public signals and the context you supply. Keep the original sources, dates and questions to validate.'],['Shape a credible idea.','Bring the customer moment, evidence and a proposed task onto the board. Develop the idea with the agent, then review the result.'],['Make the next conversation useful.','Keep the brief, opportunity, demonstrator and review notes in the private client workspace. Share only the experience you approve.']],offer:'A Pursuit sprint',deliverable:'A focused opportunity brief, a developed concept and a plan for the next conversation.',boundary:'Your hub holds client work behind sign-in. New workspaces and business connections are set up as part of an agreed engagement.'},
 studio:{name:'Studio',line:'show it.',eyebrow:'DIRECTION. CRAFT. SOMETHING REAL.',heading:<>Give the idea<br/>a world of its own.</>,body:'Turn a brief into a creative direction, a campaign, a film or an experience people can step inside.',action:'Open your Creative Studio',photo:'/cinematic-nature/ocean-assembly.webp',steps:[['Start with the brand.','Use the approved brief, brand context and the assets you choose. Make the intended audience and outcome clear.'],['Bring the work together.','Develop campaign direction, copy and storyboards with the specialist workflow. Keep completed stages when a task needs another attempt.'],['Review, then take it out.','Keep creative, files and review notes together. Edit and export the work you approve. Production tools are connected for the agreed scope.']],offer:'A Studio engagement',deliverable:'A clear creative direction and an agreed set of campaign, film, pitch or interactive assets.',boundary:'Your creative workspace requires sign-in. Media generation and publication use the providers and permissions agreed for your project.'}
} as const;
export function ProductLanding({product}:{product:'pursuit'|'studio'}){const c=content[product],destination=PRODUCT_DESTINATIONS[product];return <div className="atw product-page"><section className="product-hero" style={{backgroundImage:`linear-gradient(90deg,#170a1bdd,#240b2140),url(${c.photo})`}}><header className="atw-nav"><Link className="atw-wordmark" href="/">assembl</Link><nav aria-label="Primary"><Link href="/pursuit" aria-current={product==='pursuit'?'page':undefined}>Pursuit</Link><Link href="/do">DO</Link><Link href="/creative-studio" aria-current={product==='studio'?'page':undefined}>Studio</Link></nav><GlowDoWidget/></header><div className="product-hero-copy"><p className="atw-kicker">{c.name.toUpperCase()} / {c.eyebrow}</p><h1>{c.heading}</h1><p>{c.body}</p><div><a className="atw-pill" href={destination.workspace}>{c.action}<ArrowUpRight size={18}/></a><Link className="atw-text-link" href={`/contact?product=${product}`}>Discuss a project<ArrowRight size={18}/></Link></div></div></section><section className="product-work atw-section"><div><p className="atw-kicker">{c.name.toUpperCase()} — {c.line.toUpperCase()}</p><h2>From a brief<br/>to a better<br/><em>next step.</em></h2></div><ol>{c.steps.map(([title,body],i)=><li key={title}><span>0{i+1}</span><div><h3>{title}</h3><p>{body}</p></div></li>)}</ol></section><section className="product-offer atw-section"><p className="atw-kicker">AVAILABLE ON ITS OWN. CONNECTED WHEN YOU NEED IT.</p><h2>{c.offer}.</h2><p>{c.deliverable}</p><div><Link className="atw-pill atw-pill-dark" href={`/contact?product=${product}`}>Scope the work<ArrowUpRight size={18}/></Link><Link className="atw-text-link" href="/contact?product=system">Bring Pursuit, DO and Studio together<ArrowRight size={18}/></Link></div><small>{c.boundary}</small></section><footer className="atw-footer"><Link className="atw-wordmark" href="/">assembl</Link><p>Mahi that earns its proof.<br/>Aotearoa New Zealand.</p><nav aria-label="Product footer"><Link href="/">Home</Link><a href={destination.workspace}>Your workspace</a><Link href="/contact">Contact</Link><Link href="/legal/privacy">Privacy</Link></nav><span>Client work stays in its private workspace.</span></footer></div>;}
