import {
  Activity,
  Anchor,
  BadgeCheck,
  Building2,
  Calculator,
  ChefHat,
  ClipboardCheck,
  ClipboardList,
  ClipboardPlus,
  Compass,
  Container,
  Feather,
  FileSearch,
  FileText,
  Gavel,
  GraduationCap,
  HardHat,
  Headset,
  HeartHandshake,
  HeartPulse,
  Image as ImageIcon,
  Languages,
  LayoutTemplate,
  Megaphone,
  MessageSquare,
  Mic,
  Palette,
  PiggyBank,
  Plane,
  Refrigerator,
  Sailboat,
  ScanEye,
  School,
  ScrollText,
  Shield,
  ShieldCheck,
  Sparkles,
  Sprout,
  Stethoscope,
  Sunrise,
  Thermometer,
  TrendingUp,
  Type,
  Users,
  Vault,
  Wallet,
  Zap,
  type LucideIcon,
} from 'lucide-react';

/** Placeholder avatar icons for marketplace agents. */
const ICONS: Record<string, LucideIcon> = {
  Activity,
  Anchor,
  BadgeCheck,
  Building2,
  Calculator,
  ChefHat,
  ClipboardCheck,
  ClipboardList,
  ClipboardPlus,
  Compass,
  Container,
  Feather,
  FileSearch,
  FileText,
  Gavel,
  GraduationCap,
  HardHat,
  Headset,
  HeartHandshake,
  HeartPulse,
  Image: ImageIcon,
  Languages,
  LayoutTemplate,
  Megaphone,
  MessageSquare,
  Mic,
  Palette,
  PiggyBank,
  Plane,
  Refrigerator,
  Sailboat,
  ScanEye,
  School,
  ScrollText,
  Shield,
  ShieldCheck,
  Sparkles,
  Sprout,
  Stethoscope,
  Sunrise,
  Thermometer,
  TrendingUp,
  Type,
  Users,
  Vault,
  Wallet,
  Zap,
};

export function AgentIcon({
  name,
  className,
  strokeWidth = 1.75,
}: {
  name: string;
  className?: string;
  strokeWidth?: number;
}) {
  const Icon = ICONS[name] ?? Sparkles;
  return <Icon className={className} strokeWidth={strokeWidth} aria-hidden />;
}
