import { useState } from "react";
import { Copy, Download, AlertTriangle, Check, FileDown, ShieldAlert } from "lucide-react";
import { NeonBox } from "@/components/NeonIcons";
import jsPDF from "jspdf";

interface EntryLine {
  line: number;
  description: string;
  hsCode: string;
  origin: string;
  fta?: string;
  qty?: string;
  valueNZD: string;
  duty: string;
  gst: string;
  flagged?: boolean;
  flagReason?: string;
}

interface EntryData {
  supplier?: string;
  consignee?: string;
  invoice?: string;
  transport?: string;
  lines: EntryLine[];
  totalValue?: string;
  totalDuty?: string;
  totalGST?: string;
  totalPayable?: string;
  flaggedItems?: string[];
}

interface Props {
  data: EntryData;
  color?: string;
}

const NexusEntryCard = ({ data, color = "#5B8CFF" }: Props) => {
  const [copied, setCopied] = useState(false);

  const toCSV = () => {
    const header = "Line,Description,HS Code,Origin,FTA,Qty,CIF NZD,Duty,GST,Flagged\n";
    const rows = data.lines
      .map(
        (l) =>
          `${l.line},"${l.description}",${l.hsCode},${l.origin},${l.fta || "N/A"},${l.qty || ""},${l.valueNZD},${l.duty},${l.gst},${l.flagged ? "⚠️ " + (l.flagReason || "Review") : ""}`
      )
      .join("\n");
    const totals = `\nTOTALS,,,,,,,${data.totalDuty || ""},${data.totalGST || ""},\nTOTAL PAYABLE:,,,,,,,${data.totalPayable || ""},,`;
    return header + rows + totals;
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(toCSV());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadCSV = () => {
    const blob = new Blob([toCSV()], { type: "text/csv" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `import-entry-${data.invoice || "data"}.csv`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleDownloadPDF = () => {
    const doc = new jsPDF({ unit: "mm", format: "a4" });
    const pw = doc.internal.pageSize.getWidth();
    const m = 15;
    const mw = pw - m * 2;
    let y = 15;

    // Header
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text("ASSEMBL — IMPORT ENTRY SUMMARY", m, y);
    y += 5;
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(120);
    doc.text(`Generated by NEXUS (ASM-009) — ${new Date().toLocaleDateString("en-NZ")}`, m, y);
    y += 3;
    doc.setDrawColor(200);
    doc.line(m, y, pw - m, y);
    y += 6;

    // Meta
    doc.setTextColor(0);
    doc.setFontSize(9);
    if (data.supplier) { doc.text(`Supplier: ${data.supplier}`, m, y); y += 4; }
    if (data.consignee) { doc.text(`Consignee: ${data.consignee}`, m, y); y += 4; }
    if (data.invoice) { doc.text(`Invoice: ${data.invoice}`, m, y); y += 4; }
    if (data.transport) { doc.text(`Transport: ${data.transport}`, m, y); y += 4; }
    y += 3;

    // Table header
    const cols = [m, m+8, m+60, m+85, m+100, m+115, m+128, m+145, m+162];
    doc.setFontSize(7);
    doc.setFont("helvetica", "bold");
    ["#", "Description", "HS Code", "Origin", "FTA", "Qty", "CIF NZD", "Duty", "GST"].forEach((h, i) => {
      doc.text(h, cols[i], y);
    });
    y += 1;
    doc.line(m, y, pw - m, y);
    y += 3;

    // Rows
    doc.setFont("helvetica", "normal");
    data.lines.forEach((l) => {
      if (y > 265) { doc.addPage(); y = 15; }
      const desc = l.description.length > 30 ? l.description.slice(0, 28) + "…" : l.description;
      doc.text(String(l.line), cols[0], y);
      doc.text(desc, cols[1], y);
      doc.text(l.hsCode, cols[2], y);
      doc.text(l.origin, cols[3], y);
      doc.text(l.fta || "N/A", cols[4], y);
      doc.text(l.qty || "", cols[5], y);
      doc.text(l.valueNZD, cols[6], y);
      doc.text(l.duty, cols[7], y);
      doc.text(l.gst, cols[8], y);
      y += 4;
    });

    y += 3;
    doc.line(m, y, pw - m, y);
    y += 5;
    doc.setFont("helvetica", "bold");
    if (data.totalValue) { doc.text(`Total Customs Value: ${data.totalValue}`, m, y); y += 4; }
    if (data.totalDuty) { doc.text(`Total Duty: ${data.totalDuty}`, m, y); y += 4; }
    if (data.totalGST) { doc.text(`Total GST: ${data.totalGST}`, m, y); y += 4; }
    if (data.totalPayable) { doc.text(`TOTAL PAYABLE: ${data.totalPayable}`, m, y); y += 6; }

    // Broker sign-off
    doc.setFontSize(9);
    doc.setTextColor(180, 0, 0);
    doc.text("⚠ BROKER SIGN-OFF REQUIRED — This entry must be reviewed by a Licensed Customs Broker before lodgement.", m, y, { maxWidth: mw });
    y += 8;

    // Footer
    doc.setFontSize(7);
    doc.setTextColor(140);
    const fy = Math.min(y + 10, 280);
    doc.text(`Generated by NEXUS (ASM-009) — assembl.co.nz — AI-generated content, must be reviewed before use.`, m, fy, { maxWidth: mw });
    doc.text(`© 2026 Assembl. All rights reserved. Agent designs, system prompts, and automation workflows are proprietary trade secrets of Assembl.`, m, fy + 4, { maxWidth: mw });

    doc.save(`import-entry-${data.invoice || "data"}.pdf`);
  };

  return (
    <div className="space-y-0">
      {/* Broker sign-off banner */}
      <div
        className="rounded-t-xl px-4 py-2.5 flex items-center gap-2"
        style={{ background: "#3D0000", border: "1px solid #FF4D4D30", borderBottom: "none" }}
      >
        <ShieldAlert size={14} className="text-red-400 shrink-0" />
        <p className="text-[11px] text-red-300 font-semibold">
          Broker sign-off required — This entry must be reviewed by a Licensed Customs Broker before lodgement to TSW.
        </p>
      </div>

      <div
        className="rounded-b-xl overflow-hidden"
        style={{ background: "#0F0F1C", border: `1px solid ${color}15`, borderTop: "none" }}
      >
        {/* Header */}
        <div className="px-4 py-3 flex items-center justify-between" style={{ borderBottom: `1px solid ${color}15` }}>
          <h4 className="text-sm font-bold" style={{ color }}>
            📦 Import Entry Summary
          </h4>
          <div className="flex gap-1.5">
            <button
              onClick={handleCopy}
              className="flex items-center gap-1 px-2 py-1 rounded text-[10px] font-medium transition-colors"
              style={{ background: color + "15", color, border: `1px solid ${color}25` }}
            >
              {copied ? <Check size={10} /> : <Copy size={10} />}
              {copied ? "Copied" : "Copy"}
            </button>
            <button
              onClick={handleDownloadCSV}
              className="flex items-center gap-1 px-2 py-1 rounded text-[10px] font-medium transition-colors"
              style={{ background: color + "15", color, border: `1px solid ${color}25` }}
            >
              <Download size={10} />
              CSV
            </button>
            <button
              onClick={handleDownloadPDF}
              className="flex items-center gap-1 px-2 py-1 rounded text-[10px] font-medium transition-colors"
              style={{ background: color + "15", color, border: `1px solid ${color}25` }}
            >
              <FileDown size={10} />
              PDF
            </button>
          </div>
        </div>

        {/* Meta */}
        {(data.supplier || data.invoice || data.transport) && (
          <div className="px-4 py-2 grid grid-cols-2 gap-x-4 gap-y-1 text-[11px]" style={{ borderBottom: `1px solid ${color}08` }}>
            {data.supplier && (
              <>
                <span className="text-foreground/40">Supplier</span>
                <span className="text-foreground/70">{data.supplier}</span>
              </>
            )}
            {data.consignee && (
              <>
                <span className="text-foreground/40">Consignee</span>
                <span className="text-foreground/70">{data.consignee}</span>
              </>
            )}
            {data.invoice && (
              <>
                <span className="text-foreground/40">Invoice</span>
                <span className="text-foreground/70">{data.invoice}</span>
              </>
            )}
            {data.transport && (
              <>
                <span className="text-foreground/40">Transport</span>
                <span className="text-foreground/70">{data.transport}</span>
              </>
            )}
          </div>
        )}

        {/* Table */}
        <div className="overflow-x-auto">
          <table className="w-full text-[11px]">
            <thead>
              <tr style={{ borderBottom: `1px solid ${color}15` }}>
                {["#", "Description", "HS Code", "Origin", "FTA", "Qty", "CIF NZD", "Duty", "GST"].map((h) => (
                  <th key={h} className="px-3 py-2 text-left font-semibold" style={{ color: color + "90" }}>
                    {h}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {data.lines.map((l) => (
                <tr key={l.line} style={{ borderBottom: `1px solid ${color}08` }}>
                  <td className="px-3 py-1.5 text-foreground/50">{l.line}</td>
                  <td className="px-3 py-1.5 text-foreground/80 max-w-[180px]">
                    <div className="flex items-start gap-1">
                      {l.flagged && <AlertTriangle size={12} className="text-yellow-400 shrink-0 mt-0.5" />}
                      <span>{l.description}</span>
                    </div>
                  </td>
                  <td className="px-3 py-1.5 font-mono text-foreground/70">
                    {l.hsCode}
                    {l.flagged && <span className="text-yellow-400 ml-1">⚠️</span>}
                  </td>
                  <td className="px-3 py-1.5 text-foreground/60">{l.origin}</td>
                  <td className="px-3 py-1.5 text-foreground/60">{l.fta || "—"}</td>
                  <td className="px-3 py-1.5 text-foreground/60">{l.qty || "—"}</td>
                  <td className="px-3 py-1.5 font-mono text-foreground/80">{l.valueNZD}</td>
                  <td className="px-3 py-1.5 font-mono text-foreground/70">{l.duty}</td>
                  <td className="px-3 py-1.5 font-mono text-foreground/70">{l.gst}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {/* Totals */}
        <div className="px-4 py-3 space-y-1" style={{ borderTop: `1px solid ${color}15` }}>
          {data.totalValue && (
            <div className="flex justify-between text-xs">
              <span className="text-foreground/50">Customs Value</span>
              <span className="font-mono text-foreground/80">{data.totalValue}</span>
            </div>
          )}
          {data.totalDuty && (
            <div className="flex justify-between text-xs">
              <span className="text-foreground/50">Total Duty</span>
              <span className="font-mono text-foreground/80">{data.totalDuty}</span>
            </div>
          )}
          {data.totalGST && (
            <div className="flex justify-between text-xs">
              <span className="text-foreground/50">Total GST</span>
              <span className="font-mono text-foreground/80">{data.totalGST}</span>
            </div>
          )}
          {data.totalPayable && (
            <div className="flex justify-between text-xs font-semibold pt-1" style={{ borderTop: `1px solid ${color}15` }}>
              <span style={{ color }}>TOTAL PAYABLE</span>
              <span style={{ color }}>{data.totalPayable}</span>
            </div>
          )}
        </div>

        {/* Flagged items */}
        {data.flaggedItems && data.flaggedItems.length > 0 && (
          <div className="px-4 py-3" style={{ borderTop: `1px solid ${color}15`, background: "#FFB80008" }}>
            <p className="text-[11px] font-semibold text-yellow-400 mb-1.5 flex items-center gap-1">
              <AlertTriangle size={12} /> Items Flagged for Broker Review
            </p>
            {data.flaggedItems.map((item, i) => (
              <p key={i} className="text-[11px] text-foreground/60 pl-4">• {item}</p>
            ))}
          </div>
        )}
      </div>
    </div>
  );
};

export default NexusEntryCard;
