/**
 * Evidence-pack rendering + storage.
 *
 * `renderEvidencePackHtml` builds an auditor-ready, print-optimised HTML
 * document from the receipt payload. The assembl PDF pipeline converts this
 * HTML to a PDF at deploy/runtime (same skill the rest of the app uses); for
 * phase 1 the HTML is the canonical artifact and `pdf_uri` points at the stored
 * file. `storeReceiptArtifact` uploads it to Supabase Storage.
 *
 * Customer-facing language: this is the "evidence pack — a downloadable bundle
 * of what happened on the call". The hash chain is the depth detail.
 */
import type { VoiceManaReceipt } from '@/lib/voice/types';
import { voiceDb } from '@/lib/voice/clients/supabase';

const BUCKET = 'mana-receipts';

function esc(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

export function renderEvidencePackHtml(receipt: VoiceManaReceipt): string {
  const p = receipt.payload;
  const num = receipt.call_sid;
  const row = (k: string, v: string) =>
    `<tr><th>${esc(k)}</th><td>${esc(v)}</td></tr>`;

  const consentRows = p.consent
    ? row('Consent', p.consent.granted ? 'Granted' : 'Declined') +
      row('Consent prompt', p.consent.prompt_text) +
      row('Caller said', p.consent.response_text) +
      row('Captured', `${p.consent.captured_method} @ ${p.consent.ts}`)
    : row('Consent', 'Not captured');

  const bookingRows = p.booking
    ? row('Booking', `${p.booking.party_size} guests — ${p.booking.date} ${p.booking.time}`) +
      row('Booking id', p.booking.booking_id)
    : row('Booking', 'None');

  const toolRows = p.tool_calls
    .map(
      (t) =>
        `<li><strong>${esc(t.tool)}</strong> — ${t.ok ? 'ok' : 'failed'} — ${esc(
          t.result_summary,
        )} <span class="ts">${esc(t.ts)}</span></li>`,
    )
    .join('');

  return `<!doctype html>
<html lang="en-NZ"><head><meta charset="utf-8" />
<title>Evidence pack — call ${esc(num)}</title>
<style>
  body { font: 14px/1.5 -apple-system, Segoe UI, Roboto, sans-serif; color: #1a1a1a; margin: 40px; }
  h1 { font-size: 20px; margin-bottom: 2px; }
  .sub { color: #555; margin-top: 0; }
  table { border-collapse: collapse; width: 100%; margin: 16px 0; }
  th, td { text-align: left; padding: 6px 10px; border-bottom: 1px solid #eee; vertical-align: top; }
  th { width: 180px; color: #444; font-weight: 600; }
  .chain { font-family: ui-monospace, Menlo, monospace; font-size: 11px; word-break: break-all; background:#f7f7f8; padding:10px; border-radius:6px; }
  .ts { color:#888; font-size:11px; }
  footer { margin-top: 24px; color:#777; font-size:12px; }
</style></head>
<body>
  <h1>Evidence pack</h1>
  <p class="sub">A downloadable record of what happened on this call — consent, booking, messages — with timestamps. (Cryptographically tamper-evident: this is a Mana Receipt.)</p>
  <table>
    ${row('Agent', `${p.agent} (${p.agent_version})`)}
    ${row('Customer', p.customer_id)}
    ${row('Call', p.call_sid)}
    ${row('Caller', p.caller_number_masked)}
    ${row('Started', p.started_at)}
    ${row('Ended', p.ended_at)}
    ${row('Status', p.status)}
    ${consentRows}
    ${bookingRows}
    ${row('Confirmation SMS', p.sms_sent ? 'Sent' : 'Not sent')}
    ${row('Transferred to human', p.transferred ? 'Yes' : 'No')}
    ${row('Retention class', p.privacy.retention_class)}
    ${row('Privacy Act IPPs', p.privacy.ipps_satisfied.join(', '))}
  </table>
  <h3>What the agent did</h3>
  <ul>${toolRows || '<li>No tool calls recorded.</li>'}</ul>
  <h3>Chain integrity</h3>
  <div class="chain">
    sha256 &nbsp; ${esc(receipt.sha256)}<br/>
    prev_hash ${esc(receipt.prev_hash)}<br/>
    chain_hash ${esc(receipt.chain_hash)}
  </div>
  <footer>Generated by assembl. Built and signed off by Kate Hudson, Aotearoa.
  Built with tikanga values in the prompt design.</footer>
</body></html>`;
}

/** Store the rendered artifact in Supabase Storage; returns its path. */
export async function storeReceiptArtifact(
  receipt: VoiceManaReceipt,
  html: string = renderEvidencePackHtml(receipt),
): Promise<string> {
  const db = voiceDb();
  const path = `${receipt.payload.customer_id}/${receipt.call_sid}.html`;
  const { error } = await db.storage
    .from(BUCKET)
    .upload(path, new Blob([html], { type: 'text/html' }), { upsert: true });
  if (error) throw new Error(`storeReceiptArtifact: ${error.message}`);
  return `${BUCKET}/${path}`;
}
