import type { MetadataRoute } from 'next';

/**
 * robots.txt — generated by Next.js. Deliberately WELCOMES the answer-engine
 * crawlers.
 *
 * The market is moving from Google-search to AI-search (ChatGPT Search,
 * Perplexity, Claude, Bing Copilot, Google AI Overviews). Most NZ sites block
 * these bots by accident. assembl does the opposite: every known answer-engine
 * crawler is named and explicitly allowed, so our content is eligible to be
 * read and cited. Only the app/admin/auth surfaces are kept out.
 * Host is the canonical www origin (production 301s apex → www).
 */
const BASE = 'https://www.assembl.co.nz';

const DISALLOW = ['/api/', '/app/', '/admin/', '/auth/', '/login', '/internal/', '/dev/', '/preview/'];

// Answer-engine + model crawlers we explicitly allow (do NOT block these).
const AI_CRAWLERS = [
  'GPTBot', // OpenAI — training + browsing
  'OAI-SearchBot', // OpenAI — ChatGPT Search index
  'ChatGPT-User', // OpenAI — live user-triggered fetch
  'ClaudeBot', // Anthropic — Claude index
  'Claude-Web', // Anthropic — live browsing
  'anthropic-ai', // Anthropic — legacy token
  'PerplexityBot', // Perplexity — index
  'Perplexity-User', // Perplexity — live user-triggered fetch
  'Google-Extended', // Google — Gemini / AI Overviews opt-in
  'Applebot-Extended', // Apple Intelligence opt-in
  'Bytespider', // ByteDance / Doubao
  'Amazonbot', // Amazon
  'CCBot', // Common Crawl
  'cohere-ai', // Cohere
  'Meta-ExternalAgent', // Meta AI
  'DuckAssistBot', // DuckDuckGo AI
];

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      { userAgent: '*', allow: '/', disallow: DISALLOW },
      // Name each answer-engine crawler explicitly so intent is unambiguous.
      ...AI_CRAWLERS.map((ua) => ({ userAgent: ua, allow: '/', disallow: DISALLOW })),
    ],
    sitemap: `${BASE}/sitemap.xml`,
    host: BASE,
  };
}
