import type { MetadataRoute } from 'next';
import { headers } from 'next/headers';

/**
 * robots.txt — generated by Next.js. Deliberately WELCOMES the answer-engine
 * crawlers on the marketing site, and hard-blocks everything on the demo
 * subdomain.
 *
 * Two very different policies from the same App Router tree, keyed off the
 * incoming Host header (Next serves the same routes on every attached
 * domain):
 *
 *   - assembl.co.nz / www.assembl.co.nz → normal marketing crawl policy.
 *     Every known answer-engine crawler is named and explicitly allowed so
 *     our content is eligible to be read and cited. App/admin/auth surfaces
 *     are kept out, and the /customers/* pilot workspaces are disallowed
 *     (they carry robots:noindex meta too — hard Disallow is belt-and-braces).
 *
 *   - demo.assembl.co.nz → block ALL crawling. This subdomain hosts
 *     unfinished pre-partnership pitch surfaces that must never appear in
 *     search results.
 *
 * Host is the canonical www origin (production 301s apex → www).
 */
const BASE = 'https://www.assembl.co.nz';

const DEMO_HOSTS = new Set(['demo.assembl.co.nz']);

const DISALLOW = [
  '/api/',
  '/app/',
  '/admin/',
  '/auth/',
  '/login',
  '/internal/',
  '/dev/',
  '/preview/',
  '/customers/',
];

// Answer-engine + model crawlers we explicitly allow (do NOT block these).
const AI_CRAWLERS = [
  'GPTBot', // OpenAI — training + browsing
  'OAI-SearchBot', // OpenAI — ChatGPT Search index
  'ChatGPT-User', // OpenAI — live user-triggered fetch
  'ClaudeBot', // Anthropic — Claude index
  'Claude-Web', // Anthropic — live browsing
  'anthropic-ai', // Anthropic — legacy token
  'PerplexityBot', // Perplexity — index
  'Perplexity-User', // Perplexity — live user-triggered fetch
  'Google-Extended', // Google — Gemini / AI Overviews opt-in
  'Applebot-Extended', // Apple Intelligence opt-in
  'Bytespider', // ByteDance / Doubao
  'Amazonbot', // Amazon
  'CCBot', // Common Crawl
  'cohere-ai', // Cohere
  'Meta-ExternalAgent', // Meta AI
  'DuckAssistBot', // DuckDuckGo AI
];

export default async function robots(): Promise<MetadataRoute.Robots> {
  const h = await headers();
  const host = (h.get('host') ?? '').toLowerCase();

  // Demo subdomain: block everything.
  if (DEMO_HOSTS.has(host)) {
    return {
      rules: [{ userAgent: '*', disallow: '/' }],
    };
  }

  return {
    rules: [
      { userAgent: '*', allow: '/', disallow: DISALLOW },
      // Name each answer-engine crawler explicitly so intent is unambiguous.
      ...AI_CRAWLERS.map((ua) => ({ userAgent: ua, allow: '/', disallow: DISALLOW })),
    ],
    sitemap: `${BASE}/sitemap.xml`,
    host: BASE,
  };
}
