import type { MetadataRoute } from 'next';

/**
 * robots.txt — generated by Next.js. Allow crawling of the public marketing
 * site, keep crawlers out of app/admin/auth surfaces, and point at the sitemap.
 * Host is the canonical www origin (production 301s apex → www).
 */
const BASE = 'https://www.assembl.co.nz';

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: '*',
        allow: '/',
        disallow: ['/api/', '/app/', '/admin/', '/auth/', '/login', '/internal/', '/dev/', '/preview/'],
      },
    ],
    sitemap: `${BASE}/sitemap.xml`,
    host: BASE,
  };
}
