import type { MetadataRoute } from 'next';
/**
 * sitemap.xml — generated by Next.js. A curated list of public, indexable
 * routes (no admin/auth/api) telling the Living Business OS story. The old
 * marketplace surfaces are gone from here (and 308 to /living-site).
 * Host is the canonical www origin.
 */
const BASE = 'https://www.assembl.co.nz';

const CORE_PATHS = [
  '',
  // The Living Site funnel — the primary story; keep these prominent.
  '/living-site',
  '/install',
  '/about',
  '/os',
  '/pricing',
  '/ai-use',
  '/contact',
  '/data',
  '/faq',
  '/how-it-works',
  '/hui',
  '/industry-pack',
  '/insurance',
  '/mana-receipts',
  '/mana-receipts/sample',
  '/platform',
  '/press',
  '/public-assembly',
  '/start',
  '/te-tiriti',
  '/toro',
  '/trust',
  '/trust/soc2',
  // Assembling sub-brand
  '/assembling',
  '/assembling/for-ai-builders',
  '/assembling/sdk',
  '/assembling/rewards',
  '/assembling/interactive',
  '/assembling/privacy',
  '/assembling/terms',
  '/assembling/copyright',
];

export default function sitemap(): MetadataRoute.Sitemap {
  const lastModified = new Date();

  const core: MetadataRoute.Sitemap = CORE_PATHS.map((path) => ({
    url: `${BASE}${path}`,
    lastModified,
    changeFrequency: 'weekly',
    priority:
      path === ''
        ? 1
        : path === '/living-site' || path === '/install' || path === '/os'
          ? 0.9
          : path.startsWith('/assembling')
            ? 0.7
            : 0.6,
  }));

  return core;
}
