import type { MetadataRoute } from 'next';

/**
 * sitemap.xml — generated by Next.js. A curated list of public, indexable
 * routes (no admin/auth/api), so search engines pick up the marketing site and
 * the newer /dash sub-brand pages. Host is the canonical www origin.
 */
const BASE = 'https://www.assembl.co.nz';

const PATHS = [
  '',
  '/about',
  '/agents',
  '/ai-use',
  '/contact',
  '/data',
  '/how-it-works',
  '/hui',
  '/industry-pack',
  '/insurance',
  '/kete',
  '/mana-receipts',
  '/mana-receipts/sample',
  '/platform',
  '/press',
  '/pricing',
  '/public-assembly',
  '/start',
  '/te-tiriti',
  '/toro',
  '/trust',
  '/trust/soc2',
  // Dash sub-brand
  '/dash',
  '/dash/for-ai-builders',
  '/dash/sdk',
  '/dash/rewards',
  '/dash/interactive',
  '/dash/privacy',
  '/dash/terms',
  '/dash/copyright',
];

export default function sitemap(): MetadataRoute.Sitemap {
  const lastModified = new Date();
  return PATHS.map((path) => ({
    url: `${BASE}${path}`,
    lastModified,
    changeFrequency: 'weekly',
    priority: path === '' ? 1 : path.startsWith('/dash') ? 0.7 : 0.6,
  }));
}
