import type { MetadataRoute } from 'next';
import { PUBLIC_MARKETPLACE_AGENTS } from '@/lib/marketplace/agents';

/**
 * sitemap.xml — generated by Next.js. A curated list of public, indexable
 * routes (no admin/auth/api), plus every LIVE agent detail page, so search
 * engines AND answer engines pick up the full marketplace. Host is the
 * canonical www origin.
 */
const BASE = 'https://www.assembl.co.nz';

const CORE_PATHS = [
  '',
  '/about',
  '/agents',
  '/agents/pricing',
  '/ai-use',
  '/contact',
  '/data',
  '/faq',
  '/how-it-works',
  '/hui',
  '/industry-pack',
  '/insurance',
  '/kete',
  '/mana-receipts',
  '/mana-receipts/sample',
  '/platform',
  '/press',
  '/pricing',
  '/public-assembly',
  '/start',
  '/te-tiriti',
  '/toro',
  '/trust',
  '/trust/soc2',
  // Dash sub-brand
  '/dash',
  '/dash/for-ai-builders',
  '/dash/sdk',
  '/dash/rewards',
  '/dash/interactive',
  '/dash/privacy',
  '/dash/terms',
  '/dash/copyright',
];

export default function sitemap(): MetadataRoute.Sitemap {
  const lastModified = new Date();

  const core: MetadataRoute.Sitemap = CORE_PATHS.map((path) => ({
    url: `${BASE}${path}`,
    lastModified,
    changeFrequency: 'weekly',
    priority: path === '' ? 1 : path.startsWith('/dash') ? 0.7 : 0.6,
  }));

  // Every live agent gets its own entry — these are the high-intent,
  // citation-worthy "what does {agent} do" pages.
  const agents: MetadataRoute.Sitemap = PUBLIC_MARKETPLACE_AGENTS.filter(
    (a) => a.status === 'live',
  ).map((a) => ({
    url: `${BASE}/agents/${a.slug}`,
    lastModified,
    changeFrequency: 'weekly',
    priority: 0.7,
  }));

  return [...core, ...agents];
}
