import {Draft,safeSourceUrl,type PublicResearchResult} from './public-contract';
export function escapeHtml(value:string){return value.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));}
/** Self-contained, editable HTML slide deck. No scripts, remote fonts or tracking. */
export function makePitchDeck(result:PublicResearchResult):string{
 const d=Draft.parse(result.draft);const e=escapeHtml;const list=(items:readonly string[])=>`<ul>${items.map(x=>`<li>${e(x)}</li>`).join('')}</ul>`;
 const slide=(label:string,title:string,body:string,index:number)=>`<section class="slide"><header><b>assembl</b><span>${e(d.company)} / independent proposal</span></header><main><small>${e(label)}</small><h1 contenteditable="true">${e(title)}</h1>${body}</main><footer><span>DRAFT · ${e(result.trace.at.slice(0,10))} · Review before sharing</span><span>${String(index).padStart(2,'0')} / 06</span></footer></section>`;
 const sources=d.evidence.map((s,i)=>{const url=safeSourceUrl(s.url);if(!url)throw new Error('unsafe_source');return `<li><strong>${i+1}. ${e(s.claim)}</strong><a href="${e(url)}" rel="noopener noreferrer">${e(url)}</a></li>`;}).join('');
 return `<!doctype html><html lang="en-NZ"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(d.company)} · assembl pursuit</title><style>@page{size:landscape;margin:0}*{box-sizing:border-box}body{margin:0;background:#F5F1F2;color:#240B21;font-family:Arial,sans-serif}.slide{position:relative;min-height:56.25vw;aspect-ratio:16/9;background:#FFFDFB;border-bottom:12px solid #916A70;padding:4.2vw 5.5vw;break-after:page;display:flex;flex-direction:column;overflow-wrap:anywhere}.slide:nth-child(3n+1){background:#240B21;color:#FFFDFB}header,footer{display:flex;justify-content:space-between;gap:24px;font-size:1vw;line-height:1.5}header b{font-size:2.4vw;letter-spacing:-.05em}header span{max-width:50%;text-align:right}main{flex:1;padding:3vw 0}small{text-transform:uppercase;letter-spacing:.15em;font-size:.95vw;color:#916A70}h1{font-size:4.7vw;line-height:1.03;letter-spacing:-.055em;font-weight:500;max-width:17ch;margin:1.5vw 0 2vw}p,li{font-size:1.45vw;line-height:1.6;max-width:64ch}p{margin:1vw 0}ul{padding-left:1.6vw}li{padding:0 0 .7vw .4vw}.sources li{font-size:1.1vw;max-width:none}.sources a{display:block;font-size:.9vw;color:inherit;margin:.5vw 0;max-width:100%;word-break:break-all}.note{font-size:1vw;opacity:.8}footer{padding-top:1.2vw;border-top:1px solid #916A704D}@media print{body{background:white}.slide{height:100vh;min-height:0;aspect-ratio:auto;border-bottom:5px solid #916A70;print-color-adjust:exact;-webkit-print-color-adjust:exact}h1{font-size:44pt}p,li{font-size:14pt}small,header,footer,.note{font-size:9pt}.sources li{font-size:11pt}.sources a{font-size:9pt}header b{font-size:24pt}}</style></head><body>${slide('The opportunity',d.title,`<p contenteditable="true">${e(d.summary)}</p><p class="note">Prepared for discussion. No endorsement, budget or buying intent is implied.</p>`,1)}${slide('What the sources show','Start with the evidence.',`<ul class="sources">${sources}</ul><p class="note">Public sources retrieved ${e(result.trace.at.slice(0,10))}. Check the originals before relying on them.</p>`,2)}${slide('Proposed direction','One opening to explore.',`<p contenteditable="true">${e(d.opportunity)}</p><p class="note">This commercial interpretation is a hypothesis, not an established customer need.</p>`,3)}${slide('The demonstrator','Make the next step concrete.',`<p contenteditable="true">${e(d.proposedWork)}</p>${list(d.deliverables)}`,4)}${slide('Before committing','Questions to resolve.',list(d.unknowns),5)}${slide('Next move','A useful first conversation.',`${list(d.nextSteps)}<p class="note">Produced from a public-source research run and published Assembl product knowledge. Nothing has been sent or published.</p>`,6)}</body></html>`;
}
