import {afterEach,describe,expect,it,vi} from 'vitest';
import {runPublicResearch} from './public-research';
import {makePitchDeck} from './pitch-export';
const draft={company:'Test organisation',title:'A sourced test opportunity',summary:'A test proposal based on a public service description.',evidence:[{claim:'The test source describes a public service.',url:'https://example.com/'}],opportunity:'Propose an explanation of the next customer step.',proposedWork:'Prepare a small demonstrator for a person to review.',deliverables:['A public-source brief','A draft demonstrator'],nextSteps:['Read the original source','Validate the proposed need'],unknowns:['Demand and budget are not known.']};
const input={requestId:'72b1797b-420a-4c56-a6bf-cf74832c948e',company:'Test organisation',goal:'Research an example customer journey',consent:true as const,useTypeSafe:false};
afterEach(()=>vi.unstubAllEnvs());
describe('real-search and export boundary',()=>{
 it('requires a real provider configuration',async()=>{vi.stubEnv('ANTHROPIC_API_KEY','');await expect(runPublicResearch(input,false)).rejects.toThrow('research_provider_unavailable');});
 it('rejects a model answer without an actual web search',async()=>{vi.stubEnv('ANTHROPIC_API_KEY','test-only');const fake=vi.fn(async()=>Response.json({content:[{type:'text',text:JSON.stringify(draft)}],stop_reason:'end_turn'}));await expect(runPublicResearch(input,false,fake as typeof fetch)).rejects.toThrow('no_verified_search_result');});
 it('returns only traced evidence and escapes the exported deck',async()=>{vi.stubEnv('ANTHROPIC_API_KEY','test-only');const fake=vi.fn(async()=>Response.json({content:[{type:'server_tool_use',name:'web_search'},{type:'web_search_tool_result',content:[{type:'web_search_result',url:'https://example.com/',title:'Test source'}]},{type:'text',text:JSON.stringify({...draft,title:'<script>alert(1)</script>'})}],usage:{input_tokens:40,output_tokens:80},stop_reason:'end_turn'}));const result=await runPublicResearch(input,false,fake as typeof fetch);expect(result.trace.webSearches).toBe(1);expect(result.trace.knowledgeIds.length).toBeGreaterThan(0);expect(result.trace.typesafe.status).toBe('not_requested');const deck=makePitchDeck(result);expect(deck.match(/class="slide"/g)?.length).toBe(6);expect(deck).not.toContain('<script>');expect(deck).toContain('&lt;script&gt;');expect(deck).toContain('https://example.com/');expect(deck).toContain('#240B21');});
});
