import BrandNav from "@/components/BrandNav";
import BrandFooter from "@/components/BrandFooter";
import ParticleField from "@/components/ParticleField";

const Disclaimer = () => (
  <div className="min-h-screen star-field flex flex-col relative">
    <ParticleField />
    <BrandNav />
    <main className="flex-1 max-w-3xl mx-auto px-4 sm:px-6 py-16 sm:py-24">
      <h1 className="text-2xl sm:text-4xl font-extrabold text-foreground mb-8">Disclaimer</h1>
      <p className="text-xs text-muted-foreground mb-6">Last updated: 19 March 2026</p>

      <div className="prose-sm space-y-6 text-sm text-foreground/80 leading-relaxed">
        <section>
          <h2 className="text-lg font-bold text-foreground mb-2">1. AI-generated content</h2>
          <p>All content generated by Assembl agents is produced by artificial intelligence. While our agents are trained on New Zealand legislation, regulations, and best practices, AI-generated content may contain errors, omissions, or outdated information.</p>
          <p><strong>You must not rely on agent outputs as a substitute for professional advice.</strong></p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-foreground mb-2">2. No professional advice</h2>
          <p>Assembl agents provide <strong>general information only</strong>. They do not provide:</p>
          <ul className="list-disc pl-5 space-y-1">
            <li>Legal advice (consult a lawyer or <a href="https://communitylaw.org.nz" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">Community Law</a>)</li>
            <li>Financial or tax advice (consult a chartered accountant or <a href="https://www.ird.govt.nz" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">IRD</a>)</li>
            <li>Medical or health advice (consult a healthcare professional or call <a href="tel:0800611116" className="text-primary hover:underline">Healthline 0800 611 116</a>)</li>
            <li>Immigration advice (consult a licensed immigration adviser or <a href="https://www.immigration.govt.nz" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">Immigration NZ</a>)</li>
            <li>Building or construction advice (consult a licensed building practitioner)</li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-bold text-foreground mb-2">3. Accuracy and currency</h2>
          <p>While we make reasonable efforts to keep agent knowledge current and accurate:</p>
          <ul className="list-disc pl-5 space-y-1">
            <li>NZ legislation and regulations change frequently — always verify with official sources</li>
            <li>AI may "hallucinate" or generate plausible-sounding but incorrect information</li>
            <li>Tax rates, thresholds, and regulatory requirements should be confirmed with the relevant NZ authority</li>
            <li>We do not guarantee the accuracy, completeness, or timeliness of any content</li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-bold text-foreground mb-2">4. Use at your own risk</h2>
          <p>You use Assembl and its agent outputs entirely at your own risk. We are not responsible for any loss, damage, or liability arising from your use of or reliance on AI-generated content, including but not limited to:</p>
          <ul className="list-disc pl-5 space-y-1">
            <li>Financial losses from incorrect tax or accounting guidance</li>
            <li>Legal consequences from following AI-generated legal information</li>
            <li>Health outcomes from following AI-generated health information</li>
            <li>Regulatory penalties from relying on AI compliance guidance</li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-bold text-foreground mb-2">5. Templates and documents</h2>
          <p>Templates, documents, and structured outputs generated by our agents are starting points only. They must be reviewed by a qualified professional before use. The disclaimer on each generated document states:</p>
          <div className="p-3 rounded-lg border border-border bg-card text-xs italic">
            "Generated by [Agent Name] via Assembl. This is AI-generated content — review by a qualified professional is recommended before use."
          </div>
        </section>

        <section>
          <h2 className="text-lg font-bold text-foreground mb-2">6. Third-party links</h2>
          <p>Our agents may reference or link to third-party websites and NZ government resources. We are not responsible for the content, accuracy, or availability of external sites.</p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-foreground mb-2">7. NZ emergency and support services</h2>
          <p>If you need urgent help:</p>
          <ul className="list-disc pl-5 space-y-1">
            <li><strong>Emergency:</strong> Call 111</li>
            <li><strong>Mental health:</strong> Call or text 1737</li>
            <li><strong>Family violence:</strong> Women's Refuge 0800 733 843</li>
            <li><strong>Citizens Advice:</strong> 0800 367 222</li>
            <li><strong>Community Law:</strong> <a href="https://communitylaw.org.nz" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">communitylaw.org.nz</a></li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-bold text-foreground mb-2">8. Consumer Guarantees Act</h2>
          <p>Nothing in this disclaimer limits your rights under the Consumer Guarantees Act 1993 or the Fair Trading Act 1986 where they apply.</p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-foreground mb-2">9. Contact</h2>
          <p>Questions or concerns? Email <a href="mailto:assembl@assembl.co.nz" className="text-primary hover:underline">assembl@assembl.co.nz</a>.</p>
        </section>
      </div>
    </main>
    <BrandFooter />
  </div>
);

export default Disclaimer;
