import { useParams, Link } from "react-router-dom";
import { motion } from "framer-motion";
import {
  ArrowRight, Check, FileText, Download, Share2, Bookmark,
  Clock, Shield, User, ChevronRight, Printer
} from "lucide-react";
import jsPDF from "jspdf";
import { drawAssemblPDFHeader, drawAssemblPDFFooter, renderCrossAgentSection, drawSignOffBlock } from "@/lib/pdfBranding";
import BrandNav from "@/components/BrandNav";
import BrandFooter from "@/components/BrandFooter";
import SEO from "@/components/SEO";

/* ─── Brand tokens ─── */
const BG = "#0A1628";
const TEAL = "#3A7D6E";
const GOLD = "#D4A853";
const WHITE = "#FFFFFF";
const SURFACE = "rgba(255,255,255,0.04)";
const BORDER = "rgba(255,255,255,0.08)";

const FONT_HEAD = "'Lato', sans-serif";
const FONT_BODY = "'Plus Jakarta Sans', sans-serif";
const FONT_MONO = "'JetBrains Mono', monospace";

const ease = [0.16, 1, 0.3, 1] as const;
const fade = (i = 0) => ({
  initial: { opacity: 0, y: 20 },
  animate: { opacity: 1, y: 0 },
  transition: { delay: i * 0.1, duration: 0.6, ease },
});

/* ─── Pack definitions ─── */
type Section = {
  agent: string;
  title: string;
  body: string;
  items: { label: string; value: string; status: "ok" | "warn" | "info" }[];
};

type PackData = {
  slug: string;
  kete: string;
  subtitle: string;
  accent: string;
  accentLight: string;
  scenario: string;
  client: string;
  date: string;
  packId: string;
  summary: string;
  sections: Section[];
  signOff: string;
  seoTitle: string;
  seoDesc: string;
};

const PACKS: Record<string, PackData> = {
  manaaki: {
    slug: "manaaki",
    kete: "MANAAKI",
    subtitle: "Hospitality Intelligence",
    accent: TEAL,
    accentLight: "#5AADA0",
    scenario: "Food Safety & Liquor Compliance Review",
    client: "Coastal Brew Café, Auckland Central",
    date: "11 April 2026",
    packId: "MNK-2026-0411-001",
    summary:
      "All Food Act 2014 obligations reviewed. Liquor licence conditions checked against current practice. Staff allergen training verified. Pack ready to file with Auckland Council.",
    sections: [
      {
        agent: "HAVEN",
        title: "Food Act 2014 — Food Control Plan",
        body: "Current Food Control Plan reviewed against Ministry for Primary Industries template (June 2024 revision). All critical control points documented.",
        items: [
          { label: "FCP registration current", value: "Expires 30 Jun 2027", status: "ok" },
          { label: "Last verification visit", value: "14 Feb 2026 — Grade A", status: "ok" },
          { label: "Temperature logs (30-day)", value: "Complete — no breaches", status: "ok" },
          { label: "Corrective action register", value: "0 outstanding items", status: "ok" },
        ],
      },
      {
        agent: "BEACON",
        title: "Sale and Supply of Alcohol Act 2012 — Licence Review",
        body: "On-licence conditions (DLC-2022-0087) reviewed. Host responsibility policy, signage, and staff training assessed against current obligations.",
        items: [
          { label: "Licence class", value: "On-licence — General", status: "ok" },
          { label: "Host responsibility display", value: "Current — displayed at entry", status: "ok" },
          { label: "Manager certificate (Sarah Tane)", value: "Valid to 18 Nov 2027", status: "ok" },
          { label: "Duty manager log — last 30 days", value: "Complete", status: "ok" },
        ],
      },
      {
        agent: "HAVEN",
        title: "Allergen & Dietary Information",
        body: "Menu allergen declarations checked against the Food Information Regulations 2022. All 14 major allergens scoped.",
        items: [
          { label: "Menu allergen matrix on file", value: "Yes — updated 1 Apr 2026", status: "ok" },
          { label: "Gluten-free claim verified", value: "Kitchen separation protocol documented", status: "ok" },
          { label: "Staff allergen briefing (last session)", value: "7 Mar 2026 — 12 staff signed", status: "ok" },
          { label: "Online menu sync", value: "Website not yet updated", status: "warn" },
        ],
      },
    ],
    signOff:
      "Pack generated by MANAAKI kete. All outputs are advisory — confirm with your food safety verifier and licensing authority before relying on this pack for regulatory purposes.",
    seoTitle: "Sample Evidence Pack — Manaaki Hospitality | assembl",
    seoDesc:
      "See a sample assembl evidence pack for hospitality operators. Food safety, liquor licensing, and allergen compliance — filed, forwarded, or footnoted.",
  },

  waihanga: {
    slug: "waihanga",
    kete: "WAIHANGA",
    subtitle: "Construction Intelligence",
    accent: "#2A5A8C",
    accentLight: "#4A8ABF",
    scenario: "Site Compliance & Practical Completion Sign-Off",
    client: "47 Marine Parade, Napier — Residential Renovation",
    date: "11 April 2026",
    packId: "WHG-2026-0411-004",
    summary:
      "All three hold points cleared. Building consent conditions satisfied. H&S handover documentation complete. Pack ready for Code Compliance Certificate application.",
    sections: [
      {
        agent: "ĀRAI",
        title: "Health & Safety — Site Handover",
        body: "HealthSafe NZ Construction sector guidelines applied. Hazard register reviewed at practical completion. All notifiable work tracked and filed.",
        items: [
          { label: "Notifiable work notification (WorkSafe)", value: "Filed — WS-2025-NPR-2281", status: "ok" },
          { label: "Site Safety Plan (last revision)", value: "Rev 4 — 2 Apr 2026", status: "ok" },
          { label: "Incident register (build period)", value: "2 near-misses — both closed", status: "ok" },
          { label: "Asbestos clearance certificate", value: "Issued 15 Nov 2025", status: "ok" },
        ],
      },
      {
        agent: "WHAKAAĒ",
        title: "Building Consent Compliance — BCA Check",
        body: "Hawke's Bay Regional Council consent (BC-2025-01447) conditions mapped against work completed. Three hold points required inspector sign-off.",
        items: [
          { label: "Hold Point 1 — Foundations", value: "Cleared 3 Dec 2025 — Inspector J. Waru", status: "ok" },
          { label: "Hold Point 2 — Framing", value: "Cleared 15 Jan 2026 — Inspector J. Waru", status: "ok" },
          { label: "Hold Point 3 — Insulation & Wrap", value: "Cleared 29 Mar 2026 — Inspector J. Waru", status: "ok" },
          { label: "CCC application lodged", value: "Pending — ready to file", status: "info" },
        ],
      },
      {
        agent: "PAI",
        title: "Quality Assurance — Defect Register",
        body: "Contractor defect inspection completed 8 April 2026. Owner walkthrough conducted 10 April 2026.",
        items: [
          { label: "Defects raised at inspection", value: "7 items", status: "info" },
          { label: "Defects closed before handover", value: "7 of 7 — all cleared", status: "ok" },
          { label: "Maintenance manual provided", value: "Yes — Appendix C", status: "ok" },
          { label: "Weathertightness warranty", value: "15-year — Appendix D", status: "ok" },
        ],
      },
    ],
    signOff:
      "Pack generated by WAIHANGA kete. Confirm all items with your Licensed Building Practitioner and consenting authority before lodging CCC application.",
    seoTitle: "Sample Evidence Pack — Waihanga Construction | assembl",
    seoDesc:
      "See a sample assembl evidence pack for construction projects. H&S sign-off, consent compliance, and quality records — ready to file with your BCA.",
  },

  auaha: {
    slug: "auaha",
    kete: "AUAHA",
    subtitle: "Creative & Media Intelligence",
    accent: "#C4943A",
    accentLight: "#E8C76A",
    scenario: "Winter Campaign — Brief to Publish",
    client: "Mānuka Collective, Wellington",
    date: "11 April 2026",
    packId: "AUH-2026-0411-012",
    summary:
      "Campaign brief locked. Copy approved for three channels. Image assets spec'd and reviewed. Publication schedule confirmed. Campaign ready to go live 14 April 2026.",
    sections: [
      {
        agent: "PRISM",
        title: "Creative Brief — Approved",
        body: "Brand voice guidelines applied. Target audience (NZ women 30–55, natural wellness). Campaign theme: 'Winter warmth, from the inside.'",
        items: [
          { label: "Brand voice check", value: "Passed — warm, grounded, honest", status: "ok" },
          { label: "Campaign theme locked", value: "'Winter warmth, from the inside'", status: "ok" },
          { label: "Legal & claims review", value: "No unsubstantiated health claims", status: "ok" },
          { label: "Client sign-off date", value: "9 April 2026", status: "ok" },
        ],
      },
      {
        agent: "MUSE",
        title: "Copy — Channel Output",
        body: "Copy written and approved for email, Instagram, and Meta ads. Word counts and character limits verified per platform.",
        items: [
          { label: "Email subject line (A/B)", value: "'Winter ritual' vs 'Warm from within'", status: "ok" },
          { label: "Email body (280 words)", value: "Approved 10 Apr — Sarah K.", status: "ok" },
          { label: "Instagram caption (3 versions)", value: "All under 2,200 chars", status: "ok" },
          { label: "Meta ad (primary text + headline)", value: "Compliant with Meta ad policies", status: "ok" },
        ],
      },
      {
        agent: "REEL",
        title: "Publication Schedule",
        body: "Content calendar confirmed. All assets handed to production team. Tracking UTMs applied to all links.",
        items: [
          { label: "Email send — 14 Apr 2026 07:00 NZST", value: "Scheduled", status: "info" },
          { label: "Instagram post — 14 Apr 2026 08:30 NZST", value: "Scheduled", status: "info" },
          { label: "Meta campaign start", value: "14 Apr 2026 — $800 budget", status: "info" },
          { label: "Analytics review date", value: "21 Apr 2026 — 7-day report", status: "info" },
        ],
      },
    ],
    signOff:
      "Pack generated by AUAHA kete. Copy outputs are AI-assisted — final editorial review by client is recommended before publication.",
    seoTitle: "Sample Evidence Pack — Auaha Creative | assembl",
    seoDesc:
      "See a sample assembl evidence pack for creative campaigns. Brief to published — copy, scheduling, and approval audit trail in one pack.",
  },

  arataki: {
    slug: "arataki",
    kete: "ARATAKI",
    subtitle: "Privacy & Business Compliance",
    accent: "#5A8FBF",
    accentLight: "#7AAFFB",
    scenario: "Privacy Act 2020 Compliance Review",
    client: "Tasman Dental Group, Nelson",
    date: "11 April 2026",
    packId: "ART-2026-0411-007",
    summary:
      "All 13 Information Privacy Principles assessed. Data flows mapped. Breach response plan reviewed. Pack is IPP3A-ready and signed for filing with your Privacy Officer.",
    sections: [
      {
        agent: "ARATAKI",
        title: "Information Privacy Principles — 13-Point Assessment",
        body: "Privacy Act 2020, Part 3 applied. All 13 IPPs assessed against current practice and documented systems.",
        items: [
          { label: "IPP 1 — Purpose of collection", value: "Documented — consent form updated Feb 2026", status: "ok" },
          { label: "IPP 3 — Collection from individual", value: "Compliant — direct collection confirmed", status: "ok" },
          { label: "IPP 5 — Storage & security", value: "Encrypted at rest & in transit — Azure NZ", status: "ok" },
          { label: "IPP 11 — Disclosure overseas", value: "Practice management software — US-hosted", status: "warn" },
        ],
      },
      {
        agent: "ARATAKI",
        title: "Data Flow Map",
        body: "Personal health information tracked from collection through to disposal. Third-party processors identified and assessed.",
        items: [
          { label: "Patient data entry points", value: "3 identified — reception, online, phone", status: "ok" },
          { label: "Third-party processors", value: "4 identified — all documented", status: "ok" },
          { label: "Offshore processing (US)", value: "Dental software vendor — standard clauses in place", status: "ok" },
          { label: "Retention schedule", value: "10-year medical records policy — documented", status: "ok" },
        ],
      },
      {
        agent: "ARATAKI",
        title: "Breach Response Readiness",
        body: "Privacy breach response plan assessed against OPC guidance (August 2023). Notification obligations reviewed.",
        items: [
          { label: "Breach response plan on file", value: "Yes — updated 1 Mar 2026", status: "ok" },
          { label: "Notifiable breach threshold understood", value: "Confirmed — staff briefed", status: "ok" },
          { label: "OPC notification process", value: "Documented — 72-hour window noted", status: "ok" },
          { label: "Privacy Officer appointed", value: "Dr. A. Tane — confirmed", status: "ok" },
        ],
      },
    ],
    signOff:
      "Pack generated by ARATAKI kete. This assessment is advisory — your Privacy Officer should review and confirm before relying on this pack for regulatory purposes. IPP3A-compliant format.",
    seoTitle: "Sample Evidence Pack — Arataki Privacy Compliance | assembl",
    seoDesc:
      "See a sample assembl evidence pack for Privacy Act 2020 compliance. IPP assessment, data flow map, and breach response — ready to file with your Privacy Officer.",
  },

  pikau: {
    slug: "pikau",
    kete: "PIKAU",
    subtitle: "Customs & Freight Intelligence",
    accent: "#7B6FA0",
    accentLight: "#A89FCC",
    scenario: "Import Declaration — Electronics (Guangzhou → Auckland)",
    client: "Pacific Tech Imports Ltd, Auckland",
    date: "11 April 2026",
    packId: "PKU-2026-0411-003",
    summary:
      "Tariff classification confirmed. Prohibited goods check clear. Biosecurity requirements documented. Declaration pack ready — lodge with Customs NZ within 20 days of vessel arrival.",
    sections: [
      {
        agent: "PIKAU",
        title: "Tariff Classification",
        body: "Import Tariff 2022 (NZ Customs) applied. HS code confirmed for consumer electronics. Duty rate and GST obligations calculated.",
        items: [
          { label: "HS Code", value: "8471.30 — Portable digital ADP machines", status: "ok" },
          { label: "General tariff rate", value: "0% — Free (NZ–China FTA)", status: "ok" },
          { label: "GST at border", value: "15% on CIF value + duty", status: "info" },
          { label: "Declared value (NZD)", value: "$48,200 CIF", status: "ok" },
        ],
      },
      {
        agent: "PIKAU",
        title: "Prohibited & Restricted Goods Check",
        body: "Import prohibition and restriction rules checked against Schedule 2, Customs and Excise Act 2018.",
        items: [
          { label: "Prohibited goods flag", value: "Clear", status: "ok" },
          { label: "Restricted goods flag", value: "Clear", status: "ok" },
          { label: "Radio spectrum compliance (RSM)", value: "Required — importer to confirm 802.11ax compliance", status: "warn" },
          { label: "Consumer product safety (MBIE)", value: "Electrical safety standards — documented", status: "ok" },
        ],
      },
      {
        agent: "PIKAU",
        title: "Biosecurity & MPI Clearance",
        body: "Ministry for Primary Industries import health standard assessed. Packaging materials and country of origin verified.",
        items: [
          { label: "MPI import permit required", value: "No — electronics, no organic material", status: "ok" },
          { label: "Packaging material (wood)", value: "ISPM 15 marked — compliant", status: "ok" },
          { label: "Container inspection risk level", value: "Low — random selection applies", status: "info" },
          { label: "Broker handoff ready", value: "Documents prepared for NZ broker", status: "ok" },
        ],
      },
    ],
    signOff:
      "Pack generated by PIKAU kete. Confirm tariff classification and declaration details with your licensed customs broker before lodging with Customs NZ.",
    seoTitle: "Sample Evidence Pack — Pikau Customs & Freight | assembl",
    seoDesc:
      "See a sample assembl evidence pack for freight and customs. Tariff classification, prohibited goods check, and declaration pack — ready to lodge.",
  },

  toroa: {
    slug: "toroa",
    kete: "TOROA",
    subtitle: "Family Navigator",
    accent: TEAL,
    accentLight: "#87CEEB",
    scenario: "Weekly Family Summary — Te Whānau Roberts",
    client: "Roberts Whānau, Palmerston North",
    date: "Week ending 11 April 2026",
    packId: "TOR-2026-0411-W14",
    summary:
      "3 school notices collected and actioned. 2 appointments confirmed. Weekly budget on track ($42 under). Kai plan set for the week. All 4 whānau members checked in.",
    sections: [
      {
        agent: "TORO",
        title: "School Notices — This Week",
        body: "Notices collected from Palmerston North Intermediate and Terrace End School via SMS digest.",
        items: [
          { label: "Cross Country Rescheduled — PN Intermediate", value: "New date: 17 Apr — calendar updated", status: "ok" },
          { label: "Permission slip due — Terrace End trip", value: "Reply YES by 14 Apr — sent ✓", status: "ok" },
          { label: "Uniform shop closure — 15 Apr", value: "Noted — no action required", status: "info" },
          { label: "Next school week", value: "Week 10 — normal schedule", status: "info" },
        ],
      },
      {
        agent: "TORO",
        title: "Appointments & Coordination",
        body: "Family appointments tracked and confirmed across healthcare and education this week.",
        items: [
          { label: "GP — Mia (annual check-up)", value: "Confirmed: 14 Apr 10:30am — Angus Street", status: "ok" },
          { label: "Orthodontist — Caleb", value: "Confirmed: 16 Apr 3:45pm — remember retainer", status: "ok" },
          { label: "Parent-teacher interview — TBD", value: "No booking yet — reminder set for 13 Apr", status: "warn" },
          { label: "Shared family calendar", value: "All events synced via SMS", status: "ok" },
        ],
      },
      {
        agent: "TORO",
        title: "Budget & Kai Plan",
        body: "Weekly household budget checked. Meal plan drafted and shared with whānau via SMS.",
        items: [
          { label: "Weekly grocery spend (estimate)", value: "$210 — $42 under budget", status: "ok" },
          { label: "Upcoming bills (next 7 days)", value: "Power $145 due 15 Apr", status: "info" },
          { label: "Meal plan set", value: "5 dinners + 2 easy nights — sent to group", status: "ok" },
          { label: "Pantry staples low", value: "Rice, olive oil, tinned tomatoes", status: "warn" },
        ],
      },
    ],
    signOff:
      "Summary generated by TORO — your SMS-first family navigator. Reply STOP to pause summaries. All data stays in your household, never shared.",
    seoTitle: "Sample Evidence Pack — Toroa Family Navigator | assembl",
    seoDesc:
      "See a sample assembl family summary pack. School notices, appointments, budget, and kai plan — all in one weekly digest.",
  },
};

/* ─── Status indicator ─── */
const StatusDot = ({ status }: { status: "ok" | "warn" | "info" }) => {
  const color = status === "ok" ? "#3A7D6E" : status === "warn" ? "#D4A853" : "#5A8FBF";
  return (
    <span
      className="inline-block w-2 h-2 rounded-full shrink-0 mt-1"
      style={{ background: color, boxShadow: `0 0 6px ${color}60` }}
    />
  );
};

/* ─── Document section card ─── */
const DocSection = ({ section, accent, index }: { section: Section; accent: string; index: number }) => (
  <motion.div
    className="rounded-2xl overflow-hidden"
    style={{ background: SURFACE, border: `1px solid ${BORDER}` }}
    {...fade(index * 0.15 + 0.4)}
  >
    {/* Section header */}
    <div
      className="px-6 py-4 flex items-center gap-3"
      style={{ borderBottom: `1px solid ${BORDER}`, background: `${accent}08` }}
    >
      <span
        className="text-[9px] font-bold tracking-[3px] uppercase px-2 py-1 rounded"
        style={{ fontFamily: FONT_MONO, color: accent, background: `${accent}15`, border: `1px solid ${accent}25` }}
      >
        {section.agent}
      </span>
      <h3
        className="text-sm font-medium"
        style={{ fontFamily: FONT_HEAD, color: WHITE, letterSpacing: "0.02em" }}
      >
        {section.title}
      </h3>
    </div>

    {/* Body */}
    <div className="px-6 pt-4 pb-2">
      <p className="text-xs mb-4" style={{ fontFamily: FONT_BODY, color: "#6B7280", lineHeight: 1.7 }}>
        {section.body}
      </p>

      {/* Items */}
      <div className="space-y-2">
        {section.items.map((item) => (
          <div key={item.label} className="flex items-start gap-3 py-2" style={{ borderTop: `1px solid rgba(255,255,255,0.04)` }}>
            <StatusDot status={item.status} />
            <div className="flex-1 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-1">
              <span className="text-xs" style={{ fontFamily: FONT_BODY, color: "#6B7280" }}>
                {item.label}
              </span>
              <span
                className="text-xs font-medium"
                style={{
                  fontFamily: FONT_MONO,
                  color: item.status === "ok" ? "rgba(255,255,255,0.8)" : item.status === "warn" ? "#D4A853" : "#5A8FBF",
                }}
              >
                {item.value}
              </span>
            </div>
          </div>
        ))}
      </div>
    </div>
    <div className="px-6 pb-4" />
  </motion.div>
);

/* ─── PDF generation ─── */
function generatePackPDF(pack: PackData) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const margin = 20;
  const pw = doc.internal.pageSize.getWidth();
  const maxW = pw - margin * 2;

  let y = drawAssemblPDFHeader(doc, {
    agentName: pack.kete,
    agentDesignation: pack.subtitle,
    documentTitle: pack.scenario,
    subtitle: `${pack.client}  ·  ${pack.date}  ·  Pack ID: ${pack.packId}`,
    margin,
  });

  // Summary
  doc.setFontSize(9.5);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(40, 40, 50);
  const summaryLines = doc.splitTextToSize(pack.summary, maxW);
  for (const l of summaryLines) { doc.text(l, margin, y); y += 4.5; }
  y += 6;

  // Sections
  for (const section of pack.sections) {
    // Check page space
    if (y > 230) { doc.addPage(); y = 20; }

    // Section header bar
    doc.setFillColor(240, 238, 232);
    doc.rect(margin, y - 3, maxW, 8, "F");
    doc.setFillColor(212, 168, 67);
    doc.rect(margin, y - 3, 1.5, 8, "F");

    doc.setFontSize(7);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(100, 100, 110);
    doc.text(section.agent, margin + 5, y + 1);

    doc.setFontSize(10);
    doc.setTextColor(20, 20, 30);
    doc.text(section.title, margin + 5 + doc.getTextWidth(section.agent + "  "), y + 1);
    y += 9;

    // Body text
    doc.setFontSize(8.5);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(90, 90, 100);
    const bodyLines = doc.splitTextToSize(section.body, maxW - 4);
    for (const l of bodyLines) { doc.text(l, margin + 2, y); y += 4; }
    y += 3;

    // Items table
    const labelW = maxW * 0.55;
    const valueW = maxW * 0.35;
    const statusW = maxW * 0.1;

    for (const item of section.items) {
      if (y > 255) { doc.addPage(); y = 20; }

      // Status indicator
      const statusColor: [number, number, number] =
        item.status === "ok" ? [58, 125, 110] :
        item.status === "warn" ? [212, 168, 67] :
        [90, 143, 191];
      doc.setFillColor(...statusColor);
      doc.circle(margin + 3, y - 1, 1.5, "F");

      // Label
      doc.setFontSize(8.5);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(60, 60, 70);
      doc.text(item.label, margin + 8, y, { maxWidth: labelW - 10 });

      // Value
      doc.setFont("helvetica", "bold");
      doc.setTextColor(30, 30, 40);
      const valLines = doc.splitTextToSize(item.value, valueW);
      doc.text(valLines[0] || "", margin + labelW, y, { maxWidth: valueW });
      y += Math.max(valLines.length * 4, 5);

      // Divider
      doc.setDrawColor(230, 228, 220);
      doc.setLineWidth(0.15);
      doc.line(margin + 8, y - 1, margin + maxW, y - 1);
      y += 1;
    }
    y += 4;
  }

  // Sign-off block
  if (y > 230) { doc.addPage(); y = 20; }
  doc.setDrawColor(212, 168, 67);
  doc.setLineWidth(0.6);
  doc.line(margin, y, margin + 25, y);
  y += 5;

  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(58, 125, 110);
  doc.text("PACK SIGN-OFF", margin, y);
  y += 5;

  doc.setFontSize(8.5);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(90, 90, 100);
  const signOffLines = doc.splitTextToSize(pack.signOff, maxW);
  for (const l of signOffLines) { doc.text(l, margin, y); y += 4; }
  y += 8;

  // Signature lines
  if (y > 240) { doc.addPage(); y = 20; }
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(140, 140, 150);

  const sigY = y;
  doc.text("Reviewed by:", margin, sigY);
  doc.setDrawColor(200, 195, 185);
  doc.setLineWidth(0.3);
  doc.line(margin + 25, sigY, margin + 80, sigY);

  doc.text("Date:", margin + 90, sigY);
  doc.line(margin + 100, sigY, margin + 140, sigY);

  y = sigY + 8;
  doc.text("Signed:", margin, y);
  doc.line(margin + 25, y, margin + 80, y);

  doc.text("Role:", margin + 90, y);
  doc.line(margin + 100, y, margin + 140, y);

  // SAMPLE watermark on every page
  const totalPages = doc.getNumberOfPages();
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p);
    doc.setFontSize(60);
    doc.setTextColor(200, 200, 200);
    doc.setGState(new (doc as any).GState({ opacity: 0.08 }));
    doc.text("SAMPLE", pw / 2, 150, { align: "center", angle: 35 });
    doc.setGState(new (doc as any).GState({ opacity: 1 }));
  }

  drawAssemblPDFFooter(doc, { agentName: `${pack.kete} — ${pack.subtitle}`, margin });

  return doc;
}

/* ═══ PAGE ═══ */
const SampleEvidencePackPage = () => {
  const { kete } = useParams<{ kete: string }>();
  const pack = PACKS[kete || "manaaki"] || PACKS.manaaki;

  return (
    <div className="min-h-screen flex flex-col" style={{ background: BG, color: WHITE }}>
      <SEO title={pack.seoTitle} description={pack.seoDesc} />
      <BrandNav />

      <main className="flex-1">
        {/* ─── Hero ─── */}
        <section className="max-w-4xl mx-auto px-4 sm:px-6 pt-16 pb-10 text-center">
          {/* Sample label */}
          <motion.div {...fade(0)}>
            <span
              className="inline-block text-[9px] tracking-[4px] uppercase px-4 py-1.5 rounded-full mb-6"
              style={{
                fontFamily: FONT_MONO,
                color: pack.accent,
                background: `${pack.accent}12`,
                border: `1px solid ${pack.accent}25`,
              }}
            >
              Sample Evidence Pack
            </span>
          </motion.div>

          <motion.h1
            className="text-3xl sm:text-5xl mb-3"
            style={{ fontFamily: FONT_HEAD, fontWeight: 300, letterSpacing: "0.08em", textTransform: "uppercase" }}
            {...fade(1)}
          >
            {pack.kete}
          </motion.h1>

          <motion.p
            className="text-sm mb-8"
            style={{ fontFamily: FONT_MONO, color: pack.accentLight, letterSpacing: "0.05em" }}
            {...fade(2)}
          >
            {pack.subtitle}
          </motion.p>
        </section>

        {/* ─── Document wrapper ─── */}
        <section className="max-w-4xl mx-auto px-4 sm:px-6 pb-20">
          {/* Document header */}
          <motion.div
            className="rounded-2xl p-6 sm:p-8 mb-6"
            style={{ background: SURFACE, border: `1px solid ${BORDER}` }}
            {...fade(3)}
          >
            {/* Meta row */}
            <div className="flex flex-wrap items-center justify-between gap-4 mb-6">
              <div>
                <p
                  className="text-[10px] tracking-[3px] uppercase mb-1"
                  style={{ fontFamily: FONT_MONO, color: "#6B7280" }}
                >
                  Evidence Pack
                </p>
                <p className="text-lg font-medium" style={{ fontFamily: FONT_HEAD, color: WHITE }}>
                  {pack.scenario}
                </p>
              </div>
              <span
                className="text-[9px] tracking-[2px] uppercase px-3 py-1.5 rounded-full"
                style={{
                  fontFamily: FONT_MONO,
                  color: pack.accent,
                  background: `${pack.accent}12`,
                  border: `1px solid ${pack.accent}25`,
                }}
              >
                Sample Only
              </span>
            </div>

            {/* Details grid */}
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
              {[
                { label: "Client", value: pack.client, icon: User },
                { label: "Date", value: pack.date, icon: Clock },
                { label: "Pack ID", value: pack.packId, icon: FileText },
                { label: "Status", value: "Complete", icon: Shield },
              ].map(({ label, value, icon: Icon }) => (
                <div key={label} className="flex flex-col gap-1">
                  <div className="flex items-center gap-1.5">
                    <Icon size={11} style={{ color: "#9CA3AF" }} />
                    <span
                      className="text-[9px] tracking-[2px] uppercase"
                      style={{ fontFamily: FONT_MONO, color: "#9CA3AF" }}
                    >
                      {label}
                    </span>
                  </div>
                  <span className="text-xs" style={{ fontFamily: FONT_BODY, color: "#4AA5A8" }}>
                    {value}
                  </span>
                </div>
              ))}
            </div>

            {/* Divider */}
            <div className="my-6" style={{ borderTop: `1px solid ${BORDER}` }} />

            {/* Summary */}
            <div className="flex items-start gap-3">
              <Check size={16} style={{ color: pack.accent, marginTop: 2, flexShrink: 0 }} />
              <p className="text-sm" style={{ fontFamily: FONT_BODY, color: "rgba(255,255,255,0.65)", lineHeight: 1.7 }}>
                {pack.summary}
              </p>
            </div>
          </motion.div>

          {/* ─── Sections ─── */}
          <div className="space-y-4 mb-6">
            {pack.sections.map((section, i) => (
              <DocSection key={section.title} section={section} accent={pack.accent} index={i} />
            ))}
          </div>

          {/* ─── Sign-off block ─── */}
          <motion.div
            className="rounded-2xl p-6 mb-8"
            style={{ background: `${pack.accent}08`, border: `1px solid ${pack.accent}20` }}
            {...fade(0.8)}
          >
            <div className="flex items-start gap-3">
              <Shield size={16} style={{ color: pack.accent, marginTop: 2, flexShrink: 0 }} />
              <div>
                <p
                  className="text-[9px] tracking-[3px] uppercase mb-2"
                  style={{ fontFamily: FONT_MONO, color: pack.accent }}
                >
                  Pack Sign-Off
                </p>
                <p className="text-xs" style={{ fontFamily: FONT_BODY, color: "#6B7280", lineHeight: 1.7 }}>
                  {pack.signOff}
                </p>
              </div>
            </div>
          </motion.div>

          {/* ─── Export actions strip ─── */}
          <motion.div
            className="rounded-2xl p-6 mb-8 flex flex-wrap items-center justify-between gap-4"
            style={{ background: SURFACE, border: `1px solid ${BORDER}` }}
            {...fade(0.9)}
          >
            <p
              className="text-xs"
              style={{ fontFamily: FONT_MONO, color: "#6B7280", letterSpacing: "0.05em" }}
            >
              Export this pack:
            </p>
            <div className="flex flex-wrap gap-3">
              <button
                onClick={() => {
                  const doc = generatePackPDF(pack);
                  doc.save(`assembl-${pack.slug}-evidence-pack-${pack.packId}.pdf`);
                }}
                className="flex items-center gap-1.5 px-4 py-2 rounded-full text-xs font-medium transition-all hover:scale-105 cursor-pointer"
                style={{
                  fontFamily: FONT_BODY,
                  color: WHITE,
                  background: pack.accent,
                }}
              >
                <Download size={12} />
                Download PDF
              </button>
              <button
                onClick={() => {
                  const doc = generatePackPDF(pack);
                  doc.autoPrint();
                  window.open(doc.output("bloburl"), "_blank");
                }}
                className="flex items-center gap-1.5 px-4 py-2 rounded-full text-xs font-medium transition-all hover:opacity-80 cursor-pointer"
                style={{
                  fontFamily: FONT_BODY,
                  color: "#4AA5A8",
                  background: "rgba(255,255,255,0.06)",
                  border: "1px solid rgba(74,165,168,0.15)",
                }}
              >
                <Printer size={12} />
                Print
              </button>
              {[
                { icon: FileText, label: "Filed" },
                { icon: Share2, label: "Forwarded" },
                { icon: Bookmark, label: "Footnoted" },
              ].map(({ icon: Icon, label }) => (
                <span
                  key={label}
                  className="flex items-center gap-1.5 px-3 py-1.5 rounded-full text-xs"
                  style={{
                    fontFamily: FONT_BODY,
                    color: "#6B7280",
                    background: "rgba(255,255,255,0.65)",
                    border: "1px solid rgba(74,165,168,0.15)",
                  }}
                >
                  <Icon size={11} />
                  {label}
                </span>
              ))}
            </div>
          </motion.div>

          {/* ─── CTA ─── */}
          <motion.div
            className="rounded-2xl p-8 text-center"
            style={{ background: `linear-gradient(135deg, ${pack.accent}12, ${TEAL}08)`, border: `1px solid ${pack.accent}20` }}
            {...fade(1.0)}
          >
            <p
              className="text-[10px] tracking-[4px] uppercase mb-3"
              style={{ fontFamily: FONT_MONO, color: pack.accentLight }}
            >
              This is a sample
            </p>
            <h2
              className="text-xl sm:text-2xl mb-3"
              style={{ fontFamily: FONT_HEAD, fontWeight: 300, letterSpacing: "0.04em" }}
            >
              Your real pack is built from your actual data.
            </h2>
            <p className="text-sm mb-6 max-w-xl mx-auto" style={{ fontFamily: FONT_BODY, color: "#6B7280", lineHeight: 1.7 }}>
              Every assembl run ends in a signed evidence pack like this — except with your client's name, your documents, and your compliance history. File it, forward it, footnote it.
            </p>
            <div className="flex flex-col sm:flex-row items-center justify-center gap-3">
              <Link
                to="/contact"
                className="inline-flex items-center gap-2 px-8 py-3 rounded-full text-sm font-bold transition-all hover:scale-105"
                style={{
                  fontFamily: FONT_HEAD,
                  fontWeight: 700,
                  textTransform: "uppercase",
                  letterSpacing: "0.08em",
                  background: pack.accent,
                  color: pack.accent === GOLD || pack.accent === "#C4943A" ? "#09090F" : WHITE,
                }}
              >
                Get started <ArrowRight size={15} />
              </Link>
              <Link
                to="/"
                className="inline-flex items-center gap-2 px-6 py-3 rounded-full text-sm transition-all hover:opacity-80"
                style={{
                  fontFamily: FONT_BODY,
                  color: "#6B7280",
                  border: "1px solid rgba(74,165,168,0.15)",
                }}
              >
                See all kete <ChevronRight size={14} />
              </Link>
            </div>
          </motion.div>

          {/* ─── Other kete nav ─── */}
          <motion.div className="mt-10" {...fade(1.1)}>
            <p
              className="text-[9px] tracking-[3px] uppercase text-center mb-4"
              style={{ fontFamily: FONT_MONO, color: "#9CA3AF" }}
            >
              Explore other kete
            </p>
            <div className="flex flex-wrap justify-center gap-2">
              {Object.values(PACKS)
                .filter((p) => p.slug !== pack.slug)
                .map((p) => (
                  <Link
                    key={p.slug}
                    to={`/sample/${p.slug}`}
                    className="px-4 py-2 rounded-full text-xs transition-all hover:opacity-80"
                    style={{
                      fontFamily: FONT_MONO,
                      color: p.accentLight,
                      background: `${p.accent}10`,
                      border: `1px solid ${p.accent}20`,
                      letterSpacing: "0.05em",
                    }}
                  >
                    {p.kete}
                  </Link>
                ))}
            </div>
          </motion.div>
        </section>
      </main>

      <BrandFooter />
    </div>
  );
};

export default SampleEvidencePackPage;
