import BrandNav from "@/components/BrandNav";
import BrandFooter from "@/components/BrandFooter";
import ParticleField from "@/components/ParticleField";

const TermsOfUse = () => (
  <div className="min-h-screen star-field flex flex-col relative">
    <ParticleField />
    <BrandNav />
    <main className="flex-1 max-w-3xl mx-auto px-4 sm:px-6 py-16 sm:py-24">
      <h1 className="text-2xl sm:text-4xl font-extrabold text-foreground mb-8">Terms of Use</h1>
      <p className="text-xs text-muted-foreground mb-6">Last updated: 19 March 2026</p>

      <div className="prose-sm space-y-6 text-sm text-foreground/80 leading-relaxed">
        <section>
          <h2 className="text-lg font-bold text-foreground mb-2">1. Acceptance of terms</h2>
          <p>By accessing or using assembl.co.nz and any associated services ("the Platform"), you agree to be bound by these Terms of Use. If you do not agree, do not use the Platform. These terms are governed by the laws of New Zealand.</p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-foreground mb-2">2. About our service</h2>
          <p>Assembl provides AI-powered agents that offer general information and guidance across various NZ industries. Our agents are tools to assist — they do not replace qualified professional advice.</p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-foreground mb-2">3. No professional advice</h2>
          <p><strong>Important:</strong> Content generated by Assembl agents is AI-generated general information only. It is not legal advice, financial advice, tax advice, medical advice, or any other form of professional advice. You must consult a qualified professional before making decisions based on agent outputs.</p>
          <p>We are not liable for any actions taken or not taken based on AI-generated content.</p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-foreground mb-2">4. User accounts</h2>
          <ul className="list-disc pl-5 space-y-1">
            <li>You must provide accurate information when creating an account</li>
            <li>You are responsible for maintaining the security of your account</li>
            <li>You must be at least 16 years old to create an account</li>
            <li>One person or entity per account — sharing credentials is not permitted</li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-bold text-foreground mb-2">5. Acceptable use</h2>
          <p>You agree not to:</p>
          <ul className="list-disc pl-5 space-y-1">
            <li>Use the Platform for any unlawful purpose under NZ law</li>
            <li>Attempt to reverse-engineer, copy, or extract our system prompts, agent configurations, or proprietary workflows</li>
            <li>Resell, sublicense, or redistribute agent outputs commercially without written consent</li>
            <li>Upload malicious files, spam, or abusive content</li>
            <li>Interfere with the Platform's operation or security</li>
            <li>Use automated tools to scrape or access the Platform beyond normal use</li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-bold text-foreground mb-2">6. Intellectual property</h2>
          <p>All agent designs, system prompts, branding, user interface, and automation workflows are proprietary trade secrets of Assembl. Unauthorised reproduction, distribution, or use is prohibited and may result in legal action.</p>
          <p>Content you create using our agents remains yours. However, you grant us a licence to process your inputs to provide the service.</p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-foreground mb-2">7. Payments and subscriptions</h2>
          <ul className="list-disc pl-5 space-y-1">
            <li>Paid plans are billed monthly in NZD (GST inclusive) via Stripe</li>
            <li>You can cancel at any time — no lock-in contracts</li>
            <li>Refunds are at our discretion, in accordance with the Consumer Guarantees Act 1993</li>
            <li>We reserve the right to change pricing with 30 days' notice</li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-bold text-foreground mb-2">8. Service availability</h2>
          <p>We aim to provide reliable service but do not guarantee uninterrupted access. We may perform maintenance, updates, or modifications at any time. We are not liable for any loss resulting from service interruptions.</p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-foreground mb-2">9. Limitation of liability</h2>
          <p>To the maximum extent permitted by NZ law (including the Consumer Guarantees Act 1993 and the Fair Trading Act 1986):</p>
          <ul className="list-disc pl-5 space-y-1">
            <li>Assembl is not liable for indirect, incidental, or consequential damages</li>
            <li>Our total liability is limited to the amount you paid us in the 12 months preceding the claim</li>
            <li>We do not warrant that AI-generated content is accurate, complete, or fit for any particular purpose</li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-bold text-foreground mb-2">10. Indemnity</h2>
          <p>You agree to indemnify Assembl against any claims, losses, or damages arising from your use of the Platform, your breach of these terms, or your reliance on AI-generated content.</p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-foreground mb-2">11. Termination</h2>
          <p>We may suspend or terminate your access at our discretion if you breach these terms. You may delete your account at any time. Upon termination, your right to use the Platform ceases immediately.</p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-foreground mb-2">12. Dispute resolution</h2>
          <p>Any disputes arising from these terms shall be resolved through good-faith negotiation. If unresolved, disputes will be submitted to mediation in Auckland, New Zealand, before any court proceedings.</p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-foreground mb-2">13. Governing law</h2>
          <p>These terms are governed by the laws of New Zealand. The courts of New Zealand have exclusive jurisdiction.</p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-foreground mb-2">14. Changes to these terms</h2>
          <p>We may update these terms at any time. Material changes will be notified via email or Platform notice. Continued use after changes constitutes acceptance.</p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-foreground mb-2">15. Contact</h2>
          <p>Questions about these terms? Email <a href="mailto:assembl@assembl.co.nz" className="text-primary hover:underline">assembl@assembl.co.nz</a>.</p>
        </section>
      </div>
    </main>
    <BrandFooter />
  </div>
);

export default TermsOfUse;
