import { useState } from "react";
import { motion } from "framer-motion";
import { FileText, Sparkles, Download, Save, Copy, Send } from "lucide-react";
import { toast } from "sonner";

import { AaaipGuardBadge, useAaaipGuard } from "@/aaaip";

const KOWHAI = "#D4A843";
const POUNAMU = "#3A7D6E";

const Glass = ({ children, className = "" }: { children: React.ReactNode; className?: string }) => (
  <div className={`rounded-2xl border backdrop-blur-md ${className}`} style={{
    background: "linear-gradient(145deg, rgba(255,255,255,0.78), rgba(255,255,255,0.62))",
    borderColor: "rgba(255,255,255,0.5)", boxShadow: "8px 8px 24px rgba(166,166,180,0.28), -6px -6px 18px rgba(255,255,255,0.95)",
  }}>{children}</div>
);

export default function TenderWriterPage() {
  const [title, setTitle] = useState("");
  const [template, setTemplate] = useState("construction");
  const [requirements, setRequirements] = useState("");
  const [generating, setGenerating] = useState(false);
  const [response, setResponse] = useState("");
  const [humanSignoff, setHumanSignoff] = useState(false);
  const guard = useAaaipGuard("waihanga");

  const submitTender = () => {
    const decision = guard.check({
      kind: "submit_tender",
      payload: { title, humanSignoff },
      world: {},
      rationale: `Submit tender "${title || "Untitled"}"`,
    });
    if (decision.blocked) {
      toast.error("Tender submission blocked", { description: decision.explanation });
      return;
    }
    if (decision.requiresHuman) {
      toast.warning("Sign-off required", {
        description:
          "Waihanga tender-integrity policy requires a principal to sign off before dispatch. Tick the sign-off box and retry.",
      });
      return;
    }
    toast.success("Tender dispatched", {
      description: "Cleared by AAAIP Waihanga policies and logged to the audit feed.",
    });
  };

  const generate = () => {
    setGenerating(true);
    setTimeout(() => {
      setResponse(`# Tender Response: ${title || "Untitled Tender"}\n\n## Executive Summary\nWe are pleased to submit our response to this ${template === "construction" ? "construction works" : template === "consultancy" ? "consultancy services" : "goods and services"} tender. Our team brings extensive New Zealand construction experience with a proven track record of delivering complex projects on time and within budget.\n\n## Company Profile\nHenare Construction Ltd is a Christchurch-based construction company established in 2008. We hold a Site Safe Gold accreditation and maintain an exemplary health and safety record.\n\n## Methodology\n${requirements ? `In response to the specific requirements outlined:\n${requirements}\n\nOur proposed approach includes:` : "Our methodology follows industry best practice:"}\n\n1. **Pre-construction Planning** — Detailed programme development using MS Project/Primavera P6\n2. **Health & Safety** — Full SSSP development per WorkSafe NZ guidelines\n3. **Quality Management** — ISO 9001 certified QMS with ITP for all critical works\n4. **Environmental Management** — Compliance with resource consent conditions and ESCP\n5. **Stakeholder Management** — Regular client reporting and community liaison\n\n## Relevant Experience\n- Christchurch Metro Sports Facility ($6.3M) — In Progress\n- Kaikōura Marine Research Centre ($4.1M) — Completed 2025\n- Ōtautahi Community Hub ($2.8M) — Completed 2024\n\n## Programme\nEstimated duration: 12–18 months from contract award, subject to detailed programme review.\n\n## Pricing\nRefer to attached pricing schedule (to be completed).\n\n---\n*Generated by WAIHANGA Tender Writer — powered by IHO*`);
      setGenerating(false);
    }, 2000);
  };

  return (
    <div className="p-4 sm:p-6 lg:p-8 space-y-6 max-w-5xl mx-auto">
      <motion.div
        initial={{ opacity: 0, y: -10 }}
        animate={{ opacity: 1, y: 0 }}
        className="flex flex-wrap items-start justify-between gap-3"
      >
        <div>
          <h1 className="text-xl font-bold text-foreground flex items-center gap-2"><FileText size={22} style={{ color: KOWHAI }} /> Tender Writer — Tono</h1>
          <p className="text-xs text-[#9CA3AF]">GETS-ready tender response generator</p>
        </div>
        <AaaipGuardBadge
          domain="waihanga"
          accentColor={KOWHAI}
          subtitle="Submissions require sign-off"
        />
      </motion.div>

      <Glass className="p-6 space-y-4">
        <div>
          <label className="text-[11px] text-[#9CA3AF] mb-1 block">Tender Title</label>
          <input value={title} onChange={e => setTitle(e.target.value)} placeholder="e.g. Christchurch Metro Sports Facility — Main Works"
            className="w-full px-4 py-2.5 rounded-xl text-sm text-foreground bg-white/[0.04] border border-white/[0.06] focus:outline-none focus:border-gray-300" />
        </div>
        <div>
          <label className="text-[11px] text-[#9CA3AF] mb-1 block">Template Type</label>
          <select value={template} onChange={e => setTemplate(e.target.value)}
            className="w-full px-4 py-2.5 rounded-xl text-sm text-[#3D4250] bg-white/[0.04] border border-white/[0.06] focus:outline-none">
            <option value="construction">Construction Works</option>
            <option value="consultancy">Consultancy Services</option>
            <option value="goods">Goods & Services</option>
          </select>
        </div>
        <div>
          <label className="text-[11px] text-[#9CA3AF] mb-1 block">Requirements & Scope</label>
          <textarea value={requirements} onChange={e => setRequirements(e.target.value)} rows={5} placeholder="Paste tender requirements here..."
            className="w-full px-4 py-2.5 rounded-xl text-sm text-foreground bg-white/[0.04] border border-white/[0.06] focus:outline-none focus:border-gray-300 resize-none" />
        </div>
        <motion.button onClick={generate} disabled={generating} whileHover={{ scale: 1.02 }}
          className="flex items-center gap-2 px-6 py-3 rounded-xl text-sm font-medium disabled:opacity-50"
          style={{ background: KOWHAI, color: "#09090F" }}>
          <Sparkles size={16} />
          {generating ? "Generating..." : "Generate Response"}
        </motion.button>
      </Glass>

      {response && (
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="space-y-4">
          <Glass className="p-6">
            <div className="flex items-center justify-between mb-4">
              <h3 className="text-sm font-semibold text-foreground">Generated Response</h3>
              <div className="flex gap-2">
                <button className="p-2 rounded-lg text-gray-400 hover:text-[#6B7280] hover:bg-white/5"><Copy size={14} /></button>
                <button className="p-2 rounded-lg text-gray-400 hover:text-[#6B7280] hover:bg-white/5"><Save size={14} /></button>
                <button className="p-2 rounded-lg text-gray-400 hover:text-[#6B7280] hover:bg-white/5"><Download size={14} /></button>
              </div>
            </div>
            <textarea value={response} onChange={e => setResponse(e.target.value)} rows={20}
              className="w-full px-4 py-3 rounded-xl text-xs text-[#3D4250] bg-white/[0.03] border border-white/[0.06] focus:outline-none leading-relaxed font-mono resize-none" />
          </Glass>
          <Glass className="p-4">
            <div className="flex flex-wrap items-center justify-between gap-3">
              <label className="flex items-center gap-2 text-xs text-[#3D4250]">
                <input
                  type="checkbox"
                  checked={humanSignoff}
                  onChange={(e) => setHumanSignoff(e.target.checked)}
                  className="h-4 w-4 rounded border-gray-300"
                />
                Principal sign-off attached (required by AAAIP Waihanga policy)
              </label>
              <button
                onClick={submitTender}
                className="flex items-center gap-2 rounded-xl px-5 py-2.5 text-sm font-medium"
                style={{ background: POUNAMU, color: "#3D4250" }}
              >
                <Send size={14} />
                Submit tender
              </button>
            </div>
          </Glass>
        </motion.div>
      )}
    </div>
  );
}
