-- DISPOSABLE ONLY; precheck and candidate installed. All fixture writes roll back.
begin;
insert into auth.users(id,is_anonymous) values('ffffffff-ffff-4fff-8fff-ffffffffffff',false),('11111111-1111-4111-8111-111111111111',true),('22222222-2222-4222-8222-222222222222',false);
delete from public.do_personal_storage_enrolment;
insert into public.do_personal_storage_enrolment(owner_id,enabled,retention_reviewed,expires_at,purpose) values('ffffffff-ffff-4fff-8fff-ffffffffffff',true,true,clock_timestamp()+interval '1 day','owner_entered_responsibility_review');
update public.do_personal_storage_maintenance set status='completed',last_completed_at=clock_timestamp(),last_attempt_at=clock_timestamp() where id=true;
do $$ declare r text; begin
 if not exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='do_personal_auth_private' and p.proname='enrolled_owner_is_nonanonymous' and p.prosecdef and pg_get_userbyid(p.proowner)='postgres' and 'search_path=""'=any(p.proconfig) and p.prorettype='boolean'::regtype) then raise exception 'bridge_metadata_mismatch'; end if;
 foreach r in array array['anon','authenticated','service_role'] loop
  if has_table_privilege(r,'auth.users','SELECT') or has_column_privilege(r,'auth.users','id','SELECT') or has_column_privilege(r,'auth.users','is_anonymous','SELECT') then raise exception 'auth_direct_read_expanded'; end if;
  if has_schema_privilege(r,'do_personal_auth_private','CREATE') then raise exception 'private_schema_create_allowed'; end if;
  if has_function_privilege(r,'do_personal_auth_private.enrolled_owner_is_nonanonymous(uuid)','EXECUTE') is distinct from (r='service_role') or has_schema_privilege(r,'do_personal_auth_private','USAGE') is distinct from (r='service_role') then raise exception 'bridge_caller_acl_mismatch'; end if;
 end loop;
end $$;
set local role anon;
do $$ begin begin perform do_personal_auth_private.enrolled_owner_is_nonanonymous('ffffffff-ffff-4fff-8fff-ffffffffffff'); raise exception 'anon_bridge_allowed'; exception when insufficient_privilege then null; end; end $$;
reset role;
set local role authenticated;
select set_config('request.jwt.claim.sub','ffffffff-ffff-4fff-8fff-ffffffffffff',true);
do $$ begin begin perform do_personal_auth_private.enrolled_owner_is_nonanonymous('ffffffff-ffff-4fff-8fff-ffffffffffff'); raise exception 'authenticated_bridge_allowed'; exception when insufficient_privilege then null; end; end $$;
reset role;
set local role service_role;
select set_config('request.jwt.claim.sub','',true);
do $$ begin
 if not public.do_personal_storage_ready('ffffffff-ffff-4fff-8fff-ffffffffffff') then raise exception 'owned_readiness_failed'; end if;
 if do_personal_auth_private.enrolled_owner_is_nonanonymous(null) or do_personal_auth_private.enrolled_owner_is_nonanonymous('22222222-2222-4222-8222-222222222222') or do_personal_auth_private.enrolled_owner_is_nonanonymous('33333333-3333-4333-8333-333333333333') then raise exception 'foreign_or_missing_identity_oracle'; end if;
 begin perform id from auth.users; raise exception 'direct_auth_read_allowed'; exception when insufficient_privilege then null; end;
end $$;
select set_config('request.jwt.claim.sub','22222222-2222-4222-8222-222222222222',true);
do $$ begin if public.do_personal_storage_ready('ffffffff-ffff-4fff-8fff-ffffffffffff') then raise exception 'mismatched_uid_allowed'; end if; end $$;
select set_config('request.jwt.claim.sub','ffffffff-ffff-4fff-8fff-ffffffffffff',true);
do $$ begin if not public.do_personal_storage_ready('ffffffff-ffff-4fff-8fff-ffffffffffff') then raise exception 'matched_uid_denied'; end if; end $$;
select set_config('request.jwt.claim.sub','',true);
create temporary table users(id uuid,is_anonymous boolean);
insert into users values('ffffffff-ffff-4fff-8fff-ffffffffffff',true);
set local search_path=pg_temp,public;
do $$ begin if not public.do_personal_storage_ready('ffffffff-ffff-4fff-8fff-ffffffffffff') then raise exception 'temporary_shadow_changed_lookup'; end if; end $$;
set local search_path=public;
reset role;
revoke execute on function do_personal_auth_private.enrolled_owner_is_nonanonymous(uuid) from service_role;
set local role service_role;
do $$ begin begin perform public.do_personal_storage_ready('ffffffff-ffff-4fff-8fff-ffffffffffff'); raise exception 'missing_bridge_permission_allowed'; exception when insufficient_privilege then null; end; end $$;
reset role;
grant execute on function do_personal_auth_private.enrolled_owner_is_nonanonymous(uuid) to service_role;
update public.do_personal_storage_enrolment set retention_reviewed=false;
set local role service_role;
do $$ begin if public.do_personal_storage_ready('ffffffff-ffff-4fff-8fff-ffffffffffff') then raise exception 'unreviewed_retention_allowed'; end if; end $$;
reset role;
update public.do_personal_storage_enrolment set retention_reviewed=true;
update public.do_personal_storage_enrolment set enabled=false;
set local role service_role;
do $$ begin if public.do_personal_storage_ready('ffffffff-ffff-4fff-8fff-ffffffffffff') then raise exception 'revoked_enrollment_allowed'; end if; end $$;
reset role;
update public.do_personal_storage_enrolment set enabled=true,expires_at=clock_timestamp()-interval '1 second',enrolled_at=clock_timestamp()-interval '1 day';
set local role service_role;
do $$ begin if public.do_personal_storage_ready('ffffffff-ffff-4fff-8fff-ffffffffffff') then raise exception 'expired_enrollment_allowed'; end if; end $$;
reset role;
update public.do_personal_storage_enrolment set owner_id='11111111-1111-4111-8111-111111111111',expires_at=clock_timestamp()+interval '1 day';
set local role service_role;
do $$ begin if public.do_personal_storage_ready('11111111-1111-4111-8111-111111111111') then raise exception 'anonymous_owner_allowed'; end if; end $$;
reset role;
update public.do_personal_storage_enrolment set owner_id='ffffffff-ffff-4fff-8fff-ffffffffffff';
delete from auth.users where id='ffffffff-ffff-4fff-8fff-ffffffffffff';
set local role service_role;
do $$ begin if public.do_personal_storage_ready('ffffffff-ffff-4fff-8fff-ffffffffffff') then raise exception 'deleted_owner_allowed'; end if; end $$;
reset role;
rollback;
