import { useState } from "react";
import { Copy, Download, Check, FileDown } from "lucide-react";
import jsPDF from "jspdf";
import ReactMarkdown from "react-markdown";
import HelmChecklist from "@/components/helm/HelmChecklist";

interface Props {
  title: string;
  content: string;
  agentName: string;
  agentColor: string;
  hasChecklist?: boolean;
}

function detectOutputType(content: string): string | null {
  const lower = content.toLowerCase();
  // Check for structured sections with headers
  const patterns: [RegExp, string][] = [
    [/^#+\s*(checklist|compliance checklist|safety checklist|audit|h&s)/im, "Compliance Checklist"],
    [/^#+\s*(tax calculation|gst calculation|duty calculation|calculator)/im, "Tax Calculation"],
    [/^#+\s*(template|agreement|policy|contract|terms)/im, "Generated Template"],
    [/^#+\s*(plan|meal plan|budget|schedule|calendar)/im, "Generated Plan"],
    [/^#+\s*(report|status report|inspection|assessment)/im, "Report"],
    [/^#+\s*(checklist|moving checklist|preparation|document checklist)/im, "Checklist"],
    [/import entry summary/i, "Import Entry Summary"],
    [/^#+\s*(proposal|brief|charter|register)/im, "Document"],
  ];

  for (const [pattern, label] of patterns) {
    if (pattern.test(content)) return label;
  }

  // Check for significant structured content markers
  const checklistCount = (content.match(/^[-*]\s*\[([ xX])\]/gm) || []).length;
  if (checklistCount >= 3) return "Checklist";

  const tableRows = (content.match(/^\|.*\|$/gm) || []).length;
  if (tableRows >= 3) return "Data Table";

  const numberedSteps = (content.match(/^\d+\.\s+/gm) || []).length;
  if (numberedSteps >= 5) return "Step-by-Step Guide";

  // If content is long and has multiple headers, it's structured
  const headers = (content.match(/^#+\s+/gm) || []).length;
  if (headers >= 3 && content.length > 800) return "Structured Output";

  return null;
}

const StructuredOutputCard = ({ title, content, agentName, agentColor, hasChecklist }: Props) => {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadCSV = () => {
    const blob = new Blob([content], { type: "text/csv;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${title.toLowerCase().replace(/\s+/g, "-")}.csv`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleDownloadPDF = () => {
    const doc = new jsPDF({ unit: "mm", format: "a4" });
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    const maxWidth = pageWidth - margin * 2;
    let y = 20;

    // Header branding
    doc.setFontSize(18);
    doc.setFont("helvetica", "bold");
    doc.text("ASSEMBL", margin, y);
    y += 6;
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(120);
    doc.text(`Generated by ${agentName} — ${new Date().toLocaleDateString("en-NZ")}`, margin, y);
    y += 4;

    // Divider
    doc.setDrawColor(200);
    doc.line(margin, y, pageWidth - margin, y);
    y += 8;

    // Title
    doc.setTextColor(0);
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text(title, margin, y);
    y += 10;

    // Content - render as plain text with wrapping
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");

    const plainText = content
      .replace(/^#+\s*/gm, "")
      .replace(/\*\*(.*?)\*\*/g, "$1")
      .replace(/\*(.*?)\*/g, "$1")
      .replace(/^[-*]\s*\[([ xX])\]\s*/gm, (_, c) => (c.trim() ? "☑ " : "☐ "))
      .replace(/^[-*]\s+/gm, "• ");

    const lines = doc.splitTextToSize(plainText, maxWidth);

    for (const line of lines) {
      if (y > 270) {
        doc.addPage();
        y = 20;
      }
      doc.text(line, margin, y);
      y += 5;
    }

    // Footer
    const footerY = 285;
    doc.setFontSize(7);
    doc.setTextColor(140);
    doc.text(
      `Generated by ${agentName} — assembl.co.nz — This is AI-generated content and should be reviewed by a qualified professional before use.`,
      margin,
      footerY,
      { maxWidth }
    );

    doc.save(`${title.toLowerCase().replace(/\s+/g, "-")}.pdf`);
  };

  // Parse content: split checklist parts from text parts
  const renderContent = () => {
    if (!hasChecklist) {
      return (
        <div className="prose prose-invert prose-sm max-w-none prose-p:my-1 prose-ul:my-1 prose-ol:my-1 prose-li:my-0.5 prose-headings:text-foreground prose-strong:text-foreground">
          <ReactMarkdown>{content}</ReactMarkdown>
        </div>
      );
    }

    const lines = content.split("\n");
    const parts: { type: "text" | "checklist"; content: string }[] = [];
    let currentText = "";
    let checklistLines: string[] = [];

    const flushText = () => { if (currentText.trim()) { parts.push({ type: "text", content: currentText }); currentText = ""; } };
    const flushChecklist = () => { if (checklistLines.length) { parts.push({ type: "checklist", content: checklistLines.join("\n") }); checklistLines = []; } };

    for (const line of lines) {
      if (/^[-*]\s*\[([ xX])\]/.test(line.trim())) {
        flushText();
        checklistLines.push(line);
      } else {
        flushChecklist();
        currentText += line + "\n";
      }
    }
    flushText();
    flushChecklist();

    return (
      <>
        {parts.map((p, i) =>
          p.type === "checklist" ? (
            <HelmChecklist key={i} content={p.content} />
          ) : (
            <div key={i} className="prose prose-invert prose-sm max-w-none prose-p:my-1 prose-ul:my-1 prose-ol:my-1 prose-li:my-0.5 prose-headings:text-foreground prose-strong:text-foreground">
              <ReactMarkdown>{p.content}</ReactMarkdown>
            </div>
          )
        )}
      </>
    );
  };

  return (
    <div
      className="rounded-xl overflow-hidden my-2"
      style={{
        background: "#0F0F1C",
        borderLeft: `3px solid ${agentColor}`,
        border: `1px solid ${agentColor}15`,
        borderLeftWidth: 3,
        borderLeftColor: agentColor,
      }}
    >
      {/* Header */}
      <div className="px-4 py-2.5 flex items-center justify-between" style={{ borderBottom: `1px solid ${agentColor}10` }}>
        <span className="text-xs font-bold" style={{ color: agentColor }}>
          {title}
        </span>
      </div>

      {/* Content */}
      <div className="px-4 py-3 text-sm">
        {renderContent()}
      </div>

      {/* Actions */}
      <div className="px-4 py-2.5 flex gap-2 flex-wrap" style={{ borderTop: `1px solid ${agentColor}10` }}>
        <button
          onClick={handleCopy}
          className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-[11px] font-medium transition-colors"
          style={{ background: agentColor + "12", color: agentColor, border: `1px solid ${agentColor}20` }}
        >
          {copied ? <Check size={11} /> : <Copy size={11} />}
          {copied ? "Copied" : "Copy to clipboard"}
        </button>
        <button
          onClick={handleDownloadPDF}
          className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-[11px] font-medium transition-colors"
          style={{ background: agentColor + "12", color: agentColor, border: `1px solid ${agentColor}20` }}
        >
          <FileDown size={11} />
          Download as PDF
        </button>
        <button
          onClick={handleDownloadCSV}
          className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-[11px] font-medium transition-colors"
          style={{ background: agentColor + "12", color: agentColor, border: `1px solid ${agentColor}20` }}
        >
          <Download size={11} />
          Download as CSV
        </button>
      </div>
    </div>
  );
};

export { detectOutputType };
export default StructuredOutputCard;
