'use client';
import Link from 'next/link';
import { useState } from 'react';
import { ArrowUpRight, Download, Plus, Search } from 'lucide-react';
import { blankLead, STAGES, leadInput, leadsCsv, normalisedCompany, type Lead, type LeadInput } from '@/lib/specialists/crm';
import type { Prospect } from '@/lib/specialists/prospecting';
import { downloadText } from '@/lib/specialists/planning';
import { FluxConnections } from './FluxConnections';

const label = { new:'New', contacted:'In conversation', qualified:'Qualified', closed:'Closed' };
const sampleLeads: Lead[] = [
  { ...blankLead, id:'sample-a', name:'Example service business', company:'Example service business', value:8000, stage:'new', notes:'Fictional demo record. No actual enquiry or contact.', nextAction:'Check whether the customer wait fits our offer', owner:'Demo sales lead' },
  { ...blankLead, id:'sample-b', name:'Example dealership', company:'Example dealership', value:14000, stage:'qualified', notes:'Fictional demo record. Qualification is illustrative.', nextAction:'Prepare questions for a discovery conversation', owner:'Demo sales lead' },
];
const fmt=(value:number)=>new Intl.NumberFormat('en-NZ',{style:'currency',currency:'NZD',maximumFractionDigits:0}).format(value);
export function FluxWorkspace({ prepare }: {prepare:(text:string)=>void}) {
  const [mode,setMode]=useState<'session'|'private'>('session'); const [leads,setLeads]=useState<Lead[]>([]);
  const [form,setForm]=useState<LeadInput>({...blankLead}); const [editing,setEditing]=useState<string|null>(null); const [showForm,setShowForm]=useState(false);
  const [notice,setNotice]=useState(''); const [authNeeded,setAuthNeeded]=useState(false); const [busy,setBusy]=useState(false); const [search,setSearch]=useState('');
  const [research,setResearch]=useState({market:'New Zealand',niche:'',signals:''}); const [prospects,setProspects]=useState<Prospect[]>([]); const [researching,setResearching]=useState(false); const [researchNote,setResearchNote]=useState('');
  async function openCrm() {
    setBusy(true);setNotice('');
    try {const r=await fetch('/api/specialists/flux/leads',{cache:'no-store'});const j=await r.json();if(!r.ok){setAuthNeeded(r.status===401);throw new Error(j.error);}setMode('private');setLeads(j.leads);setShowForm(false);setAuthNeeded(false);setNotice('Your private pipeline is open. Up to 500 recent records are shown. Session-only leads have not been imported.');}
    catch(e){setNotice(e instanceof Error?e.message:'Could not open your pipeline.');}finally{setBusy(false);}
  }
  async function saveLead(event:React.FormEvent) {
    event.preventDefault();const parsed=leadInput.safeParse(form);if(!parsed.success){setNotice('Check the required name, email, value and date fields.');return;}
    if(!editing&&leads.some(l=>normalisedCompany(l.company||l.name)===normalisedCompany(form.company||form.name))){setNotice('A matching company is already in this pipeline. Open its existing record.');return;}
    setBusy(true);setNotice('');
    try {
      let row:Lead;
      if(mode==='private'){const r=await fetch('/api/specialists/flux/leads',{method:editing?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...(editing?{id:editing}:{}),lead:parsed.data})});const j=await r.json();if(!r.ok)throw new Error(j.error);row=j.lead;}
      else row={...parsed.data,id:editing||crypto.randomUUID()};
      setLeads(ls=>editing?ls.map(l=>l.id===editing?row:l):[row,...ls]);setShowForm(false);setEditing(null);setForm({...blankLead});setNotice(mode==='private'?'Record saved to your private assembl CRM.':'Record added to this session. Download it before closing the tab.');
    }catch(e){setNotice(e instanceof Error?e.message:'The record could not be saved.');}finally{setBusy(false);}
  }
  async function findProspects(event:React.FormEvent) {
    event.preventDefault();if(researching)return;setResearching(true);setResearchNote('Reading public business sources…');setProspects([]);
    try{const r=await fetch('/api/specialists/flux/research',{method:'POST',headers:{'Content-Type':'application/json'},signal:AbortSignal.timeout(55000),body:JSON.stringify(research)});const j=await r.json();if(!r.ok)throw new Error(j.error);setProspects(j.prospects);setResearchNote(j.error||`${j.prospects.length} businesses found with first-party source links. Review fit before adding a lead.`);}catch(e){setResearchNote(e instanceof Error&&e.name==='TimeoutError'?'Research took too long. Try a narrower brief.':e instanceof Error?e.message:'Research is unavailable.');}finally{setResearching(false);}
  }
  function consider(p:Prospect) {setEditing(null);setForm({...blankLead,name:p.name,company:p.name,source:p.sourceUrl,notes:`Public observation: ${p.fact}\nCommercial hypothesis: ${p.hypothesis}\nSource checked: ${p.retrievedAt}\nLocation: ${p.location}\nWebsite: ${p.website}`,nextAction:'Review business fit and contact permission'});setShowForm(true);setNotice('Review this proposed lead before adding it. No contact information or permission has been assumed.');document.getElementById('flux-pipeline')?.scrollIntoView({behavior:'auto',block:'start'});}
  const filtered=leads.filter(l=>`${l.name} ${l.company} ${l.owner}`.toLowerCase().includes(search.toLowerCase()));
  const today=new Date().toLocaleDateString('en-CA',{timeZone:'Pacific/Auckland'});
  return <div>
    <section id="flux-pipeline" className="sp-crm"><div className="sp-section-heading"><div><span className="sp-eyebrow">Customer relationships</span><h2>A pipeline with a next step.</h2></div><span className="sp-count">{mode==='private'?'Private account':'This tab only'}</span></div><div className="sp-actions"><button className="sp-primary" onClick={()=>{setEditing(null);setForm({...blankLead});setShowForm(true);}}><Plus size={16}/>Add lead</button><button className="sp-secondary" disabled={busy} onClick={()=>void openCrm()}>Open my CRM</button><button className="sp-text-button" disabled={mode==='private'||leads.length>0} onClick={()=>{setLeads(sampleLeads.map(x=>({...x})));setNotice('Fictional sample records loaded in this tab only.');}}>Try sample pipeline</button><button className="sp-text-button" disabled={!leads.length} onClick={()=>{downloadText('flux-pipeline.csv',leadsCsv(leads),'text/csv;charset=utf-8');setNotice('CSV downloaded. Check its contents before importing into your CRM.');}}><Download size={15}/>Export CSV</button></div>
    <p className="sp-muted">{mode==='private'?'Saved records belong to your signed-in account. External CRMs are separate connections.':'Build a session pipeline or sign in to save privately. This tab does not retain records after a reload.'}</p>
    {notice&&<p className="sp-notice" role="status">{notice}{authNeeded&&<> <Link href="/login?redirect=/agents/flux/app">Sign in to Flux →</Link></>}</p>}
    {showForm&&<form className="sp-paper sp-lead-form" onSubmit={saveLead}><div className="sp-section-heading"><h3>{editing?'Edit opportunity':'Review new lead'}</h3><button type="button" className="sp-text-button" onClick={()=>setShowForm(false)}>Cancel</button></div><div className="sp-form-grid">{([{key:'name',title:'Lead name *'},{key:'company',title:'Company'},{key:'email',title:'Email, if permissioned'},{key:'phone',title:'Phone, if permissioned'},{key:'owner',title:'Owner'},{key:'source',title:'Source or evidence URL'}] as const).map(f=><label key={f.key}>{f.title}<input required={f.key==='name'} type={f.key==='email'?'email':'text'} value={form[f.key]} maxLength={f.key==='source'?1500:160} onChange={e=>setForm(x=>({...x,[f.key]:e.target.value}))}/></label>)}<label>Value (NZD)<input type="number" min="0" max="99999999.99" step="0.01" value={form.value??''} onChange={e=>setForm(x=>({...x,value:e.target.value===''?null:Number(e.target.value)}))}/></label><label>Stage<select value={form.stage} onChange={e=>setForm(x=>({...x,stage:e.target.value as LeadInput['stage']}))}>{STAGES.map(s=><option value={s} key={s}>{label[s]}</option>)}</select></label><label>Next action<input value={form.nextAction} maxLength={500} onChange={e=>setForm(x=>({...x,nextAction:e.target.value}))}/></label><label>Follow-up date<input type="date" value={form.due} onChange={e=>setForm(x=>({...x,due:e.target.value}))}/></label></div><label>Contact permission<select value={form.permission} onChange={e=>setForm(x=>({...x,permission:e.target.value as LeadInput['permission']}))}><option value="not-confirmed">Not confirmed — review first</option><option value="requested-contact">Requested contact</option><option value="existing-relationship">Existing relationship — check scope</option><option value="do-not-contact">Do not contact</option></select></label><label>Evidence, activity and open questions<textarea rows={4} value={form.notes} maxLength={12000} onChange={e=>setForm(x=>({...x,notes:e.target.value}))}/></label><button className="sp-primary" disabled={busy} type="submit">{busy?'Saving…':mode==='private'?'Save private record':'Add to this session'}</button></form>}
    <label className="sp-search"><Search size={17}/><span className="sr-only">Search pipeline</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Find a company, owner or lead"/></label>
    <div className="sp-pipeline">{STAGES.map(stage=><section key={stage}><header><h3>{label[stage]}</h3><span>{filtered.filter(l=>l.stage===stage).length}</span></header><p className="sp-pipeline-value">{fmt(filtered.filter(l=>l.stage===stage).reduce((n,l)=>n+(l.value||0),0))}</p>{filtered.filter(l=>l.stage===stage).map(l=><article className="sp-lead" key={l.id}><button className="sp-lead-name" onClick={()=>{const {id,created_at: _created,updated_at: _updated,...input}=l;void _created;void _updated;setEditing(id);setForm(input);setShowForm(true);}}>{l.company||l.name}<ArrowUpRight size={15}/></button><p>{l.nextAction||'Choose the next useful action'}</p><span className="sp-lead-owner">{l.owner||'Owner not yet chosen'}</span>{l.due&&<time className={l.due<today?'sp-overdue':''} dateTime={l.due}>{l.due<today?'Review overdue · ':''}{l.due}</time>}<span className="sp-permission">{l.permission==='do-not-contact'?'Do not contact':l.permission==='not-confirmed'?'Contact permission unconfirmed':'Check permission before outreach'}</span><button className="sp-text-button" disabled={l.permission==='do-not-contact'} onClick={()=>prepare(`Prepare a reviewable next-step brief for this opportunity. Company: ${l.company||l.name}. Stage: ${l.stage}. Next action: ${l.nextAction||'undecided'}. Owner: ${l.owner||'unassigned'}. Contact permission: ${l.permission}. Notes: ${l.notes.slice(0,430)}. Source supplied by user, not independently read: ${l.source.slice(0,180)}. Do not invent facts or send anything.`)}>Prepare follow-up</button></article>)}{!filtered.some(l=>l.stage===stage)&&<div className="sp-pipeline-empty">Ready for a considered opportunity.</div>}</section>)}</div></section>
    <section className="sp-research"><div className="sp-section-heading"><div><span className="sp-eyebrow">Find a reason to have a conversation</span><h2>Research fit. Keep the evidence.</h2></div></div><form className="sp-paper" onSubmit={findProspects}><div className="sp-form-grid"><label>Market<input value={research.market} maxLength={100} required onChange={e=>setResearch(x=>({...x,market:e.target.value}))}/></label><label>Business type<input value={research.niche} maxLength={200} minLength={3} required placeholder="e.g. independent vehicle dealerships" onChange={e=>setResearch(x=>({...x,niche:e.target.value}))}/></label></div><label>Public signals to look for<textarea rows={3} maxLength={500} minLength={3} required value={research.signals} onChange={e=>setResearch(x=>({...x,signals:e.target.value}))} placeholder="e.g. offers online service bookings and has several locations"/></label><p className="sp-muted">This brief goes to live web search. Use business categories and public signals; leave private customer information out. Results are candidates for review, with no assumed buying intent or contact permission.</p><button className="sp-primary" disabled={researching} type="submit"><Search size={16}/>{researching?'Researching…':'Find relevant businesses'}</button></form><p className="sp-notice" role="status">{researchNote}</p><div className="sp-prospects">{prospects.map(p=><article className="sp-paper" key={p.website}><span className="sp-eyebrow">{p.location} · Needs review</span><h3>{p.name}</h3><p>{p.fact}</p><p className="sp-hypothesis"><strong>Possible fit:</strong> {p.hypothesis}</p><a href={p.sourceUrl} target="_blank" rel="noopener noreferrer">Business source<ArrowUpRight size={14}/></a><small>Retrieved {new Date(p.retrievedAt).toLocaleString('en-NZ')}</small><button className="sp-secondary" onClick={()=>consider(p)}>Review as a lead<Plus size={15}/></button></article>)}</div></section>
    <FluxConnections leads={leads}/>
  </div>;
}
