'use client';
import { useState } from 'react';
import { ArrowUpRight, Download } from 'lucide-react';
import { downloadText } from '@/lib/specialists/planning';

const workflows = [
  { name:'Hire & welcome', wait:'While the role and agreement are being reviewed', output:'Role and onboarding brief', items:['Confirm the role’s purpose and essential tasks','Identify hours, location and support needs','Agree who reviews the agreement and pay settings','Prepare a welcoming first week and check-in'] },
  { name:'Leave & pay', wait:'While payroll checks the record', output:'Payroll question brief', items:['Describe the question without employee identifiers','Collect the relevant dates and agreement terms securely','Check current official rules and the actual payroll record','Name the payroll reviewer and response date'] },
  { name:'People conversation', wait:'Before a manager meets the person', output:'Fair conversation plan', items:['Separate the concern from any conclusion','Prepare open questions and an opportunity to respond','Check what support or representation is appropriate','Agree a human review before any decision'] },
  { name:'Workplace change', wait:'While a proposal is being considered', output:'Consultation preparation brief', items:['Describe the proposed change and reasons','Record open questions and affected roles','Plan a genuine opportunity for feedback','Ask an employment specialist to review the process'] },
];
export function HrPlanner({ prepare }: { prepare:(text:string)=>void }) {
  const [flow,setFlow]=useState(0); const [role,setRole]=useState(''); const [facts,setFacts]=useState(''); const [reviewer,setReviewer]=useState(''); const [due,setDue]=useState(''); const [checks,setChecks]=useState<Record<string,boolean>>({}); const [notice,setNotice]=useState('');
  const w=workflows[flow];
  const brief=()=>`${w.output.toUpperCase()} — DRAFT\nPrepared ${new Date().toLocaleDateString('en-NZ')}\nContext: ${w.wait}\nRole: ${role || 'Not entered'}\nConfirmed facts: ${facts || 'Not entered'}\nProposed reviewer: ${reviewer || 'Not yet named'}\nTarget review date (chosen, not a legal deadline): ${due || 'Not selected'}\n\n${w.items.map((item,i)=>`${checks[`${flow}-${i}`]?'[x]':'[ ]'} ${item}`).join('\n')}\n\nNo employment decision has been made or communicated. Notes and checklist completion are user-entered, not an independent finding. Check current sources and get qualified advice for high-stakes matters.\n`;
  return <div><div className="sp-section-heading"><div><span className="sp-eyebrow">A useful next step for your people</span><h2>Prepare the work. Keep the human.</h2></div></div><div className="sp-workflow-tabs" role="group" aria-label="HR workflows">{workflows.map((x,i)=><button aria-pressed={flow===i} key={x.name} onClick={()=>setFlow(i)}>{x.name}</button>)}</div><section className="sp-paper"><span className="sp-eyebrow">{w.wait}</span><h3>{w.output}</h3><div className="sp-checklist">{w.items.map((x,i)=><label key={x}><input type="checkbox" checked={!!checks[`${flow}-${i}`]} onChange={e=>setChecks(c=>({...c,[`${flow}-${i}`]:e.target.checked}))}/><span>{x}</span></label>)}</div><div className="sp-form-grid"><label>Role or team<input value={role} maxLength={120} onChange={e=>setRole(e.target.value)} placeholder="e.g. customer service team"/></label><label>Review with<input value={reviewer} maxLength={120} onChange={e=>setReviewer(e.target.value)} placeholder="HR lead or employment specialist"/></label></div><label>What is confirmed, and what still needs checking?<textarea rows={4} value={facts} maxLength={400} onChange={e=>setFacts(e.target.value)} placeholder="Use general details. Leave employee names and sensitive records out."/></label><label>Target review date<input type="date" value={due} onChange={e=>setDue(e.target.value)}/></label><p className="sp-muted">Notes stay in this tab until you choose to use them in chat or download them. The date you choose is a planning date.</p><div className="sp-actions"><button className="sp-primary" onClick={()=>prepare(`Prepare a ${w.output}. Role: ${role || 'not specified'}. Facts and open questions: ${facts || 'not specified'}. Proposed reviewer: ${reviewer || 'not chosen'}. Target review date, not a statutory deadline: ${due || 'not chosen'}. Keep this a fair process, with no predetermined outcome. Verify current legal and pay rules before using them.`)}>Prepare with Aroha<ArrowUpRight size={16}/></button><button className="sp-secondary" onClick={()=>{downloadText('aroha-hr-brief.txt',brief());setNotice('Brief downloaded for your review.');}}><Download size={16}/>Download brief</button></div>{notice&&<p role="status">{notice}</p>}</section><div className="sp-principles"><article><span>01</span><h3>Facts before findings.</h3><p>Keep what happened separate from what it might mean. Hear the person’s perspective.</p></article><article><span>02</span><h3>Current sources.</h3><p>Pay and legal answers use official page checks, with gaps and effective dates visible.</p></article><article><span>03</span><h3>A person decides.</h3><p>Aroha prepares the brief. Your HR lead or employment adviser reviews the next step.</p></article></div></div>;
}
