'use client';
import { useState } from 'react';
import { ArrowUpRight, Check, Download } from 'lucide-react';
import { villageCosts, downloadText } from '@/lib/specialists/planning';

const steps = [
  { title: 'Listen first', question: 'What would they like to keep in their life?', tasks: ['Ask whether they want to explore a move', 'Include staying at home as an option', 'Agree who they want involved'] },
  { title: 'Understand the options', question: 'Independence, support, or an assessed care need?', tasks: ['Separate village living from residential care', 'Ask the appropriate care team about an assessment if needed', 'Record location and everyday-life priorities'] },
  { title: 'Visit & compare', question: 'How does each place feel to them?', tasks: ['Visit at their pace and speak to residents', 'Ask about services, transport and pets', 'Get written answers on availability and future care'] },
  { title: 'Understand the costs', question: 'What is paid now, during the stay, and on leaving?', tasks: ['Collect the entry and ongoing fee schedule', 'Check DMF, other deductions and repayment timing', 'Ask a qualified adviser about affordability and funding'] },
  { title: 'Independent review', question: 'What needs a lawyer or qualified adviser?', tasks: ['Take the actual ORA and disclosure documents to an independent lawyer', 'Check consent and any attorney authority', 'Confirm the applicable cancellation and exit terms'] },
  { title: 'Move & settle', question: 'What makes this feel like their home?', tasks: ['Agree a move plan and key contacts', 'Plan familiar routines and visits', 'Check in after the move and record unresolved questions'] },
];
const money = (n: number) => new Intl.NumberFormat('en-NZ', { style: 'currency', currency: 'NZD', maximumFractionDigits: 0 }).format(n);
export function RetirementPlanner({ prepare }: { prepare: (text: string) => void }) {
  const [step, setStep] = useState(0); const [done, setDone] = useState<string[]>([]);
  const [person, setPerson] = useState('parent'); const [place, setPlace] = useState(''); const [wishes, setWishes] = useState('');
  const [reviewer, setReviewer] = useState(''); const [consent, setConsent] = useState(false);
  const [names, setNames] = useState(['Option A', 'Option B']);
  const [costs, setCosts] = useState([{ entry: '', weekly: '', years: '', dmf: '', other: '' }, { entry: '', weekly: '', years: '', dmf: '', other: '' }]);
  const [message, setMessage] = useState('');
  const plan = () => `FAMILY PREPARATION PLAN — DRAFT\nPrepared ${new Date().toLocaleDateString('en-NZ')}\nSupporting: ${person}\nArea: ${place || 'Not selected'}\nWhat matters to them: ${wishes || 'Ask them first'}\nReview with: ${reviewer || 'Not yet chosen'}\nCurrent focus: ${steps[step].title}\n\n${steps.map((s,i) => `${i+1}. ${s.title}\n${s.tasks.map((t,j) => `${done.includes(`${i}-${j}`) ? '[x]' : '[ ]'} ${t}`).join('\n')}`).join('\n\n')}\n\nComparison notes (user-entered; not provider quotes):\n${costs.map((c,i) => `${names[i]}: ${JSON.stringify(c)}`).join('\n')}\n\nThe older person controls whether to proceed and who is involved. A checked item is your record, not evidence of legal or care approval. No invitation, referral or booking has been sent.\n`;
  return <div className="sp-planner">
    <div className="sp-section-heading"><div><span className="sp-eyebrow">The family journey</span><h2>One step at a time.</h2></div><span className="sp-count">{done.length} / 18 noted</span></div>
    <div className="sp-journey" role="group" aria-label="Family journey stages">{steps.map((s,i) => <button key={s.title} type="button" aria-pressed={step === i} aria-controls="retirement-step" id={`retirement-tab-${i}`} onClick={() => setStep(i)}><span>0{i+1}</span>{s.title}</button>)}</div>
    <section className="sp-paper" id="retirement-step" aria-labelledby={`retirement-tab-${step}`}><span className="sp-eyebrow">0{step+1} · {steps[step].title}</span><h3>{steps[step].question}</h3><div className="sp-checklist">{steps[step].tasks.map((t,j) => <label key={t}><input type="checkbox" checked={done.includes(`${step}-${j}`)} onChange={e => setDone(d => e.target.checked ? [...d,`${step}-${j}`] : d.filter(x => x !== `${step}-${j}`))} /><span>{t}</span></label>)}</div><button className="sp-text-button" onClick={() => prepare(`Help our family with this step: ${steps[step].title}. ${steps[step].question} Prepare a useful, respectful conversation and questions for the right reviewer. Check official sources before giving legal or financial rules.`)}>Talk this step through<ArrowUpRight size={16}/></button></section>
    <section className="sp-paper"><span className="sp-eyebrow">Their life comes first</span><h3>A brief in their words.</h3><p className="sp-muted">Keep this general. These notes stay in this tab until you choose to use them in chat or download them.</p><div className="sp-form-grid"><label>I’m supporting<select value={person} onChange={e => setPerson(e.target.value)}>{['myself','parent','relative','friend','partner'].map(x => <option key={x}>{x}</option>)}</select></label><label>Preferred area<input value={place} maxLength={100} onChange={e => setPlace(e.target.value)} placeholder="e.g. close to friends in Hamilton"/></label></div><label>What matters most to them?<textarea value={wishes} maxLength={400} onChange={e => setWishes(e.target.value)} placeholder="Familiar routines, whānau nearby, a garden…" rows={3}/></label><label>Who will review the next step?<input value={reviewer} maxLength={100} onChange={e => setReviewer(e.target.value)} placeholder="A chosen support person or adviser role"/></label><label className="sp-consent"><input type="checkbox" checked={consent} onChange={e => setConsent(e.target.checked)}/>I have included only general details they agree to use in this conversation.</label><div className="sp-actions"><button className="sp-primary" disabled={!consent} onClick={() => prepare(`Help us prepare a family plan. Supporting: ${person}. Area: ${place || 'undecided'}. Their priorities: ${wishes || 'not yet discussed'}. Proposed reviewer: ${reviewer || 'not yet chosen'}. Current stage: ${steps[step].title}. Keep their choice central, include a skip path, and identify questions for independent advisers. These notes are shared with their agreement.`)}>Use brief in chat<ArrowUpRight size={16}/></button><button className="sp-secondary" onClick={() => { downloadText('retirement-family-plan.txt', plan()); setMessage('Plan downloaded. Review it before sharing.'); }}><Download size={16}/>Download plan</button></div>{message && <p role="status" className="sp-muted">{message}</p>}</section>
    <section className="sp-costs"><div className="sp-section-heading"><div><span className="sp-eyebrow">Put the written quotes side by side</span><h2>Understand the shape of the costs.</h2></div></div><p className="sp-muted">Enter the amounts from each village’s documents. This is arithmetic on your inputs, with flat weekly fees and a 52-week year. It excludes inflation, opportunity cost, tax, resale delay and any unentered exit deductions. It does not determine affordability or subsidy eligibility.</p><div className="sp-compare">{costs.map((c,i) => {
      const result = Object.values(c).every(x => x.trim() !== '') ? villageCosts(Object.fromEntries(Object.entries(c).map(([k,v]) => [k,Number(v)])) as Parameters<typeof villageCosts>[0]) : null;
      return <div className="sp-paper" key={i}><label className="sp-option-name">Comparison label<input value={names[i]} maxLength={80} onChange={e => setNames(n => n.map((x,j) => j === i ? e.target.value : x))}/></label>{([{ key:'entry', label:'Entry contribution (NZD)' },{key:'weekly',label:'Weekly fees (NZD)'},{key:'years',label:'Years in this illustration'},{key:'dmf',label:'DMF applied for that stay (%)'},{key:'other',label:'Other costs over that stay (NZD)'}] as const).map(f => <label key={f.key}>{f.label}<input type="number" aria-label={`${names[i]} ${f.label}`} min="0" max={f.key === 'dmf' ? 100 : f.key === 'years' ? 50 : undefined} step="any" value={c[f.key]} onChange={e => setCosts(all => all.map((x,j) => j === i ? {...x,[f.key]:e.target.value} : x))}/></label>)}<div className="sp-cost-result">{result ? <><span>Illustrative cost over the entered stay</span><strong>{money(result.illustrativeCost)}</strong><p>DMF {money(result.managementFee)} · ongoing {money(result.runningFees)} · other {money(Number(c.other))}</p><p>Entry capital less entered DMF: {money(result.capitalBeforeOtherExitAdjustments)}, before other exit adjustments. Repayment timing is unconfirmed.</p></> : <p>Complete every field, including 0 where appropriate, to compare.</p>}</div></div>;
    })}</div><button className="sp-text-button" onClick={() => prepare(`Help us check a retirement village cost comparison. User-entered figures only, not verified quotes: ${costs.map((c,i) => `${names[i]} ${JSON.stringify(c)}`).join('; ')}. Explain missing contract details and questions for an independent lawyer or financial adviser. Do not judge affordability or assume repayment timing.`)}>Check the questions behind these numbers<ArrowUpRight size={16}/></button></section>
    <p className="sp-footnote"><Check size={14}/>Your pace. Your chosen people. You can leave this plan unfinished.</p>
  </div>;
}
