'use client';
import Link from 'next/link';
import { useState } from 'react';
import { ArrowDown, ArrowUpRight, BookOpen, Check, RefreshCw } from 'lucide-react';
import { VERTICALS } from '@/lib/verticals/config';
import { OFFICIAL_SOURCES, type SpecialistSlug, type SourceDefinition } from '@/lib/specialists/sources';
import type { SourceCheck } from '@/lib/specialists/live-sources';
import { VerticalPhone } from '@/components/verticals/VerticalPhone';
import { VerticalAppTools } from '@/components/verticals/VerticalAppTools';
import { RetirementPlanner } from './RetirementPlanner';
import { HrPlanner } from './HrPlanner';
import { FluxWorkspace } from './FluxWorkspace';
import './specialists.css';

function SourceDesk({slug}:{slug:SpecialistSlug}) {
  const [topic,setTopic]=useState(slug==='retirement'?'village contract legal rights':'pay wage salary kiwisaver');const [checks,setChecks]=useState<SourceCheck[]>([]);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  async function check(){setBusy(true);setError('');try{const r=await fetch(`/api/specialists/${slug}/sources?topic=${encodeURIComponent(topic)}`,{cache:'no-store',signal:AbortSignal.timeout(20000)});if(!r.ok)throw new Error();const data=await r.json();setChecks(data.checks);}catch{setError('The source check could not finish. No figures have been substituted.');}finally{setBusy(false);}}
  const catalogue=OFFICIAL_SOURCES.filter(s=>s.agents.includes(slug));
  const rows: (SourceCheck | (SourceDefinition & {status: 'unchecked'}))[] = checks.length ? checks : catalogue.map(s=>({...s,status:'unchecked' as const}));
  return <section className="sp-source-desk" id="sources"><div className="sp-section-heading"><div><span className="sp-eyebrow">Evidence you can open</span><h2>Check the source.</h2></div><BookOpen size={26}/></div><p className="sp-muted">The agent reads relevant official pages for every reply. A successful page check confirms retrieval, not individual eligibility or professional advice. You can inspect the same source catalogue here.</p><div className="sp-source-controls"><label>Topic<select value={topic} onChange={e=>setTopic(e.target.value)}>{(slug==='retirement'?[['village contract legal rights','Village contracts & rights'],['care subsidy asset threshold income','Care funding & thresholds'],['pension super allowance rates','NZ Super & allowances'],['epa attorney consent capacity','Consent & attorney authority'],['statistics figures sector residents','Sector evidence & figures']]:[['pay wage salary kiwisaver','Pay & KiwiSaver'],['agreement hire contract law','Hiring & agreements'],['leave holiday sick pay','Leave & holidays'],['disciplinary restructure grievance law','People processes']]).map(([value,title])=><option value={value} key={value}>{title}</option>)}</select></label><button className="sp-primary" onClick={()=>void check()} disabled={busy}><RefreshCw size={16} className={busy?'sp-spin':''}/>{busy?'Checking official pages…':'Check now'}</button></div>{error&&<p role="alert" className="sp-notice">{error}</p>}<div className="sp-sources">{rows.map(s=><article key={s.id}><div><span className="sp-eyebrow">{s.publisher} · {s.kind}</span><a href={s.url} target="_blank" rel="noopener noreferrer">{s.title}<ArrowUpRight size={15}/></a></div>{s.status!=='unchecked'?s.status==='retrieved'?<p className="sp-source-status"><Check size={13}/>Read {new Date(s.retrievedAt).toLocaleString('en-NZ')}{s.sourceDate&&<span>{s.sourceDate}</span>}<small>Source fingerprint {s.hash.slice(0,12)}</small></p>:<p className="sp-source-status">Could not verify this page now.</p>:<span className="sp-source-status">Official link · not checked in this panel yet</span>}</article>)}</div></section>;
}

export function SpecialistWorkspace({slug}:{slug:SpecialistSlug}) {
  const v=VERTICALS[slug]; const [prompt,setPrompt]=useState<{text:string;id:number}>();
  function prepare(text:string){setPrompt({text:text.slice(0,1000),id:Date.now()});document.getElementById('specialist-chat')?.scrollIntoView({behavior:'auto',block:'start'});}
  return <div className={`sp-root sp-${slug}`}><a className="sp-skip" href="#workspace">Skip to the workspace</a><header className="sp-header"><Link className="sp-wordmark" href="/">assembl<span>{v.name}</span></Link><div className="sp-header-actions"><Link className="sp-text-button" href="/agents">All agents</Link><VerticalAppTools slug={slug} app/></div></header><main><section className="sp-hero"><div className="sp-hero-copy"><span className="sp-eyebrow">{v.field}</span><h1>{v.title}</h1><p>{v.description}</p><a className="sp-primary" href="#workspace">{slug==='retirement'?'Start your family plan':slug==='flux'?'Open the sales workspace':'Prepare the next people step'}<ArrowDown size={17}/></a><div className="sp-hero-proof"><span><Check size={14}/>You choose the next step</span><span><Check size={14}/>{slug==='flux'?'Evidence stays with the lead':'Official sources, checked when needed'}</span><span><Check size={14}/>A person reviews the draft</span></div><div className="sp-folio" aria-label="Preparation journey"><div className="sp-folio-sheet"><span>01 / What matters</span><strong>{slug==='retirement'?'Their wishes.':slug==='flux'?'A real customer need.':'The person and the facts.'}</strong><i/><i/></div><div className="sp-folio-sheet"><span>02 / What we know</span><strong>{slug==='flux'?'The evidence.':'Sources & questions.'}</strong><i/><i/></div><div className="sp-folio-sheet"><span>03 / What comes next</span><strong>{slug==='retirement'?'A family plan.':slug==='flux'?'A considered follow-up.':'A fair next step.'}</strong><div className="sp-folio-stamp"><Check size={12}/>Prepared for your review</div></div></div></div><div className="sp-hero-phone" id="specialist-chat"><VerticalPhone slug={slug} preparedPrompt={prompt}/><p className="sp-phone-caption">A live conversation. Drafts for your review.</p></div></section><section className="sp-workspace" id="workspace">{slug==='retirement'?<RetirementPlanner prepare={prepare}/>:slug==='flux'?<FluxWorkspace prepare={prepare}/>:<HrPlanner prepare={prepare}/>}</section>{slug!=='flux'&&<SourceDesk slug={slug}/>}<section className="sp-related"><span className="sp-eyebrow">Explore the other specialists</span><nav aria-label="Specialist apps">{(['retirement','flux','aroha'] as const).filter(s=>s!==slug).map(s=><a href={`/agents/${s}/app`} key={s}>{VERTICALS[s].name}<ArrowUpRight size={18}/></a>)}</nav></section></main><footer className="sp-footer"><Link href="/">assembl</Link><p>Mahi that earns its proof.</p><span>Prepare · Review · Choose</span></footer></div>;
}
