/** Regenerate the extension from the exact same companion shipped by /api/do/widget. */
import { writeFileSync } from 'node:fs';
import { Script } from 'node:vm';
import { DO_DISTRIBUTION_ORIGIN, doWidgetScript } from '../apps/do/shared/distribution';

const source = doWidgetScript(DO_DISTRIBUTION_ORIGIN);
new Script(source); // Catch syntax errors before packaging a browser extension.
writeFileSync('apps/do/extension/floating.js', "'use strict';\n// Generated by scripts/generate-do-companion.ts.\n" + source + '\n');
console.log('Shared DO companion regenerated.');
