"use client";
import type {Hub} from "@/components/client-hub-migration/original/lib/pursuit-hub";
import {currentArtDirection,directionNames,artDirectionNotes} from "@/components/client-hub-migration/original/lib/creative-direction";
import {hubVisualBrief} from "@/components/client-hub-migration/original/lib/hub-visuals";

export default function ArtDirection({hub,onChange}:{hub:Hub;onChange:(hub:Hub)=>void}){
 const a=currentArtDirection(hub),chosen=a?.directions.find(d=>d.id===a.selected);
 function editFrame(index:number,field:"visual"|"meaning",value:string){if(!a||!hub.engine)return;onChange({...hub,engine:{...hub.engine,concepts:hub.engine.concepts.map(c=>c.id===hub.engine?.selected?{...c,artDirection:{...a,storyboard:a.storyboard.map((s,i)=>i===index?{...s,[field]:value}:s)}}:c)}});}
 function download(){const text=hubVisualBrief(hub)+(a?"\n\nDIRECTIONS CONSIDERED\n"+a.directions.map(d=>`${directionNames[d.id]}\n${d.metaphor}\nFrame: ${d.composition}\nMotion: ${d.motion}\nType: ${d.typography}`).join("\n\n"):"");const u=URL.createObjectURL(new Blob([text],{type:"text/plain"})),link=document.createElement("a");link.href=u;link.download="assembl-client-art-direction.txt";link.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
 return <section className="cs-direction" aria-label="Client art direction"><div className="cs-direction-heading"><div><span className="cs-eyebrow">THE IDEA BEHIND THE IMAGE</span><h3>{chosen?chosen.metaphor:"Many parts. One useful outcome."}</h3></div><button className="cs-secondary" onClick={download}>Download production brief ↗</button></div>
 {a&&chosen?<><p>{a.reason}</p><div className="cs-direction-meta"><span>{directionNames[a.selected]}</span><span>Proposed art direction · reviewable draft</span></div>{artDirectionNotes(a).map(note=><p className="cs-callout" key={note}>Brief check: {note}</p>)}<ol className="cs-storyboard">{a.storyboard.map((s,i)=><li key={i}><span>0{i+1} / {['GATHER','COORDINATE','REVEAL'][i]}</span><h4>{s.visual}</h4><p>{s.meaning}</p></li>)}</ol><details><summary>Edit the storyboard</summary>{a.storyboard.map((s,i)=><div key={i}><label>Frame {i+1} · what moves<textarea rows={3} maxLength={420} value={s.visual} onChange={e=>editFrame(i,"visual",e.target.value)}/></label><label>Frame {i+1} · what it means<textarea rows={2} maxLength={420} value={s.meaning} onChange={e=>editFrame(i,"meaning",e.target.value)}/></label></div>)}<p className="cs-small">Save the concept to keep these changes.</p></details><details><summary>Three directions considered</summary>{a.directions.map(d=><article className="cs-direction-alternative" key={d.id}><h4>{directionNames[d.id]}{d.id===a.selected?" · selected":""}</h4><p>{d.metaphor}</p><dl><dt>Frame</dt><dd>{d.composition}</dd><dt>Motion</dt><dd>{d.motion}</dd><dt>Type</dt><dd>{d.typography}</dd></dl></article>)}</details><p className="cs-small">This storyboard guides the next images and film. Review the actual media above before sharing; a production brief does not generate footage by itself.</p></>:<><p>Form the experience with the agent to receive three distinct creative directions, a chosen visual metaphor and a motion storyboard for {hub.buyer}.</p><details><summary>Current client visual brief</summary><p>{hubVisualBrief(hub)}</p></details></>}
 </section>;
}
