"use client";
import ContextVisual from "@/components/client-hub-migration/ContextVisual";
import {useLayoutEffect,useRef,useState,type PointerEvent,type KeyboardEvent} from "react";
import {ArrowUpRight,Check,Grip,Layers3,Maximize2,Minus,Plus,RotateCcw,ShieldCheck,Sparkles,X} from "lucide-react";
import {boardNodeIds,boardPositions,newIdeaBoard,selectBoardIdea,type BoardNodeId,type BoardIdea,type BoardSource,type IdeaBoardState} from "@/components/client-hub-migration/original/lib/idea-board";
import "./idea-board.css";

type Props={ideas:BoardIdea[];sources:BoardSource[];value?:IdeaBoardState;onChange:(state:IdeaBoardState)=>void;onDevelop:(id:string)=>void;onExplore?:(id:string)=>void;busy?:boolean;actionLabel?:string;localPreview?:boolean;liveHref?:string;onFresh?:()=>void};
const labels:Record<BoardNodeId,string>={idea:"The idea",moment:"Customer moment",agent:"Agent prepares",review:"Human handoff",outcome:"What changes",evidence:"Source evidence"};
export default function IdeaBoard({ideas,sources,value,onChange,onDevelop,onExplore,busy=false,actionLabel="Form this experience",localPreview=false,liveHref="/hub",onFresh}:Props){
 const idea=ideas.find(i=>i.id===value?.ideaId)||ideas[0];
 const state=idea?selectBoardIdea(value,idea.id,sources.map(s=>s.id)):newIdeaBoard("");
 const [tab,setTab]=useState<"ideas"|"sources">("ideas"),[zoom,setZoom]=useState(0.8),[inspecting,setInspecting]=useState<BoardNodeId>(),[announcement,setAnnouncement]=useState(""),[dragged,setDragged]=useState(false);
 const plane=useRef<HTMLDivElement>(null),scroll=useRef<HTMLDivElement>(null),drag=useRef<{id:BoardNodeId;pointerId:number;clientX:number;clientY:number;x:number;y:number}|undefined>(undefined),latest=useRef(state);useLayoutEffect(()=>{latest.current=state;},[state]);
 function choose(id:string){onChange(selectBoardIdea(value,id,sources.map(s=>s.id)));setAnnouncement("Idea placed on the board. Its customer moment, agent task and handoff are connected.");setInspecting(undefined);}
 function move(id:BoardNodeId,x:number,y:number){const old=latest.current;const next={...old,nodes:old.nodes.map(n=>n.id===id?{...n,x:Math.max(0,Math.min(900,x)),y:Math.max(0,Math.min(650,y))}:n)};latest.current=next;onChange(next);}
 function start(event:PointerEvent<HTMLButtonElement>,id:BoardNodeId){if(busy||event.button!==0)return;const node=state.nodes.find(n=>n.id===id)||{...boardPositions[id]};event.currentTarget.setPointerCapture(event.pointerId);drag.current={id,pointerId:event.pointerId,clientX:event.clientX,clientY:event.clientY,x:node.x,y:node.y};setDragged(true);}
 function moving(event:PointerEvent<HTMLButtonElement>){const d=drag.current;if(!d||d.pointerId!==event.pointerId)return;move(d.id,d.x+(event.clientX-d.clientX)/zoom,d.y+(event.clientY-d.clientY)/zoom);}
 function finish(){if(drag.current)setAnnouncement(`${labels[drag.current.id]} moved. Save the concept to keep this arrangement.`);drag.current=undefined;setDragged(false);}
 function keyMove(event:KeyboardEvent,id:BoardNodeId){const delta=event.shiftKey?50:10,directions:Record<string,[number,number]>={ArrowLeft:[-delta,0],ArrowRight:[delta,0],ArrowUp:[0,-delta],ArrowDown:[0,delta]};const d=directions[event.key];if(!d||busy)return;event.preventDefault();const n=state.nodes.find(n=>n.id===id)!;move(id,n.x+d[0],n.y+d[1]);setAnnouncement(`${labels[id]} moved.`);}
 function pin(id:string){const old=latest.current;onChange({...old,sourceIds:old.sourceIds.includes(id)?old.sourceIds.filter(x=>x!==id):[...old.sourceIds,id].slice(0,12)});}
 const checked=sources.filter(s=>state.sourceIds.includes(s.id)),nodeText:Record<BoardNodeId,string>={idea:idea?.promise||"",moment:idea?.moment||"",agent:idea?.agent||"",review:idea?.review||"",outcome:idea?.outcome||"",evidence:checked.length?checked.map(s=>s.title).join(" · "):"Add a source from the tray. Ideas can begin as hypotheses; evidence gives them a firmer basis."};
 const pos=(id:BoardNodeId)=>state.nodes.find(n=>n.id===id)||{id,...boardPositions[id],note:""};
 return <div className={`ib ${busy?"ib-forming":""} ${dragged?"ib-dragging":""}`}>
  <div className="ib-top"><div><span className="ib-label">THE IDEA BOARD</span><h2>Move the parts.<br/><span>Make the possibility.</span></h2></div><p>Pick an idea, arrange its parts and add your direction. The agent turns your board into a customer experience.</p></div>
  <div className="ib-shell">
   <aside className="ib-tray" aria-label="Idea and evidence tray"><div className="ib-tabs"><button aria-pressed={tab==="ideas"} onClick={()=>setTab("ideas")}>Ideas <span>{ideas.length}</span></button><button aria-pressed={tab==="sources"} onClick={()=>setTab("sources")}>Sources <span>{sources.length}</span></button></div>
    <div className="ib-tray-scroll">{tab==="ideas"?ideas.map((item,i)=><article className={`ib-pick ${idea?.id===item.id?"ib-picked":""}`} key={item.id} draggable={!busy} onDragStart={event=>{event.dataTransfer.setData("application/x-assembl-idea",item.id);event.dataTransfer.effectAllowed="copy";}}><div className="ib-pick-image"><ContextVisual src={item.image} alt="Illustrative concept scene" compact/><span>0{i+1}</span></div><small>{item.origin}</small><h3>{item.title}</h3><p>{item.promise}</p><button disabled={busy} onClick={()=>choose(item.id)}>{idea?.id===item.id?<><Check size={15}/>On the board</>:<><Plus size={15}/>Place on board</>}</button>{item.blocked&&<span className="ib-hold">Review needed</span>}</article>):<>{sources.map(s=><article className="ib-source" key={s.id} draggable={!busy} onDragStart={event=>event.dataTransfer.setData("application/x-assembl-source",s.id)}><small>{s.checked?"Checked source":"Needs verification"}</small><h3>{s.title}</h3><p>{s.claim}</p><a href={s.url} target="_blank" rel="noreferrer">Read source ↗</a><button disabled={busy} onClick={()=>pin(s.id)}>{state.sourceIds.includes(s.id)?<><Check size={14}/>Pinned · remove</>:<><Plus size={14}/>Pin to board</>}</button></article>)}{!sources.length&&<p className="ib-tray-empty">No source extracts yet. You can explore a proposed idea, then use Radar to find evidence.</p>}</>}
    </div>{onFresh&&<button className="ib-fresh" disabled={busy} onClick={onFresh}><Sparkles size={16}/>Ask for fresh ideas</button>}
   </aside>
   <div className="ib-workspace"><div className="ib-toolbar"><span><Layers3 size={16}/>{idea?"Connected concept":"Your canvas"}</span><div><button title="Zoom out" aria-label="Zoom board out" onClick={()=>setZoom(v=>Math.max(.45,v-.1))}><Minus size={16}/></button><span>{Math.round(zoom*100)}%</span><button title="Zoom in" aria-label="Zoom board in" onClick={()=>setZoom(v=>Math.min(1.25,v+.1))}><Plus size={16}/></button><button aria-label="Fit board in view" onClick={()=>{setZoom(Math.max(.35,Math.min(1,(scroll.current?.clientWidth||920)/1175)));if(scroll.current){scroll.current.scrollTop=0;scroll.current.scrollLeft=0;}}}><Maximize2 size={16}/></button><button disabled={busy} onClick={()=>{onChange({...state,nodes:state.nodes.map(n=>({...n,...boardPositions[n.id]}))});setAnnouncement("Board arranged.");}}><RotateCcw size={14}/><span>Arrange</span></button></div></div>
    <div className="ib-scroll" ref={scroll} onDragOver={event=>{event.preventDefault();event.dataTransfer.dropEffect="copy";}} onDrop={event=>{event.preventDefault();if(busy)return;const id=event.dataTransfer.getData("application/x-assembl-idea"),source=event.dataTransfer.getData("application/x-assembl-source");if(ideas.some(i=>i.id===id))choose(id);else if(sources.some(s=>s.id===source)&&!state.sourceIds.includes(source))pin(source);}}>
     <div className="ib-size" style={{width:1175*zoom,height:990*zoom}}><div ref={plane} className="ib-plane" style={{transform:`scale(${zoom})`}} aria-label="Visual concept board">
      <svg className="ib-wires" viewBox="0 0 1175 990" aria-hidden="true">{boardNodeIds.filter(id=>id!=="idea").map(id=>{const from=pos("idea"),to=pos(id);return <path key={id} d={`M${from.x+125},${from.y+90} C${from.x+125},${to.y+90} ${to.x+125},${from.y+90} ${to.x+125},${to.y+90}`}/>;})}</svg>
      {idea?boardNodeIds.map((node,i)=><article key={node} className={`ib-node ib-node-${node}`} style={{left:pos(node).x,top:pos(node).y}}><button className="ib-handle" aria-label={`Move ${labels[node]}. Use arrow keys to move.`} disabled={busy} onPointerDown={event=>start(event,node)} onPointerMove={moving} onPointerUp={finish} onPointerCancel={finish} onLostPointerCapture={finish} onKeyDown={event=>keyMove(event,node)}><span>0{i+1} / {labels[node]}</span><Grip size={17}/></button>{node==="idea"&&<ContextVisual className="ib-node-image" src={idea.image} alt="Selected idea visual" compact/>}<button className="ib-node-body" onClick={()=>setInspecting(node)}><h3>{node==="idea"?idea.title:labels[node]}</h3><p>{pos(node).note||nodeText[node]}</p><span>{node==="evidence"?<><ShieldCheck size={13}/>{checked.length} sources on this board</>:"Add direction ↗"}</span></button></article>):<div className="ib-empty"><Sparkles size={32}/><h3>Your next idea starts here.</h3><p>Develop ideas from a brief, or bring an opportunity in from Radar.</p></div>}
     </div></div>
    </div>
    <div className="ib-bottom"><p><Grip size={14}/>Drag the handles or use their arrow keys. Click a part to shape it.</p><span>{checked.filter(s=>s.checked).length} checked sources</span></div>
   </div>
  </div>
  {inspecting&&idea&&<section className="ib-inspector" aria-label={`${labels[inspecting]} direction`}><div><span className="ib-label">SHAPE THIS PART</span><h3>{labels[inspecting]}</h3><p>{nodeText[inspecting]}</p>{inspecting==="evidence"&&<div className="ib-inspector-sources">{checked.map(s=><a key={s.id} href={s.url} target="_blank" rel="noreferrer">{s.checked?"Checked":"To verify"} · {s.title} ↗</a>)}<button onClick={()=>setTab("sources")}>Choose evidence from the tray</button></div>}</div><label>Your direction for the agent<textarea aria-label="Your direction for the agent" disabled={busy} rows={4} maxLength={1400} placeholder="What should this part include or change?" value={pos(inspecting).note} onChange={event=>onChange({...state,nodes:state.nodes.map(n=>n.id===inspecting?{...n,note:event.target.value}:n)})}/><small>Saved with this concept. These instructions guide the build; they do not become verified facts.</small></label><button aria-label="Close board direction" onClick={()=>setInspecting(undefined)}><X size={18}/></button></section>}
  <div className="ib-form"><div><span className="ib-label">{busy?"AGENT AT WORK":"READY TO TAKE SHAPE"}</span><h3>{busy?"Your next experience is being assembled.":idea?.title||"Choose an idea to begin."}</h3><p>{idea?.blocked||"The selected idea and your direction become an interactive draft, with a customer choice and a human review step."}</p></div><div>{localPreview?<a className="ib-form-button" href={liveHref}>Open the live agent <ArrowUpRight size={17}/></a>:<button className="ib-form-button" disabled={busy||!idea||!!idea.blocked} onClick={()=>idea&&onDevelop(idea.id)}><Sparkles size={17}/>{busy?"Forming…":actionLabel}<ArrowUpRight size={17}/></button>}{onExplore&&idea&&<button className="ib-sample" disabled={busy} onClick={()=>onExplore(idea.id)}>Open {idea.origin==="worked example"?"worked example":"existing interaction"}</button>}</div></div>
  <p className="ib-announcement" role="status">{announcement}</p>
 </div>;
}
