"use client";
import {useCommittedCallback} from "@/lib/client-hub-migration/use-committed-callback";
import { migrationFetch as fetch } from "@/lib/client-hub-migration/review-adapter";
import {useEffect,useState} from "react";
import {FileText,Plus,Upload} from "lucide-react";
import {blankKnowledge,knowledgeInScope,type Knowledge,type KnowledgeRecord} from "@/components/client-hub-migration/original/lib/company-knowledge";
import {extractDocument} from "@/components/client-hub-migration/original/lib/document-text";
import {companyIdentity} from "@/components/client-hub-migration/original/lib/workspace-identity";
const localKey=(company:string)=>`assembl-knowledge-preview:${companyIdentity(company)}`;
async function read(r:Response){const d=await r.json() as {error?:string;items:KnowledgeRecord[];item:KnowledgeRecord;filename:string;fileKey:string;fileType:string};if(!r.ok)throw Error(d.error||"This document could not be saved.");return d;}
export default function KnowledgeLibrary({company,buyer,localPreview=false,seed="",onUsed}:{company:string;buyer:string;localPreview?:boolean;seed?:string;onUsed?:()=>void}){
 const [items,setItems]=useState<KnowledgeRecord[]>([]),[selected,setSelected]=useState<KnowledgeRecord|null>(null),[draft,setDraft]=useState<Knowledge>(()=>({...blankKnowledge(company,buyer),text:seed,title:seed?"New learning to review":""})),[busy,setBusy]=useState(""),[message,setMessage]=useState(""),[error,setError]=useState("");
 async function refresh(){try{if(localPreview){setItems(JSON.parse(localStorage.getItem(localKey(company))||"[]"));return;}setItems((await read(await fetch(`/api/knowledge?company=${encodeURIComponent(company)}`))).items);}catch(x){setError((x as Error).message);}}
 const refreshWorkspace=useCommittedCallback(refresh);
 useEffect(()=>{void refreshWorkspace();},[company,localPreview,refreshWorkspace]);
 function change(p:Partial<Knowledge>){setDraft(x=>({...x,...p,status:"Draft",reviewedAt:""}));setMessage("");}
 async function upload(file?:File){if(!file)return;setBusy("Reading document text");setError("");try{const text=await extractDocument(file);if(localPreview){change({text,title:file.name,filename:file.name,fileKey:"",fileType:file.type});setMessage("Text extracted for this device preview. The original file is stored only in the signed-in hub.");return;}const form=new FormData();form.set("file",file);form.set("company",company);const saved=await read(await fetch("/api/knowledge",{method:"POST",body:form}));change({text,title:file.name,filename:saved.filename,fileKey:saved.fileKey,fileType:saved.fileType});setMessage("Text extracted. Check it below, save a draft, then approve it for the agent.");}catch(x){setError((x as Error).message);}finally{setBusy("");}}
 async function save(status:Knowledge["status"]){setError("");setBusy("Saving knowledge");try{const payload={...draft,status,reviewedAt:status==="Approved"?new Date().toISOString():""};if(!payload.title.trim()||!payload.text.trim())throw Error("Add a title and the relevant text.");if(status==="Approved"&&!payload.reviewer.trim())throw Error("Enter the reviewer’s name before approving this reference.");const contentChanged=selected&&(selected.payload.text!==draft.text||selected.payload.title!==draft.title||selected.payload.buyer!==draft.buyer||selected.payload.fileKey!==draft.fileKey);if(status==="Approved"&&contentChanged)throw Error("Save these changes as a draft first, then approve the saved version.");let item:KnowledgeRecord;
  if(localPreview){item={id:selected?.id||crypto.randomUUID(),revision:(selected?.revision||0)+1,updatedAt:Date.now(),payload};const next=[item,...items.filter(x=>x.id!==item.id)];localStorage.setItem(localKey(company),JSON.stringify(next));setItems(next);}else{item=(await read(await fetch("/api/knowledge",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:selected?.id,revision:selected?.revision||0,payload})}))).item;await refresh();}
  setSelected(item);setDraft(item.payload);setMessage(status==="Approved"?"Approved. The agent can retrieve this version for the selected company and client.":status==="Archived"?"Archived. The agent will no longer retrieve this document.":"Draft saved. Review it, then approve the version the agent may use.");onUsed?.();
 }catch(x){setError((x as Error).message);}finally{setBusy("");}}
 return <div className="enterprise-panel"><p className="ep-lead">Give {company}’s agent the context your team trusts.</p><p>Upload capability statements, pitch decks, product notes or lessons from a meeting. Review the extracted text before the agent can use it. This adds reference knowledge; it does not retrain the underlying model.</p>{localPreview&&<p className="ep-note">Device preview. Documents and approvals here do not transfer to the live hub.</p>}
 <div className="ep-knowledge-grid"><aside><button className="cs-secondary" onClick={()=>{setSelected(null);setDraft(blankKnowledge(company,buyer));setMessage("");}}><Plus size={16}/>New reference</button>{items.filter(x=>knowledgeInScope(x.payload,company,buyer)).map(x=><button className="ep-doc" aria-pressed={selected?.id===x.id} key={x.id} onClick={()=>{setSelected(x);setDraft(x.payload);setMessage("");}}><FileText size={18}/><span><b>{x.payload.title}</b><small>{x.payload.status} · v{x.revision} · {x.payload.buyer||"Company-wide"}</small></span></button>)}{!items.length&&<p className="cs-small">Start with a company overview and one approved case study.</p>}</aside><div>
 <label className="ep-upload"><Upload size={20}/>{busy||"Add a document"}<input type="file" accept=".pdf,.pptx,.docx,.txt,.md" disabled={!!busy} onChange={e=>void upload(e.target.files?.[0])}/><small>PDF, Word, PowerPoint or text · up to 12 MB / 100 pages or slides</small></label>
 <label>Reference title<input value={draft.title} maxLength={180} onChange={e=>change({title:e.target.value})}/></label><label>Available to<select value={draft.buyer?"client":"company"} onChange={e=>change({buyer:e.target.value==="client"?buyer:""})}><option value="client">{company} pitching to {buyer}</option><option value="company">All {company} client pitches</option></select></label>
 <label>Text the agent may use<textarea rows={12} maxLength={120000} value={draft.text} onChange={e=>change({text:e.target.value})}/></label><p className="cs-small">Check tables, figures and page or slide labels. Image-only content is not extracted. Instructions inside documents are treated as reference text.</p>
 <div className="cs-pair"><label>Reviewed by<input value={draft.reviewer} maxLength={100} onChange={e=>setDraft(x=>({...x,reviewer:e.target.value}))}/></label><label>Review again by (optional)<input type="date" value={draft.reviewDue} onChange={e=>change({reviewDue:e.target.value})}/></label></div><p className="cs-small">Expired, draft and archived references are excluded. Changes need a new approval. Private reference documents are excluded from demo links.</p>
 <div className="cs-actions"><button className="cs-secondary" disabled={!!busy} onClick={()=>save("Draft")}>Save draft</button><button className="cs-primary" disabled={!!busy} onClick={()=>save("Approved")}>Approve for agent</button>{selected&&<button className="cs-text" disabled={!!busy} onClick={()=>save("Archived")}>Archive reference</button>}{selected?.payload.fileKey&&!localPreview&&<a href={`/api/knowledge?company=${encodeURIComponent(company)}&file=${selected.id}`} target="_blank" rel="noreferrer">Download original</a>}</div></div></div>{message&&<p role="status" className="ep-note">{message}</p>}{error&&<p role="alert" className="ep-error">{error}</p>}</div>;
}
