"use client";
import {useCommittedCallback} from "@/lib/client-hub-migration/use-committed-callback";
import {useEffect,useRef,useState} from "react";
import {ArrowRight,Check,LoaderCircle,Plus,Radar,Save,ShieldCheck} from "lucide-react";
import {sellerProfileSchema,type SellerProfile} from "@/components/client-hub-migration/original/lib/radar-contract";
import {radarPacket,developRadarOpportunity,type SavedRadarRun} from "@/components/client-hub-migration/original/lib/radar-client";
import {hubRadarWorkspace,saveHubRadarProfile,runHubRadar} from "@/components/client-hub-migration/original/lib/radar-hub-client";
import type {RadarContext} from "@/components/client-hub-migration/original/lib/radar-hub-contract";
import {companies,companyKey} from "@/components/client-hub-migration/original/lib/pursuit-companies";
import {companyRuns,defaultRadarMission,sameCompany,sellerFocus,governmentPriority,sortRadarOpportunities,scopeIssue,type ResearchFocus} from "@/components/client-hub-migration/original/lib/radar-scope";
import IdeaBoard from "./idea-board";
import {newIdeaBoard,type IdeaBoardState} from "@/components/client-hub-migration/original/lib/idea-board";
import {clients} from "@/components/client-hub-migration/original/lib/concept-engine";
import {radarSector} from "@/components/client-hub-migration/original/lib/radar-handoff";
import "./radar-studio.css";

export type RadarGuard=""|"dirty"|"running";
type Props={startingBrief?:string;seller:string;buyer:string;procurementOnly?:boolean;onDevelop:(id:string)=>void;onGuardChange:(guard:RadarGuard)=>void};
function message(error:unknown){return error instanceof Error?error.message:"This action could not finish. Your saved work is preserved.";}
export default function RadarStudio({startingBrief="",seller,buyer,procurementOnly=false,onDevelop,onGuardChange}:Props){
 const [board,setBoard]=useState<IdeaBoardState>(),[activeStage,setActiveStage]=useState(""),[elapsed,setElapsed]=useState(0);
 const [scope,setScope]=useState<RadarContext["scope"]>(procurementOnly?"government":"client");
 const context:RadarContext={buyer,scope};
 function blank():SellerProfile{return {id:crypto.randomUUID(),name:seller.startsWith("Your ")?"":seller,focus:sellerFocus({name:seller}),website:"",offering:"",targetCustomers:companies[companyKey(seller)].targets,voice:"Clear, specific New Zealand English. Separate evidence from proposed concepts.",evidence:[],approved:false};}
 const [profiles,setProfiles]=useState<SellerProfile[]>([]),[profile,setProfile]=useState<SellerProfile>(blank),[dirty,setDirty]=useState(false),[loaded,setLoaded]=useState(false);
 const [runs,setRuns]=useState<SavedRadarRun[]>([]),[runId,updateRunId]=useState(""),[mission,setMission]=useState(defaultRadarMission({name:seller},buyer,procurementOnly));
 const [busy,setBusy]=useState(""),[error,setError]=useState(""),[notice,setNotice]=useState(""),[ready,setReady]=useState(false),[serviceNote,setServiceNote]=useState("");
 const [profileOpen,setProfileOpen]=useState(true),[unfinished,setUnfinished]=useState<Array<{runId:string;status:string;error?:string}>>([]);
 function setRunId(next:string){setBoard(undefined);updateRunId(next);}
 useEffect(()=>{if(!activeStage)return;const start=Date.now();const tick=setInterval(()=>setElapsed(Math.floor((Date.now()-start)/1000)),1000);return()=>clearInterval(tick);},[activeStage]);
 const active=useRef(true),lock=useRef(false),visibleRuns=companyRuns(runs,profile),run=visibleRuns.find(r=>r.runId===runId);
 useEffect(()=>{onGuardChange(busy?"running":dirty?"dirty":"");return()=>onGuardChange("");},[busy,dirty,onGuardChange]);
 useEffect(()=>{if(!dirty&&!busy)return;const warn=(e:BeforeUnloadEvent)=>e.preventDefault();window.addEventListener("beforeunload",warn);return()=>window.removeEventListener("beforeunload",warn);},[dirty,busy]);
 async function load(nextScope=scope){const loadContext={...context,scope:nextScope};if(lock.current)return;lock.current=true;setBusy("Opening saved intelligence");setError("");
  try{const data=await hubRadarWorkspace(loadContext);if(!active.current)return;
   const selected=(loaded?data.profiles.find(p=>p.id===profile.id):data.profiles.find(p=>sameCompany(p.name,seller)))||blank();
   const workspace=await hubRadarWorkspace(loadContext,selected.id,true),matching=companyRuns(workspace.runs,selected);if(!active.current)return;
   setProfiles(data.profiles);setRuns(matching);setProfile(selected);setRunId(matching.some(r=>r.runId===runId)?runId:matching[0]?.runId||"");setDirty(false);setLoaded(true);setProfileOpen(!selected.approved);if(!loaded)setMission(defaultRadarMission(selected,buyer,scope==="government"));
   setReady(workspace.ready);setServiceNote(workspace.serviceNote);setUnfinished(workspace.pending);
   if(workspace.pending.some(p=>p.status==="running"))setNotice("Research is still running. Refresh saved runs shortly. Completed research remains available below.");
  }catch(e){if(active.current)setError(message(e));}finally{lock.current=false;if(active.current)setBusy("");}
 }
 const loadWorkspace=useCommittedCallback(load);
 useEffect(()=>{active.current=true;void loadWorkspace();return()=>{active.current=false;};},[loadWorkspace]);
 function changeScope(next:RadarContext["scope"]){setScope(next);setRunId("");setRuns([]);setMission(defaultRadarMission(profile,buyer,next==="government"));void load(next);}
 function chooseProfile(next:SellerProfile){setProfile(next);setRunId("");setMission(defaultRadarMission(next,sameCompany(next.name,seller)?buyer:"",procurementOnly));setNotice("");if(profiles.some(p=>p.id===next.id)){lock.current=true;setBusy("Opening this company’s research");void hubRadarWorkspace(context,next.id).then(({runs:saved})=>{if(active.current){setRuns(saved);setRunId(companyRuns(saved,next)[0]?.runId||"");}}).catch(e=>{if(active.current)setError(message(e));}).finally(()=>{lock.current=false;if(active.current)setBusy("");});}}
 function edit(next:SellerProfile){setProfile({...next,approved:false});setDirty(true);setNotice("");}
 async function save(){if(lock.current)return;lock.current=true;setBusy("Saving company profile");setError("");
  try{const parsed=sellerProfileSchema.safeParse(profile);if(!parsed.success)throw Error("Complete the company name, capabilities and any evidence extracts before saving.");
   const saved=await saveHubRadarProfile(parsed.data);if(!active.current)return;setProfiles(old=>[saved,...old.filter(p=>p.id!==saved.id)]);setProfile(saved);setDirty(false);setNotice("Company profile saved. Each research run keeps the version it used.");if(saved.approved)setProfileOpen(false);
  }catch(e){if(active.current)setError(message(e));}finally{lock.current=false;if(active.current)setBusy("");}
 }
 async function research(resumeId?:string){if(lock.current||dirty||!ready||!profile.approved)return;lock.current=true;setBusy("Researching sources, checking claims and developing client opportunities");setActiveStage("scout");setElapsed(0);setError("");setNotice("");
  try{const saved=await runHubRadar(mission.trim(),profile.id,context,stage=>{setActiveStage(stage);setElapsed(0);setBusy(({verify:"Checking the sources independently",develop:"Developing opportunities and demonstrator ideas",direct:"Assembling the final client report"} as Record<string,string>)[stage]||"Continuing research");},resumeId);if(saved.seller.id!==profile.id||!sameCompany(saved.seller.name,profile.name))throw Error("The returned research belongs to a different company. It has not been opened in this workspace.");if(!active.current)return;setUnfinished([]);setRuns(old=>[saved,...old.filter(r=>r.runId!==saved.runId)]);setRunId(saved.runId);setNotice("Research saved. Review a proposed opportunity, then develop it in this studio.");
  }catch(e){if(active.current){setError(message(e));try{const data=await hubRadarWorkspace(context,profile.id);if(active.current)setUnfinished(data.pending);}catch{}}}finally{lock.current=false;if(active.current){setBusy("");setActiveStage("");}}
 }
 async function develop(opportunityId:string){if(!run||lock.current||dirty)return;lock.current=true;setBusy("Opening this opportunity in the studio");setError("");
  try{const id=await developRadarOpportunity(run,opportunityId,board?.ideaId===opportunityId?board:newIdeaBoard(opportunityId,run.opportunities.find(o=>o.id===opportunityId)!.evidence.slice(0,3).map((_,i)=>`${opportunityId.slice(0,80)}-source-${i}`)));if(active.current)onDevelop(id);}catch(e){if(active.current)setError(message(e));}finally{lock.current=false;if(active.current)setBusy("");}
 }

 return <div className="rs">
  <div className="rs-account"><span><ShieldCheck size={16}/>Private research · {seller} × {scope==="government"?"NZ government":buyer}</span><small>Uses your hub sign-in</small></div>
  {loaded&&<div className="rs-connection"><ShieldCheck size={17}/><span><b>{ready?"Research service ready":"Research service needs attention"}</b><small>{ready?"Connected through this hub. Review the company profile, then start research below.":serviceNote||"Retry the connection. Saved research remains available."}</small></span></div>}
  <div className="rs-stage-map" aria-label="Research stages">{[["scout","Find the signal","Market, buyer and procurement scouts"],["verify","Check the evidence","Independent source verification"],["develop","Shape the possibilities","Ideas, demonstrators and pursuit work"],["direct","Bring it together","A sourced opportunity for your board"]].map(([key,title,description],i)=><div key={key} className={activeStage===key?"is-active":activeStage&&["scout","verify","develop","direct"].indexOf(activeStage)>i?"is-done":""}><span>0{i+1}</span><b>{title}</b><p>{description}</p>{activeStage===key&&<small>Working · {elapsed}s</small>}</div>)}</div>
  <p className="rs-intro">Your company’s strengths meet a real reason for a client to act. Radar brings the evidence and a proposed experience into this studio.</p>
  {(busy||error||notice)&&<div className={error?"rs-status rs-error":"rs-status"} role={error?"alert":"status"}>{busy?<><LoaderCircle className="rs-spin" size={17}/>{busy}…</>:error||notice}</div>}
  {serviceNote&&<div className="rs-status">{serviceNote}<button className="cs-text" disabled={!!busy||dirty} onClick={()=>void load()}>Retry</button></div>}
  {!loaded&&!busy&&<button className="cs-secondary" onClick={()=>void load()}>Load saved work</button>}
  {loaded&&<>
   <details className="rs-company" open={profileOpen} onToggle={e=>setProfileOpen(e.currentTarget.open)}><summary><span className="rs-number">01</span><span><b>{profile.name||"Your company"}</b><small>{profile.approved&&!dirty?"Reviewed profile · ready for research":"Define what you can credibly deliver"}</small></span>{profile.approved&&!dirty&&<Check size={18}/>}</summary>
    <fieldset disabled={!!busy}>
     {!profile.approved&&<div className="rs-setup"><b>One company setup before the first run</b><p>Describe the seller’s real capabilities, review them and save. This keeps ideas relevant and prevents the agent inventing what your company can deliver.</p>{startingBrief&&<button className="cs-secondary" onClick={()=>edit({...profile,offering:("Starting concept brief, not verified delivery credentials: "+startingBrief).slice(0,3000)})}>Use this hub’s brief as a starting point</button>}</div>}
     <div className="rs-profile-actions"><label>Company profile<select value={profiles.some(p=>p.id===profile.id)?profile.id:""} disabled={dirty} onChange={e=>{const found=profiles.find(p=>p.id===e.target.value);if(found)chooseProfile(found);}}><option value="" disabled>New company</option>{profiles.filter(p=>sameCompany(p.name,seller)).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><button className="cs-secondary" disabled={dirty} onClick={()=>{chooseProfile(blank());setDirty(true);}}><Plus size={15}/>New company</button></div>
     <div className="cs-pair"><label>Company name<input value={profile.name} readOnly={companyKey(seller)!=="custom"} maxLength={100} onChange={e=>edit({...profile,name:e.target.value})} placeholder="assembl, SAP, your agency or construction firm"/></label><label>Website<input type="url" value={profile.website} maxLength={1500} onChange={e=>edit({...profile,website:e.target.value})} placeholder="https://"/></label></div>
     <label>Type of work to pursue<select value={sellerFocus(profile)} disabled={companyKey(profile.name)!=="custom"} onChange={e=>{const next={...profile,focus:e.target.value as ResearchFocus};edit(next);setMission(defaultRadarMission(next,buyer,scope==="government"));}}><option value="technology">Enterprise technology & digital services</option><option value="construction">Construction & major projects</option><option value="agency">Agency & creative services</option><option value="other">Other · use the reviewed capabilities</option></select></label>
     <label>What can you deliver?<textarea rows={3} value={profile.offering} maxLength={3000} onChange={e=>edit({...profile,offering:e.target.value})} placeholder="Products, services, specialist expertise and delivery limits"/></label>
     <div className="cs-pair"><label>Clients you want to win<textarea rows={2} value={profile.targetCustomers} maxLength={1800} onChange={e=>edit({...profile,targetCustomers:e.target.value})}/></label><label>Your voice<textarea rows={2} value={profile.voice} maxLength={600} onChange={e=>edit({...profile,voice:e.target.value})}/></label></div>
     <details className="rs-evidence"><summary>Capability evidence · {profile.evidence.length} extracts</summary><p>Use checked extracts from your case studies, services or policies. Only approved evidence goes into the research.</p>
      {profile.evidence.map((item,i)=><div className="rs-extract" key={item.id}><label>Evidence title<input value={item.title} maxLength={160} onChange={e=>edit({...profile,evidence:profile.evidence.map((x,n)=>n===i?{...x,title:e.target.value,approved:false}:x)})}/></label><label>Factual extract<textarea rows={3} value={item.body} maxLength={6000} onChange={e=>edit({...profile,evidence:profile.evidence.map((x,n)=>n===i?{...x,body:e.target.value,approved:false}:x)})}/></label><div className="cs-actions"><label className="cs-check"><input type="checkbox" checked={item.approved} onChange={e=>edit({...profile,evidence:profile.evidence.map((x,n)=>n===i?{...x,approved:e.target.checked}:x)})}/>Checked and approved for use</label><button className="cs-text" onClick={()=>edit({...profile,evidence:profile.evidence.filter((_,n)=>n!==i)})}>Remove</button></div></div>)}
      <button className="cs-secondary" disabled={profile.evidence.length>=12} onClick={()=>edit({...profile,evidence:[...profile.evidence,{id:crypto.randomUUID(),title:"",body:"",approved:false}]})}>Add evidence</button>
     </details>
     <label className="cs-check"><input type="checkbox" checked={profile.approved} onChange={e=>{setProfile({...profile,approved:e.target.checked});setDirty(true);}}/>I have reviewed this company profile for research and private concept development.</label>
     <div className="cs-actions"><button className="cs-primary" onClick={save}><Save size={15}/>Save company profile</button>{dirty&&<button className="cs-secondary" onClick={()=>{chooseProfile(profiles.find(p=>p.id===profile.id)||blank());setDirty(false);}}>Discard profile edits</button>}</div>
    </fieldset>
   </details>
   <section className="rs-mission"><div className="rs-section-title"><span className="rs-number">02</span><div><h3>Find a reason to act.</h3><p>Research for <b>{profile.name||seller} × {scope==="government"?"NZ government":buyer}</b>. Saved research stays with this client and company.</p></div></div><div className="rs-govt-priority"><b>NZ government & GETS · high research priority</b><p>{sellerFocus(profile)==="construction"?"School property, building works and public construction programmes.":sellerFocus(profile)==="technology"?"Software, data, AI, digital services and enterprise systems.":"Public-sector opportunities matched to the reviewed company capabilities."} Each result needs a checked scope, status and source.</p><button className="cs-text" disabled={!!busy||dirty} onClick={()=>changeScope(scope==="government"?"client":"government")}>{scope==="government"?`Return to ${buyer} research`:"Research government procurement separately"}</button></div><label>Research brief<textarea rows={3} value={mission} maxLength={4000} disabled={!!busy} onChange={e=>setMission(e.target.value)}/></label><div className="cs-actions"><button className="cs-primary" disabled={!!busy||dirty||!ready||!profile.approved||!profiles.some(p=>p.id===profile.id)||mission.trim().length<10} onClick={()=>void research()}><Radar size={16}/>{scope==="client"?`Research ${buyer}`:"Research government opportunities"}</button><small>{!ready?"The research connection must be available.":dirty?"Save your company profile first.":!profile.approved?"Review your company profile first.":"Scouts → independent checks → proposed opportunities"}</small>{(!profile.approved||dirty)&&<button className="cs-text" onClick={()=>{setProfileOpen(true);document.querySelector(".rs-company")?.scrollIntoView({block:"start",behavior:"auto"});}}>Review company setup ↑</button>}</div></section>
   <section className="rs-results">{unfinished.length>0&&<details className="rs-resumable"><summary>{unfinished.length} unfinished research runs · continue saved work</summary>{unfinished.map(r=><div className="rs-status" key={r.runId}><span>{r.status==="running"?"A research stage is running.":r.error||"Research is saved partway through."}</span>{r.status!=="running"&&<button className="cs-secondary" disabled={!!busy||dirty||!ready} onClick={()=>void research(r.runId)}>Continue saved research</button>}</div>)}</details>}<div className="rs-section-title"><span className="rs-number">03</span><div><h3>An opportunity to develop.</h3><p>Evidence, proposed ideas and questions to validate with the client. A gap in public information does not prove a missing capability.</p></div></div><div className="rs-history"><label>{scope==="client"?`${buyer} research`:"Government research"}<select value={runId} disabled={!!busy} onChange={e=>setRunId(e.target.value)}><option value="">Choose a run</option>{visibleRuns.map(r=><option key={r.runId} value={r.runId}>{r.context?.buyer||r.seller.name} · {new Date(r.generatedAt).toLocaleString("en-NZ")}</option>)}</select></label><button className="cs-text" disabled={!!busy||dirty} onClick={()=>void load()}>Refresh saved runs</button></div>
    {run?<><IdeaBoard ideas={sortRadarOpportunities(run.opportunities,run.seller).map(o=>{let blocked="";try{radarPacket(run,o.id);}catch(e){blocked=message(e);}let sector: keyof typeof clients="custom";if(!blocked)sector=radarSector(radarPacket(run,o.id));return {id:o.id,title:o.headline,promise:o.assemblOutcome,moment:o.whyItMayMatter,agent:o.demoIdea,review:o.nextAction,outcome:`Priority ${o.score.total} · ${o.unknowns[0]||"Validate the opportunity with the client."}`,origin:"Radar proposal",image:clients[sector].image,blocked:dirty?"Save or discard the company profile edits first.":blocked};})} sources={(run.opportunities.find(o=>o.id===board?.ideaId)||sortRadarOpportunities(run.opportunities,run.seller)[0])?.evidence.map((ev,i)=>({id:`${(board?.ideaId||sortRadarOpportunities(run.opportunities,run.seller)[0].id).slice(0,80)}-source-${i}`,title:ev.sourceTitle||"Research source",claim:ev.claim,url:ev.sourceUrl,checked:ev.verified}))||[]} value={board} onChange={next=>{const o=run.opportunities.find(o=>o.id===next.ideaId);setBoard(board?.ideaId!==next.ideaId?{...next,sourceIds:o?.evidence.slice(0,3).map((_,i)=>`${next.ideaId.slice(0,80)}-source-${i}`)||[]}:next);}} busy={!!busy} onDevelop={key=>void develop(key)} actionLabel="Develop in the studio"/>
     <p className="rs-run-context">Researched for <b>{run.seller.name}</b> using its saved company profile. {run.mission}</p>{sortRadarOpportunities(run.opportunities,run.seller).map(o=>{const allowed=(()=>{try{radarPacket(run,o.id);return true;}catch{return false;}})();return <details className="rs-opportunity" key={o.id}><summary className="rs-opportunity-head"><div><span className="cs-eyebrow">{o.accountName} · {o.stage}{governmentPriority(o)&&!scopeIssue(run.seller,o)?" · NZ GOVERNMENT PRIORITY":""}</span><h3>{o.headline}</h3></div><span className="rs-priority">Priority <b>{o.score.total}</b></span></summary><div className="rs-facts"><div><h4>What changed</h4><p>{o.whatChanged}</p></div><div><h4>Why it matters</h4><p>{o.whyItMayMatter}</p></div><div><h4>What {run.seller.name} could do</h4><p>{o.assemblOutcome}</p></div></div><div className="rs-demo"><span className="cs-eyebrow">THE CLIENT EXPERIENCE</span><p>{o.demoIdea}</p></div><p className="rs-buyers"><b>Buyer roles</b> {o.buyerRoles.join(", ")||"To confirm"}</p><details className="rs-evidence"><summary><ShieldCheck size={15}/>Sources, caveats and open questions</summary>{o.evidence.map((ev,i)=><div key={i} className="rs-source"><b>{ev.verified?"Checked by Radar":"Needs verification"}</b><p>{ev.claim}</p><a href={ev.sourceUrl} target="_blank" rel="noreferrer">{ev.sourceTitle||ev.sourceUrl} ↗</a><small>{ev.publishedAt&&`Published ${ev.publishedAt}. `}{ev.eventAt&&`Event ${ev.eventAt}. `}{ev.caveat}</small></div>)}{o.unknowns.length>0&&<><h4>Still to establish</h4><ul>{o.unknowns.map((u,i)=><li key={i}>{u}</li>)}</ul></>}<p className="cs-small">Priority uses service fit ({o.score.serviceFit}, 35%), evidence ({o.score.evidenceStrength}, 35%), timing ({o.score.timing}, 20%) and buyer access ({o.score.buyerAccess}, 10%). Relevant government procurement appears first, followed by the normal priority score. Held or mismatched work appears last. The score is not a probability of winning.</p></details><div className="rs-next"><p><b>Next step</b> {o.nextAction}</p><button className="cs-primary" disabled={!allowed||!!busy||dirty} onClick={()=>develop(o.id)}>Develop this idea<ArrowRight size={16}/></button></div>{!allowed&&<p className="cs-small">{scopeIssue(run.seller,o)||"A reviewed company profile, checked evidence and an opportunity not on hold are needed before development."}</p>}</details>;})}{!run.opportunities.length&&<p className="rs-empty">No defensible opportunities were found. Refine the brief and try a new run.</p>}</>:<div className="rs-empty"><Radar size={28}/><h3>{profile.name||seller}’s next opportunity starts here.</h3><p>Research from your company’s reviewed capabilities, then choose a proposed experience to develop in the studio.</p></div>}
   </section>
  </>}
 </div>;
}
