"use client";
import { migrationFetch as fetch } from "@/lib/client-hub-migration/review-adapter";
import AgentAnswer from "./agent-answer";
import {useEffect,useRef,useState} from "react";
import {BookOpen,Download,Send,Sparkles,Plug,MessageCircle} from "lucide-react";
import type {Hub} from "@/components/client-hub-migration/original/lib/pursuit-hub";
import type {KnowledgeReceipt} from "@/components/client-hub-migration/original/lib/company-knowledge";
import {defaultAgentSetup,connectionBrief,type AgentSetup} from "@/components/client-hub-migration/original/lib/agent-connection-brief";
type Message={id:string;message:string;answers:Array<{reply:string;provider:string}>;receipts:KnowledgeReceipt[];contextSummary:string};
async function read(r:Response){const d=await r.json() as {error?:string;messages:Message[];item:Message;setup:AgentSetup;connection:{configured:boolean;label:string;status:string}};if(!r.ok)throw Error(d.error||"The agent could not respond.");return d;}
export default function SalesAgentStudio({hub,localPreview,initialMessage="",onKnowledge,onDevelop,onBrief}:{hub:Hub;localPreview:boolean;initialMessage?:string;onKnowledge:(seed?:string)=>void;onDevelop:()=>void;onBrief:(text:string)=>void}){
 const [tab,setTab]=useState("Chat"),[message,setMessage]=useState(initialMessage),[messages,setMessages]=useState<Message[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[mode,setMode]=useState<AgentSetup["mode"]>("assembl"),[consent,setConsent]=useState(false),[setup,setSetup]=useState<AgentSetup>(()=>defaultAgentSetup(hub.seller)),[connection,setConnection]=useState({configured:false,label:"Company agent",status:"Setup required"});
 const alive=useRef(true),bottom=useRef<HTMLDivElement>(null);
 useEffect(()=>{alive.current=true;if(!localPreview)void fetch(`/api/sales-agent?company=${encodeURIComponent(hub.seller)}&buyer=${encodeURIComponent(hub.buyer)}`).then(read).then(d=>{if(!alive.current)return;setMessages(d.messages||[]);setConnection(d.connection);if(d.setup)setSetup(d.setup);}).catch(x=>{if(alive.current)setError(x.message);});else{try{const saved=localStorage.getItem(`assembl-agent-setup:${hub.seller}`);if(saved)setSetup(JSON.parse(saved));}catch{}}return()=>{alive.current=false;};},[hub.seller,hub.buyer,localPreview]);
 async function ask(e:React.FormEvent){e.preventDefault();if(!message.trim()||busy)return;setError("");setBusy(true);const prompt=message;try{const r=await read(await fetch("/api/sales-agent",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"chat",hub:{...hub,...(hub.sellerBrand?{sellerBrand:{...hub.sellerBrand,logo:"",decks:[]}}:{}),...(hub.clientBrand?{clientBrand:{...hub.clientBrand,logo:""}}:{})},message:prompt,mode,shareContext:consent})}));if(!alive.current)return;setMessages(x=>[...x,r.item]);setMessage("");setTimeout(()=>bottom.current?.scrollIntoView({block:"nearest",behavior:"smooth"}),50);}catch(x){if(alive.current)setError((x as Error).message);}finally{if(alive.current)setBusy(false);}}
 async function saveSetup(){setError("");setBusy(true);try{if(localPreview)localStorage.setItem(`assembl-agent-setup:${hub.seller}`,JSON.stringify(setup));else await read(await fetch("/api/sales-agent",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"setup",setup})}));setNotice("Connection brief saved. IT configuration is still required before the company agent can respond.");}catch(x){setError((x as Error).message);}finally{setBusy(false);}}
 function exportSetup(){const u=URL.createObjectURL(new Blob([connectionBrief(setup)],{type:"text/markdown"})),a=document.createElement("a");a.href=u;a.download=`${hub.seller.toLowerCase()}-agent-it-setup.md`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
 return <div className="enterprise-panel ep-agent"><div className="ep-agent-context"><MessageCircle size={25}/><div><b>Your sales agent</b><span>{hub.seller} pitching to {hub.buyer}</span></div><button className="cs-text" onClick={()=>onKnowledge()}><BookOpen size={16}/>Company knowledge</button></div><nav className="ep-tabs" aria-label="Agent workspace"><button aria-pressed={tab==="Chat"} onClick={()=>setTab("Chat")}>Ask & develop ideas</button><button aria-pressed={tab==="Setup"} onClick={()=>setTab("Setup")}><Plug size={16}/>Connect a company agent</button></nav>
 {tab==="Chat"?<><div className="ep-agent-toolbar"><label>Work with<select value={mode} onChange={e=>{setMode(e.target.value as AgentSetup["mode"]);setConsent(false);}}><option value="assembl">assembl sales agent</option><option value="company" disabled={!connection.configured}>{setup.platform} {connection.configured?"":"— setup required"}</option><option value="both" disabled={!connection.configured}>Both agents {connection.configured?"":"— setup required"}</option></select></label><span className="cs-small">{mode==="assembl"?"Approved references + this client brief":connection.status}</span></div>{mode!=="assembl"&&<label className="cs-check"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>Send this client brief, commercial plan and approved reference extracts to the company’s configured agent.</label>}
 <div className="ep-conversation" aria-label="Sales agent conversation">{!messages.length&&<div className="ep-agent-empty"><Sparkles size={27}/><h3>What could {hub.seller} help {hub.buyer} do next?</h3><p>Ask for a useful customer journey, a sharper proposition, a pilot scope or the evidence missing from this pitch.</p><div className="ep-prompts">{["Suggest three client-specific ideas we could demonstrate.","Where is the real customer wait, and what useful work could happen?","What would the buyer need to approve a bounded pilot?"].map(q=><button key={q} onClick={()=>setMessage(q)}>{q}</button>)}</div></div>}{messages.map(m=><article className="ep-exchange" key={m.id}><p className="ep-question">{m.message}</p><small>{m.contextSummary}</small>{m.answers.map((a,i)=><div className="ep-answer" key={i}><b>{a.provider} · draft</b><div className="ep-response"><AgentAnswer text={a.reply}/></div><div className="cs-actions"><button className="cs-text" onClick={()=>onBrief(a.reply)}>Use as the concept brief</button><button className="cs-text" onClick={()=>onKnowledge(a.reply)}>Save learning for review</button></div></div>)}{m.receipts?.length>0&&<details><summary>{m.receipts.length} company reference extracts supplied</summary>{m.receipts.map((r,i)=><div className="ep-receipt" key={`${r.id}-${i}`}><b>{r.title} · v{r.revision}</b><small>{r.id} · {r.scope}</small><p>{r.excerpt}</p></div>)}</details>}</article>)}<div ref={bottom}/></div>
 {localPreview?<div className="ep-note"><b>Live agent chat is in the signed-in hub.</b><p>This page previews the interface on your device. Open the same company and client online to use saved company knowledge and the connected assembl agent.</p><a className="cs-primary" href={`http://127.0.0.1:3187/hub?company=${/^sap$/i.test(hub.seller)?"sap":/^hawkins$/i.test(hub.seller)?"hawkins":/^southbase$/i.test(hub.seller)?"southbase":"custom"}&client=${hub.engine?.sector||"custom"}`} target="_blank" rel="noreferrer">Open the signed-in hub ↗</a></div>:<form className="ep-composer" onSubmit={ask}><label htmlFor="agent-message">Ask your sales agent</label><textarea id="agent-message" value={message} rows={3} maxLength={6000} onChange={e=>setMessage(e.target.value)} placeholder={`Help ${hub.seller} pitch a useful concept to ${hub.buyer}…`}/><div><span className="cs-small">Company documents are private. Replies stay drafts.</span><button className="cs-primary" disabled={busy||!message.trim()||(mode!=="assembl"&&!consent)} type="submit"><Send size={16}/>{busy?"Agent is preparing a reply…":"Ask agent"}</button></div></form>}
 <button className="cs-secondary ep-develop" onClick={onDevelop}><Sparkles size={16}/>Generate three ideas in the hub</button></>:<><h3>Use assembl, your own agent, or both.</h3><p>Prepare the client’s connection brief here. Its IT team confirms the platform, permissions and approved data before the company agent is enabled.</p><div className="ep-status"><Plug size={18}/><b>{connection.status}</b><span>{connection.label}</span></div><label>Preferred arrangement<select value={setup.mode} onChange={e=>setSetup({...setup,mode:e.target.value as AgentSetup["mode"]})}><option value="assembl">assembl agent</option><option value="company">Company agent</option><option value="both">Both agents</option></select></label><div className="cs-pair"><label>Company agent platform<input maxLength={100} value={setup.platform} onChange={e=>setSetup({...setup,platform:e.target.value})}/></label><label>Client technical owner<input value={setup.contact} maxLength={180} placeholder="Name or team to confirm" onChange={e=>setSetup({...setup,contact:e.target.value})}/></label></div>{([['tasks','Tasks it should help with'],['data','Approved context and document boundaries'],['notes','Tenant, access and review notes']] as const).map(([key,label])=><label key={key}>{label}<textarea rows={3} maxLength={3000} value={setup[key]} onChange={e=>setSetup({...setup,[key]:e.target.value})}/></label>)}<p className="ep-note">For SAP Joule, IT must confirm the available integration direction and tenant capabilities. This setup does not claim a live Joule connection. <a href="https://architecture.learning.sap.com/docs/golden-path/ai-golden-path/build-and-deliver/build-ai-agents" target="_blank" rel="noreferrer">SAP architecture guidance ↗</a></p><p className="cs-small">Do not put API keys or passwords here. The export describes the server-side adapter, data boundary and acceptance tests for the client’s IT team.</p><div className="cs-actions"><button className="cs-primary" disabled={busy} onClick={saveSetup}>Save connection brief</button><button className="cs-secondary" onClick={exportSetup}><Download size={16}/>Download IT setup</button></div></>}
 {notice&&<p role="status" className="ep-note">{notice}</p>}{error&&<p role="alert" className="ep-error">{error}</p>}</div>;
}
