"use client";
import {useState} from "react";
import {Download,ShieldCheck,Server,FileCheck2} from "lucide-react";
import type {Hub} from "@/components/client-hub-migration/original/lib/pursuit-hub";
import {defaultSecurity,deploymentOptions,reviewStates,securityBrief,securityChecks,securitySources,type SecurityPlan} from "@/components/client-hub-migration/original/lib/enterprise-security";
import "./security-studio.css";
export default function SecurityStudio({hub,onChange,onSave,busy}:{hub:Hub;onChange:(h:Hub)=>void;onSave:()=>void;busy:boolean}){
 const [tab,setTab]=useState("readiness"),p=hub.security||defaultSecurity(hub);
 const update=(next:Partial<SecurityPlan>)=>onChange({...hub,security:{...p,...next}});
 const exportPack=()=>{const url=URL.createObjectURL(new Blob([securityBrief(hub)],{type:"text/markdown;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download="assembl-enterprise-evaluation-draft.md";a.click();setTimeout(()=>URL.revokeObjectURL(url),1500);};
 return <div className="security-studio">
  <div className="ss-intro"><ShieldCheck size={30}/><div><span className="cs-eyebrow">ENTERPRISE EVALUATION</span><h3>A clear route from concept to pilot.</h3><p>Workspace customer: <b>{hub.seller}</b>. Pitch recipient: <b>{hub.buyer}</b>. The software agreement with assembl and the customer’s onward proposal are separate relationships.</p></div></div>
  <nav className="ep-tabs" aria-label="Security and implementation"><button aria-pressed={tab==="readiness"} onClick={()=>setTab("readiness")}>Current readiness</button><button aria-pressed={tab==="hosting"} onClick={()=>setTab("hosting")}>Hosting & integration</button><button aria-pressed={tab==="documents"} onClick={()=>setTab("documents")}>Terms & data</button></nav>
  {tab==="readiness"&&<>
   <div className="ss-two"><section className="ss-card"><h3>Implemented in this workspace</h3><ul><li>Owner sign-in and private workspace routes.</li><li>Company-scoped references, research and saved campaigns.</li><li>Reviewed document context with sources and version checks.</li><li>One reviewed demo per revocable unlisted link.</li><li>Server-side agent credentials and signed research requests.</li><li>Agent drafts and simulated client-system actions.</li></ul></section><section className="ss-card"><h3>Evidence still needed for enterprise use</h3><ul><li>Client SSO, user roles and offboarding.</li><li>Independent security testing and remediation evidence.</li><li>Confirmed data locations, provider terms and retention.</li><li>Backup restoration, incident response and support commitments.</li><li>Agreed contracts, insurance and production acceptance.</li></ul><p className="cs-small">No assembl ISO 27001, SOC 2, SAP certification or enterprise SLA is claimed.</p></section></div>
   <h3 className="ss-heading">Where information goes today</h3><div className="ss-flow"><div><b>Private hub</b><span>ChatGPT sign-in · selected company and client</span></div><span aria-hidden="true">→</span><div><b>Application & storage</b><span>Sites / Cloudflare · saved records, images and private files</span></div><span aria-hidden="true">→</span><div><b>Requested AI work</b><span>Research bridge / Supabase · configured AI provider and web search</span></div></div><p>Chat and concept requests include selected context and approved reference extracts. Generated media may use a separate media provider. Verify the full provider chain, account terms, logs and locations before using client production data.</p>
   <div className="cs-callout"><b>Client hosting changes the responsibilities; it does not remove them.</b><p>Start with public or synthetic information. A client or implementation partner can operate a future instance, with explicit responsibility for software, access, operations, data and support.</p></div>
   <h3 className="ss-heading">Review with the buying team</h3><p>These are recorded review decisions. Changing a status does not configure a control or grant system access.</p>
   {securityChecks.map(item=>{const r=p.reviews.find(x=>x.id===item.id)||{id:item.id,status:"Not assessed" as const,owner:"",evidence:""};const change=(v:Partial<typeof r>)=>update({reviews:[...p.reviews.filter(x=>x.id!==item.id),{...r,...v}]});return <details className="ss-review" key={item.id}><summary><span>{item.title}</span><small>{r.status}</small></summary><p>{item.detail}</p><div className="cs-pair"><label>Review status<select value={r.status} onChange={e=>change({status:e.target.value as typeof r.status})}>{reviewStates.map(x=><option key={x}>{x}</option>)}</select></label><label>Responsible reviewer<input value={r.owner} maxLength={180} onChange={e=>change({owner:e.target.value})}/></label></div><label>Evidence, gap or agreed decision<textarea value={r.evidence} maxLength={1800} rows={3} onChange={e=>change({evidence:e.target.value})}/></label></details>;})}
  </>}
  {tab==="hosting"&&<><div className="ss-intro"><Server size={28}/><div><h3>Choose a route to evaluate.</h3><p>This records the proposed approach. It does not move the application or activate a client connection.</p></div></div><div className="ss-hosting">{deploymentOptions.map(x=><label className="ss-card" key={x.id}><span><input type="radio" name="hosting-route" checked={p.deployment===x.id} onChange={()=>update({deployment:x.id})}/><b>{x.title}</b></span><p>{x.description}</p><p>{x.responsibility}</p><small>{x.status}</small></label>)}</div><label>Proposed environment<input value={p.environment} maxLength={400} placeholder="e.g. client-approved SAP BTP / Azure / AWS environment" onChange={e=>update({environment:e.target.value})}/></label><div className="cs-pair"><label>IT owner<input value={p.itOwner} maxLength={180} onChange={e=>update({itOwner:e.target.value})}/></label><label>Regions and transfer requirements<input value={p.region} maxLength={240} onChange={e=>update({region:e.target.value})}/></label></div><div className="ss-steps">{["Agree one use case, data boundary and contract","Build an isolated test with synthetic data","Connect approved identity and read-only APIs","Run a limited pilot with monitoring and rollback","Complete assurance and approve production"].map((x,i)=><div key={x}><span>0{i+1}</span><p>{x}</p></div>)}</div><div className="cs-callout"><b>What client hosting would require</b><p>The current application uses Sites identity, a Cloudflare runtime and storage, and a separate AI/research service. A client-hosted edition requires adapting those components, packaging the application and testing it in the selected platform. The exported demo website is a presentation, not the complete server product.</p><p>SAP BTP/Kyma is a possible target for an adapted application. The client confirms entitlement, architecture, integration and procurement requirements. SAP Joule is configured through the separate agent IT setup.</p></div></>}
  {tab==="documents"&&<><div className="ss-intro"><FileCheck2 size={28}/><div><h3>Terms a lawyer and IT team can review.</h3><p>The downloadable pack includes draft evaluation terms, a data-processing schedule, a privacy-notice draft, implementation responsibilities and this review register. It is not published or accepted as binding terms.</p></div></div><div className="cs-pair"><label>assembl legal entity<input value={p.operator} maxLength={180} placeholder="Legal business name to confirm" onChange={e=>update({operator:e.target.value})}/></label><label>Workspace customer’s legal entity<input value={p.customer} maxLength={180} onChange={e=>update({customer:e.target.value})}/></label></div><div className="cs-pair"><label>Privacy / support contact<input value={p.contact} maxLength={180} placeholder="Confirmed contact email and role" onChange={e=>update({contact:e.target.value})}/></label><label>Legal reviewer<input value={p.legalOwner} maxLength={180} onChange={e=>update({legalOwner:e.target.value})}/></label></div><label>Permitted data and purpose<textarea value={p.data} maxLength={1800} rows={4} onChange={e=>update({data:e.target.value})}/></label><label>Retention, export and deletion agreement<textarea value={p.retention} maxLength={1000} rows={3} placeholder="Periods, responsibility, backups and how completion is evidenced" onChange={e=>update({retention:e.target.value})}/></label><p className="cs-small">Archiving a reference stops retrieval; it does not delete its file or past outputs. Unlisted links can be forwarded. These details belong in the final agreement and privacy notice.</p><details className="ss-review"><summary>Read the draft pack before downloading</summary><pre className="ss-document">{securityBrief(hub)}</pre></details></>}
  <div className="ss-actions"><button className="cs-primary" disabled={busy} onClick={onSave}>Save evaluation plan</button><button className="cs-secondary" onClick={exportPack}><Download size={16}/>Download legal & IT draft pack</button></div>
  <details className="ss-review"><summary>Sources and review date · 13 September 2026</summary>{securitySources.map(x=><p key={x.url}><a href={x.url} target="_blank" rel="noreferrer">{x.title} ↗</a><br/>{x.note}</p>)}<p>Product readiness is based on the current implementation, not an independent certification. Client requirements and legal roles must be confirmed for the proposed use.</p></details>
 </div>;
}
