"use client";
import PreviewImage from "@/components/client-hub-migration/PreviewImage";
import { migrationFetch as fetch } from "@/lib/client-hub-migration/review-adapter";
import {useState} from "react";
import {ImagePlus,FileUp,Check} from "lucide-react";
import {defaultSellerBrand,resolveSellerBrand,sellerBrandSchema,sellerFonts,type SellerBrand,type BrandDeck} from "@/components/client-hub-migration/original/lib/seller-brand";
import type {Hub} from "@/components/client-hub-migration/original/lib/pursuit-hub";
export default function SellerBrandEditor({hub,localPreview,onApply}:{hub:Hub;localPreview:boolean;onApply:(brand:SellerBrand)=>void}){
 const [draft,setDraft]=useState<SellerBrand>(()=>structuredClone(resolveSellerBrand(hub))),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);
 function edit(patch:Partial<SellerBrand>){setDraft(d=>({...d,...patch}));setError("");setNotice("");}
 async function apply(asDefault=false){const parsed=sellerBrandSchema.safeParse(draft);if(!parsed.success){setError(parsed.error.issues[0]?.message||"Check the brand details.");return;}setBusy(true);setError("");try{if(asDefault){const r=await fetch("/api/brand/company",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({seller:hub.seller,brand:parsed.data})});if(!r.ok)throw Error("The company default could not be saved. Apply it to this pitch and try again later.");}onApply(parsed.data);setNotice(asDefault?`Saved as ${hub.seller}’s default for new pitches. Save this concept to keep its copy.`:"Applied to this pitch. Save the concept to keep its branding and reference decks.");}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function logo(file?:File){if(!file)return;if(file.size>150000||!["image/png","image/jpeg","image/webp"].includes(file.type)){setError("Use a PNG, JPEG or WebP logo under 150 KB.");return;}try{const data=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;reader.readAsDataURL(file);});edit({logo:data});}catch{setError("The logo could not load.");}}
 async function deck(file?:File){if(!file)return;if(file.size>12000000||!/\.(pdf|pptx)$/i.test(file.name)){setError("Use a PDF or PowerPoint (.pptx) under 12 MB.");return;}setBusy(true);setError("");try{const body=new FormData();body.set("file",file);const r=await fetch("/api/brand/decks",{method:"POST",body});const d=await r.json() as {error?:string;deck:BrandDeck};if(!r.ok)throw Error(d.error||"The deck could not be saved.");edit({decks:[...draft.decks,d.deck]});setNotice("Reference uploaded privately. Apply the brand to attach it to this pitch.");}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="cb-editor"><fieldset disabled={busy}><p><b>{hub.seller} sets the presentation style.</b> {hub.buyer} remains recognisable inside the proposed customer experience.</p><div className="cb-colours">{([['primary','Primary'],['onPrimary','Button text'],['accent','Accent'],['paper','Background'],['ink','Body text']] as const).map(([key,label])=><label key={key}>{label}<input type="color" value={draft[key]} onChange={e=>edit({[key]:e.target.value})}/><small>{draft[key]}</small></label>)}</div><label>Typography<select value={draft.font} onChange={e=>edit({font:e.target.value as SellerBrand['font']})}><option value="sap72">SAP 72 · open-source product typeface</option><option value="system">Clean system sans serif</option><option value="arial">Arial / Helvetica</option><option value="editorial">Editorial serif</option></select></label><label className="cb-upload"><ImagePlus size={16}/>Your company logo<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>void logo(e.target.files?.[0])}/></label>{draft.logo&&<button className="cs-text" onClick={()=>edit({logo:""})}>Use the company name instead</button>}
 <section className="sb-decks"><h3>Pitch decks & brand references</h3><p>Keep examples from {hub.seller} beside the pitch. Files stay private. Add the points to follow below; the agent uses those reviewed notes.</p><label className="cb-upload"><FileUp size={16}/>{localPreview?"Upload in your signed-in hub":"Add a reference deck"}<input type="file" accept=".pdf,.pptx" disabled={localPreview||draft.decks.length>=6} onChange={e=>void deck(e.target.files?.[0])}/><small>PDF or PowerPoint · up to 12 MB each · six references</small></label>{draft.decks.map(d=><div className="sb-deck" key={d.id}><a href={`/api/brand/decks?id=${d.id}`}>{d.name} ↗<small>{(d.bytes/1000000).toFixed(1)} MB · private reference</small></a><button className="cs-text" onClick={()=>edit({decks:draft.decks.filter(x=>x.id!==d.id)})}>Detach</button></div>)}<label>Brand and pitch notes<textarea rows={4} maxLength={3000} value={draft.notes} placeholder="e.g. Use a concise SAP-led introduction, blue section dividers and the client's colours only in the customer app. From the deck: lead with the operational problem, then show the proposed journey." onChange={e=>edit({notes:e.target.value,notesApproved:false})}/></label><label className="cs-check"><input type="checkbox" checked={draft.notesApproved} onChange={e=>edit({notesApproved:e.target.checked})}/>Use these reviewed notes to guide new agent drafts.</label><small>Reference files are stored, not automatically read or copied into the presentation. Notes guide the style and framing; they do not establish capabilities or results.</small></section>
 <p className="cs-small">SAP colours follow its <a href="https://www.sap.com/design-system/digital/foundations/identity/color/" target="_blank" rel="noreferrer">published palette</a>; SAP 72 is its open-source product font. Southbase’s green is from its <a href="https://southbase.co.nz/" target="_blank" rel="noreferrer">current website</a>. These are adaptable concept styles, not official brand approval.</p>{error&&<p role="alert" className="rs-error">{error}</p>}{notice&&<p role="status"><Check size={15}/>{notice}</p>}<div className="cs-actions"><button className="cs-primary" onClick={()=>void apply()}>Apply to this pitch</button><button className="cs-secondary" disabled={localPreview} onClick={()=>void apply(true)}>Save company default</button><button className="cs-text" onClick={()=>edit(defaultSellerBrand(hub.seller))}>Reset starting style</button></div></fieldset><aside className="cb-preview sb-preview" style={{background:draft.paper,color:draft.ink,fontFamily:sellerFonts[draft.font],borderTop:`8px solid ${draft.primary}`}}>{draft.logo?<PreviewImage src={draft.logo} alt={hub.seller}/>:<strong className="sb-name">{hub.seller}</strong>}<span>A proposed idea for {hub.buyer}</span><h3 style={{fontFamily:"inherit"}}>{hub.seller}<br/>× {hub.buyer}</h3><p>Your voice and presentation style, with a recognisable client experience inside.</p><div style={{background:draft.primary,color:draft.onPrimary}}>Explore the idea ↗</div><small>Proposed concept · created with assembl</small></aside></div>;
}
