import Link from 'next/link';
import { PUBLIC_KNOWLEDGE_VERSION } from '@/lib/pursuit/public-knowledge';
export const metadata = { title: 'Assembl knowledge and tools for agents', description: 'Public Assembl knowledge search, MCP connection details, API schemas and the current limits of the research trial.' };
export default function AgentToolsPage() {
  return <main style={{maxWidth:1000,margin:'auto',padding:'70px 24px',color:'#240B21',fontFamily:'var(--font-body), sans-serif'}}>
    <p style={{fontSize:11,letterSpacing:'.12em'}}>ASSEMBL / FOR AGENTS AND DEVELOPERS</p><h1 style={{fontSize:'clamp(42px,7vw,80px)',lineHeight:1.03,letterSpacing:'-.055em'}}>Find the knowledge.<br />Call the right tool.</h1>
    <p style={{maxWidth:680,fontSize:19,lineHeight:1.65,marginTop:30}}>Start with the free public knowledge search. It contains published Assembl product knowledge, not private client hubs or confidential documents.</p>
    <section style={{padding:'30px 0',borderTop:'1px solid #916a7040',marginTop:35}}><h2>Connect an agent</h2><p>Stateless Streamable HTTP MCP endpoint:</p><pre style={{whiteSpace:'pre-wrap',wordBreak:'break-all',padding:20,background:'#F5F1F2'}}>https://www.assembl.co.nz/api/knowledge/mcp</pre><p>No key is required for this public, read-only knowledge tool. It does not expose live paid research, account access or private records.</p><p><a href="/api/knowledge/openapi">OpenAPI schema</a> · <a href="/api/knowledge/search?q=pursuit">Try public knowledge search</a> · <a href="/api/pursuit/research">Research availability</a></p></section>
    <section style={{padding:'30px 0',borderTop:'1px solid #916a7040'}}><h2>What is actually searched?</h2><p>The public research trial calls provider web search and searches the published Assembl records. A completed result includes source URLs, retrieval time, model identity, search count and the knowledge record IDs used. TypeSafe is a separate opt-in decision step when enabled. It is not a web search engine.</p><p>Published knowledge version: {PUBLIC_KNOWLEDGE_VERSION}. A listed endpoint, schema or connected provider is not proof that a live request succeeded.</p><p><Link href="/#try-pursuit">Try the research canvas</Link></p></section>
    <section style={{padding:'30px 0',borderTop:'1px solid #916a7040'}}><h2>Paid NZ tools</h2><p>Company resolution, trade finding and public-register checks are being developed separately. Existing sandbox examples do not establish live availability. Do not send payment or production information until the requested tool has verified upstream access, agreed pricing and a working receipt.</p><p>Paid access and billing are not activated by this page. <Link href="/contact?product=agent-tools">Discuss API access</Link>.</p></section>
    <section style={{padding:'30px 0',borderTop:'1px solid #916a7040'}}><h2>Limits and privacy</h2><p>The homepage trial is for public business research. It cannot send messages, publish, buy, execute code or write to private client hubs. Do not put confidential material into the brief. A provider failure produces an error, never a substituted sample.</p><p>The server keeps a bounded, private request record for safe retries and abuse control. Source-linked claims and proposed commercial ideas still need human review.</p><p>Downloadable pitches are editable HTML slides with sources. Export does not imply that a client endorsed the proposal.</p></section>
    <Link href="/">Back to assembl</Link>
  </main>;
}
