
INSERT INTO public.agent_knowledge_base (agent_id, topic, content, source_url, confidence) VALUES
('LEDGER', 'CCA 2002 s.18 retention trust',
'Construction Contracts Act 2002 sections 18A–18FA (as amended 2015 and effective from 5 October 2023): retention money withheld under a commercial construction contract MUST be held on trust by the party withholding it. Retentions must be held in cash or liquid assets in a dedicated trust account at a registered NZ bank (or backed by a complying instrument). Records: a separate ledger per contract showing amounts in/out, dates, and payee. Quarterly written reports must be sent to the party from whom money is held, including amount held, account details, and movements. Directors are personally liable for non-compliance.',
'https://www.legislation.govt.nz/act/public/2002/0046/latest/whole.html', 0.95),
('LEDGER', 'MBIE retention regulations 2023',
'MBIE Construction Contracts (Retention Money) Amendment Act 2023, in force 5 October 2023. Key changes vs 2017 regime: (1) retentions held on trust by operation of law — no need for written declaration; (2) cash or complying instrument only; (3) trust account must be at a NZ-registered bank; (4) quarterly reporting mandatory; (5) record-keeping offences carry fines up to $200,000 for companies and $50,000 for directors personally; (6) on insolvency, retentions are NOT available to general creditors.',
'https://www.building.govt.nz/projects-and-consents/why-contracts-are-valuable/retentions-regime/', 0.95),
('KAUPAPA', 'CCA 2002 s.20 payment claim',
'Construction Contracts Act 2002 s.20 — a payment claim served by a payee MUST contain ALL of: (a) be in writing; (b) contain sufficient details to identify the construction contract; (c) identify the construction work and the relevant period to which the progress payment relates; (d) state a claimed amount and the due date for payment; (e) indicate the manner in which the payee calculated the claimed amount; (f) state that it is made under the Construction Contracts Act 2002. If the payer does not respond with a payment schedule within 20 working days, the claimed amount becomes a debt due by operation of law (s.22) and the payee can sue or suspend work (s.24A).',
'https://www.legislation.govt.nz/act/public/2002/0046/latest/DLM164989.html', 0.95),
('APEX', 'NZS3910:2023 payments',
'NZS 3910:2023 General Conditions of Contract for Building and Civil Engineering Construction. Key payment clauses: Clause 12 (payment claims and schedules — aligned with CCA 2002 s.20–22), Clause 12.4 (engineer issues a payment schedule within 12 working days of claim), Clause 12.6 (retention — default 10% of certified value up to a cap, released 50% at practical completion and balance at end of defects liability period). Variations under Clause 9; Practical Completion under Clause 10; Defects Liability typically 12 months under Clause 11.',
'https://www.standards.govt.nz/shop/nzs-39102023/', 0.9),
('ARAI', 'WorkSafe toolbox rotation',
'NZ construction toolbox talk rotation — minimum weekly cycle: (1) working at heights and fall protection (HSWA Reg 12), (2) scaffolding inspection and tagging, (3) silica dust and respiratory protection (WES 0.05 mg/m3), (4) manual handling and musculoskeletal risk, (5) traffic management and excavation zones, (6) hand tools and PPE, (7) electrical hazards and lockout/tagout, (8) emergency response and first aid, (9) mental health and fatigue (MATES in Construction), (10) hot works and fire risk. Each talk: 10–15 minutes, attendance signed off, recorded in site diary.',
'https://www.worksafe.govt.nz/topic-and-industry/construction/', 0.9),
('PULSE', 'HSWA 2015 notifiable events',
'Health and Safety at Work Act 2015 s.23–25 — a notifiable event is (a) the death of a person, (b) a notifiable injury or illness, or (c) a notifiable incident. Notifiable injury/illness (s.23): includes amputation, serious head/eye injury, serious burn, separation of skin (degloving/scalping), spinal injury, loss of bodily function, serious lacerations, and any injury requiring immediate hospital admission. Notifiable incident (s.24): unplanned/uncontrolled escape of substance, electric shock, collapse/overturning of plant, structural collapse, scaffold fall ≥5m, etc. Duty (s.56): notify WorkSafe ASAP and within 7 days submit the prescribed form. Preserve site (s.55) until WorkSafe permits otherwise. Maximum penalty for failure to notify: $50,000 individual / $300,000 PCBU.',
'https://www.legislation.govt.nz/act/public/2015/0070/latest/whole.html', 0.95),
('ARC', 'Council knock-back triggers',
'Common council building consent knock-back triggers (RFI / S37 hold) by major NZ council: AUCKLAND: H1 schedule method without supporting calcs; missing PS1 from CPEng for specific design; incomplete fire design (C/AS2); seismic restraint details; stormwater disposal calcs. CHRISTCHURCH: TC2/TC3 ground assessment missing; foundation details vs MBIE guidance; chimney requirements post-quake. WELLINGTON: wind zone evidence (very high / extra high); slope stability for sites >15° gradient. HAMILTON: earthworks volume triggering land-use consent; flood hazard overlay checks. TAURANGA: liquefaction assessment for low-lying sites; coastal erosion setback. QUEENSTOWN-LAKES: alpine snow load calcs (NZS1170.3); landscape/built form compliance for outstanding natural landscape zones. DUNEDIN: harbourside flood hazard; heritage overlay restrictions.',
'https://www.building.govt.nz/projects-and-consents/apply-for-building-consent/', 0.85),
('APEX', 'Building Code H1',
'NZ Building Code Clause H1 Energy Efficiency. Current edition: H1/AS1 5th Edition Amendment 2 (effective 1 May 2024 for housing). Key requirements: minimum R-values vary by climate zone (1–6); window R-value ≥0.46 (zone 1–2) up to ≥0.50 (zone 5–6); roof R-values from R6.6 to R7.0 depending on zone; underfloor R2.5–R2.8. Schedule, calculation, and modelling methods all permitted. The Schedule Method is most common for residential. Update cycle: H1 amendments approximately every 18 months.',
'https://www.building.govt.nz/building-code-compliance/h-energy-efficiency/h1-energy-efficiency/', 0.9),
('ANCHOR', 'PS1 producer statement',
'PS1 = Producer Statement Design (Engineering NZ / ACENZ template). Issued by a Chartered Professional Engineer (CPEng) or registered architect for design work. States the design complies with relevant Building Code clauses. Required for: specific structural design, fire engineering, geotechnical design, and other specialist design where prescriptive solutions don''t apply. Must include: project, designer name + registration #, scope of design, Code clauses covered, design standards used, and a signed statement. PS3 (Construction) and PS4 (Construction Review) follow at later stages. LBPs sign restricted building work via Memorandum (not PS1).',
'https://www.engineeringnz.org/our-work/producer-statements/', 0.9)
ON CONFLICT (agent_id, topic) DO UPDATE SET
  content = EXCLUDED.content,
  source_url = EXCLUDED.source_url,
  confidence = EXCLUDED.confidence,
  last_verified = now(),
  is_stale = false,
  stale_reason = null;
