-- Pilot (Kaiurungi) — the guided agent maker.
--
-- Pilot walks a non-technical user through building their own agent in seven
-- steps and saves the result as a DRAFT. Nothing a user builds goes live until
-- a human signs the Mana Receipt. This migration adds:
--
--   profiles.first_pilot_agent_free_used  free-first-one tracking (the first
--                                         agent a user builds is free; after
--                                         that, Pilot is $9.99/mo).
--   pilot_agents                          user-built agent drafts (owner-scoped).
--   pilot_receipts                        hash-chained Mana Receipts for every
--                                         save / submit / publish action.
--
-- Self-healing throughout (ADD COLUMN IF NOT EXISTS, CREATE TABLE IF NOT
-- EXISTS, DROP POLICY IF EXISTS before CREATE) so a re-apply on a partially
-- migrated branch never errors. RLS is owner-scoped from day one; the service
-- role bypasses RLS for server-side writes (Stripe staging, receipt signing).

BEGIN;

-- ── Free-first-one tracking ──────────────────────────────────────────────
-- The first agent a user ships with Pilot is free; this flag flips true the
-- moment they save or publish their first one. profiles is auto-created on
-- signup by handle_new_user().
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS first_pilot_agent_free_used boolean NOT NULL DEFAULT false;

-- ── User-built agent drafts ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.pilot_agents (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_id uuid NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  -- Stable per-owner slug; only becomes a global marketplace slug on publish.
  slug text NOT NULL,
  name text NOT NULL DEFAULT '',
  te_reo text,
  description text NOT NULL DEFAULT '',
  category text NOT NULL DEFAULT 'build',
  icon text NOT NULL DEFAULT 'Sparkles',
  accent text NOT NULL DEFAULT '#FFD42A',
  -- The structured answers from the seven-step flow.
  goal jsonb NOT NULL DEFAULT '{}'::jsonb,         -- { output, audience, frequency }
  inputs jsonb NOT NULL DEFAULT '{}'::jsonb,        -- { needs[], access[] }
  tools jsonb NOT NULL DEFAULT '[]'::jsonb,         -- selected tool/skill ids
  compliance jsonb NOT NULL DEFAULT '[]'::jsonb,    -- NZ Acts/standards auto-added
  model_preference text NOT NULL DEFAULT 'claude'
    CHECK (model_preference IN ('claude', 'gpt', 'gemini', 'llama')),
  system_prompt text NOT NULL DEFAULT '',
  price_tier text NOT NULL DEFAULT 'free'
    CHECK (price_tier IN ('free', 'toro', 'whanau', 'pro', 'business')),
  status text NOT NULL DEFAULT 'draft'
    CHECK (status IN ('draft', 'submitted', 'published', 'archived')),
  -- Staged Stripe product/price — created on ship, NOT made live until publish.
  stripe_product_id text,
  stripe_price_id text,
  mana_receipt_id uuid,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (owner_id, slug)
);

CREATE INDEX IF NOT EXISTS pilot_agents_owner_idx ON public.pilot_agents (owner_id);
CREATE INDEX IF NOT EXISTS pilot_agents_status_idx ON public.pilot_agents (status);

-- ── Mana Receipts (hash-chained) ─────────────────────────────────────────
-- Every Pilot action that matters — saved to My Agents, submitted for review,
-- published — gets a signed, hash-chained receipt. Append-only: service role
-- writes, owners read their own.
CREATE TABLE IF NOT EXISTS public.pilot_receipts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  pilot_agent_id uuid REFERENCES public.pilot_agents (id) ON DELETE SET NULL,
  owner_id uuid NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  receipt_number bigint GENERATED BY DEFAULT AS IDENTITY,
  action text NOT NULL CHECK (action IN ('saved', 'submitted', 'published')),
  payload_json jsonb NOT NULL,
  sha256 text NOT NULL,
  prev_hash text NOT NULL,
  chain_hash text NOT NULL UNIQUE,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS pilot_receipts_owner_idx ON public.pilot_receipts (owner_id);
CREATE INDEX IF NOT EXISTS pilot_receipts_agent_idx ON public.pilot_receipts (pilot_agent_id);
CREATE INDEX IF NOT EXISTS pilot_receipts_number_idx ON public.pilot_receipts (receipt_number);

-- ── RLS ──────────────────────────────────────────────────────────────────
ALTER TABLE public.pilot_agents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pilot_receipts ENABLE ROW LEVEL SECURITY;

-- Drafts: owner-scoped CRUD.
DROP POLICY IF EXISTS pilot_agents_owner ON public.pilot_agents;
CREATE POLICY pilot_agents_owner ON public.pilot_agents
  FOR ALL TO authenticated
  USING (owner_id = auth.uid())
  WITH CHECK (owner_id = auth.uid());

-- Receipts: owners read their own; writes are service-role only (append-only).
DROP POLICY IF EXISTS pilot_receipts_owner_read ON public.pilot_receipts;
CREATE POLICY pilot_receipts_owner_read ON public.pilot_receipts
  FOR SELECT TO authenticated
  USING (owner_id = auth.uid());

COMMIT;
