-- Phase 5: Casing normalisation on PROD before any new INSERTs
-- Generated by Kaihanga autonomous prep mode 2026-05-13
--
-- Source of truth: locked 2026-05-08 Plugin Canon — kete pack names lowercase, agent_id lowercase
--
-- Prod-side casing drift to fix:
--   * agent_prompts.pack: AKO → ako, HOKO → hoko
--   * agent_toolsets.agent_id: ECHO → echo (collision), PRISM → prism (collision)
--
-- Lovable-side casing drift (informational; Lovable not modified):
--   * agent_prompts.pack: AKO, SHARED, TORO — uppercase variants present
--   * agent_toolsets.agent_id: 10 collision groups (arai/ARAI, aroha/AROHA, aura/AURA,
--     echo/ECHO, haven/HAVEN, kaupapa/KAUPAPA, ledger/LEDGER, motor/MOTOR, nova/NOVA, prism/PRISM)
--
-- WARNING: The agent_toolsets collisions (ECHO + echo, PRISM + prism on prod) must MERGE,
--   not LOWER() — both casings hold DIFFERENT tool wirings. We UNION them under the lowercase.
--
-- This migration MUST run BEFORE Phase 4b (agent_toolsets_fill), otherwise the new INSERTs
-- will trip the (agent_id, tool_name) UNIQUE constraint.

BEGIN;

-- ── agent_prompts.pack normalisation ──────────────────────────────────────
-- AKO → ako (currently 6 rows: ako, ako-comply, ako-whanau, apex-ako, mana-ako, nova-ako)
-- HOKO → hoko (currently 4 rows: anchor-hoko, flux-hoko, nova-hoko, prism-hoko)

-- Safety: confirm no lowercase pack='ako' rows already exist (would collide on UNIQUE constraint)
DO $$
DECLARE
  existing_ako int;
  existing_hoko int;
BEGIN
  SELECT count(*) INTO existing_ako FROM agent_prompts WHERE pack = 'ako';
  SELECT count(*) INTO existing_hoko FROM agent_prompts WHERE pack = 'hoko';
  IF existing_ako > 0 THEN
    RAISE EXCEPTION 'Lowercase pack=ako already has % rows — manual merge required before normalisation', existing_ako;
  END IF;
  IF existing_hoko > 0 THEN
    RAISE EXCEPTION 'Lowercase pack=hoko already has % rows — manual merge required before normalisation', existing_hoko;
  END IF;
END $$;

UPDATE agent_prompts SET pack = 'ako', updated_at = now() WHERE pack = 'AKO';
UPDATE agent_prompts SET pack = 'hoko', updated_at = now() WHERE pack = 'HOKO';

-- ── agent_toolsets.agent_id merge (collisions exist on prod) ──────────────
-- ECHO wirings UNION INTO echo
-- Step 1: insert ECHO's wirings under 'echo' (skip if already there)
INSERT INTO agent_toolsets (agent_id, tool_name)
SELECT 'echo', tool_name
FROM agent_toolsets
WHERE agent_id = 'ECHO'
ON CONFLICT (agent_id, tool_name) DO NOTHING;
-- Step 2: drop the uppercase rows
DELETE FROM agent_toolsets WHERE agent_id = 'ECHO';

-- PRISM wirings UNION INTO prism
INSERT INTO agent_toolsets (agent_id, tool_name)
SELECT 'prism', tool_name
FROM agent_toolsets
WHERE agent_id = 'PRISM'
ON CONFLICT (agent_id, tool_name) DO NOTHING;
DELETE FROM agent_toolsets WHERE agent_id = 'PRISM';

-- ── Verification ─────────────────────────────────────────────────────────
-- SELECT pack, count(*) FROM agent_prompts GROUP BY pack ORDER BY pack;
--   (expect: ako, arataki, auaha, core, council, hangarau, hauora, hoko, manaaki,
--    pakihi, pikau, shared, toro, waihanga — all lowercase, no uppercase variants)
--
-- SELECT agent_id FROM agent_toolsets WHERE agent_id <> LOWER(agent_id);
--   (expect: 0 rows)

COMMIT;
