-- ══════════════════════════════════════════════════════════════════════
-- SUPERSEDED 2026-05-17
--
-- This migration originally tried to introduce an alternate VOYAGE
-- schema with `trips` + `trip_families` + `trip_convoys` tables — a
-- different design from the canonical 11-table Italy-trip schema that
-- landed in 20260328130000_voyage_trip_planner.sql.
--
-- The alternate schema never successfully applied to production
-- (the `trips` table was never created — every fresh-DB replay failed
-- at `CREATE TABLE public.trip_destinations` because the March
-- migration already creates that table with a different FK), and the
-- only consumer (`supabase/functions/voyage-agent/index.ts`) has been
-- retargeted to the canonical March schema.
--
-- Body is intentionally empty so fresh Supabase preview branches can
-- replay the migration history cleanly. The version row in
-- `supabase_migrations.schema_migrations` is preserved.
-- See: supabase/migrations/20260328130000_voyage_trip_planner.sql
-- ══════════════════════════════════════════════════════════════════════

SELECT 1; -- explicit no-op
