-- Phase 9: Tōro activation — flip is_active=TRUE on parent + 8 sub-agents
-- Generated by Kaihanga 2026-05-13 (queued; applies AFTER Reo's Phase 3 editorial pass lands)
--
-- After Reo's editorial merge migration canonicalises brand drift in the 9 Tōro prompts
-- (lowercase 'assembl', no 'SMS-first', no 'Tōroa', adds CROSS-AGENT AWARENESS + EVIDENCE PACK
-- OUTPUTS sections), this migration flips them all from is_active=FALSE to is_active=TRUE
-- in one shot.
--
-- WAITS ON:
--   * Reo's PR landing UPDATE statements on 9 Tōro prompts:
--     - toro (parent), toro-education, toro-email, toro-family, toro-health,
--       toro-home, toro-homework, toro-logistics, toro-money
--   * Reo's brand-drift verification clean (zero capital-A 'Assembl' in the 9 prompts post-merge)
--
-- After this migration, the Tōro pack will show:
--   - 12 total agents under pack='toro' (3 LIVE from PR #117 + 9 newly activated)
--   - 12 is_active=TRUE
--
-- Idempotent. Safe to re-run.

BEGIN;

-- Activate Tōro parent + 8 sub-agents
UPDATE agent_prompts
  SET is_active = TRUE, updated_at = now()
WHERE pack = 'toro'
  AND agent_name IN (
    'toro',
    'toro-education',
    'toro-email',
    'toro-family',
    'toro-health',
    'toro-home',
    'toro-homework',
    'toro-logistics',
    'toro-money'
  )
  AND is_active = FALSE;  -- only flip currently-inactive rows

-- Capture how many rows actually flipped
DO $$
DECLARE
  flipped int;
  current_active int;
BEGIN
  SELECT count(*) INTO current_active FROM agent_prompts WHERE pack = 'toro' AND is_active = TRUE;
  RAISE NOTICE 'pack=toro now has % active rows', current_active;
  -- expect 12: 3 (PR #117) + 9 (today's port + Reo's pass)
END $$;

COMMIT;

-- ── Verification ──
--
-- Expect: 12 rows, all is_active=TRUE
-- SELECT agent_name, is_active, length(system_prompt) FROM agent_prompts WHERE pack = 'toro' ORDER BY agent_name;
--
-- Expect: 0 rows (no Tōro agent should have lingering brand drift after Reo's pass)
-- SELECT agent_name FROM agent_prompts
--   WHERE pack = 'toro'
--   AND (system_prompt LIKE '%Assembl%' OR system_prompt LIKE '%SMS-first%' OR system_prompt LIKE '%Tōroa%');
