DELETE FROM public.industry_knowledge_base
WHERE kete = 'pikau' AND tier = 1 AND doc_title IN (
  'Customs and Excise Act 2018',
  'Biosecurity Act 1993',
  'Working Tariff Document of New Zealand',
  'Import Health Standards (IHS) — MPI catalogue',
  'NZ Free Trade Agreements — MFAT directory',
  'Hazardous Substances and New Organisms (HSNO) Act 1996',
  'Goods Management Levy — NZ Customs Service',
  'Trade Single Window (TSW) — NZ Customs / MPI joint portal'
);

INSERT INTO public.industry_knowledge_base
  (kete, tier, doc_title, doc_source_url, doc_source_publisher, applicable_agents,
   update_cadence, next_review_due, notes)
VALUES
  ('pikau', 1,
   'Customs and Excise Act 2018',
   'https://www.legislation.govt.nz/act/public/2018/0004/latest/whole.html',
   'Parliamentary Counsel Office',
   '["pikau","apex-pikau","nova-pikau","mana-pikau","flux","haven","mariner","anchor"]'::jsonb,
   'monthly', CURRENT_DATE,
   'Primary customs statute. Subpart 3 of Part 3 (read with s.405) governs entry; s.354 governs records; Schedule 4 sets valuation methods (s.102 only covers provisional values). System prompt section citations must align here.'),
  ('pikau', 1,
   'Biosecurity Act 1993',
   'https://www.legislation.govt.nz/act/public/1993/0095/latest/whole.html',
   'Parliamentary Counsel Office',
   '["pikau","apex-pikau","nova-pikau","mana-pikau","flux","haven","mariner","anchor"]'::jsonb,
   'monthly', CURRENT_DATE,
   's.22 = meaning of import health standard. ss.23-24D = IHS issuance lifecycle. ss.25-28A = clearance regime. s.30 = uncleared imports. Critical for MPI Biosecurity Pre-Check workflow.'),
  ('pikau', 1,
   'Working Tariff Document of New Zealand',
   'https://www.customs.govt.nz/business/tariffs/working-tariff-document-of-new-zealand/',
   'New Zealand Customs Service',
   '["pikau","apex-pikau","nova-pikau","flux","haven","mariner"]'::jsonb,
   'fortnightly', CURRENT_DATE,
   'NZ-specific HSTC schedule based on WCO Harmonized System. Powers the Tariff Classifier workflow. NOTE: WiseTech holds the contract to digitise WTD — BorderWise Community Edition (NZ) is the canonical reference. Aironaut chapter focus: Ch.02-22 (food), Ch.39/44/48/73 (packaging), Ch.87 (cars), Ch.94 (furniture).'),
  ('pikau', 1,
   'Import Health Standards (IHS) — MPI catalogue',
   'https://www.mpi.govt.nz/import/border-clearance/importing-by-product/',
   'Ministry for Primary Industries',
   '["pikau","apex-pikau","nova-pikau","mana-pikau","haven"]'::jsonb,
   'fortnightly', CURRENT_DATE,
   'MPI catalogue of all current IHS by commodity. Each IHS sets specific requirements for that import category. Powers the Biosecurity Pre-Check workflow. Aironaut-relevant IHS list: containers, food (specific commodity IHSs), used vehicles, personal effects, wood packaging (ISPM 15).'),
  ('pikau', 1,
   'NZ Free Trade Agreements — MFAT directory',
   'https://www.mfat.govt.nz/en/trade/free-trade-agreements/',
   'Ministry of Foreign Affairs and Trade',
   '["pikau","apex-pikau","nova-pikau","flux"]'::jsonb,
   'monthly', CURRENT_DATE,
   'In-force NZ FTAs: CPTPP, RCEP, AANZFTA, NZ-China, NZ-UK, NZ-EU, DEPA, ANZCERTA/CER, NZ-Korea, GSP. Each FTA has its own ROO tests and origin proof requirements. Powers the Origin & Preference Workbench workflow.'),
  ('pikau', 1,
   'Hazardous Substances and New Organisms (HSNO) Act 1996',
   'https://www.legislation.govt.nz/act/public/1996/0030/latest/whole.html',
   'Parliamentary Counsel Office',
   '["pikau","apex-pikau","mana-pikau","haven"]'::jsonb,
   'quarterly', CURRENT_DATE,
   'Governs import of hazardous substances and dangerous goods. 9 hazard classes per UN system. EPA Group Standards apply for routine substances. Critical for Excise & Restricted Goods Watch workflow and lithium battery handling (UN3480/UN3481).'),
  ('pikau', 1,
   'Goods Management Levy — NZ Customs Service',
   'https://www.customs.govt.nz/business/customs-fees-and-charges/the-customs-levy/',
   'New Zealand Customs Service',
   '["pikau","apex-pikau","nova-pikau","flux","mariner","ledger"]'::jsonb,
   'monthly', CURRENT_DATE,
   'In force from 1 April 2026. Replaced per-report charging with per-consignment. Air NZ$2.21+GST low-value imports, sea NZ$2.09+GST low-value imports, exports NZ$2.48+GST. Powers the Landed-Cost Calculator and is PIKAU''s wedge moment for the CBAFF pitch.'),
  ('pikau', 1,
   'Trade Single Window (TSW) — NZ Customs / MPI joint portal',
   'https://www.customs.govt.nz/business/trade-single-window/',
   'New Zealand Customs Service',
   '["pikau","apex-pikau","nova-pikau","mana-pikau","flux","haven"]'::jsonb,
   'monthly', CURRENT_DATE,
   'Joint Customs + MPI lodgement portal — WCO3 message format mandatory since November 2016. PIKAU NEVER lodges to TSW. PIKAU produces draft entries that the licensed broker reviews and lodges via their own TSW-compliant software (typically CargoWise). This boundary is enforced by the Mana Trust Layer.');