-- Avoid duplicates by deleting any existing AKO tier-1 rows with these titles first.
DELETE FROM public.industry_knowledge_base
WHERE kete = 'ako' AND tier = 1 AND doc_title IN (
  'Education and Training Act 2020 — Part 3 (Early Childhood Education)',
  'Education (Early Childhood Services) Regulations 2008 — incl. amendments effective 20 April 2026',
  'Licensing Criteria for Early Childhood Education and Care Services 2008 (consolidated April 2026)',
  'Te Whāriki — He whāriki mātauranga mō ngā mokopuna o Aotearoa (Early Childhood Curriculum)',
  'ECE Funding Handbook',
  'Children''s Act 2014 — Safety Checking of the Children''s Workforce',
  'ERO Akarangi — Quality Evaluation Framework for Early Learning Services',
  'Privacy Act 2020 + Office of the Privacy Commissioner ECE guidance'
);

INSERT INTO public.industry_knowledge_base
  (kete, tier, doc_title, doc_source_url, doc_source_publisher, applicable_agents,
   update_cadence, next_review_due, notes)
VALUES
  ('ako', 1,
   'Education and Training Act 2020 — Part 3 (Early Childhood Education)',
   'https://www.legislation.govt.nz/act/public/2020/0038/latest/whole.html',
   'Parliamentary Counsel Office',
   '["apex-ako","nova-ako","mana-ako","anchor"]'::jsonb,
   'monthly', CURRENT_DATE,
   'Primary statute. Licensing, criteria-making power, Director of Regulation pathway live from 23 Feb 2026.'),
  ('ako', 1,
   'Education (Early Childhood Services) Regulations 2008 — incl. amendments effective 20 April 2026',
   'https://www.legislation.govt.nz/regulation/public/2008/0204/latest/DLM1412501.html',
   'Parliamentary Counsel Office',
   '["apex-ako","nova-ako","mana-ako","anchor"]'::jsonb,
   'monthly', CURRENT_DATE,
   'Sets the licensing criteria. The 20 April 2026 amendment is the wedge moment for the AKO MVP.'),
  ('ako', 1,
   'Licensing Criteria for Early Childhood Education and Care Services 2008 (consolidated April 2026)',
   'https://www.education.govt.nz/early-childhood/running-an-ece-service/the-regulatory-framework-for-ece/licensing-criteria/centre-based-ece-services/',
   'Ministry of Education',
   '["apex-ako","nova-ako","mana-ako"]'::jsonb,
   'fortnightly', CURRENT_DATE,
   'The 78-criterion regime (down from 98) — primary input to the Licensing Criteria Matcher workflow.'),
  ('ako', 1,
   'Te Whāriki — He whāriki mātauranga mō ngā mokopuna o Aotearoa (Early Childhood Curriculum)',
   'https://tewhariki.tahurangi.education.govt.nz/te-whariki/5637194831.p',
   'Ministry of Education',
   '["nova-ako","apex-ako","aroha"]'::jsonb,
   'quarterly', CURRENT_DATE,
   'National curriculum. Required for learning-story drafting and tikanga compliance.'),
  ('ako', 1,
   'ECE Funding Handbook',
   'https://www.education.govt.nz/early-childhood/funding-and-data/funding-handbook/',
   'Ministry of Education',
   '["apex-ako","mana-ako","anchor"]'::jsonb,
   'monthly', CURRENT_DATE,
   '20 Hours ECE, equity funding, attendance, and audit rules. Powers the funding-claim workflow.'),
  ('ako', 1,
   'Children''s Act 2014 — Safety Checking of the Children''s Workforce',
   'https://www.legislation.govt.nz/act/public/2014/0040/latest/DLM5501618.html',
   'Parliamentary Counsel Office',
   '["mana-ako","apex-ako","anchor"]'::jsonb,
   'quarterly', CURRENT_DATE,
   'Mandatory safety checks for ECE staff. Triggers staff-register compliance flags.'),
  ('ako', 1,
   'ERO Akarangi — Quality Evaluation Framework for Early Learning Services',
   'https://ero.govt.nz/our-research/akarangi-quality-evaluation-of-early-learning-services',
   'Education Review Office',
   '["mana-ako","apex-ako"]'::jsonb,
   'bi-monthly', CURRENT_DATE,
   'ERO review methodology. Powers the readiness report scoring rubric.'),
  ('ako', 1,
   'Privacy Act 2020 + Office of the Privacy Commissioner ECE guidance',
   'https://www.privacy.org.nz/responsibilities/your-obligations/privacy-and-children/',
   'Office of the Privacy Commissioner',
   '["mana-ako","anchor","apex-ako"]'::jsonb,
   'quarterly', CURRENT_DATE,
   'Children''s privacy + IPP3A (1 May 2026) for ECE record-keeping and parent communications.');