-- Mana Receipt ledger for voice calls — tamper-evident hash chain.
--
-- Customer-facing, this is the "evidence pack" / "receipt": a downloadable
-- bundle (PDF) of what the agent did on a call — consent, booking, SMS,
-- transfer — with sources and timestamps. "Mana Receipt" is the
-- second-reference depth term for the cryptographic backbone.
--
-- Every call produces exactly one receipt. `sha256` is the hash of the
-- canonical receipt payload (sorted keys, no whitespace — see
-- lib/voice/hashing.ts, which reuses lib/evidence canonicalisation).
-- `prev_hash` is the previous receipt's `chain_hash`; `chain_hash =
-- sha256(prev_hash || sha256)`. Tampering with any payload breaks the chain
-- from that receipt forward. `receipt_number` is a human-readable monotonic
-- counter (Mana Receipt #1 is the demo call).
--
-- This is the simpler hash-chain ledger scoped to phase-1 voice. The richer
-- Ed25519-signed ledger in lib/evidence/ remains the production signing path;
-- phase 2 will sign these receipts with the agent keyring too.

BEGIN;

CREATE TABLE IF NOT EXISTS public.mana_receipt (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  call_sid text NOT NULL UNIQUE REFERENCES public.kete_session (call_sid) ON DELETE CASCADE,
  receipt_number bigint GENERATED BY DEFAULT AS IDENTITY,
  payload_json jsonb NOT NULL,
  sha256 text NOT NULL,
  prev_hash text NOT NULL,
  chain_hash text NOT NULL UNIQUE,
  pdf_uri text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS mana_receipt_created_idx
  ON public.mana_receipt (created_at DESC);

CREATE INDEX IF NOT EXISTS mana_receipt_number_idx
  ON public.mana_receipt (receipt_number);

-- Append-only by intent: the chain is verifiable precisely because rows are
-- never updated. RLS on; service role writes, admin dashboard reads.
ALTER TABLE public.mana_receipt ENABLE ROW LEVEL SECURITY;

COMMIT;

-- Verification (chain walk):
-- SELECT receipt_number, sha256, prev_hash, chain_hash
--   FROM public.mana_receipt ORDER BY receipt_number;
-- Each row's prev_hash must equal the previous row's chain_hash; the first
-- row's prev_hash is the seed (64 zeros) from MANA_RECEIPT_PREV_HASH.
