-- Business Pulse weekly brief storage.
--
-- One row per (tenant, brief_date). Sections are stored as jsonb so the
-- shape can evolve as the pulse-synthesis skill matures without a wave of
-- migrations. The handover spec at
-- docs/handover/claude-for-small-business-2026-05-16.md references
-- org_id / organizations; this codebase uses tenant_id / tenants — same
-- concept, existing convention. See the README in plugins/arataki for the
-- workflow + skill set.
--
-- RLS: tenant_members read their tenant's briefs; service_role manages.
-- 7-year retention aligns with assembl_audit_log (Customs Act 2018 s.405
-- + Tax Administration Act 1994).

create table if not exists public.business_pulse_briefs (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  brief_date date not null,
  timezone text not null default 'Pacific/Auckland',

  -- delivery surfaces
  drive_path text,
  slack_channel text,
  slack_message_ts text,

  -- brief sections (jsonb so the schema can evolve)
  three_things jsonb not null default '[]'::jsonb,
  cash_position jsonb,
  pipeline_movement jsonb,
  weekly_commitments jsonb,
  pilot_health jsonb, -- assembl-internal briefs only; never customer-facing

  -- compliance gates
  tikanga_check_passed boolean not null default false,
  privacy_check_passed boolean not null default false,
  tikanga_notes text,
  privacy_notes text,

  -- run metadata
  generated_by text not null default 'arataki/business-pulse',
  run_status text not null default 'completed'
    check (run_status in ('running', 'completed', 'skipped', 'failed')),
  error_message text,
  generated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),

  -- one brief per tenant per day
  unique (tenant_id, brief_date)
);

-- Discipline rule from the handover spec: at most three "three things".
-- Enforced structurally so the synthesis prompt cannot drift to four.
alter table public.business_pulse_briefs
  drop constraint if exists business_pulse_briefs_three_things_max;

alter table public.business_pulse_briefs
  add constraint business_pulse_briefs_three_things_max
  check (jsonb_typeof(three_things) = 'array' and jsonb_array_length(three_things) <= 3);

create index if not exists business_pulse_briefs_tenant_date_idx
  on public.business_pulse_briefs(tenant_id, brief_date desc);

create index if not exists business_pulse_briefs_run_status_idx
  on public.business_pulse_briefs(run_status)
  where run_status in ('running', 'failed');

alter table public.business_pulse_briefs enable row level security;

drop policy if exists "business_pulse_briefs_tenant_select" on public.business_pulse_briefs;
create policy "business_pulse_briefs_tenant_select"
  on public.business_pulse_briefs
  for select to authenticated
  using (public.is_tenant_member(tenant_id));

drop policy if exists "business_pulse_briefs_service_manage" on public.business_pulse_briefs;
create policy "business_pulse_briefs_service_manage"
  on public.business_pulse_briefs
  for all to service_role
  using (true)
  with check (true);

comment on table public.business_pulse_briefs is
  'Weekly Business Pulse brief, one row per (tenant, brief_date). Generated by the arataki/business-pulse workflow. RLS: tenant_members read, service_role manage. 7-year retention per Customs Act 2018 s.405 + Tax Administration Act 1994.';

comment on column public.business_pulse_briefs.three_things is
  'Top three items needing operator attention this week. Max length 3 enforced by check constraint.';

comment on column public.business_pulse_briefs.pilot_health is
  'assembl-internal only. NEVER populated on customer-facing briefs.';
