-- Business Pulse briefs — Monday 07:00 NZT cross-kete weekly synthesis.
--
-- Owned by the ARATAKI plugin's `business-pulse` skill. One row per
-- (tenant, brief_date). The brief itself is read-only; any suggested
-- action surfaces as a staged draft, never auto-executes — see
-- docs/handover/claude-for-small-business-2026-05-16.md Part 3.
--
-- This migration mirrors the live shape already deployed to the
-- assembl-prod project (`wurwcrgxjjwqdaxqceey`). It is idempotent so
-- applying it against a fresh environment produces the same table,
-- constraints, indexes, and RLS policies.
--
-- Tenancy note: the handover doc's draft used `org_id` / `organizations`,
-- but the schema canon is `tenant_id` / `tenants` (with the
-- `is_tenant_member(uuid)` helper that other tables use). The doc's
-- spec was adapted accordingly during build.

create table if not exists public.business_pulse_briefs (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  brief_date date not null,
  timezone text not null default 'Pacific/Auckland',
  drive_path text,
  slack_channel text,
  slack_message_ts text,
  three_things jsonb not null default '[]'::jsonb,
  cash_position jsonb,
  pipeline_movement jsonb,
  weekly_commitments jsonb,
  pilot_health jsonb,
  source_status jsonb not null default '{}'::jsonb,
  markdown text not null default '',
  tikanga_check_passed boolean not null default false,
  privacy_check_passed boolean not null default false,
  tikanga_notes text,
  privacy_notes text,
  generated_by text not null default 'arataki/business-pulse',
  run_status text not null default 'completed',
  error_message text,
  generated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  constraint business_pulse_briefs_tenant_id_brief_date_key
    unique (tenant_id, brief_date),
  constraint business_pulse_briefs_three_things_max
    check (jsonb_typeof(three_things) = 'array' and jsonb_array_length(three_things) <= 3),
  constraint business_pulse_briefs_run_status_check
    check (run_status in ('running', 'completed', 'skipped', 'failed'))
);

create index if not exists business_pulse_briefs_tenant_date_idx
  on public.business_pulse_briefs (tenant_id, brief_date desc);

create index if not exists business_pulse_briefs_run_status_idx
  on public.business_pulse_briefs (run_status)
  where run_status in ('running', 'failed');

alter table public.business_pulse_briefs enable row level security;

drop policy if exists business_pulse_briefs_tenant_select
  on public.business_pulse_briefs;

create policy business_pulse_briefs_tenant_select
  on public.business_pulse_briefs
  for select
  to authenticated
  using (is_tenant_member(tenant_id));

drop policy if exists business_pulse_briefs_service_manage
  on public.business_pulse_briefs;

create policy business_pulse_briefs_service_manage
  on public.business_pulse_briefs
  for all
  to service_role
  using (true)
  with check (true);

comment on table public.business_pulse_briefs is
  'Weekly Business Pulse brief, one row per (tenant, brief_date). Generated by the arataki/business-pulse workflow. RLS: tenant_members read, service_role manage. 7-year retention per Customs Act 2018 s.405 + Tax Administration Act 1994.';
