-- Family OS joins the genome (family-first migration, 2026-07-17): one
-- Family Genome for the demo household, under tenant 'family' — the same
-- living_site_genome table and operating loop every other tenant reads.
--
-- SAMPLE only — this is the FICTIONAL demo roster (Mum, partner, Tama,
-- Aria, co-parent, the dog). No real names, schools, homes or medical
-- details are seeded here; the private family profile data stays out of
-- the genome by design.

insert into public.living_site_genome
  (tenant, fact_id, section, label, value, read_by, source, verification, verified_at) values
  ('family', 'g-name', 'identity', 'Household',
   'Family OS household · Tāmaki Makaurau — sample family, details fictional',
   '{voice,email,support}', 'seed', 'confirmed', now()),
  ('family', 'g-approver', 'identity', 'Who says yes',
   'A parent approves everything — the agents draft and suggest; nothing books, pays or sends on its own',
   '{voice,email,support,crm}', 'seed', 'confirmed', now()),
  ('family', 'g-parents', 'team', 'Parents',
   'Mum runs the family week · her partner is the second pair of hands for pickups and logistics',
   '{voice,email,crm}', 'seed', 'confirmed', now()),
  ('family', 'g-kids', 'team', 'Kids',
   'Tama — Year 9 (NZ Curriculum L5) · Aria — Year 7 (NZ Curriculum L4) · local colleges',
   '{voice,support,email}', 'seed', 'confirmed', now()),
  ('family', 'g-coparent', 'team', 'Co-parent',
   'Week-about care — has the kids on alternate weeks; one shared calendar keeps both weeks lined up',
   '{voice,email,crm}', 'seed', 'confirmed', now()),
  ('family', 'g-dog', 'team', 'The dog',
   'One family dog · a monthly vet reminder sits on the calendar',
   '{voice,email}', 'seed', 'confirmed', now()),
  ('family', 'g-newsletter', 'services', 'Newsletter parsing',
   'A school newsletter becomes the family week — events, tasks, pickups, shopping lists and approvals, all proposed first',
   '{email,voice,crm}', 'seed', 'confirmed', now()),
  ('family', 'g-echo', 'services', 'Inbox · Echo',
   'Reads forwarded school mail and bills into the week — proposes only; connecting an inbox is a one-time authorise',
   '{email,support}', 'seed', 'confirmed', now()),
  ('family', 'g-toro', 'services', 'Kids’ money · Tōro',
   'Chores → allowance → savings · each release is drafted for a parent’s yes — no money moves on its own',
   '{voice,email,crm}', 'seed', 'confirmed', now()),
  ('family', 'g-homework', 'services', 'Homework help',
   'Answers at each kid’s NZ Curriculum level, grounded to their year — it explains, it never does the homework',
   '{voice,support}', 'seed', 'confirmed', now()),
  ('family', 'g-pack', 'services', 'Dog training · PACK',
   'Calm, cited training guidance for reactivity and jumping — biting or aggression goes to a certified behaviourist',
   '{voice,support,faq}', 'seed', 'confirmed', now()),
  ('family', 'g-moana', 'services', 'On the water · Moana',
   'Boating questions grounded in NZ safety guidance — weather and tides come first, the skipper makes every call',
   '{voice,support}', 'seed', 'confirmed', now()),
  ('family', 'g-nutfree', 'knowledge', 'Shared lunches',
   'Class shared plates are always nut-free — there are allergies in the class, so labels get checked',
   '{voice,support,faq}', 'seed', 'confirmed', now()),
  ('family', 'g-homework-grounding', 'knowledge', 'Homework grounding',
   'Each kid’s year level and curriculum stage live here so help never pitches above their level',
   '{voice,support}', 'seed', 'confirmed', now()),
  ('family', 'g-proof', 'proof', 'How trust is kept',
   'Every action is draft-only and leaves a record — approvals show who said yes and when',
   '{email,support}', 'seed', 'confirmed', now()),
  ('family', 'g-custody', 'operations', 'Custody rhythm',
   'Week-about from a reference Monday — the console shows whose week it is and which home is base',
   '{voice,email,crm}', 'seed', 'confirmed', now()),
  ('family', 'g-pickups', 'operations', 'Pickup board',
   'Who collects whom, from where, when — an assigned adult plus a backup, with maps and ride links as handoffs',
   '{voice,booking,email}', 'seed', 'confirmed', now()),
  ('family', 'g-approvals', 'operations', 'Approvals queue',
   'Anything with money, transport, messaging or shopping waits in the queue for a parent’s yes',
   '{voice,email,crm}', 'seed', 'confirmed', now()),
  ('family', 'g-digest', 'operations', 'Weekly brief',
   'The week can be emailed as a drafted brief — it queues for approval like everything else',
   '{email}', 'seed', 'confirmed', now())
on conflict (tenant, fact_id) do nothing;
