const { PGlite } = await import(process.env.PERSONAL_DO_SQL_TEST_MODULE || '@electric-sql/pglite');
import { readFileSync } from 'node:fs';
import assert from 'node:assert/strict';
const db = new PGlite();
await db.exec(`create role anon; create role authenticated; create role service_role; create schema auth; create table auth.users(id uuid primary key);`);
await db.exec(readFileSync(new URL('../../supabase/migrations/20260930220845_do_consumer_usage_billing.sql', import.meta.url),'utf8'));
const owner='00000000-0000-4000-8000-000000000001', other='00000000-0000-4000-8000-000000000002';
await db.query(`insert into auth.users values ($1),($2)`,[owner,other]);
await db.query(`insert into personal_do_billing_accounts(owner_id,stripe_customer_id) values($1,'cus_1'),($2,'cus_2')`,[owner,other]);
const sync = async (id,status='active',created=1) => (await db.query(`select sync_personal_do_subscription($1,'cus_1','sub_1','price_1',$2,now()+interval '1 month',false,$3) as result`,[id,status,created])).rows[0].result;
assert.equal(await sync('evt1'),'processed'); assert.equal(await sync('evt1'),'already_processed');
const admit=async(who,id,digest='a',daily=2,monthly=2,reserve=10,budget=20,global=20)=>(await db.query(`select admit_personal_do_request($1,$2,$3,'price_1',$4,$5,$6,$7,$8) as result`,[who,id,digest,daily,monthly,reserve,budget,global])).rows[0].result;
const a='00000000-0000-4000-8000-000000000010', b='00000000-0000-4000-8000-000000000011',c='00000000-0000-4000-8000-000000000012';
assert.equal(await admit(other,a),'entitlement_required');
assert.equal(await admit(owner,a),'admitted');
assert.equal(await admit(owner,a),'already_pending');
assert.equal(await admit(owner,a,'different'),'idempotency_conflict');
assert.equal(await admit(owner,b),'request_in_progress');
await db.query(`update personal_do_usage set status='failed' where owner_id=$1`,[owner]);
assert.equal(await admit(owner,b),'admitted');
await db.query(`update personal_do_usage set status='failed' where owner_id=$1`,[owner]);
assert.equal(await admit(owner,c),'cost_limit');
await sync('cancel','canceled',3); await sync('stale','active',2); await sync('late-active','active',4);
assert.equal((await db.query(`select status from personal_do_subscriptions`)).rows[0].status,'canceled');
assert.equal(await admit(owner,c),'entitlement_required');
// Additional atomic budget/allowance boundaries using only the disposable local database.
await db.query(`delete from personal_do_usage`);
await db.query(`update personal_do_subscriptions set status='active'`);
await db.query(`insert into personal_do_subscriptions(stripe_subscription_id,owner_id,price_id,status,period_end) values('sub_2',$1,'price_1','active',now()+interval '1 month')`,[other]);
const parallel = await Promise.all([admit(owner,a,'a',10,10,10,20,10),admit(other,b,'b',10,10,10,20,10)]);
// Invalid inconsistent owner/global caps reject before starting.
assert.deepEqual(parallel,['invalid_configuration','invalid_configuration']);
const budgetRace = await Promise.all([admit(owner,a,'a',10,10,10,10,10),admit(other,b,'b',10,10,10,10,10)]);
assert.equal(budgetRace.filter(value=>value==='admitted').length,1);
assert.equal(budgetRace.filter(value=>value==='cost_limit').length,1);
await db.query(`delete from personal_do_usage`);
assert.equal(await admit(owner,a,'a',1,10,10,100,100),'admitted');
await db.query(`update personal_do_usage set status='succeeded'`);
assert.equal(await admit(owner,b,'b',1,10,10,100,100),'usage_limit');
assert.equal(await admit(owner,b,'b',10,1,10,100,100),'usage_limit');
await db.query(`delete from personal_do_usage`);
assert.equal(await admit(owner,a,'a',10,10,10,100,100),'admitted');
await db.query(`update personal_do_usage set expires_at=now()-interval '1 second'`);
assert.equal(await admit(owner,b,'b',10,10,10,100,100),'admitted');
assert.equal((await db.query(`select reserved_cost_cents from personal_do_usage where request_id=$1`,[a])).rows[0].reserved_cost_cents,10);
await db.exec(`set role authenticated`);
await assert.rejects(()=>db.query(`select admit_personal_do_request($1,$2,'a','price_1',2,2,10,20,20)`,[owner,c]),/permission denied/);
await assert.rejects(()=>db.query(`select * from personal_do_subscriptions`),/permission denied/);
await db.exec(`reset role`);
const attempt1=(await db.query(`select * from personal_do_checkout_attempt($1)`,[owner])).rows[0];
const attempt2=(await db.query(`select * from personal_do_checkout_attempt($1)`,[owner])).rows[0];
assert.equal(attempt1.attempt_id,attempt2.attempt_id);
console.log('SQL applied locally; entitlement, retry, concurrency, cost, cancellation, service-role and checkout assertions passed.');
await db.close();
