"use client";
import PreviewImage from "@/components/client-hub-migration/PreviewImage";
import { migrationFetch as fetch } from "@/lib/client-hub-migration/review-adapter";
import {useEffect,useRef,useState} from "react";
import {ArrowUpRight,ArrowRight,Clapperboard,ImagePlus,Upload,Download,Sparkles,Check,Copy,LoaderCircle,Layers3,Plus} from "lucide-react";
import type {Design} from "@/components/client-hub-migration/original/lib/creative";
import {nadirDirection} from "@/components/client-hub-migration/original/lib/hub-visuals";
import "./media-studio.css";
const mediaConnectionAvailable=false;
type Asset={id:string;name:string;src:string;prompt:string};
export const originals:Asset[]=[{id:"architecture",name:"A vision worth building",src:"/cinematic/architecture.png",prompt:"Cinematic New Zealand coastal architecture at dawn. A sculptural pale stone and glass pavilion, native planting, ocean horizon, a restrained plum accent. Photorealistic editorial architecture, warm light, generous negative space. No words or logos."},{id:"loyalty",name:"A reason to return",src:"/cinematic/loyalty.png",prompt:"Luxury macro product campaign: a matte plum coffee cup, soft steam, pale rose stone, polished chrome rings and glass caustics. Warm studio sunlight, sculptural composition, premium editorial photography. No words or logos."},{id:"assembl-form",name:"Possibility, assembled",src:"/cinematic/assembl-form.png",prompt:"Premium 3D exploded infinity ribbon made from chrome and translucent plum glass segments. Precisely aligned floating components, soft studio shadows, warm pale background, generous negative space. No words or logos."}];
export default function MediaStudio({design,onArtwork,onView,visualDirection,curatedAssets}:{design:Design;visualDirection?:string;curatedAssets?:Asset[];onArtwork:(src:string,alt:string)=>void;onView:(view:string)=>void}){
 const [assets,setAssets]=useState<Asset[]>([]),[prompt,setPrompt]=useState(""),[ratio,setRatio]=useState("16:9"),[busy,setBusy]=useState(""),[error,setError]=useState(""),[notice,setNotice]=useState(""),[connection,setConnection]=useState(false);const upload=useRef<HTMLInputElement>(null),alive=useRef(true);const current=design.frame.artwork||{src:originals[0].src,alt:originals[0].name};
 useEffect(()=>{alive.current=true;if(!mediaConnectionAvailable)return()=>{alive.current=false;};void fetch("/api/media").then(r=>r.json() as Promise<{items?:Asset[]}>).then(d=>{if(alive.current&&d.items)setAssets(d.items.map((a:{id:string;name:string;prompt:string})=>({...a,src:`/api/media?id=${a.id}`})));}).catch(()=>{});return()=>{alive.current=false;};},[]);
 const brief=()=>{const core=`Client: ${design.client}. Buyer: ${design.buyer}. Brand colours: ${design.frame.tokens.ink}, ${design.frame.tokens.accent}, ${design.frame.tokens.paper}. Format ${ratio}. Original concept, no invented projects, results or endorsement. No text or logos.\nUser direction: ${prompt}\nVisual direction: `;return core+(visualDirection||nadirDirection).slice(0,Math.max(0,3500-core.length));};
 async function optimise(file:Blob){if(file.size>15000000)throw Error("Choose an image under 15 MB.");const bitmap=await createImageBitmap(file);try{const scale=Math.min(1,1800/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement("canvas");canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);const ctx=canvas.getContext("2d");if(!ctx)throw Error("Image preview unavailable.");ctx.fillStyle="#f6f3ef";ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);let data=canvas.toDataURL("image/jpeg",.9);if(data.length>1800000)data=canvas.toDataURL("image/jpeg",.72);if(data.length>1800000)throw Error("This image is too detailed to save. Upload a smaller version.");return data;}finally{bitmap.close();}}
 async function saveImage(file:Blob,name:string,sourcePrompt:string){const data=await optimise(file);const r=await fetch("/api/media",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({data,name:name.slice(0,100),prompt:sourcePrompt.slice(0,4000)})});const d=await r.json() as {error?:string;item:Asset};if(!r.ok)throw Error(d.error||"Could not save the image.");const a=d.item as Asset;setAssets(old=>[a,...old]);onArtwork(a.src,a.name);setNotice("Image saved to your collection and added to this design. Save the project to keep this selection.");}
 async function generate(){if(!mediaConnectionAvailable){setError("Image generation is unavailable in this migration.");return;}if(prompt.trim().length<8)return;setBusy("Creating your image…");setError("");setNotice("");setConnection(false);try{const r=await fetch("/api/media/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({prompt:brief().slice(0,3500),ratio})});const d=await r.json() as {error?:string;needsConnection?:boolean;image:string};if(!r.ok){setConnection(!!d.needsConnection);throw Error(d.error||"Image generation could not finish.");}setBusy("Saving your new image…");const blob=await(await fetch(d.image)).blob();await saveImage(blob,prompt.slice(0,70),brief());}catch(e){setError(e instanceof Error?e.message:"Could not create the image.");}finally{setBusy("");}}
 async function importImage(file?:File){if(!mediaConnectionAvailable){setError("Hosted image uploads are unavailable in this migration.");return;}if(!file)return;setBusy("Adding your image…");setError("");try{await saveImage(file,file.name,prompt);}catch(e){setError(e instanceof Error?e.message:"Could not import the image.");}finally{setBusy("");if(upload.current)upload.current.value="";}}
 async function copy(){try{await navigator.clipboard.writeText(brief());setNotice("Creative brief copied. Use it in a separately approved creative tool. Uploading results to this workspace is not connected.");}catch{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([brief()],{type:"text/plain"}));a.download="assembl-image-brief.txt";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}}
 function choose(a:Asset){onArtwork(a.src,a.name);setPrompt(a.prompt);setNotice("Visual applied to your site, deck and film canvas. Save the project to keep it.");}
 return <div className="ms-studio"><div className="ms-intro"><div><p>ASSEMBL CREATIVE / MAKE THE POSSIBILITY VISIBLE</p><h1>See it. Shape it.<br/><em>Make it move.</em></h1></div><p>Images that stop the scroll.<br/>Films that make the idea felt.<br/>Experiences that move the buyer.</p></div>
 <div className="ms-workbench"><section className="ms-main"><div className="ms-canvas" onPointerMove={e=>{if(matchMedia("(prefers-reduced-motion: reduce)").matches||e.pointerType!=="mouse")return;const r=e.currentTarget.getBoundingClientRect();e.currentTarget.style.setProperty("--rx",`${((e.clientY-r.top)/r.height-.5)*-4}deg`);e.currentTarget.style.setProperty("--ry",`${((e.clientX-r.left)/r.width-.5)*5}deg`);}} onPointerLeave={e=>{e.currentTarget.style.setProperty("--rx","0deg");e.currentTarget.style.setProperty("--ry","0deg");}}><PreviewImage src={current.src} alt={current.alt}/><div className="ms-canvas-top"><span><span/> CURRENT VISUAL</span><span>{design.client.toUpperCase()} / CREATIVE</span></div><div className="ms-canvas-caption"><p>{current.alt}</p><button onClick={()=>onView("canvas")}>Use in site & deck <ArrowUpRight size={18}/></button></div>{busy&&<div className="ms-processing"><LoaderCircle className="cr-spin" size={26}/><b>{busy}</b><span>Your current visual stays in place.</span></div>}</div><div className="ms-canvas-tools"><span>Visual linked to this design</span><div><button onClick={()=>upload.current?.click()} disabled={!mediaConnectionAvailable||!!busy}><Upload size={14}/> Upload</button><a href={current.src} download="assembl-visual.jpg"><Download size={14}/> Download</a><button onClick={()=>onView("video")}><Clapperboard size={14}/> Animate</button></div></div></section>
 <aside className="ms-composer"><p className="ms-eyebrow"><Sparkles size={13}/> YOUR CREATIVE PARTNER</p><h2>What do you<br/>want to make?</h2><div className="ms-modes"><button className="active"><ImagePlus size={15}/> Image</button><button onClick={()=>onView("video")}><Clapperboard size={15}/> Film</button><button onClick={()=>onView("canvas")}><Layers3 size={15}/> Site & deck</button></div><label htmlFor="ms-prompt">Describe the image</label><textarea id="ms-prompt" placeholder="A directly overhead view of the objects that matter to this client, precisely arranged and ready to assemble…" rows={6} maxLength={2000} value={prompt} onChange={e=>setPrompt(e.target.value)} disabled={!!busy}/><div className="ms-composer-options"><label>Format<select value={ratio} disabled={!!busy} onChange={e=>setRatio(e.target.value)}><option value="16:9">16:9 · landscape</option><option value="9:16">9:16 · portrait</option><option value="1:1">1:1 · square</option></select></label><div className="ms-brand"><span>Brand palette</span><div>{[design.frame.tokens.ink,design.frame.tokens.accent,design.frame.tokens.paper].map((c,i)=><i key={i} style={{background:c}} title={c}/>)}</div></div></div><button className="ms-generate" onClick={generate} disabled={!mediaConnectionAvailable||!!busy||prompt.trim().length<8}>{busy?<LoaderCircle size={17} className="cr-spin"/>:<Sparkles size={17}/>} {busy?"Creating…":"Generate image"}<ArrowUpRight size={17}/></button><p className="ms-generation-note">Image generation and hosted uploads are not connected. You can edit and copy a creative brief; no image service is called.</p><button className="ms-copy" onClick={copy}><Copy size={13}/> Copy brief for ChatGPT / your image agent</button>{connection&&<p className="ms-connection">No connected image provider or hosted upload is available here.</p>}<input ref={upload} type="file" accept="image/png,image/jpeg,image/webp" disabled={!mediaConnectionAvailable} hidden onChange={e=>void importImage(e.target.files?.[0])}/></aside></div>
 {error&&<div className="ms-message error" role="alert">{error}</div>}{notice&&<div className="ms-message" role="status"><Check size={15}/>{notice}</div>}
 <section className="ms-collection"><div className="ms-section-heading"><div><p className="ms-eyebrow">START WITH A STRONG DIRECTION</p><h2>Your next idea is already taking shape.</h2></div><button onClick={()=>upload.current?.click()} disabled={!mediaConnectionAvailable||!!busy}><Plus size={15}/> Add an image</button></div><div className="ms-gallery">{[...assets,...(curatedAssets||originals)].map(a=><button key={a.id} className={current.src===a.src?"selected":""} onClick={()=>choose(a)} disabled={!!busy}><div><PreviewImage src={a.src} alt={a.name} loading="lazy"/>{current.src===a.src?<span className="ms-selected"><Check size={13}/> In your design</span>:<span className="ms-use">Use this visual <ArrowUpRight size={15}/></span>}</div><p>{a.name}</p><span>{a.src.startsWith("/cinematic")?"INDEPENDENT ILLUSTRATIVE ASSET":"YOUR COLLECTION"}</span></button>)}</div></section>
 <section className="ms-film-banner"><div><p className="ms-eyebrow">IMAGES ARE JUST THE BEGINNING.</p><h2>Now give<br/>the story <em>motion.</em></h2><p>Frame the scenes. Set the pace. Add your narration. Export a film in landscape, portrait or square.</p><button onClick={()=>onView("video")}>Open the film canvas <ArrowRight size={18}/></button></div><p className="ms-generation-note">Hosted example films are not connected. The storyboard editor can prepare local scene copy.</p></section></div>;
}
